mxlib: /home/jrmales/Source/mxlib/tests/include/ao/analysis/aoAtmosphere_test.cpp File Reference
aoAtmosphere_test.cpp File Reference
#include "../../../catch2/catch.hpp"
#include "../../../../include/ao/analysis/aoAtmosphere.hpp"
Functions
SCENARIO ("Loading aoAtmosphere config settings", "[ao::analysis::aoAtmosphere]")
Function Documentation
SCENARIO()
SCENARIO ("Loading aoAtmosphere config settings" , "" [ao::analysis::aoAtmosphere])
Test:
Scenario: Loading aoAtmosphere config settings
Verify parsing of config
Definition at line 20 of file aoAtmosphere_test.cpp.
References mx::AO::analysis::aoAtmosphere< _realT >::alpha(), mx::AO::analysis::aoAtmosphere< _realT >::beta(), mx::AO::analysis::aoAtmosphere< _realT >::beta_0(), mx::AO::analysis::aoAtmosphere< _realT >::H(), mx::AO::analysis::aoAtmosphere< _realT >::h_obs(), mx::AO::analysis::aoAtmosphere< _realT >::L_0(), mx::AO::analysis::aoAtmosphere< _realT >::l_0(), mx::AO::analysis::aoAtmosphere< _realT >::lam_0(), mx::AO::analysis::aoAtmosphere< _realT >::layer_Cn2(), mx::AO::analysis::aoAtmosphere< _realT >::layer_dir(), mx::AO::analysis::aoAtmosphere< _realT >::layer_v_wind(), mx::AO::analysis::aoAtmosphere< _realT >::layer_z(), mx::AO::analysis::aoAtmosphere< _realT >::loadConfig(), mx::AO::analysis::aoAtmosphere< _realT >::nonKolmogorov(), mx::app::appConfigurator::parseCommandLine(), mx::AO::analysis::aoAtmosphere< _realT >::r_0(), mx::app::appConfigurator::readConfig(), mx::AO::analysis::aoAtmosphere< _realT >::setupConfig(), mx::AO::analysis::aoAtmosphere< _realT >::v_wind(), mx::app::writeConfigFile(), and mx::AO::analysis::aoAtmosphere< _realT >::z_mean().