mxlib: ao/analysis/aoConstants.hpp File Reference
aoConstants.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Calculate and provide constants related to adaptive optics.
Calculate and provide constants related to adaptive optics.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file aoConstants.hpp.
#include <cmath>
#include "../../math/constants.hpp"
#include "../../math/func/gamma.hpp"
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename floatT >
void mx::AO::constants::calcConstants (floatT &a_sf, floatT &a_psd)
Calculate the AO constants.
template<typename floatT >
constexpr floatT mx::AO::constants::a_SF ()
The scaling constant for the Kolmorogov optical phase structure function.
template<typename floatT >
constexpr floatT mx::AO::constants::a_PSD ()
The scaling constant for the Kolmorogov optical phase power spectral density.
Function Documentation
calcConstants()
template<typename floatT > void mx::AO::constants::calcConstants (floatT & a_sf, floatT & a_psd)
Calculate the AO constants.
Definition at line 25 of file aoConstants.hpp.
References mx::AO::constants::calcConstants(), and mx::math::six_fifths().
Referenced by mx::AO::constants::calcConstants().