mxlib: ao/aoPaths.hpp File Reference
aoPaths.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Standardized paths for the mx::AO system.
Standardized paths for the mx::AO system.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file aoPaths.hpp.
#include "../sys/environment.hpp"
#include "../ioutils/fileUtils.hpp"
Namespaces
namespace mx
The mxlib c++ namespace.
namespace mx::AO::path
Namespace for paths.
namespace mx::AO::path::basis
Namespace for basis paths.
Functions
std::string mx::AO::path::basis::root (const std::string &basisName, bool create=false)
The root path for basis files.
std::string mx::AO::path::dm::root (const std::string &dmName, bool create=false)
The root path for deformable mirror (DM) files.
std::string mx::AO::path::dm::influenceFunctions (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence functions.
std::string mx::AO::path::dm::actuatorPositions (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) actuator positions.
std::string mx::AO::path::dm::pseudoInverse (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence function pseudo-inverse.
std::string mx::AO::path::dm::mirrorModes (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence function based mirror modes.
std::string mx::AO::path::dm::singularValues (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence function pseudo-inverse singular values.
std::string mx::AO::path::dm::basisRoot (const std::string &dmName, const std::string &basisName, bool create=false)
The root path for the deformable mirror (DM) basis related files.
std::string mx::AO::path::dm::M2c (const std::string &dmName, const std::string &basisName, bool create=false)
The path for the modes-to-commands (M2c) matrix for a deformable mirror (DM) and a basis set.
std::string mx::AO::path::dm::projectedModes (const std::string &dmName, const std::string &basisName, bool create=false)
The path for the projected modes for a deformable mirror (DM) and a basis set.
std::string mx::AO::path::pupil::root (const std::string &pupilName, bool create=false)
The root path for pupil files.
std::string mx::AO::path::pupil::pupilFile (const std::string &pupilName, bool create=false)
The path for the pupil FITS file.
std::string mx::AO::path::sys::root (const std::string &sysName, bool create=false)
The root path for system files.
std::string mx::AO::path::sys::cal::root (const std::string &sysName, bool create=false)
The root path for system calibration files.
std::string mx::AO::path::sys::cal::sysResp (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, bool create=false)
Path for the system response calibration.
std::string mx::AO::path::sys::cal::rMat (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response calibration.
std::string mx::AO::path::sys::cal::rImages (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response calibration.
std::string mx::AO::path::sys::cal::iMat (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response interaction matrix.
std::string mx::AO::path::sys::cal::U (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response interaction matrix.
std::string mx::AO::path::sys::cal::S (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response interaction matrix.
std::string mx::AO::path::sys::cal::VT (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response interaction matrix.
Function Documentation
actuatorPositions()
std::string mx::AO::path::dm::actuatorPositions (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) actuator positions.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM actuator positions
Definition at line 118 of file aoPaths.hpp.
References mx::AO::path::dm::actuatorPositions().
Referenced by mx::AO::path::dm::actuatorPositions().
basisRoot()
std::string mx::AO::path::dm::basisRoot (const std::string & dmName, const std::string & basisName, bool create = false)
The root path for the deformable mirror (DM) basis related files.
Parameters
[in] dmName the name of the DM
[in] basisName the name of the basis set
[in] create [optional] create the root directory if it noes not exist.
Returns
the root path for the DM basis related files
Definition at line 175 of file aoPaths.hpp.
References mx::AO::path::dm::basisRoot(), and mx::ioutils::createDirectories().
Referenced by mx::AO::path::dm::basisRoot(), mx::AO::path::dm::M2c(), and mx::AO::path::dm::projectedModes().
iMat()
std::string mx::AO::path::sys::cal::iMat (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response interaction matrix.
Definition at line 446 of file aoPaths.hpp.
References mx::AO::path::sys::cal::iMat(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::iMat().
influenceFunctions()
std::string mx::AO::path::dm::influenceFunctions (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence functions.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence functions.
Definition at line 104 of file aoPaths.hpp.
References mx::AO::path::dm::influenceFunctions().
Referenced by mx::AO::path::dm::influenceFunctions().
M2c()
std::string mx::AO::path::dm::M2c (const std::string & dmName, const std::string & basisName, bool create = false)
The path for the modes-to-commands (M2c) matrix for a deformable mirror (DM) and a basis set.
Parameters
[in] dmName the name of the DM
[in] basisName the name of the basis set
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containting the M2c matrix for a DM and a basis set.
Definition at line 195 of file aoPaths.hpp.
References mx::AO::path::dm::basisRoot(), mx::ioutils::createDirectories(), and mx::AO::path::dm::M2c().
Referenced by mx::AO::path::dm::M2c().
mirrorModes()
std::string mx::AO::path::dm::mirrorModes (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence function based mirror modes.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence function based mirror modes
Definition at line 146 of file aoPaths.hpp.
References mx::AO::path::dm::mirrorModes().
Referenced by mx::AO::path::dm::mirrorModes().
projectedModes()
std::string mx::AO::path::dm::projectedModes (const std::string & dmName, const std::string & basisName, bool create = false)
The path for the projected modes for a deformable mirror (DM) and a basis set.
These are the modes as reproduced by the DM actuators.
Parameters
[in] dmName the name of the DM
[in] basisName the name of the basis set
[in] pupilName the name of the pupil
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containting the M2c matrix for a DM and a basis set.
Definition at line 245 of file aoPaths.hpp.
References mx::AO::path::dm::basisRoot(), mx::ioutils::createDirectories(), and mx::AO::path::dm::projectedModes().
Referenced by mx::AO::path::dm::projectedModes().
pseudoInverse()
std::string mx::AO::path::dm::pseudoInverse (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence function pseudo-inverse.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence function pseudo-inverse matrix
Definition at line 132 of file aoPaths.hpp.
References mx::AO::path::dm::pseudoInverse().
Referenced by mx::AO::path::dm::pseudoInverse().
pupilFile()
std::string mx::AO::path::pupil::pupilFile (const std::string & pupilName, bool create = false)
The path for the pupil FITS file.
Parameters
[in] pupilName the name of the pupil file
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the pupil as a 1/0 mask
Definition at line 323 of file aoPaths.hpp.
References mx::AO::path::pupil::pupilFile().
Referenced by mx::AO::path::pupil::pupilFile().
rImages()
std::string mx::AO::path::sys::cal::rImages (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response calibration.
Definition at line 425 of file aoPaths.hpp.
References mx::AO::path::sys::cal::rImages(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::rImages().
rMat()
std::string mx::AO::path::sys::cal::rMat (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response calibration.
Definition at line 404 of file aoPaths.hpp.
References mx::AO::path::sys::cal::rMat(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::rMat().
root() [1/4]
std::string mx::AO::path::dm::root (const std::string & dmName, bool create = false)
The root path for deformable mirror (DM) files.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for DM files.
Definition at line 83 of file aoPaths.hpp.
References mx::ioutils::createDirectories(), and mx::sys::getEnv().
root() [2/4]
std::string mx::AO::path::pupil::root (const std::string & pupilName, bool create = false)
The root path for pupil files.
Parameters
[in] pupilName the name of the basis
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for pupil files.
Definition at line 301 of file aoPaths.hpp.
References mx::ioutils::createDirectories(), and mx::sys::getEnv().
root() [3/4]
std::string mx::AO::path::sys::root (const std::string & sysName, bool create = false)
The root path for system files.
Parameters
[in] sysName the name of the system
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for calibration files.
Definition at line 344 of file aoPaths.hpp.
References mx::ioutils::createDirectories(), and mx::sys::getEnv().
Referenced by mx::AO::path::sys::cal::root().
root() [4/4]
std::string mx::AO::path::sys::cal::root (const std::string & sysName, bool create = false)
The root path for system calibration files.
Parameters
[in] sysName the name of the system
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for calibration files.
Definition at line 368 of file aoPaths.hpp.
References mx::ioutils::createDirectories(), and mx::AO::path::sys::root().
S()
std::string mx::AO::path::sys::cal::S (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response interaction matrix.
Definition at line 490 of file aoPaths.hpp.
References mx::AO::path::sys::cal::S(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::S().
singularValues()
std::string mx::AO::path::dm::singularValues (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence function pseudo-inverse singular values.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence function pseudo-inverse singular values
Definition at line 160 of file aoPaths.hpp.
References mx::AO::path::dm::singularValues().
Referenced by mx::AO::path::dm::singularValues().
sysResp()
std::string mx::AO::path::sys::cal::sysResp (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, bool create = false)
Path for the system response calibration.
Definition at line 384 of file aoPaths.hpp.
References mx::ioutils::createDirectories(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::iMat(), mx::AO::path::sys::cal::rImages(), mx::AO::path::sys::cal::rMat(), mx::AO::path::sys::cal::S(), mx::AO::path::sys::cal::sysResp(), mx::AO::path::sys::cal::U(), and mx::AO::path::sys::cal::VT().
U()
std::string mx::AO::path::sys::cal::U (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response interaction matrix.
Definition at line 468 of file aoPaths.hpp.
References mx::AO::path::sys::cal::sysResp(), and mx::AO::path::sys::cal::U().
Referenced by mx::AO::path::sys::cal::U().
VT()
std::string mx::AO::path::sys::cal::VT (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response interaction matrix.
Definition at line 512 of file aoPaths.hpp.
References mx::AO::path::sys::cal::sysResp(), and mx::AO::path::sys::cal::VT().
Referenced by mx::AO::path::sys::cal::VT().