mxlib: /home/jrmales/Source/mxlib/tests/include/ao/analysis/aoSystem_test.cpp File Reference
aoSystem_test.cpp File Reference
#include "../../../catch2/catch.hpp"
#include "../../../../include/ao/analysis/aoSystem.hpp"
Functions
SCENARIO ("Loading aoSystem config settings", "[ao::analysis::aoSystem]")
Function Documentation
SCENARIO()
SCENARIO ("Loading aoSystem config settings" , "" [ao::analysis::aoSystem])
Scenario: Loading aoSystem config settings
Verify parsing of config
Definition at line 19 of file aoSystem_test.cpp.
References mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::bin_npix(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::circularLimit(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::D(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::d_min(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::d_opt(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::deltaTau(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::F0(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::Fbg(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::Fg(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::fit_mn_max(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::lam_sci(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::lam_wfs(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::loadConfig(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::minTauWFS(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::ncp_alpha(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::ncp_wfe(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::npix_wfs(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::optd(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::optd_delta(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::optTau(), mx::AO::analysis::aoAtmosphere< _realT >::r_0(), mx::app::appConfigurator::readConfig(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::ron_wfs(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::secZeta(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::setupConfig(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::spatialFilter_ku(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::spatialFilter_kv(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::starMag(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::tauWFS(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::wfsBeta(), mx::app::writeConfigFile(), and mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::zeta().