mxlib: astro/astroDynamics.hpp File Reference
astroDynamics.hpp File Reference
Astronomy » Astronomy Files
Various utilities for astrodynamics.
Various utilities for astrodynamics.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file astroDynamics.hpp.
#include <cmath>
#include "sofa.hpp"
#include "../math/constants.hpp"
#include "../math/geo.hpp"
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename realT >
int mx::astro::hrMinSecFromDay (int &Dy, int &hr, int &min, realT &sec, realT day)
Breaks down a decimal day into hours, minutes and decimal point seconds.
template<typename realT >
int mx::astro::getGMST (realT &GMST, int Yr, int Mo, int Dy, int hr, int min, realT sec)
Returns Greenwich Mean Sidereal Time for a given UTC time.
template<typename realT >
int mx::astro::getGMST (realT &GMST, int Yr, int Mo, realT day)
Returns Greenwich Mean Sidereal Time for a given UTC time.
template<typename realT >
int mx::astro::getLMST (realT &LMST, int Yr, int Mo, int Dy, int hr, int min, realT sec, realT lon)
Returns Local Mean Sidereal Time for a given UTC time and longitude.
template<typename realT >
int mx::astro::getLMST (realT &LMST, int Yr, int Mo, realT day, realT lon)
Returns Local Mean Sidereal Time for a given UTC time.
template<typename realT >
int mx::astro::calcAzEl (realT &az, realT &el, realT ha, realT dec, realT lat)
Calculates the Azimuth and Elevation for a given Hour-Angle, Declination, and Latitude.
template<typename realT >
realT mx::astro::parAngRad (realT sinHA, realT cosHA, realT sinDec, realT cosDec, realT tanLat)
Calculate the Parallactic Angle from the pre-calculated trig functions. Result in radians.
template<typename realT >
realT mx::astro::parAngDeg (realT sinHA, realT cosHA, realT sinDec, realT cosDec, realT tanLat)
Calculate the Parallactic Angle from the pre-calculated trig functions. Result in degrees.
template<typename realT >
realT mx::astro::parAngRad (realT ha, realT dec, realT lat)
Calculate the Parallactic Angle, with angles in radians.
template<typename realT >
realT mx::astro::parAngDeg (realT ha, realT dec, realT lat, bool newflag)
Calculate the Parallactic Angle, with angles in degrees.
Function Documentation
getGMST() [1/2]
template<typename realT > int mx::astro::getGMST (realT & GMST, int Yr, int Mo, int Dy, int hr, int min, realT sec)
Returns Greenwich Mean Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Return values
0 on success
Todo:
handle SOFA error.
Todo:
handle SOFA error.
Todo:
handle SOFA error.
Todo:
handle SOFA error.
Parameters
[out] GMST GMST in hours
[in] Yr integer year
[in] Mo integer month (1-12)
[in] Dy integer day (1-31)
[in] hr integer hour (0-23)
[in] min integer minute (0-59)
[in] sec decimal second (0-59)
Definition at line 72 of file astroDynamics.hpp.
References mx::astro::getGMST(), and mx::math::six_fifths().
Referenced by mx::astro::getGMST(), mx::astro::getGMST(), and mx::astro::getLMST().
getGMST() [2/2]
template<typename realT > int mx::astro::getGMST (realT & GMST, int Yr, int Mo, realT day)
Returns Greenwich Mean Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Parameters
GMST [output] GMST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
day [input] decimal day (1-31)
Return values
0 on sucess
Parameters
[out] GMST GMST in hours
[in] Yr integer year
[in] Mo integer month (1-12)
[in] day decimal day (1-31)
Definition at line 130 of file astroDynamics.hpp.
References mx::astro::getGMST().
getLMST() [1/2]
template<typename realT > int mx::astro::getLMST (realT & LMST, int Yr, int Mo, int Dy, int hr, int min, realT sec, realT lon)
Returns Local Mean Sidereal Time for a given UTC time and longitude.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Return values
0 on success
Parameters
[out] LMST LMST in hours
[in] Yr integer year
[in] Mo integer month (1-12)
[in] Dy integer day (1-31)
[in] hr integer hour (0-23)
[in] min integer minute (0-59)
[in] sec decimal second (0-59)
[in] lon longitude in degrees, E+, W-
Definition at line 150 of file astroDynamics.hpp.
References mx::astro::getGMST(), and mx::astro::getLMST().
Referenced by mx::astro::getLMST(), and mx::astro::getLMST().
getLMST() [2/2]
template<typename realT > int mx::astro::getLMST (realT & LMST, int Yr, int Mo, realT day, realT lon)
Returns Local Mean Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Template Parameters
realT the floating point type for all calculations
Return values
0 on sucess
Parameters
[out] LMST LMST in hours
[in] Yr integer year
[in] Mo integer month (1-12)
[in] day decimal day (1-31)
[in] lon longitude in degrees, E+, W-
Definition at line 182 of file astroDynamics.hpp.
References mx::astro::getLMST().
hrMinSecFromDay()
template<typename realT > int mx::astro::hrMinSecFromDay (int & Dy, int & hr, int & min, realT & sec, realT day)
Breaks down a decimal day into hours, minutes and decimal point seconds.
Assumes 86400 seconds per day, ignoring leap seconds.
Template Parameters
realT the floating point type for calculations
Return values
0 on success
-1 on failure.
Parameters
[out] Dy the integer day
[out] hr the integer hour
[out] min the integer minute
[out] sec the integer second
[in] day the decimal day to be broken down
Definition at line 51 of file astroDynamics.hpp.
References mx::astro::hrMinSecFromDay().
Referenced by mx::astro::hrMinSecFromDay().