mxlib: ao/basis.hpp File Reference
basis.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Utilities for working with a modal basis.
Utilities for working with a modal basis.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file basis.hpp.
#include "../ioutils/fits/fitsFile.hpp"
#include "../sigproc/fourierModes.hpp"
#include "../sigproc/gramSchmidt.hpp"
#include "../improc/imageFilters.hpp"
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename realT >
void mx::AO::applyPupil2Basis (eigenCube< realT > &modes, const std::string &basisName, const std::string &pupilName, realT fwhm=0)
Multiply a raw modal basis by a pupil mask.
template<typename realT >
void mx::AO::orthogonalizeBasis (const std::string &orthoName, const std::string &basisName, const std::string &pupilName, int method)
Calculate an orthogonal projection of a basis on a pupil.
Function Documentation
applyPupil2Basis()
template<typename realT > void mx::AO::applyPupil2Basis (eigenCube< realT > & modes, const std::string & basisName, const std::string & pupilName, realT fwhm = 0)
Multiply a raw modal basis by a pupil mask.
Definition at line 38 of file basis.hpp.
References mx::AO::applyPupil2Basis(), mx::improc::filterImage(), mx::improc::padImage(), and mx::math::six_fifths().
Referenced by mx::AO::applyPupil2Basis(), and mx::AO::orthogonalizeBasis().
orthogonalizeBasis()
template<typename realT > void mx::AO::orthogonalizeBasis (const std::string & orthoName, const std::string & basisName, const std::string & pupilName, int method)
Calculate an orthogonal projection of a basis on a pupil.
Can use either the stabilized Gramm Schmidt (SGS) procedure, or Singular Value Decomposition (SVD). This calls applyPupil2Basis as a first step..
Parameters
[in] basisName the name of the basis to orthogonalize
[in] pupilName the name of the pupil on which to orthogonalize.
[in] method either MXAO_ORTHO_METHOD_SGS (for SGS) or MXAO_ORTHO_METHOD_SVD (for SVD)
Template Parameters
realT
Definition at line 143 of file basis.hpp.
References mx::AO::applyPupil2Basis(), mx::improc::eigenCube< dataT >::image(), and mx::math::six_fifths().