mxlib: mx::improc::ds9Interface Class Reference
mx::improc::ds9Interface Class Reference
Image ProcessingGeneral Mathematics » | Plotting Data
An interface to the ds9 image viewer.
Handles spawning the ds9 window, and manages shared memory segments, one for each frame.
Definition at line 98 of file ds9Interface.hpp.
#include <improc/ds9Interface.hpp>
Public Member Functions
ds9Interface ()
Default c'tor.
ds9Interface (const std::string &nn)
Constructor which initializes the access point title.
ds9Interface (const char *nn)
Constructor which initializes the access point title.
template<typename arrayT >
ds9Interface (const arrayT &array, int frame=1)
Constructor which, after initialization, proceeds to display an Eigen-like array in ds9.
~ds9Interface ()
Destructor.
void initialize ()
Initialize the ds9Interface structure.
std::string title ()
Get the title of the ds9Interface.
int title (const std::string &nn)
Set the title of the ds9Interface.
int connect ()
Establish the existence of the desired DS9 XPA access point, spawning a new instance if needed.
int addframe (size_t frame)
Open a frame in ds9.
int display (const void *im, int bitpix, size_t pixsz, size_t dim1, size_t dim2, size_t dim3, int frame=1)
Display an image in ds9.
template<typename dataT >
int display (const dataT *im, size_t dim1, size_t dim2, size_t dim3, int frame=1)
Display an image in ds9.
template<typename arrayT >
int display (const arrayT &array, int frame=1)
Display an Eigen-like array in ds9.
template<typename arrayT >
int operator() (const arrayT &array, int frame=1)
Display an Eigen-like array in ds9.
int shutdown ()
Shutdown the ds9 interface.
Protected Member Functions
int spawn ()
Spawn (open) the ds9 image viewer.
int addsegment (size_t frame)
Add a segment corresponding to a particular frame in ds9.
Protected Attributes
XPA xpa {NULL}
The XPA structure to hold connections.
std::string m_title
The title of the window, which sets the XPA access point.
std::string m_ipAndPort
The ip:port string to uniquely identify a single XPA access point.
bool m_connected {false}
Whether or not the connect() procedure has completed successfully.
std::vector< ds9Segment > m_segs
A vector of shared memory segments, one per frame.
Constructor & Destructor Documentation
ds9Interface() [1/4]
mx::improc::ds9Interface::ds9Interface ()
Default c'tor.
Definition at line 307 of file ds9Interface.hpp.
References initialize().
ds9Interface() [2/4]
mx::improc::ds9Interface::ds9Interface (const std::string & nn) explicit
Constructor which initializes the access point title.
Definition at line 312 of file ds9Interface.hpp.
References initialize(), and title().
ds9Interface() [3/4]
mx::improc::ds9Interface::ds9Interface (const char * nn) explicit
Constructor which initializes the access point title.
Definition at line 318 of file ds9Interface.hpp.
References initialize(), and title().
ds9Interface() [4/4]
template<typename arrayT > mx::improc::ds9Interface::ds9Interface (const arrayT & array, int frame = 1)
Constructor which, after initialization, proceeds to display an Eigen-like array in ds9.
see display<typename arrayT>(arrayT & array, int frame=1) for more info.
Parameters
[in] array [in] An array containing an image or cube of images
[in] frame [in] [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 326 of file ds9Interface.hpp.
References display(), and initialize().
~ds9Interface()
mx::improc::ds9Interface::~ds9Interface ()
Destructor.
Calls shutdown, and closes the XPA connections.
Definition at line 335 of file ds9Interface.hpp.
References shutdown(), and xpa.
Member Function Documentation
addframe()
int mx::improc::ds9Interface::addframe (size_t frame) inline
Open a frame in ds9.
Nothing is done if the frame already exists. First calls addsegment.
Return values
0 on sucess
-1 on an error
Parameters
[in] frame [in] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 505 of file ds9Interface.hpp.
References addsegment(), connect(), DS9INTERFACE_CMD_MAX_LENGTH, and m_connected.
Referenced by display().
addsegment()
int mx::improc::ds9Interface::addsegment (size_t frame) inline protected
Add a segment corresponding to a particular frame in ds9.
Nothing is done if the frame already exists. Note that this does not open a new frame in ds9.
Parameters
frame is the number of the new frame to initialize. Note frame must be >= 1.
Return values
0 on sucess
-1 on an error
Parameters
[in] frame [in] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 482 of file ds9Interface.hpp.
References m_segs.
Referenced by addframe().
connect()
int mx::improc::ds9Interface::connect () inline
Establish the existence of the desired DS9 XPA access point, spawning a new instance if needed.
This isn't really a "connection", the main point is to get the unique ip:port name of the DS9 instance we will be communicating with.
Return values
0 on success.
-1 on error.
Definition at line 363 of file ds9Interface.hpp.
References DS9INTERFACE_SPAWN_SLEEP, DS9INTERFACE_SPAWN_TIMEOUT, m_connected, m_ipAndPort, m_title, shutdown(), spawn(), and xpa.
Referenced by addframe(), and display().
display() [1/3]
template<typename arrayT > int mx::improc::ds9Interface::display (const arrayT & array, int frame = 1)
Display an Eigen-like array in ds9.
Uses the rows(), cols(), and possibly planes(), methods of arrayT.
see display<typename dataT>(const dataT *im, size_t dim1, size_t dim2, size_t dim3, int frame=1) for more.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Return values
0 on sucess
-1 on an error
Parameters
[in] array [in] An array containing an image or cube of images
[in] frame [in] [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 715 of file ds9Interface.hpp.
References display().
display() [2/3]
template<typename dataT > int mx::improc::ds9Interface::display (const dataT * im, size_t dim1, size_t dim2, size_t dim3, int frame = 1)
Display an image in ds9.
A new ds9 instance is opened if necessary, and a new sharedmemory segment is added if necessary. The image is described by a pointer and its 2 or 3 dimensions.
Return values
0 on sucess
-1 on an error
Parameters
[in] im [in] the address of the image
[in] dim1 [in] the first dimension of the image (in pixels)
[in] dim2 [in] the second dimension of the image (in pixels)
[in] dim3 [in] the third dimension of the image (in pixels), set to 1 if not a cube.
[in] frame [in] [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 703 of file ds9Interface.hpp.
References display().
display() [3/3]
int mx::improc::ds9Interface::display (const void * im, int bitpix, size_t pixsz, size_t dim1, size_t dim2, size_t dim3, int frame = 1)
Display an image in ds9.
A new ds9 instance is opened if necessary, and a new sharedmemory segment is added if necessary. The image is described by a pointer and its 2 or 3 dimensions.
Return values
0 on sucess
-1 on an error
Parameters
[in] im [in] the address of the image
[in] dim1 [in] the first dimension of the image (in pixels)
[in] dim2 [in] the second dimension of the image (in pixels)
[in] dim3 [in] the third dimension of the image (in pixels), set to 1 if not a cube.
[in] frame [in] [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 605 of file ds9Interface.hpp.
References addframe(), connect(), DS9INTERFACE_CMD_MAX_LENGTH, m_connected, and m_segs.
Referenced by display(), ds9Interface(), and operator()().
initialize()
void mx::improc::ds9Interface::initialize () inline
Initialize the ds9Interface structure.
Established a persistent XPA connection.
Return values
0 on sucess
-1 on an error
Definition at line 342 of file ds9Interface.hpp.
References xpa.
Referenced by ds9Interface().
operator()()
template<typename arrayT > int mx::improc::ds9Interface::operator() (const arrayT & array, int frame = 1)
Display an Eigen-like array in ds9.
see display<typename arrayT>(arrayT & array, int frame=1) for more.
Return values
0 on sucess
-1 on an error
Parameters
[in] array [in] An array containing an image or cube of images
[in] frame [in] [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 725 of file ds9Interface.hpp.
References display().
shutdown()
int mx::improc::ds9Interface::shutdown () inline
Shutdown the ds9 interface.
Detaches from the shared memory segments.
Return values
0 on sucess
-1 on an error
Definition at line 782 of file ds9Interface.hpp.
References m_segs.
Referenced by connect(), and ~ds9Interface().
spawn()
int mx::improc::ds9Interface::spawn () inline protected
Spawn (open) the ds9 image viewer.
This forks and execs. An error is returned if exec fails.
Return values
0 on sucess
-1 on an error.
Definition at line 436 of file ds9Interface.hpp.
References m_title.
Referenced by connect().
title() [1/2]
std::string mx::improc::ds9Interface::title () inline
Get the title of the ds9Interface.
Returns
the current value of m_title
Definition at line 348 of file ds9Interface.hpp.
References m_title.
Referenced by ds9Interface().
title() [2/2]
int mx::improc::ds9Interface::title (const std::string & nn) inline
Set the title of the ds9Interface.
The title is used as the name of the XPA access point
Return values
0 on sucess
-1 on an error
Parameters
[in] nn [in] the title to set.
Definition at line 354 of file ds9Interface.hpp.
References m_connected, and m_title.
Member Data Documentation
m_connected
bool mx::improc::ds9Interface::m_connected {false} protected
Whether or not the connect() procedure has completed successfully.
Definition at line 116 of file ds9Interface.hpp.
Referenced by addframe(), connect(), display(), and title().
m_ipAndPort
std::string mx::improc::ds9Interface::m_ipAndPort protected
The ip:port string to uniquely identify a single XPA access point.
We use this so that we don't send to multiple "DS9:ds9" windows, and and always send to the same one.
Definition at line 113 of file ds9Interface.hpp.
Referenced by connect().
m_segs
std::vector<ds9Segment> mx::improc::ds9Interface::m_segs protected
A vector of shared memory segments, one per frame.
Definition at line 120 of file ds9Interface.hpp.
Referenced by addsegment(), display(), and shutdown().
m_title
std::string mx::improc::ds9Interface::m_title protected
The title of the window, which sets the XPA access point.
Definition at line 107 of file ds9Interface.hpp.
Referenced by connect(), spawn(), and title().
xpa
XPA mx::improc::ds9Interface::xpa {NULL} protected
The XPA structure to hold connections.
Definition at line 104 of file ds9Interface.hpp.
Referenced by connect(), initialize(), and ~ds9Interface().
The documentation for this class was generated from the following file:
improc/ds9Interface.hpp