mxlib: mx::math::randomT< typeT, _ranengT, _randistT > Class Template Reference
mx::math::randomT< typeT, _ranengT, _randistT > Class Template Reference
General Mathematics » Random Numbers
template<class typeT, class _ranengT, class _randistT>
class mx::math::randomT< typeT, _ranengT, _randistT >
A random number type, which functions like any other arithmetic type.
Combines a random engine, and a random distribution. Using the type conversion operator randomT returns the next random deviate whenever it is referenced.
Example:
//This can also be done using the alias definition mx::math::normDistT.
randomT<double, std::mt19937_64, std::normal_distribution<double> > norm_distd;
norm_distd.seed(); //
double d1 = norm_distd; //get a normally distributed value
double d2 = norm_distd; //get the next normally distributed value
Tests:
Verify compilation and basic operation of randomT with std::distributions [test doc]
Verify compilation and basic operation of randomT with the Laplace distribution [test doc]
Definition at line 63 of file randomT.hpp.
#include <math/randomT.hpp>
Public Types
typedef _randistT randistT
Typedef for the distribution type.
typedef _ranengT ranengT
Typedef for the engine type.
Public Member Functions
randomT (bool doSeed=true)
Constructor.
operator typeT ()
The conversion operator, returns the next value in the sequence, according to the distribution.
void seed (typename ranengT::result_type seedval)
Set the seed of the random engine.
void seed ()
Seed the random engine with a good value.
Public Attributes
_randistT distribution
The random distribution.
ranengT engine
The random engine.
Member Typedef Documentation
randistT
template<class typeT , class _ranengT , class _randistT > typedef _randistT mx::math::randomT< typeT, _ranengT, _randistT >::randistT
Typedef for the distribution type.
Definition at line 68 of file randomT.hpp.
ranengT
template<class typeT , class _ranengT , class _randistT > typedef _ranengT mx::math::randomT< typeT, _ranengT, _randistT >::ranengT
Typedef for the engine type.
Definition at line 71 of file randomT.hpp.
Constructor & Destructor Documentation
randomT()
template<class typeT , class _ranengT , class _randistT > mx::math::randomT< typeT, _ranengT, _randistT >::randomT (bool doSeed = true) inline
Constructor.
By default this calls the seed method, which will use /dev/random to seed the generator on linux, and time(0) on other systems. Set to false to suppress seeding, and/or set a seed with seed(x).
Parameters
[in] doSeed [optional] if true then the seed method is called upon construction.
Definition at line 77 of file randomT.hpp.
References mx::math::randomT< typeT, _ranengT, _randistT >::seed(), and mx::math::six_fifths().
Member Function Documentation
operator typeT()
template<class typeT , class _ranengT , class _randistT > mx::math::randomT< typeT, _ranengT, _randistT >::operator typeT () inline
The conversion operator, returns the next value in the sequence, according to the distribution.
Definition at line 92 of file randomT.hpp.
seed() [1/2]
template<class typeT , class _ranengT , class _randistT > void mx::math::randomT< typeT, _ranengT, _randistT >::seed () inline
Seed the random engine with a good value.
Calls mx::randomSeed to get the value. On linux this uses /dev/urandom. On other sytems, this uses time(0).
Definition at line 110 of file randomT.hpp.
References mx::math::randomSeed(), mx::math::randomT< typeT, _ranengT, _randistT >::seed(), and mx::math::six_fifths().
Referenced by mx::math::randomT< typeT, _ranengT, _randistT >::randomT(), and mx::math::randomT< typeT, _ranengT, _randistT >::seed().
seed() [2/2]
template<class typeT , class _ranengT , class _randistT > void mx::math::randomT< typeT, _ranengT, _randistT >::seed (typename ranengT::result_type seedval) inline
Set the seed of the random engine.
Calls the engines seed member function.
Parameters
[in] seedval the argument to pass to ranengT::seed()
Definition at line 101 of file randomT.hpp.
References mx::math::randomT< typeT, _ranengT, _randistT >::engine, and mx::math::six_fifths().
Referenced by mx::AO::influenceFunctionsGaussian(), mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::intensityPSD(), SCENARIO(), SCENARIO(), and mx::AO::analysis::speckleAmpPSD().
Member Data Documentation
distribution
template<class typeT , class _ranengT , class _randistT > _randistT mx::math::randomT< typeT, _ranengT, _randistT >::distribution
The random distribution.
Definition at line 86 of file randomT.hpp.
Referenced by mx::math::randomT< int, std::mt19937_64, std::poisson_distribution< int > >::operator int().
engine
template<class typeT , class _ranengT , class _randistT > ranengT mx::math::randomT< typeT, _ranengT, _randistT >::engine
The random engine.
Definition at line 89 of file randomT.hpp.
Referenced by mx::math::randomT< int, std::mt19937_64, std::poisson_distribution< int > >::operator int(), and mx::math::randomT< typeT, _ranengT, _randistT >::seed().
The documentation for this class was generated from the following file:
math/randomT.hpp