mxlib: mx::ioutils::fits::fitsHeader Class Reference
mx::ioutils::fits::fitsHeader Class Reference
General Utilities » Input/Output Utilities | Image Processing » FITS Files
Class to manage a complete fits header.
Manages tasks such as insertion (avoiding duplicates), and keyword lookup. The cards are stored in a std::list to preserve order, but a std::unordered_multimap is used to provide fast keyword lookup.
Definition at line 55 of file fitsHeader.hpp.
#include <ioutils/fits/fitsHeader.hpp>
Public Types
typedef std::list< fitsHeaderCard >::iterator headerIterator
The iterator type for the cards list.
typedef std::unordered_multimap< std::string, headerIterator >::iterator mapIterator
The iterator type for the card map.
Public Member Functions
fitsHeader ()
Default c'tor.
fitsHeader (const fitsHeader &head)
Copy constructor.
~fitsHeader ()
Destructor.
fitsHeader & operator= (const fitsHeader &head)
Assignment.
headerIterator begin ()
Get iterator to the beginning of the cards list.
headerIterator end ()
Get iterator to the end of the cards list.
headerIterator iterator (const std::string &keyword)
Get iterator pointing to a specific element.
bool empty ()
Test whether the header is empty.
size_t size ()
Get number of cards currently stored in the header.
void clear ()
Clear all cards from the header.
size_t count (const std::string &keyword)
Get number of cards with a given keyword.
void erase (const std::string &keyword)
Erase card by keyword.
void erase (headerIterator it)
Erase card by iterator.
void eraseStandardTop ()
Erase the standard entries at the top of the header.
void append (fitsHeaderCard card)
Append a fitsHeaderCard to the end of the header.
template<typename typeT >
void append (const std::string &k, const typeT &v, const std::string &c)
Append a card to the end of the header, from the three components of a card.
template<typename typeT >
void append (const std::string &k, const typeT &v)
Append a card to the end of the header, from the components of a card with no comment.
void append (const std::string &k)
Append a card to the end of the header, with just a keyword.
void append (fitsHeader &head)
Append a fitsHeader to the end of the header.
void insert_before (headerIterator it, fitsHeaderCard card)
Insert a card before another card.
template<typename typeT >
void insert_before (headerIterator it, const std::string &k, typeT v, const std::string &c)
Insert a card before another card, specifying the card by its components.
template<typename typeT >
void insert_before (headerIterator it, const std::string &k, typeT v)
Insert a card before another card, specifying the card by its components.
void insert_after (headerIterator it, fitsHeaderCard card)
Insert a card after another card.
template<typename typeT >
void insert_after (headerIterator it, const std::string &k, typeT v, const std::string &c)
Insert a card after another card, specifying the card by its components.
template<typename typeT >
void insert_after (headerIterator it, const std::string &k, typeT v)
Insert a card after another card, specifying the card by its components.
fitsHeaderCard & operator[] (const std::string &keyword)
Card access by keyword operator.
const fitsHeaderCard & operator[] (const std::string &keyword) const
Card access by keyword operator (const version)
Protected Attributes
std::list< fitsHeaderCard > cards
The storage for the FITS header cards.
std::unordered_multimap< std::string, headerIterator > cardMap
This multimap allows for fast lookup by keyword.
Member Typedef Documentation
headerIterator
typedef std::list<fitsHeaderCard>::iterator mx::ioutils::fits::fitsHeader::headerIterator
The iterator type for the cards list.
Definition at line 61 of file fitsHeader.hpp.
mapIterator
typedef std::unordered_multimap<std::string, headerIterator>::iterator mx::ioutils::fits::fitsHeader::mapIterator
The iterator type for the card map.
Definition at line 64 of file fitsHeader.hpp.
Constructor & Destructor Documentation
fitsHeader() [1/2]
mx::ioutils::fits::fitsHeader::fitsHeader ()
Default c'tor.
fitsHeader() [2/2]
mx::ioutils::fits::fitsHeader::fitsHeader (const fitsHeader & head)
Copy constructor.
Must be explicitly defined to handle creation of new iterators in the cardMap
Parameters
head The fitsHeader to copy
~fitsHeader()
mx::ioutils::fits::fitsHeader::~fitsHeader ()
Destructor.
Member Function Documentation
append() [1/5]
void mx::ioutils::fits::fitsHeader::append (const std::string & k)
Append a card to the end of the header, with just a keyword.
Appens a headerCard with unknownType
Parameters
k is the keyword string
append() [2/5]
template<typename typeT > void mx::ioutils::fits::fitsHeader::append (const std::string & k, const typeT & v)
Append a card to the end of the header, from the components of a card with no comment.
Template Parameters
typeT is the data type of the value
Parameters
k is the keyword string
v is the value of typeT
Definition at line 284 of file fitsHeader.hpp.
References append(), and mx::astro::constants::k().
append() [3/5]
template<typename typeT > void mx::ioutils::fits::fitsHeader::append (const std::string & k, const typeT & v, const std::string & c)
Append a card to the end of the header, from the three components of a card.
Template Parameters
typeT is the data type of the value
Parameters
k is the keyword string
v is the value of typeT
c is the comment string
Definition at line 274 of file fitsHeader.hpp.
References append(), mx::astro::constants::c(), and mx::astro::constants::k().
append() [4/5]
void mx::ioutils::fits::fitsHeader::append (fitsHeader & head)
Append a fitsHeader to the end of the header.
Parameters
head is a populated fitsHeader
append() [5/5]
void mx::ioutils::fits::fitsHeader::append (fitsHeaderCard card)
Append a fitsHeaderCard to the end of the header.
Parameters
card is a fitsHeaderCard already populated
Referenced by append(), and mx::ioutils::fits::fitsFile< dataT >::readHeader().
begin()
headerIterator mx::ioutils::fits::fitsHeader::begin ()
Get iterator to the beginning of the cards list.
Referenced by mx::ioutils::fits::fitsFile< dataT >::readHeader(), and mx::ioutils::fits::fitsFile< dataT >::write().
clear()
void mx::ioutils::fits::fitsHeader::clear ()
Clear all cards from the header.
count()
size_t mx::ioutils::fits::fitsHeader::count (const std::string & keyword)
Get number of cards with a given keyword.
Reeturns the result of the count() method of the header map.
Return values
the number of cards with keyword.
Parameters
[in] keyword [in] the keyword to loop up
empty()
bool mx::ioutils::fits::fitsHeader::empty ()
Test whether the header is empty.
end()
headerIterator mx::ioutils::fits::fitsHeader::end ()
Get iterator to the end of the cards list.
Referenced by mx::ioutils::fits::fitsFile< dataT >::readHeader(), and mx::ioutils::fits::fitsFile< dataT >::write().
erase() [1/2]
void mx::ioutils::fits::fitsHeader::erase (const std::string & keyword)
Erase card by keyword.
This can not be used to erase COMMENT or HISTORY cards.
Parameters
keyword the keyword of the card to delete
Referenced by mx::ioutils::fits::fitsFile< dataT >::readHeader().
erase() [2/2]
void mx::ioutils::fits::fitsHeader::erase (headerIterator it)
Erase card by iterator.
This handles COMMENT and HISTORY cards, deleting only the one pointed to by it
Parameters
it is a headerIterator pointing to the card to delete.
eraseStandardTop()
void mx::ioutils::fits::fitsHeader::eraseStandardTop ()
Erase the standard entries at the top of the header.
Erases each entry down to BSCALE. This is useful for appending a header to a newly created file.
insert_after() [1/3]
template<typename typeT > void mx::ioutils::fits::fitsHeader::insert_after (headerIterator it, const std::string & k, typeT v)
Insert a card after another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element after which to insert
k is the keyword
v is the value
Definition at line 323 of file fitsHeader.hpp.
References insert_after(), and mx::astro::constants::k().
insert_after() [2/3]
template<typename typeT > void mx::ioutils::fits::fitsHeader::insert_after (headerIterator it, const std::string & k, typeT v, const std::string & c)
Insert a card after another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element after which to insert
k is the keyword
v is the value
c is the comment
Definition at line 312 of file fitsHeader.hpp.
References mx::astro::constants::c(), insert_after(), and mx::astro::constants::k().
insert_after() [3/3]
void mx::ioutils::fits::fitsHeader::insert_after (headerIterator it, fitsHeaderCard card)
Insert a card after another card.
Parameters
it points to the element after which to insert
card contains the card to insert
Referenced by insert_after().
insert_before() [1/3]
template<typename typeT > void mx::ioutils::fits::fitsHeader::insert_before (headerIterator it, const std::string & k, typeT v)
Insert a card before another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element before which to insert
k is the keyword
v is the value
Definition at line 303 of file fitsHeader.hpp.
References insert_before(), and mx::astro::constants::k().
insert_before() [2/3]
template<typename typeT > void mx::ioutils::fits::fitsHeader::insert_before (headerIterator it, const std::string & k, typeT v, const std::string & c)
Insert a card before another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element before which to insert
k is the keyword
v is the value
c is the comment
Definition at line 292 of file fitsHeader.hpp.
References mx::astro::constants::c(), insert_before(), and mx::astro::constants::k().
insert_before() [3/3]
void mx::ioutils::fits::fitsHeader::insert_before (headerIterator it, fitsHeaderCard card)
Insert a card before another card.
Parameters
it points to the element before which to insert
card contains the card to insert
Referenced by insert_before().
iterator()
headerIterator mx::ioutils::fits::fitsHeader::iterator (const std::string & keyword)
Get iterator pointing to a specific element.
Parameters
keyword The keyword to look up
operator=()
fitsHeader& mx::ioutils::fits::fitsHeader::operator= (const fitsHeader & head)
Assignment.
Must be explicitly defined to handle creation of new iterators in the cardMap
Parameters
head The fitsHeader to copy
operator[]() [1/2]
fitsHeaderCard& mx::ioutils::fits::fitsHeader::operator[] (const std::string & keyword)
Card access by keyword operator.
Looks up the card by its keyword, and returns a reference to it.
Parameters
keyword is the header keyword to look up
Return values
fitsHeaderCard& reference to the fitsHeaderCard
operator[]() [2/2]
const fitsHeaderCard& mx::ioutils::fits::fitsHeader::operator[] (const std::string & keyword) const
Card access by keyword operator (const version)
Looks up the card by its keyword, and returns a reference to it.
Parameters
keyword is the header keyword to look up
Return values
fitsHeaderCard& const reference to the fitsHeaderCard
size()
size_t mx::ioutils::fits::fitsHeader::size ()
Get number of cards currently stored in the header.
Referenced by mx::ioutils::fits::fitsFile< dataT >::readHeader().
Member Data Documentation
cardMap
std::unordered_multimap<std::string, headerIterator> mx::ioutils::fits::fitsHeader::cardMap protected
This multimap allows for fast lookup by keyword.
Use unordered_multimap to handle HISTORY and COMMENT properly, and be as efficient as possible.
Definition at line 77 of file fitsHeader.hpp.
cards
std::list<fitsHeaderCard> mx::ioutils::fits::fitsHeader::cards protected
The storage for the FITS header cards.
We use a list, rather than forward_list, so that append (insert at end) is constant time.
Definition at line 72 of file fitsHeader.hpp.
The documentation for this class was generated from the following file:
ioutils/fits/fitsHeader.hpp