mxlib: mx::improc::eigenCube< dataT > Class Template Reference
mx::improc::eigenCube< dataT > Class Template Reference
Image Processing » Image Processing with Eigen
template<typename dataT>
class mx::improc::eigenCube< dataT >
An image cube with an Eigen-like API.
Definition at line 30 of file eigenCube.hpp.
#include <improc/eigenCube.hpp>
Public Member Functions
eigenCube (Index nrows, Index ncols, Index nplanes)
C'tor which will allocate space..
eigenCube (dataT *ndata, size_t nrows, size_t ncols, size_t nplanes)
C'tor taking an existing array as an argument.
Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > cube ()
Returns a 2D Eigen::Eigen::Map pointed at the entire cube.
Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > image (Index n)
Returns a 2D Eigen::Eigen::Map pointed at the specified image.
const Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > image (Index n) const
Returns a 2D Eigen::Eigen::Map pointed at the specified image.
Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic >, Eigen::Unaligned, Eigen::Stride< Eigen::Dynamic, Eigen::Dynamic > > pixel (Index i, Index j)
Returns an Eigen::Eigen::Map-ed vector of the pixels at the given coordinate.
Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > asVectors ()
Return an Eigen::Eigen::Map of the cube where each image is a vector.
void Covar (Eigen::Matrix< dataT, Eigen::Dynamic, Eigen::Dynamic > &cv)
Calculate the covariance matrix of the images in the cube.
template<typename eigenT >
void sum (eigenT &mim)
Calculate the sum image of the cube.
template<typename eigenT >
void mean (eigenT &mim)
Calculate the mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void mean (eigenT &mim, eigenCubeT &mask, double minGoodFract=0.0)
Calculate the mean image of the cube with a mask.
template<typename eigenT >
void mean (eigenT &mim, std::vector< dataT > &weights)
Calculate the weighted mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void mean (eigenT &mim, std::vector< dataT > &weights, eigenCubeT &mask, double minGoodFract=0.0)
Calculate the weighted mean image of the cube, with a mask cube.
template<typename eigenT >
void median (eigenT &mim)
Calculate the median image of the cube.
template<typename eigenT >
void sigmaMean (eigenT &mim, Scalar sigma)
Calculate the sigma clipped mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void sigmaMean (eigenT &mim, eigenCubeT &mask, Scalar sigma, double minGoodFract=0.0)
Calculate the sigma clipped mean image of the cube, with a mask cube.
template<typename eigenT >
void sigmaMean (eigenT &mim, std::vector< dataT > &weights, Scalar sigma)
Calculate the sigma clipped weighted mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void sigmaMean (eigenT &mim, std::vector< dataT > &weights, eigenCubeT &mask, Scalar sigma, double minGoodFract=0.0)
Calculate the sigma clipped weighted mean image of the cube, with a mask cube.
Constructor & Destructor Documentation
eigenCube() [1/2]
template<typename dataT > mx::improc::eigenCube< dataT >::eigenCube (Index nrows, Index ncols, Index nplanes)
C'tor which will allocate space..
Parameters
[in] nrows Number of rows in the cube
[in] ncols Number of columns the cube
[in] nplanes Number of planes in the cube
Definition at line 227 of file eigenCube.hpp.
eigenCube() [2/2]
template<typename dataT > mx::improc::eigenCube< dataT >::eigenCube (dataT * ndata, size_t nrows, size_t ncols, size_t nplanes)
C'tor taking an existing array as an argument.
The existing array is used as is, as in a map, and ownership is not taken. You are responsible for memory management, e.g. free-ing this array.
Parameters
[in] ndata Allocated array with a cube of nrows x ncols x nplanes
[in] nrows Number of rows in the cube
[in] ncols Number of columns the cube
[in] nplanes Number of planes in the cube
Definition at line 238 of file eigenCube.hpp.
Member Function Documentation
asVectors()
template<typename dataT > Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > mx::improc::eigenCube< dataT >::asVectors
Return an Eigen::Eigen::Map of the cube where each image is a vector.
Definition at line 393 of file eigenCube.hpp.
Referenced by mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().
Covar()
template<typename dataT > void mx::improc::eigenCube< dataT >::Covar (Eigen::Matrix< dataT, Eigen::Dynamic, Eigen::Dynamic > & cv)
Calculate the covariance matrix of the images in the cube.
Definition at line 399 of file eigenCube.hpp.
cube()
template<typename dataT > Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > mx::improc::eigenCube< dataT >::cube
Returns a 2D Eigen::Eigen::Map pointed at the entire cube.
Definition at line 369 of file eigenCube.hpp.
Referenced by mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().
image() [1/2]
template<typename dataT > Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > mx::improc::eigenCube< dataT >::image (Index n)
Returns a 2D Eigen::Eigen::Map pointed at the specified image.
Parameters
[in] n the image number
Definition at line 375 of file eigenCube.hpp.
Referenced by mx::improc::HCIobservation< _realT >::coaddImages(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::meanSubtract(), mx::improc::HCIobservation< _realT >::preProcess(), mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::regions(), and SCENARIO().
image() [2/2]
template<typename dataT > const Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic > > mx::improc::eigenCube< dataT >::image (Index n) const
Returns a 2D Eigen::Eigen::Map pointed at the specified image.
Parameters
[in] n the image number
Definition at line 381 of file eigenCube.hpp.
mean() [1/4]
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim)
Calculate the mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image. Is resized.
Definition at line 422 of file eigenCube.hpp.
Referenced by mx::improc::HCIobservation< _realT >::coaddImages(), and mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::meanSubtract().
mean() [2/4]
template<typename dataT > template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim, eigenCubeT & mask, double minGoodFract = 0.0)
Calculate the mean image of the cube with a mask.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
[in] minGoodFract [optional] the minimum fraction of good pixels, if not met then the pixel is NaN-ed.
Definition at line 438 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::math::vectorMean().
mean() [3/4]
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim, std::vector< dataT > & weights)
Calculate the weighted mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
Definition at line 478 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::math::vectorMean().
mean() [4/4]
template<typename dataT > template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim, std::vector< dataT > & weights, eigenCubeT & mask, double minGoodFract = 0.0)
Calculate the weighted mean image of the cube, with a mask cube.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
[in] minGoodFract [optional] the minimum fraction of good pixels, if not met then the pixel is NaN-ed.
Definition at line 505 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::math::vectorMean().
median()
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::median (eigenT & mim)
Calculate the median image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant median image. Is resized.
Definition at line 547 of file eigenCube.hpp.
References mx::improc::HCI::imageMedian.
Referenced by mx::improc::HCIobservation< _realT >::coaddImages(), and mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::meanSubtract().
pixel()
template<typename dataT > Eigen::Map< Eigen::Array< dataT, Eigen::Dynamic, Eigen::Dynamic >, Eigen::Unaligned, Eigen::Stride< Eigen::Dynamic, Eigen::Dynamic > > mx::improc::eigenCube< dataT >::pixel (Index i, Index j)
Returns an Eigen::Eigen::Map-ed vector of the pixels at the given coordinate.
Definition at line 387 of file eigenCube.hpp.
Referenced by SCENARIO().
sigmaMean() [1/4]
template<typename dataT > template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, eigenCubeT & mask, Scalar sigma, double minGoodFract = 0.0)
Calculate the sigma clipped mean image of the cube, with a mask cube.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
[in] sigma the sigma value at which to clip.
[in] minGoodFract [optional] the minimum fraction of good pixels, if not met then the pixel is NaN-ed.
Definition at line 591 of file eigenCube.hpp.
References mx::astro::constants::k(), mx::astro::constants::sigma(), and mx::math::vectorSigmaMean().
sigmaMean() [2/4]
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, Scalar sigma)
Calculate the sigma clipped mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image
[in] sigma the sigma value at which to clip.
Definition at line 565 of file eigenCube.hpp.
References mx::astro::constants::k(), mx::astro::constants::sigma(), and mx::math::vectorSigmaMean().
sigmaMean() [3/4]
template<typename dataT > template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, std::vector< dataT > & weights, eigenCubeT & mask, Scalar sigma, double minGoodFract = 0.0)
Calculate the sigma clipped weighted mean image of the cube, with a mask cube.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
[in] sigma the sigma value at which to clip.
[in] minGoodFract [optional] the minimum fraction of good pixels, if not met then the pixel is NaN-ed.
Definition at line 660 of file eigenCube.hpp.
References mx::astro::constants::k(), mx::astro::constants::sigma(), and mx::math::vectorSigmaMean().
sigmaMean() [4/4]
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, std::vector< dataT > & weights, Scalar sigma)
Calculate the sigma clipped weighted mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
[in] sigma the sigma value at which to clip.
Definition at line 633 of file eigenCube.hpp.
References mx::astro::constants::k(), mx::astro::constants::sigma(), and mx::math::vectorSigmaMean().
sum()
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::sum (eigenT & mim)
Calculate the sum image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant sum image. Is resized.
Definition at line 406 of file eigenCube.hpp.
The documentation for this class was generated from the following file:
improc/eigenCube.hpp