mxlib: mx::ioutils::fits::fitsFile< dataT > Class Template Reference
mx::ioutils::fits::fitsFile< dataT > Class Template Reference
General Utilities » Input/Output Utilities | Image Processing » FITS Files
template<typename dataT>
class mx::ioutils::fits::fitsFile< dataT >
Class to manage interactions with a FITS file.
This class wraps the functionality of cfitsio.
Template Parameters
dataT is the datatype to use for in-memory storage of the image. This does not have to match the data type stored on disk.
Definition at line 55 of file fitsFile.hpp.
#include <ioutils/fits/fitsFile.hpp>
Public Member Functions
fitsFile ()
Default constructor.
fitsFile (const std::string &fname, bool doopen=true)
Constructor with _fileName, and option to open.
~fitsFile ()
Destructor.
std::string fileName ()
Get the current value of _fileName.
int fileName (const std::string &fname, bool doopen=true)
Set the file path, and optionally open the file.
int naxis ()
Get the current value of _naxis.
long naxes (int dim)
Get the current value of m_naxes for the specified dimension.
int open ()
Open the file.
int open (const std::string &fname)
Open the file, first setting the file path.
int close ()
Close the file.
int getDimensions ()
Get the number of dimensions (i.e. _naxis)
long getSize ()
Get the total size.
long getSize (size_t axis)
Get the size of a specific dimension.
Reading Basic Arrays
These methods read FITS data into basic or raw arrays specified by a pointer.
int read (dataT *data)
Read the contents of the FITS file into an array.
int read (dataT *data, fitsHeader &head)
Read the contents of the FITS file into an array.
int read (dataT *data, const std::string &fname)
Read the contents of the FITS file into an array.
int read (dataT *data, fitsHeader &head, const std::string &fname)
Read the contents of the FITS file into an array and read the header.
int read (dataT *im, const std::vector< std::string > &flist)
Read data from a vector list of files into an image cube.
int read (dataT *im, std::vector< fitsHeader > &heads, const std::vector< std::string > &flist)
Read data from a vector of files into an image cube with individual headers.
Reading Eigen Arrays
These methods read FITS data into array types with an Eigen-like interface.
template<typename arrT >
int read (arrT &data)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename arrT >
int read (arrT &data, fitsHeader &head)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename arrT >
int read (arrT &data, const std::string &fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename arrT >
int read (arrT &data, fitsHeader &head, const std::string &fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename cubeT >
int read (cubeT &cube, const std::vector< std::string > &flist, std::vector< fitsHeader > *heads=0)
Read data from a vector list of files into an image cube.
template<typename cubeT >
int read (cubeT &cube, std::vector< fitsHeader > &heads, const std::vector< std::string > &flist)
Read data from a vector of files into an image cube with individual headers.
Reading Headers
int readHeader (fitsHeader &head)
Read the header from the fits file.
int readHeader (fitsHeader &head, const std::string &fname)
Read the header from the fits file.
int readHeader (std::vector< fitsHeader > &heads, const std::vector< std::string > &flist)
Read the headers from a list of FITS files.
Writing Basic Arrays
These methods write basic arrays specified by a pointer to FITS.
int write (const dataT *im, int d1, int d2, int d3, fitsHeader *head)
Write the contents of a raw array to the FITS file.
int write (const dataT *im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
int write (const dataT *im, int d1, int d2, int d3, fitsHeader &head)
Write the contents of a raw array to the FITS file.
int write (const std::string &fname, const dataT *im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
int write (const std::string &fname, const dataT *im, int d1, int d2, int d3, fitsHeader &head)
Write the contents of a raw array to the FITS file.
Writing Eigen Arrays
These methods write array types with an Eigen-like interface.
template<typename arrT >
int write (const std::string &fname, const arrT &im)
Write the contents of an Eigen-type array to a FITS file.
template<typename arrT >
int write (const std::string &fname, const arrT &im, fitsHeader &head)
Write the contents of an Eigen-type array to a FITS file.
Reading Subsets
It is often desirable to read only a subset of an image or images into memory. These methods allow you to specify this.
void setReadSize ()
Set to read all the pixels in the file.
void setReadSize (long x0, long y0, long xpix, long ypix)
Set to read only a subset of the pixels in the file.
Protected Member Functions
void construct ()
One time initialization common to all constructors.
Protected Attributes
std::string _fileName
The path to the file.
fitsfile * _fptr {nullptr}
The cfitsio data structure.
int _naxis
The dimensions of the image (1D, 2D, 3D etc)
long * m_naxes {nullptr}
The size of each dimension.
bool _isOpen
Flag indicating whether the file is open or not.
dataT _nulval
The value to replace null values with.
int _anynul
Records whether any null values were replaced.
int _noComment
Flag to control whether the comment string is read.
long _x0
The starting x-pixel to read from.
long _y0
The starting y-pixel to read from.
long _xpix
The number of x-pixels to read.
long _ypix
The number of y-pixels to read.
Constructor & Destructor Documentation
fitsFile() [1/2]
template<typename dataT > mx::ioutils::fits::fitsFile< dataT >::fitsFile
Default constructor.
Definition at line 531 of file fitsFile.hpp.
fitsFile() [2/2]
template<typename dataT > mx::ioutils::fits::fitsFile< dataT >::fitsFile (const std::string & fname, bool doopen = true)
Constructor with _fileName, and option to open.
Parameters
fname File name to set on construction
doopen If true, then the file is opened (the default).
Definition at line 537 of file fitsFile.hpp.
~fitsFile()
template<typename dataT > mx::ioutils::fits::fitsFile< dataT >::~fitsFile
Destructor.
Definition at line 544 of file fitsFile.hpp.
Member Function Documentation
close()
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::close
Close the file.
Returns
0 on success
-1 on error
Definition at line 643 of file fitsFile.hpp.
References mx::ioutils::fits::fitsErrText(), MXE_FILECERR, and mxError.
construct()
template<typename dataT > void mx::ioutils::fits::fitsFile< dataT >::construct protected
One time initialization common to all constructors.
Definition at line 517 of file fitsFile.hpp.
fileName() [1/2]
template<typename dataT > std::string mx::ioutils::fits::fitsFile< dataT >::fileName
Get the current value of _fileName.
Returns
the current value of _fileName.
Definition at line 552 of file fitsFile.hpp.
fileName() [2/2]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::fileName (const std::string & fname, bool doopen = true)
Set the file path, and optionally open the file.
Returns
0 on success
-1 on success
Parameters
fname The new file name.
doopen If true, then the file is opened (the default).
Definition at line 558 of file fitsFile.hpp.
getDimensions()
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::getDimensions
Get the number of dimensions (i.e. _naxis)
Definition at line 676 of file fitsFile.hpp.
getSize() [1/2]
template<typename dataT > long mx::ioutils::fits::fitsFile< dataT >::getSize
Get the total size.
Definition at line 684 of file fitsFile.hpp.
getSize() [2/2]
template<typename dataT > long mx::ioutils::fits::fitsFile< dataT >::getSize (size_t axis)
Get the size of a specific dimension.
Definition at line 703 of file fitsFile.hpp.
naxes()
template<typename dataT > long mx::ioutils::fits::fitsFile< dataT >::naxes (int dim)
Get the current value of m_naxes for the specified dimension.
Returns
the current value of m_naxes for the specified dimension
Parameters
[in] dim [in] the dimension
Definition at line 583 of file fitsFile.hpp.
naxis()
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::naxis
Get the current value of _naxis.
Returns
the current value of _naxis
Definition at line 577 of file fitsFile.hpp.
open() [1/2]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::open
Open the file.
File name needs to already have been set.
Returns
0 on success
-1 on error
Definition at line 591 of file fitsFile.hpp.
References mx::ioutils::fits::fitsErrText(), MXE_FILEOERR, MXE_FILERERR, and mxError.
open() [2/2]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::open (const std::string & fname)
Open the file, first setting the file path.
Returns
0 on success
-1 on error
Parameters
fname The name of the file to open.
Definition at line 637 of file fitsFile.hpp.
read() [1/12]
template<typename dataT > template<typename arrT > int mx::ioutils::fits::fitsFile< dataT >::read (arrT & data)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data [out] is the array, which will be resized as necessary using its resize(int, int) member
Definition at line 899 of file fitsFile.hpp.
References mx::ioutils::fits::fitsErrText(), MXE_FILERERR, and mxError.
read() [2/12]
template<typename dataT > template<typename arrT > int mx::ioutils::fits::fitsFile< dataT >::read (arrT & data, const std::string & fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data [out] is the array, which will be resized as necessary using its resize(int, int) member
[in] fname [in] is the file path, which is passed to fileName
Definition at line 983 of file fitsFile.hpp.
read() [3/12]
template<typename dataT > template<typename arrT > int mx::ioutils::fits::fitsFile< dataT >::read (arrT & data, fitsHeader & head)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data [out] is the array, which will be resized as necessary using its resize(int, int) member
[out] head [out] is a fitsHeader object which is passed to readHeader
Definition at line 974 of file fitsFile.hpp.
read() [4/12]
template<typename dataT > template<typename arrT > int mx::ioutils::fits::fitsFile< dataT >::read (arrT & data, fitsHeader & head, const std::string & fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data [out] the array, which will be resized as necessary using its resize(int, int) member
[out] head [out] a fitsHeader object which is passed to readHeader
[in] fname [in] the file path, which is passed to fileName
Definition at line 994 of file fitsFile.hpp.
read() [5/12]
template<typename dataT > template<typename cubeT > int mx::ioutils::fits::fitsFile< dataT >::read (cubeT & cube, const std::vector< std::string > & flist, std::vector< fitsHeader > * heads = 0)
Read data from a vector list of files into an image cube.
The type cubeT can be any type with the following members defined:
resize(int, int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef cubeT::Scalar (is the data type, does not have to be dataT)
Note
The images must all be the same size, or all be as large or larger than the subset specified.
Template Parameters
cubeT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] cube [out] A cube which will be resized using its resize(int, int, int) member.
[in] flist [in] The list of files to read.
[out] heads [out] [optional] A vector of fits headers, allocated to contain one per image.
Definition at line 1009 of file fitsFile.hpp.
References mx::ioutils::fits::fitsErrText(), MXE_FILERERR, MXE_PARAMNOTSET, and mxError.
read() [6/12]
template<typename dataT > template<typename cubeT > int mx::ioutils::fits::fitsFile< dataT >::read (cubeT & cube, std::vector< fitsHeader > & heads, const std::vector< std::string > & flist)
Read data from a vector of files into an image cube with individual headers.
The type cubeT can be any type with the following members defined:
resize(int, int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef cubeT::Scalar (is the data type, does not have to be dataT)
Template Parameters
cubeT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] cube [out] A cube which will be resized using its resize(int, int, int) member.
[out] heads [out] The vector of fits headers, allocated to contain one per image.
[in] flist [in] The list of files to read.
Definition at line 1122 of file fitsFile.hpp.
read() [7/12]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::read (dataT * data)
Read the contents of the FITS file into an array.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data [out] an allocated arrray large enough to hold the entire image
Definition at line 723 of file fitsFile.hpp.
References mx::ioutils::fits::fitsErrText(), MXE_FILERERR, and mxError.
read() [8/12]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::read (dataT * data, const std::string & fname)
Read the contents of the FITS file into an array.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data [out] is an allocated arrray large enough to hold the entire image
[in] fname [in] is the file path, which is passed to fileName
Definition at line 795 of file fitsFile.hpp.
read() [9/12]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::read (dataT * data, fitsHeader & head)
Read the contents of the FITS file into an array.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data [out] an allocated arrray large enough to hold the entire image
[out] head [out] a fitsHeader object which is passed to readHeader
Definition at line 784 of file fitsFile.hpp.
read() [10/12]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::read (dataT * data, fitsHeader & head, const std::string & fname)
Read the contents of the FITS file into an array and read the header.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data [out] an allocated arrray large enough to hold the entire image
[out] head [out] a fitsHeader object which is passed to readHeader
[in] fname [in] the file path, which is passed to fileName
Definition at line 804 of file fitsFile.hpp.
read() [11/12]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::read (dataT * im, const std::vector< std::string > & flist)
Read data from a vector list of files into an image cube.
Parameters
[out] im [out] An allocated array large enough to hold all the images
[in] flist [in] The list of files to read.
Definition at line 815 of file fitsFile.hpp.
References MXE_PARAMNOTSET, and mxError.
read() [12/12]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::read (dataT * im, std::vector< fitsHeader > & heads, const std::vector< std::string > & flist)
Read data from a vector of files into an image cube with individual headers.
Parameters
[out] im [out] An allocated array large enough to hold all the images
[in,out] heads [in/out] The vector of fits headers, allocated to contain one per image.
[in] flist [in] The list of files to read.
Definition at line 841 of file fitsFile.hpp.
References MXE_PARAMNOTSET, and mxError.
readHeader() [1/3]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::readHeader (fitsHeader & head)
Read the header from the fits file.
If head is not empty, then only the keywords already in head are updated. Otherwise the complete header is read.
Returns
0 on success
-1 on error
Parameters
[out] head [out] a fitsHeader object
Definition at line 1131 of file fitsFile.hpp.
References mx::ioutils::fits::fitsHeader::append(), mx::ioutils::fits::fitsHeader::begin(), mx::ioutils::fits::fitsHeader::end(), mx::ioutils::fits::fitsHeader::erase(), mx::ioutils::fits::fitsErrText(), MXE_FILERERR, mxError, and mx::ioutils::fits::fitsHeader::size().
readHeader() [2/3]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::readHeader (fitsHeader & head, const std::string & fname)
Read the header from the fits file.
If head is not empty, then only the keywords already in head are updated. Otherwise the complete header is read.
Returns
0 on success
-1 on error
Parameters
[out] head [out] a fitsHeader object
[in] fname [in] the file path, which is passed to fileName
Definition at line 1248 of file fitsFile.hpp.
readHeader() [3/3]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::readHeader (std::vector< fitsHeader > & heads, const std::vector< std::string > & flist)
Read the headers from a list of FITS files.
In each case, if the header is not empty then only the keywords already in head are updated. Otherwise the complete header is read.
Returns
0 on success
-1 on error
Parameters
flist A vector of fitsHeader objects to read into. [in] A list of files, each of which is passed to fileName
Definition at line 1257 of file fitsFile.hpp.
setReadSize() [1/2]
template<typename dataT > void mx::ioutils::fits::fitsFile< dataT >::setReadSize
Set to read all the pixels in the file.
Definition at line 1429 of file fitsFile.hpp.
setReadSize() [2/2]
template<typename dataT > void mx::ioutils::fits::fitsFile< dataT >::setReadSize (long x0, long y0, long xpix, long ypix)
Set to read only a subset of the pixels in the file.
Parameters
x0 is the starting x-pixel to read
y0 is the starting y-pixel to read
xpix is the number of x-pixels to read
ypix is the number of y-pixels to read
Definition at line 1438 of file fitsFile.hpp.
write() [1/7]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::write (const dataT * im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] im [in] is the array
[in] d1 [in] is the first dimension
[in] d2 [in] is the second dimension
[in] d3 [in] is the third dimenesion (minimum value is 1)
Definition at line 1358 of file fitsFile.hpp.
write() [2/7]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::write (const dataT * im, int d1, int d2, int d3, fitsHeader & head)
Write the contents of a raw array to the FITS file.
Note: the type of the array must match dataT
Returns
0 on success
-1 on error
Parameters
[in] im [in] is the array
[in] d1 [in] is the first dimension
[in] d2 [in] is the second dimension
[in] d3 [in] is the third dimenesion (minimum value is 1)
[in] head [in] is the header
Definition at line 1368 of file fitsFile.hpp.
write() [3/7]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::write (const dataT * im, int d1, int d2, int d3, fitsHeader * head)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] im [in] is the array
[in] d1 [in] is the first dimension
[in] d2 [in] is the second dimension
[in] d3 [in] is the third dimenesion (minimum value is 1)
[in] head [in] a pointer to the header. Set to 0 if not used.
Definition at line 1273 of file fitsFile.hpp.
References mx::ioutils::fits::fitsHeader::begin(), mx::ioutils::fits::fitsHeader::end(), mx::ioutils::fits::fitsErrText(), MXE_FILEOERR, MXE_FILEWERR, and mxError.
write() [4/7]
template<typename dataT > template<typename arrT > int mx::ioutils::fits::fitsFile< dataT >::write (const std::string & fname, const arrT & im)
Write the contents of an Eigen-type array to a FITS file.
The type arrT can be any type with the following members defined:
data() (returns a pointer to the underlying array)
rows() (returrns the number of rows)
cols() (returns the number of columns)
may have planes() defined
Note: as with all write methods, the Scalar type of the array must match dataT
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[in] fname [in] is the name of the file.
[in] im [in] is the array
Definition at line 1406 of file fitsFile.hpp.
write() [5/7]
template<typename dataT > template<typename arrT > int mx::ioutils::fits::fitsFile< dataT >::write (const std::string & fname, const arrT & im, fitsHeader & head)
Write the contents of an Eigen-type array to a FITS file.
The type arrT can be any type with the following members defined:
data() (returns a pointer to the underlying array)
rows() (returrns the number of rows)
cols() (returns the number of columns)
may have planes() defined.
Note: as with all write methods, the Scalar type of the array must match dataT
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[in] fname [in] is the file path, which is passed to fileName
[in] im [in] is the array
[in] head [in] is a fitsHeader object which is passed to readHeader
Definition at line 1418 of file fitsFile.hpp.
write() [6/7]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::write (const std::string & fname, const dataT * im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] fname [in] is the name of the file.
[in] im [in] is the array
[in] d1 [in] is the first dimension
[in] d2 [in] is the second dimension
[in] d3 [in] is the third dimenesion (minimum value is 1)
Definition at line 1379 of file fitsFile.hpp.
write() [7/7]
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::write (const std::string & fname, const dataT * im, int d1, int d2, int d3, fitsHeader & head)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] fname [in] is the name of the file.
[in] im [in] is the array
[in] d1 [in] is the first dimension
[in] d2 [in] is the second dimension
[in] d3 [in] is the third dimenesion (minimum value is 1)
[in] head [in] is the header
Definition at line 1391 of file fitsFile.hpp.
Member Data Documentation
_anynul
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::_anynul protected
Records whether any null values were replaced.
Definition at line 79 of file fitsFile.hpp.
_fileName
template<typename dataT > std::string mx::ioutils::fits::fitsFile< dataT >::_fileName protected
The path to the file.
Definition at line 61 of file fitsFile.hpp.
_fptr
template<typename dataT > fitsfile* mx::ioutils::fits::fitsFile< dataT >::_fptr {nullptr} protected
The cfitsio data structure.
Definition at line 64 of file fitsFile.hpp.
_isOpen
template<typename dataT > bool mx::ioutils::fits::fitsFile< dataT >::_isOpen protected
Flag indicating whether the file is open or not.
Definition at line 73 of file fitsFile.hpp.
_naxis
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::_naxis protected
The dimensions of the image (1D, 2D, 3D etc)
Definition at line 67 of file fitsFile.hpp.
_noComment
template<typename dataT > int mx::ioutils::fits::fitsFile< dataT >::_noComment protected
Flag to control whether the comment string is read.
Definition at line 82 of file fitsFile.hpp.
_nulval
template<typename dataT > dataT mx::ioutils::fits::fitsFile< dataT >::_nulval protected
The value to replace null values with.
Definition at line 76 of file fitsFile.hpp.
_x0
template<typename dataT > long mx::ioutils::fits::fitsFile< dataT >::_x0 protected
The starting x-pixel to read from.
Definition at line 86 of file fitsFile.hpp.
_xpix
template<typename dataT > long mx::ioutils::fits::fitsFile< dataT >::_xpix protected
The number of x-pixels to read.
Definition at line 92 of file fitsFile.hpp.
_y0
template<typename dataT > long mx::ioutils::fits::fitsFile< dataT >::_y0 protected
The starting y-pixel to read from.
Definition at line 89 of file fitsFile.hpp.
_ypix
template<typename dataT > long mx::ioutils::fits::fitsFile< dataT >::_ypix protected
The number of y-pixels to read.
Definition at line 95 of file fitsFile.hpp.
m_naxes
template<typename dataT > long* mx::ioutils::fits::fitsFile< dataT >::m_naxes {nullptr} protected
The size of each dimension.
Definition at line 70 of file fitsFile.hpp.
The documentation for this class was generated from the following file:
ioutils/fits/fitsFile.hpp