mxlib: mx::AO::sim::directPhaseReconstructor< realT > Class Template Reference
mx::AO::sim::directPhaseReconstructor< realT > Class Template Reference
template<typename realT>
class mx::AO::sim::directPhaseReconstructor< realT >
Direct Phase Reconstructor.
A Pyramid Wavefront Sensor slope reconstructor.
Calculates modal amplitudes by direct projection of modes onto the phase screen.
Calculates slopes, normalized by total flux in the image.
Definition at line 40 of file directPhaseReconstructor.hpp.
#include <ao/sim/directPhaseReconstructor.hpp>
Public Types
typedef Eigen::Array< realT, -1, -1 > imageT
The type of the WFS image.
typedef Eigen::Array< realT, -1, -1 > rmatT
The type of the response matrix.
typedef directPhaseReconstructorSpec specT
The specificaion type.
typedef Eigen::Array< realT, -1, -1 > imageT
The type of the measurement (i.e. the slope vector)
typedef Eigen::Array< realT, -1, -1 > rmatT
The type of the response matrix.
typedef Eigen::Array< realT, -1, -1 > imageT
The type of the measurement (i.e. the slope vector)
typedef Eigen::Array< realT, -1, -1 > rmatT
The type of the response matrix.
Public Member Functions
directPhaseReconstructor ()
Default c'tor.
realT calAmp ()
Get the calibration amplitude used in response matrix acquisition (m_calAmp)
void calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (m_calAmp)
int nModes ()
Get the number of modes (m_nModes)
int detRows ()
Get the number of detector rows (m_detRows)
void detRows (int dr)
Set the number of detector rows (m_detRows)
int detCols ()
Get the number of detector columns (m_detCols)
void detCols (int dc)
Set the number of detector columns (m_detCols)
void loadRecon (const std::string &fname)
Load the reconstrutor from the specified FITS file.
int measurementSize ()
Return the size of the unbinned measurement.
template<typename measurementT , typename wfsImageT >
void calcMeasurement (measurementT &slopes, wfsImageT &wfsImage)
Calculate the slope measurement.
template<typename measurementT , typename wfsImageT >
void reconstruct (measurementT &commandVect, wfsImageT &wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
void initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
template<typename measurementT >
void accumulateRMat (int i, measurementT &measureVec)
Accumalte the next measurement in the response matrix.
void saveRMat (std::string fname)
Write the accumulated response matrix to disk.
directPhaseReconstructor ()
Default c'tor.
realT calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
void calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
int nModes ()
Get the number of modes (_nModes)
int detRows ()
Get the number of detector rows (_detRows)
void detRows (int dr)
Set the number of detector rows (_detRows)
int detCols ()
Get the number of detector columns (_detCols)
void detCols (int dc)
Set the number of detector columns (_detCols)
void loadRecon (std::string fname)
Load the reconstrutor from the specified FITS file.
int measurementSize ()
Return the size of the unbinned measurement.
template<typename measurementT , typename wfsImageT >
void calcMeasurement (measurementT &slopes, wfsImageT &wfsImage)
Calculate the slope measurement.
template<typename measurementT , typename wfsImageT >
void reconstruct (measurementT &commandVect, wfsImageT &wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
void initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
template<typename measurementT >
void accumulateRMat (int i, measurementT &measureVec)
Accumalte the next measurement in the response matrix.
void saveRMat (std::string fname)
Write the accumulated response matrix to disk.
directPhaseReconstructor ()
Default c'tor.
realT calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
void calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
int nModes ()
Get the number of modes (_nModes)
int detRows ()
Get the number of detector rows (_detRows)
void detRows (int dr)
Set the number of detector rows (_detRows)
int detCols ()
Get the number of detector columns (_detCols)
void detCols (int dc)
Set the number of detector columns (_detCols)
void loadRecon (const std::string &fname)
Load the reconstrutor from the specified FITS file.
int measurementSize ()
Return the size of the unbinned measurement.
template<typename measurementT , typename wfsImageT >
void calcMeasurement (measurementT &slopes, wfsImageT &wfsImage)
Calculate the slope measurement.
template<typename measurementT , typename wfsImageT >
void reconstruct (measurementT &commandVect, wfsImageT &wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
void initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
template<typename measurementT >
void accumulateRMat (int i, measurementT &measureVec)
Accumalte the next measurement in the response matrix.
void saveRMat (std::string fname)
Write the accumulated response matrix to disk.
Protected Attributes
realT m_calAmp { 1e-6 }
The offset coordinates of non-zero pixels in the pupil. Set by the DM.
imageT m_rMat
The response matrix.
Eigen::Array< realT, -1, -1 > _recon
The reconstructor matrix.
imageT _rMat
The response matrix.
int _nModes { 0 }
The number of modes to be reconstructed.
int _detRows { 0 }
The size of the WFS image, in rows.
int _detCols { 0 }
The size of the WFS image, in columns.
int _measurementSize { 0 }
The number of values in the measurement.
realT _calAmp
The calibration amplitude used for response matrix acquisition.
The Pupil
The Basis
improc::eigenCube< realT > * m_modes { nullptr }
The mirror modes, managed by the DM.
int m_nModes { 0 }
The number of modes to be reconstructed.
int m_detRows { 0 }
The size of the WFS image, in rows.
int m_detCols { 0 }
The size of the WFS image, in columns.
The Reconstructor
Eigen::Array< realT, -1, -1 > m_recon
The reconstructor matrix.
int m_measurementSize { 0 }
The number of values in the measurement.
Member Typedef Documentation
imageT [1/3]
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::imageT
The type of the WFS image.
Definition at line 44 of file directPhaseReconstructor.hpp.
imageT [2/3]
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::imageT
The type of the measurement (i.e. the slope vector)
The type of the WFS image
Definition at line 43 of file directPhaseReconstructorD.hpp.
imageT [3/3]
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::imageT
The type of the measurement (i.e. the slope vector)
The type of the WFS image
Definition at line 43 of file directPhaseReconstructorOrtho.hpp.
rmatT [1/3]
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::rmatT
The type of the response matrix.
Definition at line 47 of file directPhaseReconstructor.hpp.
rmatT [2/3]
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::rmatT
The type of the response matrix.
Definition at line 46 of file directPhaseReconstructorD.hpp.
rmatT [3/3]
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::rmatT
The type of the response matrix.
Definition at line 46 of file directPhaseReconstructorOrtho.hpp.
specT
template<typename realT > typedef directPhaseReconstructorSpec mx::AO::sim::directPhaseReconstructor< realT >::specT
The specificaion type.
Definition at line 50 of file directPhaseReconstructor.hpp.
Constructor & Destructor Documentation
directPhaseReconstructor() [1/3]
template<typename realT > mx::AO::sim::directPhaseReconstructor< realT >::directPhaseReconstructor ()
Default c'tor.
Definition at line 181 of file directPhaseReconstructor.hpp.
directPhaseReconstructor() [2/3]
template<typename realT > mx::AO::sim::directPhaseReconstructor< realT >::directPhaseReconstructor ()
Default c'tor.
directPhaseReconstructor() [3/3]
template<typename realT > mx::AO::sim::directPhaseReconstructor< realT >::directPhaseReconstructor ()
Default c'tor.
Member Function Documentation
accumulateRMat() [1/3]
template<typename realT > template<typename measurementT > void mx::AO::sim::directPhaseReconstructor< realT >::accumulateRMat (int i, measurementT & measureVec)
Accumalte the next measurement in the response matrix.
Parameters
i the measurement index
measureVec is the i-th measurement vector
Definition at line 399 of file directPhaseReconstructor.hpp.
accumulateRMat() [2/3]
template<typename realT > template<typename measurementT > void mx::AO::sim::directPhaseReconstructor< realT >::accumulateRMat (int i, measurementT & measureVec)
Accumalte the next measurement in the response matrix.
Parameters
i the measurement index
measureVec is the i-th measurement vector
accumulateRMat() [3/3]
template<typename realT > template<typename measurementT > void mx::AO::sim::directPhaseReconstructor< realT >::accumulateRMat (int i, measurementT & measureVec)
Accumalte the next measurement in the response matrix.
Parameters
i the measurement index
measureVec is the i-th measurement vector
calAmp() [1/6]
template<typename realT > realT mx::AO::sim::directPhaseReconstructor< realT >::calAmp ()
Get the calibration amplitude used in response matrix acquisition (m_calAmp)
Definition at line 251 of file directPhaseReconstructor.hpp.
References mx::math::six_fifths().
calAmp() [2/6]
template<typename realT > realT mx::AO::sim::directPhaseReconstructor< realT >::calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
calAmp() [3/6]
template<typename realT > realT mx::AO::sim::directPhaseReconstructor< realT >::calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
calAmp() [4/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (m_calAmp)
Parameters
ca [in] the new calibration amplitude
Definition at line 257 of file directPhaseReconstructor.hpp.
calAmp() [5/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
Parameters
ca [in] the new calibration amplitude
calAmp() [6/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
Parameters
ca [in] the new calibration amplitude
calcMeasurement() [1/3]
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::calcMeasurement (measurementT & slopes, wfsImageT & wfsImage)
Calculate the slope measurement.
Parameters
slopes [out] a (m_measurementSize X 2) array of slopes
wfsImage [in] the WFS image from which to measure the slopes
Definition at line 299 of file directPhaseReconstructor.hpp.
calcMeasurement() [2/3]
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::calcMeasurement (measurementT & slopes, wfsImageT & wfsImage)
Calculate the slope measurement.
Parameters
slopes [out] a (_measurementSize X 2) array of slopes
wfsImage [in] the WFS image from which to measure the slopes
calcMeasurement() [3/3]
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::calcMeasurement (measurementT & slopes, wfsImageT & wfsImage)
Calculate the slope measurement.
Parameters
slopes [out] a (_measurementSize X 2) array of slopes
wfsImage [in] the WFS image from which to measure the slopes
detCols() [1/6]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detCols ()
Get the number of detector columns (m_detCols)
Definition at line 275 of file directPhaseReconstructor.hpp.
detCols() [2/6]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detCols ()
Get the number of detector columns (_detCols)
detCols() [3/6]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detCols ()
Get the number of detector columns (_detCols)
detCols() [4/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detCols (int dc)
Set the number of detector columns (m_detCols)
detCols() [5/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detCols (int dc)
Set the number of detector columns (_detCols)
detCols() [6/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detCols (int dc)
Set the number of detector columns (_detCols)
detRows() [1/6]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detRows ()
Get the number of detector rows (m_detRows)
Definition at line 269 of file directPhaseReconstructor.hpp.
detRows() [2/6]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detRows ()
Get the number of detector rows (_detRows)
detRows() [3/6]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detRows ()
Get the number of detector rows (_detRows)
detRows() [4/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detRows (int dr)
Set the number of detector rows (m_detRows)
detRows() [5/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detRows (int dr)
Set the number of detector rows (_detRows)
detRows() [6/6]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detRows (int dr)
Set the number of detector rows (_detRows)
initializeRMat() [1/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
Parameters
nmodes the number of modes
calamp the calibration amplitude
detrows the number of detector rows
detcols the number of detector columns
Definition at line 384 of file directPhaseReconstructor.hpp.
initializeRMat() [2/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
Parameters
nmodes the number of modes
calamp the calibration amplitude
detrows the number of detector rows
detcols the number of detector columns
initializeRMat() [3/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
Parameters
nmodes the number of modes
calamp the calibration amplitude
detrows the number of detector rows
detcols the number of detector columns
loadRecon() [1/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::loadRecon (const std::string & fname)
Load the reconstrutor from the specified FITS file.
Parameters
fname is the name of the FITS file, including path
Definition at line 281 of file directPhaseReconstructor.hpp.
References mx::fits::fitsFile< dataT, verboseT >::read().
loadRecon() [2/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::loadRecon (const std::string & fname)
Load the reconstrutor from the specified FITS file.
Parameters
fname is the name of the FITS file, including path
loadRecon() [3/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::loadRecon (std::string fname)
Load the reconstrutor from the specified FITS file.
Parameters
fname is the name of the FITS file, including path
Definition at line 249 of file directPhaseReconstructorD.hpp.
measurementSize() [1/3]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::measurementSize ()
Return the size of the unbinned measurement.
Definition at line 292 of file directPhaseReconstructor.hpp.
measurementSize() [2/3]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::measurementSize ()
Return the size of the unbinned measurement.
measurementSize() [3/3]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::measurementSize ()
Return the size of the unbinned measurement.
nModes() [1/3]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::nModes ()
Get the number of modes (m_nModes)
Definition at line 263 of file directPhaseReconstructor.hpp.
nModes() [2/3]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::nModes ()
Get the number of modes (_nModes)
nModes() [3/3]
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::nModes ()
Get the number of modes (_nModes)
reconstruct() [1/3]
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::reconstruct (measurementT & commandVect, wfsImageT & wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
Definition at line 312 of file directPhaseReconstructor.hpp.
reconstruct() [2/3]
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::reconstruct (measurementT & commandVect, wfsImageT & wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
reconstruct() [3/3]
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::reconstruct (measurementT & commandVect, wfsImageT & wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
saveRMat() [1/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::saveRMat (std::string fname)
Write the accumulated response matrix to disk.
Parameters
fname the name, including path, of the response matrix
Definition at line 423 of file directPhaseReconstructor.hpp.
References mx::fits::fitsHeader< verboseT >::append(), and mx::fits::fitsFile< dataT, verboseT >::write().
saveRMat() [2/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::saveRMat (std::string fname)
Write the accumulated response matrix to disk.
Parameters
fname the name, including path, of the response matrix
saveRMat() [3/3]
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::saveRMat (std::string fname)
Write the accumulated response matrix to disk.
Parameters
fname the name, including path, of the response matrix
Member Data Documentation
_calAmp
template<typename realT > realT mx::AO::sim::directPhaseReconstructor< realT >::_calAmp protected
The calibration amplitude used for response matrix acquisition.
Definition at line 60 of file directPhaseReconstructorOrtho.hpp.
_detCols
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_detCols { 0 } protected
The size of the WFS image, in columns.
Definition at line 59 of file directPhaseReconstructorD.hpp.
_detRows
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_detRows { 0 } protected
The size of the WFS image, in rows.
Definition at line 58 of file directPhaseReconstructorD.hpp.
_measurementSize
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_measurementSize { 0 } protected
The number of values in the measurement.
Definition at line 61 of file directPhaseReconstructorD.hpp.
_nModes
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_nModes { 0 } protected
The number of modes to be reconstructed.
Definition at line 56 of file directPhaseReconstructorD.hpp.
_recon
template<typename realT > Eigen::Array< realT, -1, -1 > mx::AO::sim::directPhaseReconstructor< realT >::_recon protected
The reconstructor matrix.
Definition at line 51 of file directPhaseReconstructorD.hpp.
_rMat
template<typename realT > imageT mx::AO::sim::directPhaseReconstructor< realT >::_rMat protected
The response matrix.
Definition at line 53 of file directPhaseReconstructorD.hpp.
m_calAmp
template<typename realT > realT mx::AO::sim::directPhaseReconstructor< realT >::m_calAmp { 1e-6 } protected
The offset coordinates of non-zero pixels in the pupil. Set by the DM.
The calibration amplitude used for response matrix acquisition
Definition at line 93 of file directPhaseReconstructor.hpp.
m_detCols
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::m_detCols { 0 } protected
The size of the WFS image, in columns.
Definition at line 68 of file directPhaseReconstructor.hpp.
m_detRows
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::m_detRows { 0 } protected
The size of the WFS image, in rows.
Definition at line 67 of file directPhaseReconstructor.hpp.
m_measurementSize
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::m_measurementSize { 0 } protected
The number of values in the measurement.
Definition at line 89 of file directPhaseReconstructor.hpp.
m_modes
template<typename realT > improc::eigenCube<realT>* mx::AO::sim::directPhaseReconstructor< realT >::m_modes { nullptr } protected
The mirror modes, managed by the DM.
Definition at line 63 of file directPhaseReconstructor.hpp.
m_nModes
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::m_nModes { 0 } protected
The number of modes to be reconstructed.
Definition at line 65 of file directPhaseReconstructor.hpp.
m_recon
template<typename realT > Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::m_recon protected
The reconstructor matrix.
Definition at line 86 of file directPhaseReconstructor.hpp.
m_rMat
template<typename realT > imageT mx::AO::sim::directPhaseReconstructor< realT >::m_rMat protected
The response matrix.
Definition at line 95 of file directPhaseReconstructor.hpp.
The documentation for this class was generated from the following files:
ao/sim/directPhaseReconstructor.hpp
ao/sim/directPhaseReconstructorD.hpp
ao/sim/directPhaseReconstructorOrtho.hpp