mxlib: mx::err::mxException Class Reference
mx::err::mxException Class Reference
The mxlib exception class.
Provides a rich error report via the standard what().
Definition at line 44 of file mxExceptionOld.hpp.
#include <error/mxExceptionOld.hpp>
Public Member Functions
mxException () noexcept
Default constructor.
mxException (const mxException &e) noexcept
Copy constructor.
mxException (const std::string &esrc, const int &ec, const std::string &emnem, const std::string &efile, const int &line, const std::string &expl)
Construct and fill in each of the values, except errno.
mxException (const std::string &esrc, const int &ec, const std::string &emnem, const int &en, const std::string &efile, const int &line, const std::string &expl)
Construct and fill in each of the values, including errno.
mxException & operator= (const mxException &e) noexcept
Assignment operator.
virtual ~mxException () throw ()
Destructor.
virtual void build_what ()
Build the what string.
virtual const char * what () const noexcept
Return the details of the exception as a single string.
Protected Attributes
char m_whatstr [4096]
Contains the what() string.
std::string m_source { "" }
The source of the exception, such as stdlib or cfitisio or the function name.
int m_code { 0 }
The mxlib error code.
std::string m_codeName { "" }
The name of the error code.
int m_errno { 0 }
The errno error code (only used if non-zero)
std::string m_file { "" }
The source file where the exception originated.
int m_line { 0 }
The line number of the file where the exception originated.
std::string m_explanation { "" }
The long explanation of the error.
Constructor & Destructor Documentation
mxException() [1/4]
mx::err::mxException::mxException () inline noexcept
Default constructor.
Definition at line 74 of file mxExceptionOld.hpp.
References build_what().
mxException() [2/4]
mx::err::mxException::mxException (const mxException & e) inline noexcept
Copy constructor.
Definition at line 80 of file mxExceptionOld.hpp.
References build_what().
mxException() [3/4]
mx::err::mxException::mxException (const std::string & esrc, const int & ec, const std::string & emnem, const std::string & efile, const int & line, const std::string & expl) inline
Construct and fill in each of the values, except errno.
Parameters
[in] esrc the source of the exception, typically the class and function
[in] ec the error code
[in] emnem the name of the error code
[in] efile the source file in which the exception occurred, normally FILE
[in] line the line number where the exception was thrown
[in] expl the explanation for why the exception was thrown
Definition at line 88 of file mxExceptionOld.hpp.
References build_what().
mxException() [4/4]
mx::err::mxException::mxException (const std::string & esrc, const int & ec, const std::string & emnem, const int & en, const std::string & efile, const int & line, const std::string & expl) inline
Construct and fill in each of the values, including errno.
Parameters
[in] esrc the source of the exception, typically the class and function
[in] ec the error code
[in] emnem the name of the error code
[in] en the value of errno
[in] efile the source file in which the exception occurred, normally FILE
[in] line the line number where the exception was thrown
[in] expl the explanation for why the exception was thrown
Definition at line 102 of file mxExceptionOld.hpp.
References build_what().
~mxException()
virtual mx::err::mxException::~mxException () throw () inline virtual
Destructor.
Definition at line 133 of file mxExceptionOld.hpp.
Member Function Documentation
build_what()
virtual void mx::err::mxException::build_what () inline virtual
Build the what string.
Must be called after updating any values, since the what() method is const const.
Definition at line 140 of file mxExceptionOld.hpp.
References mx::errno_CodeToName(), m_code, m_codeName, m_errno, m_explanation, m_file, m_line, m_source, and m_whatstr.
Referenced by mxException(), mxException(), mxException(), mxException(), and operator=().
operator=()
mxException & mx::err::mxException::operator= (const mxException & e) inline noexcept
Assignment operator.
Definition at line 117 of file mxExceptionOld.hpp.
References build_what(), m_code, m_codeName, m_errno, m_explanation, m_file, m_line, and m_source.
what()
virtual const char * mx::err::mxException::what () const inline virtual noexcept
Return the details of the exception as a single string.
Definition at line 172 of file mxExceptionOld.hpp.
References m_whatstr.
Member Data Documentation
m_code
int mx::err::mxException::m_code { 0 } protected
The mxlib error code.
Definition at line 55 of file mxExceptionOld.hpp.
Referenced by build_what(), and operator=().
m_codeName
std::string mx::err::mxException::m_codeName { "" } protected
The name of the error code.
Definition at line 58 of file mxExceptionOld.hpp.
Referenced by build_what(), and operator=().
m_errno
int mx::err::mxException::m_errno { 0 } protected
The errno error code (only used if non-zero)
Definition at line 61 of file mxExceptionOld.hpp.
Referenced by build_what(), and operator=().
m_explanation
std::string mx::err::mxException::m_explanation { "" } protected
The long explanation of the error.
Definition at line 70 of file mxExceptionOld.hpp.
Referenced by build_what(), and operator=().
m_file
std::string mx::err::mxException::m_file { "" } protected
The source file where the exception originated.
Definition at line 64 of file mxExceptionOld.hpp.
Referenced by build_what(), and operator=().
m_line
int mx::err::mxException::m_line { 0 } protected
The line number of the file where the exception originated.
Definition at line 67 of file mxExceptionOld.hpp.
Referenced by build_what(), and operator=().
m_source
std::string mx::err::mxException::m_source { "" } protected
The source of the exception, such as stdlib or cfitisio or the function name.
Definition at line 52 of file mxExceptionOld.hpp.
Referenced by build_what(), and operator=().
m_whatstr
char mx::err::mxException::m_whatstr[4096] protected
Contains the what() string.
Definition at line 49 of file mxExceptionOld.hpp.
Referenced by build_what(), and what().
The documentation for this class was generated from the following file:
error/mxExceptionOld.hpp