mxlib: mx::math::logInterpolator< interpT > Class Template Reference
mx::math::logInterpolator< interpT > Class Template Reference
General Mathematics » Interpolation
template<typename interpT>
class mx::math::logInterpolator< interpT >
Interpolate a function in log space.
Given a discrete function, conduct linear interpolation in log space. The input vectors are converted to their log10 values. Linear interpolation using gslInterpolator is conducted on the log10 of the input value. The output is converted back. So the result is
y = pow(10, interp(log10(x))).
Definition at line 52 of file logInterpolator.hpp.
#include <math/logInterpolator.hpp>
Public Member Functions
logInterpolator ()
Default constructor.
logInterpolator (const std::vector< realT > &x, const std::vector< realT > &y)
Convert the inputs to their log10 values, and construct the interpolator.
void setup (const std::vector< realT > &x, const std::vector< realT > &y)
Convert the inputs to their log10 values, and construct the interpolator.
realT operator() (const realT &x)
Calculate the interpolated value at the input.
Protected Attributes
gslInterpolator< interpT > m_interp
The interpolator.
std::vector< realT > m_logx
Internal storage of the log10 values of the x values.
std::vector< realT > m_logy
Internal storage of the lgo10 values of the y values.
Constructor & Destructor Documentation
logInterpolator() [1/2]
template<typename interpT > mx::math::logInterpolator< interpT >::logInterpolator () inline
Default constructor.
Definition at line 66 of file logInterpolator.hpp.
logInterpolator() [2/2]
template<typename interpT > mx::math::logInterpolator< interpT >::logInterpolator (const std::vector< realT > & x, const std::vector< realT > & y) inline
Convert the inputs to their log10 values, and construct the interpolator.
Exceptions
mxException if vectors are not the same size.
Parameters
[in] y the input x-axis [in] the input y-axis
Definition at line 74 of file logInterpolator.hpp.
References mx::math::logInterpolator< interpT >::setup().
Member Function Documentation
operator()()
template<typename interpT > realT mx::math::logInterpolator< interpT >::operator() (const realT & x) inline
Calculate the interpolated value at the input.
x.
Returns
the interpolated value
Definition at line 121 of file logInterpolator.hpp.
References mx::math::logInterpolator< interpT >::m_interp, and mx::math::six_fifths().
setup()
template<typename interpT > void mx::math::logInterpolator< interpT >::setup (const std::vector< realT > & x, const std::vector< realT > & y) inline
Convert the inputs to their log10 values, and construct the interpolator.
Exceptions
mx::err::sizeerr if vectors are not the same size.
mx::err::invalidarg if any of the values are <= 0
Parameters
[in] y the input x-axis [in] the input y-axis
Definition at line 86 of file logInterpolator.hpp.
References mx::invalidarg, mx::math::logInterpolator< interpT >::m_interp, mx::math::logInterpolator< interpT >::m_logx, mx::math::logInterpolator< interpT >::m_logy, mx::math::six_fifths(), and mx::sizeerr.
Referenced by mx::math::logInterpolator< interpT >::logInterpolator().
Member Data Documentation
m_interp
template<typename interpT > gslInterpolator<interpT> mx::math::logInterpolator< interpT >::m_interp protected
The interpolator.
Definition at line 59 of file logInterpolator.hpp.
Referenced by mx::math::logInterpolator< interpT >::operator()(), and mx::math::logInterpolator< interpT >::setup().
m_logx
template<typename interpT > std::vector<realT> mx::math::logInterpolator< interpT >::m_logx protected
Internal storage of the log10 values of the x values.
Definition at line 61 of file logInterpolator.hpp.
Referenced by mx::math::logInterpolator< interpT >::setup().
m_logy
template<typename interpT > std::vector<realT> mx::math::logInterpolator< interpT >::m_logy protected
Internal storage of the lgo10 values of the y values.
Definition at line 62 of file logInterpolator.hpp.
Referenced by mx::math::logInterpolator< interpT >::setup().
The documentation for this class was generated from the following file:
math/logInterpolator.hpp