mxlib: mx::improc::imageXCorrFFT< _realImageT > Class Template Reference
mx::improc::imageXCorrFFT< _realImageT > Class Template Reference
Image Processing » Image Registration
template<class _realImageT>
class mx::improc::imageXCorrFFT< _realImageT >
Find the optimum shift to align two images using the FFT cross correlation.
The reference image must be the same size as the target image. Both the reference image and the target image being analyzed can be masked, normalized by mean subtraction and variance division, and windowed. Seperate masks and windows for the reference and target image are used.
The reference mask, reference window, and normalization flag must be set before setting the reference (unless using the defaults). If the reference mask, reference window, or normalization flag are changed then the reference must be set again. After configuring the reference, then operator() can be called repeatedly to determine the shifts for a sequence of imaages. The mask and window can be changed between calls without requiring resetting the reference. No new heap allocations take place on these calls to operator(), and the reference image is not re-normalized on each call.
The shift is reported in pixels such that if the mxlib imageShift function is used to shift the input image by the negative of the shifts, it will align with the reference at the center of the array.
Several peak finding methods are provided:
xcorrPeakMethod::centerOfLight uses center of light
xcorrPeakMethod::gaussFit uses Gaussian centroiding
xcorrPeakMethod::interpPeak uses interpolation to find the peak to a given tolerance.
xcorrPeakMethod::none will just return the coordinate of the max pixel
This class uses the real-to-complex transforms of FFTW by default. This should offer improved speed and memory use. For testing the complex-to-complex transforms can be used by defining XCFFT_C2C before including this file.
Template Parameters
_realImageT is the Eigen-like array type used for image processing. Must have a real floating point Scalar type (float, double, etc.). See typedefs.
Definition at line 80 of file imageXCorrFFT.hpp.
#include <improc/imageXCorrFFT.hpp>
Public Types
typedef _realImageT realImageT
the Eigen-like array type used for image processing
typedef _realImageT::Scalar realT
the scalar type of the image type
typedef std::complex< realT > complexT
Complex floating point type.
typedef eigenImage< complexT > complexArrayT
Complex eigen array type with Scalar==complexT.
Public Member Functions
Construction and Destruction
imageXCorrFFT ()
Default c'tor.
Configuration Member Access
int rows ()
Get the number of rows in the input images.
int cols ()
Get the number of columns in the input images.
int padFactor (realT os)
Set the padding factor.
realT padFactor ()
Get the padding factor.
int rowsPadded ()
Get the number of rows in the padded cross-correlation.
int colsPadded ()
Get the number of rows in the padded cross-correlation.
int resize (int nrows, int ncols, realT padFactor)
Set the size of the cross-correlation problem based on input image size.
int resize (int nrows, int ncols)
Set the size of the cross-correlation problem based on input image size.
int refMaskIm (const realImageT &mask)
Set the reference mask image.
const realImageT & refMaskIm ()
Get a reference to the reference mask image.
bool haveRefMask ()
Get the value of the haveRefMask flag.
int maskIm (const realImageT &mask)
Set the mask image.
const realImageT & maskIm ()
Get a reference to the mask image.
bool haveMask ()
Get the value of the haveMask flag.
int refWinIm (const realImageT &win)
Set the reference window image.
const realImageT & refWinIm ()
Get a reference to the reference window image.
bool haveRefWindow ()
Get the value of the haveRefWindow flag.
int winIm (const realImageT &win)
Set the window image.
const realImageT & winIm ()
Get a reference to the window image.
bool haveWindow ()
Get the value of the haveWindow flag.
void normalize (bool no)
Set the normalize flag.
bool normalize ()
Get the current value of the normalize flag.
int refIm (const realImageT &im0, realT padFactor)
Set the reference image.
int refIm (const realImageT &im0)
Set the reference image.
const realImageT & refIm ()
Get a reference to the reference image.
bool refValid ()
Get the value of the reference valid flag.
void maxLag (int ml)
Set the maximum lag.
int maxLag ()
Get the current maximum lag.
void tol (realT nt)
Set the tolerance of the interpolated-magnified image, in pixels.
realT tol ()
Get the tolerance of the interpolated-magnified image, in pixels.
Working Memory Member Access
const realImageT & refACIm ()
Get a reference to the reference auto-correlation image.
realT refX0 ()
Get the x-shift of the reference image to itself.
realT refY0 ()
Get the y-shift of the reference image to itself.
const realImageT & normIm ()
Get a reference to the normalized image.
const realImageT & ccIm ()
Get a reference to the cross correlation image.
const realImageT & magIm ()
Get a reference to the magnified image.
Cross Correlation Operator
template<class imT >
int operator() (realT &xShift, realT &yShift, realT &xcPeak, const imT &im)
Conduct the cross correlation to a specified tolerance.
template<class im0T , class imT >
int operator() (realT &xShift, realT &yShift, realT &xcPeak, im0T &im0, imT &im)
Conduct the cross correlation to a specified tolerance.
Protected Member Functions
Peak Finding
void findPeak (realT &xShift, realT &yShift, realT &xcPeak)
Protected Attributes
Configuration Member Data
int m_rows { 0 }
The number of rows in the images.
int m_cols { 0 }
The number of columns in the images.
realT m_padFactor { 1 }
The padding factor for the CC.
realT m_padFactorR { 1 }
realT m_padFactorC { 1 }
int m_rowsPadded { 0 }
The number of rows in the padded CC.
int m_colsPadded { 0 }
The number of columns in the padded CC.
realImageT m_refMaskIm
bool m_haveRefMask { false }
Flag indicating that a referece mask has been provided.
realImageT m_maskIm
bool m_haveMask { false }
Flag indicating that a mask has been provided.
realImageT m_refWinIm
Window image to use for the reference.
bool m_haveRefWindow { false }
Flag indicating that a window has been provided for the reference.
realImageT m_winIm
Window image for the target image.
bool m_haveWindow { false }
Flag indicating that a window has been provided.
bool m_normalize { true }
realImageT m_refIm
The normalized reference image.
bool m_refValid { false }
int m_maxLag { 5 }
The maximum lag to consider in the initial cross-correlation. Default is 5.
realT m_tol { 0.1 }
realT m_magSize { 0 }
realT m_mag { 1 }
xcorrPeakMethod m_peakMethod { xcorrPeakMethod::interpPeak }
The peak finding method to use.
Working Memory Member Data
realImageT m_refACIm
The auto-correlation image of the reference.
realT m_refX0 { 0 }
realT m_refY0 { 0 }
realT m_refPeak { 0 }
realImageT m_normIm
The normalized image.
realImageT m_ccIm
The cross-correlation image.
realImageT m_magIm
The magnified image, used if m_peakMethod == xcorrPeakMethod::interpPeak.
complexArrayT m_ftIm0
Working memory for the FT of the reference image.
complexArrayT m_ftWork
Working memory for the FFT.
complexArrayT m_ftWorkPadded
Working memory for the padded inverse FFT input.
complexArrayT m_ftWorkPaddedOut
Working memory for the FFT and MFT output.
complexArrayT m_mtWorkPadded
Working memory for the MFT for xcorrPeakMethod::mftOversamp.
math::ft::fftT< fftOutT, fftInT, 2 > m_fft_fwd
FFT object for the forward transform.
math::ft::fftT< fftInT, fftOutT, 2 > m_fft_bwd
FFT object for the backward transform.
math::ft::mftT< complexT, complexT, 2 > m_mft_bwd
Member Typedef Documentation
complexArrayT
template<class _realImageT > typedef eigenImage<complexT> mx::improc::imageXCorrFFT< _realImageT >::complexArrayT
Complex eigen array type with Scalar==complexT.
Definition at line 98 of file imageXCorrFFT.hpp.
complexT
template<class _realImageT > typedef std::complex<realT> mx::improc::imageXCorrFFT< _realImageT >::complexT
Complex floating point type.
Definition at line 87 of file imageXCorrFFT.hpp.
realImageT
template<class _realImageT > typedef _realImageT mx::improc::imageXCorrFFT< _realImageT >::realImageT
the Eigen-like array type used for image processing
Definition at line 83 of file imageXCorrFFT.hpp.
realT
template<class _realImageT > typedef _realImageT::Scalar mx::improc::imageXCorrFFT< _realImageT >::realT
the scalar type of the image type
Definition at line 85 of file imageXCorrFFT.hpp.
Constructor & Destructor Documentation
imageXCorrFFT()
template<class realImageT > mx::improc::imageXCorrFFT< realImageT >::imageXCorrFFT ()
Default c'tor.
Definition at line 538 of file imageXCorrFFT.hpp.
Member Function Documentation
ccIm()
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::ccIm ()
Get a reference to the cross correlation image.
Returns
a const referent to m_ccIm.
Definition at line 1002 of file imageXCorrFFT.hpp.
cols()
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::cols ()
Get the number of columns in the input images.
This can only be set by a call to resize() or refIm().
Returns
the current value of m_cols
Definition at line 550 of file imageXCorrFFT.hpp.
colsPadded()
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::colsPadded ()
Get the number of rows in the padded cross-correlation.
This can only be set by a call to resize() or refIm().
Returns
the current value of m_colsPadded
Definition at line 588 of file imageXCorrFFT.hpp.
findPeak()
template<class realImageT > void mx::improc::imageXCorrFFT< realImageT >::findPeak (realT & xShift, realT & yShift, realT & xcPeak) protected
Parameters
[out] xShift the x shift of im w.r.t. im0, in pixels
[out] yShift the y shift of im w.r.t. im0, in pixels
[out] xcPeak the x-corr peak
Definition at line 1014 of file imageXCorrFFT.hpp.
References mx::math::ft::augmentR2CFFTOutput(), backward, mx::improc::imageCenterOfLight(), mx::improc::imageMagnify(), mx::invalidconfig, and mx::improc::imageXCorrFFT< _realImageT >::resize().
haveMask()
template<class realImageT > bool mx::improc::imageXCorrFFT< realImageT >::haveMask ()
Get the value of the haveMask flag.
Returns
the current value of m_haveMask
Definition at line 743 of file imageXCorrFFT.hpp.
haveRefMask()
template<class realImageT > bool mx::improc::imageXCorrFFT< realImageT >::haveRefMask ()
Get the value of the haveRefMask flag.
Returns
the current value of m_haveRefMask
Definition at line 722 of file imageXCorrFFT.hpp.
haveRefWindow()
template<class realImageT > bool mx::improc::imageXCorrFFT< realImageT >::haveRefWindow ()
Get the value of the haveRefWindow flag.
Returns
the current value of m_haveRefWindow
Definition at line 766 of file imageXCorrFFT.hpp.
haveWindow()
template<class realImageT > bool mx::improc::imageXCorrFFT< realImageT >::haveWindow ()
Get the value of the haveWindow flag.
Returns
the current value of m_haveWindow
Definition at line 787 of file imageXCorrFFT.hpp.
magIm()
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::magIm ()
Get a reference to the magnified image.
Returns
a const referent to m_magIm.
Definition at line 1008 of file imageXCorrFFT.hpp.
maskIm() [1/2]
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::maskIm ()
Get a reference to the mask image.
Returns
a const referance to the mask image.
Definition at line 737 of file imageXCorrFFT.hpp.
maskIm() [2/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::maskIm (const realImageT & mask)
Set the mask image.
This does not invalidate the reference
Returns
0 on success
-1 on error
Parameters
[in] mask the new mask image
Definition at line 728 of file imageXCorrFFT.hpp.
maxLag() [1/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::maxLag ()
Get the current maximum lag.
Returns
the current value of m_maxLag
Definition at line 933 of file imageXCorrFFT.hpp.
maxLag() [2/2]
template<class realImageT > void mx::improc::imageXCorrFFT< realImageT >::maxLag (int ml)
Set the maximum lag.
Parameters
[in] ml the new maximum lag
Definition at line 926 of file imageXCorrFFT.hpp.
Referenced by SCENARIO(), and SCENARIO().
normalize() [1/2]
template<class realImageT > bool mx::improc::imageXCorrFFT< realImageT >::normalize ()
Get the current value of the normalize flag.
Returns
the current value of m_normalize
Definition at line 803 of file imageXCorrFFT.hpp.
normalize() [2/2]
template<class realImageT > void mx::improc::imageXCorrFFT< realImageT >::normalize (bool no)
Set the normalize flag.
Changing this invalidates the reference.
Parameters
[in] no the new normalize flag value
Definition at line 793 of file imageXCorrFFT.hpp.
normIm()
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::normIm ()
Get a reference to the normalized image.
Returns
a const referent to m_normIm.
Definition at line 996 of file imageXCorrFFT.hpp.
operator()() [1/2]
template<class realImageT > template<class imT > int mx::improc::imageXCorrFFT< realImageT >::operator() (realT & xShift, realT & yShift, realT & xcPeak, const imT & im)
Conduct the cross correlation to a specified tolerance.
Returns
0 on success
-1 on error
Parameters
[out] xShift the x shift of im w.r.t. im0, in pixels
[out] yShift the y shift of im w.r.t. im0, in pixels
[out] xcPeak the xc peak
[in] im the image to cross-correlate with the reference
Definition at line 1154 of file imageXCorrFFT.hpp.
References mx::invalidconfig, mx::math::ft::padC2CFFTOutput(), mx::math::ft::padR2CFFTOutput(), and mx::sizeerr.
operator()() [2/2]
template<class realImageT > template<class im0T , class imT > int mx::improc::imageXCorrFFT< realImageT >::operator() (realT & xShift, realT & yShift, realT & xcPeak, im0T & im0, imT & im)
Conduct the cross correlation to a specified tolerance.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
0 on success
-1 on error
Parameters
[out] xShift the x shift of im w.r.t. im0, in pixels
[out] yShift the y shift of im w.r.t. im0, in pixels
[out] xcPeak the xc peak
[in] im0 a new reference image
[in] im the image to cross-correlate with the reference
Definition at line 1244 of file imageXCorrFFT.hpp.
padFactor() [1/2]
template<class realImageT > imageXCorrFFT< realImageT >::realT mx::improc::imageXCorrFFT< realImageT >::padFactor ()
Get the padding factor.
Returns
the current value of m_padFactor
Definition at line 576 of file imageXCorrFFT.hpp.
padFactor() [2/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::padFactor (realT os)
Set the padding factor.
This can also be set by a call to resize() or refIm(). The padding factor must be greater than or equal to 1.
If m_rows and m_cols are both greater than 0 this calls resize(int, int, realT).
Parameters
[in] os the new padding factor
Definition at line 556 of file imageXCorrFFT.hpp.
References mx::invalidarg, and mx::internal::mxlib_error_report().
refACIm()
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::refACIm ()
Get a reference to the reference auto-correlation image.
Returns
a const referent to m_refACIm.
Definition at line 978 of file imageXCorrFFT.hpp.
refIm() [1/3]
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::refIm ()
Get a reference to the reference image.
Returns
a const referent to m_refIm.
Definition at line 914 of file imageXCorrFFT.hpp.
refIm() [2/3]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::refIm (const realImageT & im0)
Set the reference image.
Calls refIm(const realImageT &, realT) with the current value of m_padFactor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
0 on success
-1 on error
Parameters
[in] im0 The new reference image
Definition at line 908 of file imageXCorrFFT.hpp.
refIm() [3/3]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::refIm (const realImageT & im0, realT padFactor)
Set the reference image.
Performs the following steps
Applies the mask if supplied.
If desired, normalizes the reference image by mean subtraction and variance division.
Applies the window if supplied.
Stores the result as m_refIm
Resizes working memory with a call to resize()
Shifts to FFT order and Fourier transforms and conjugates the result.
Calls operator() to measure the reference shifts
Stores the resultant auto-correlation in m_refACIm
Returns
0 on success
-1 on error
Parameters
[in] im0 The new reference image
[in] padFactor [optional] the padding factor to use
Definition at line 809 of file imageXCorrFFT.hpp.
References mx::improc::imageShiftWP(), mx::internal::mxlib_error_report(), and mx::sizeerr.
Referenced by SCENARIO(), and SCENARIO().
refMaskIm() [1/2]
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::refMaskIm ()
Get a reference to the reference mask image.
Returns
a const reference to the reference mask image.
Definition at line 716 of file imageXCorrFFT.hpp.
refMaskIm() [2/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::refMaskIm (const realImageT & mask)
Set the reference mask image.
This invalidates the reference
Returns
0 on success
-1 on error
Parameters
[in] mask the new reference mask image
Definition at line 705 of file imageXCorrFFT.hpp.
refValid()
template<class realImageT > bool mx::improc::imageXCorrFFT< realImageT >::refValid ()
Get the value of the reference valid flag.
Returns
the value of m_refValid
Definition at line 920 of file imageXCorrFFT.hpp.
refWinIm() [1/2]
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::refWinIm ()
Get a reference to the reference window image.
Returns
a const referance to the reference window image.
Definition at line 760 of file imageXCorrFFT.hpp.
refWinIm() [2/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::refWinIm (const realImageT & win)
Set the reference window image.
This invalidates the reference.
Returns
0 on success
-1 on error
Parameters
[in] win the new reference window image
Definition at line 749 of file imageXCorrFFT.hpp.
refX0()
template<class realImageT > imageXCorrFFT< realImageT >::realT mx::improc::imageXCorrFFT< realImageT >::refX0 ()
Get the x-shift of the reference image to itself.
Returns
m_refX0
Definition at line 984 of file imageXCorrFFT.hpp.
refY0()
template<class realImageT > imageXCorrFFT< realImageT >::realT mx::improc::imageXCorrFFT< realImageT >::refY0 ()
Get the y-shift of the reference image to itself.
Returns
m_refY0
Definition at line 990 of file imageXCorrFFT.hpp.
resize() [1/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::resize (int nrows, int ncols)
Set the size of the cross-correlation problem based on input image size.
Calls resize(int, int, realT) with the current value of m_padFactor.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
0 on success
-1 on error
Parameters
[in] nrows the number of rows in the images to register
[in] ncols the number of columns in the images to register
Definition at line 699 of file imageXCorrFFT.hpp.
resize() [2/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::resize (int nrows, int ncols, realT padFactor)
Set the size of the cross-correlation problem based on input image size.
This resizes all working memory and conducts fftw planning. If there are no changes to size or padding, this returns immediately making no changes.
If there are changes to size or padding the reference is invalidated.
If nrows or ncols is 0, this resizes all working memory to 0.
Returns
0 on success
-1 on error
Parameters
[in] nrows the number of rows in the images to register
[in] ncols the number of columns in the images to register
[in] padFactor the padding factor. Must be >= 1.
Definition at line 594 of file imageXCorrFFT.hpp.
References backward, forward, mx::invalidarg, and mx::internal::mxlib_error_report().
Referenced by mx::improc::imageXCorrFFT< _realImageT >::findPeak().
rows()
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::rows ()
Get the number of rows in the input images.
This can only be set by a call to resize() or refIm().
Returns
the current value of m_rows
Definition at line 544 of file imageXCorrFFT.hpp.
rowsPadded()
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::rowsPadded ()
Get the number of rows in the padded cross-correlation.
This can only be set by a call to resize() or refIm().
Returns
the current value of m_rowsPadded
Definition at line 582 of file imageXCorrFFT.hpp.
tol() [1/2]
template<class realImageT > imageXCorrFFT< realImageT >::realT mx::improc::imageXCorrFFT< realImageT >::tol ()
Get the tolerance of the interpolated-magnified image, in pixels.
Returns
the current value of m_tol.
Definition at line 939 of file imageXCorrFFT.hpp.
tol() [2/2]
template<class realImageT > void mx::improc::imageXCorrFFT< realImageT >::tol (realT nt)
Set the tolerance of the interpolated-magnified image, in pixels.
Parameters
[in] nt The new value of the interpolation tolerance.
Definition at line 945 of file imageXCorrFFT.hpp.
Referenced by SCENARIO().
winIm() [1/2]
template<class realImageT > const realImageT & mx::improc::imageXCorrFFT< realImageT >::winIm ()
Get a reference to the window image.
Returns
a const referance to the window image.
Definition at line 781 of file imageXCorrFFT.hpp.
winIm() [2/2]
template<class realImageT > int mx::improc::imageXCorrFFT< realImageT >::winIm (const realImageT & win)
Set the window image.
This does not invalidate the reference.
Returns
0 on success
-1 on error
Parameters
[in] win the new window image
Definition at line 772 of file imageXCorrFFT.hpp.
Member Data Documentation
m_ccIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_ccIm protected
The cross-correlation image.
Definition at line 178 of file imageXCorrFFT.hpp.
m_cols
template<class _realImageT > int mx::improc::imageXCorrFFT< _realImageT >::m_cols { 0 } protected
The number of columns in the images.
Definition at line 106 of file imageXCorrFFT.hpp.
m_colsPadded
template<class _realImageT > int mx::improc::imageXCorrFFT< _realImageT >::m_colsPadded { 0 } protected
The number of columns in the padded CC.
Definition at line 118 of file imageXCorrFFT.hpp.
m_fft_bwd
template<class _realImageT > math::ft::fftT<fftInT, fftOutT, 2> mx::improc::imageXCorrFFT< _realImageT >::m_fft_bwd
FFT object for the backward transform.
Definition at line 199 of file imageXCorrFFT.hpp.
m_fft_fwd
template<class _realImageT > math::ft::fftT<fftOutT, fftInT, 2> mx::improc::imageXCorrFFT< _realImageT >::m_fft_fwd
FFT object for the forward transform.
Definition at line 197 of file imageXCorrFFT.hpp.
m_ftIm0
template<class _realImageT > complexArrayT mx::improc::imageXCorrFFT< _realImageT >::m_ftIm0 protected
Working memory for the FT of the reference image.
Definition at line 182 of file imageXCorrFFT.hpp.
m_ftWork
template<class _realImageT > complexArrayT mx::improc::imageXCorrFFT< _realImageT >::m_ftWork
Working memory for the FFT.
Definition at line 185 of file imageXCorrFFT.hpp.
m_ftWorkPadded
template<class _realImageT > complexArrayT mx::improc::imageXCorrFFT< _realImageT >::m_ftWorkPadded
Working memory for the padded inverse FFT input.
Definition at line 191 of file imageXCorrFFT.hpp.
m_ftWorkPaddedOut
template<class _realImageT > complexArrayT mx::improc::imageXCorrFFT< _realImageT >::m_ftWorkPaddedOut
Working memory for the FFT and MFT output.
Definition at line 193 of file imageXCorrFFT.hpp.
m_haveMask
template<class _realImageT > bool mx::improc::imageXCorrFFT< _realImageT >::m_haveMask { false } protected
Flag indicating that a mask has been provided.
Definition at line 128 of file imageXCorrFFT.hpp.
m_haveRefMask
template<class _realImageT > bool mx::improc::imageXCorrFFT< _realImageT >::m_haveRefMask { false } protected
Flag indicating that a referece mask has been provided.
Definition at line 123 of file imageXCorrFFT.hpp.
m_haveRefWindow
template<class _realImageT > bool mx::improc::imageXCorrFFT< _realImageT >::m_haveRefWindow { false } protected
Flag indicating that a window has been provided for the reference.
Definition at line 132 of file imageXCorrFFT.hpp.
m_haveWindow
template<class _realImageT > bool mx::improc::imageXCorrFFT< _realImageT >::m_haveWindow { false } protected
Flag indicating that a window has been provided.
Definition at line 136 of file imageXCorrFFT.hpp.
m_mag
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_mag { 1 } protected
The magnification, in principle is 1/m_tol but will vary slightly based on integer array sizes
Definition at line 154 of file imageXCorrFFT.hpp.
m_magIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_magIm protected
The magnified image, used if m_peakMethod == xcorrPeakMethod::interpPeak.
Definition at line 180 of file imageXCorrFFT.hpp.
m_magSize
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_magSize { 0 } protected
Magnified size of the ccIm when using interp. Set as function of m_tol and m_maxLag.
Definition at line 151 of file imageXCorrFFT.hpp.
m_maskIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_maskIm protected
Mask image to use, may be needed for proper normalization even if refIm has 0 mask applied.
Definition at line 125 of file imageXCorrFFT.hpp.
m_maxLag
template<class _realImageT > int mx::improc::imageXCorrFFT< _realImageT >::m_maxLag { 5 } protected
The maximum lag to consider in the initial cross-correlation. Default is 5.
Definition at line 146 of file imageXCorrFFT.hpp.
m_mft_bwd
template<class _realImageT > math::ft::mftT<complexT, complexT, 2> mx::improc::imageXCorrFFT< _realImageT >::m_mft_bwd
MFT object used to oversample the peak for xcorrPeakMethod::mftOversamp
Definition at line 201 of file imageXCorrFFT.hpp.
m_mtWorkPadded
template<class _realImageT > complexArrayT mx::improc::imageXCorrFFT< _realImageT >::m_mtWorkPadded
Working memory for the MFT for xcorrPeakMethod::mftOversamp.
Definition at line 195 of file imageXCorrFFT.hpp.
m_normalize
template<class _realImageT > bool mx::improc::imageXCorrFFT< _realImageT >::m_normalize { true } protected
Flag specifying whether images should be normalized prior to performing the cross-correlation
Definition at line 138 of file imageXCorrFFT.hpp.
m_normIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_normIm protected
The normalized image.
Definition at line 176 of file imageXCorrFFT.hpp.
m_padFactor
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_padFactor { 1 } protected
The padding factor for the CC.
Definition at line 108 of file imageXCorrFFT.hpp.
m_padFactorC
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_padFactorC { 1 } protected
The actual padding factor for cols of the CC set based on the resultant array sizes.
Definition at line 113 of file imageXCorrFFT.hpp.
m_padFactorR
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_padFactorR { 1 } protected
The actual padding factor for rows of the CC set based on the resultant array sizes.
Definition at line 110 of file imageXCorrFFT.hpp.
m_peakMethod
template<class _realImageT > xcorrPeakMethod mx::improc::imageXCorrFFT< _realImageT >::m_peakMethod { xcorrPeakMethod::interpPeak } protected
The peak finding method to use.
Definition at line 158 of file imageXCorrFFT.hpp.
m_refACIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_refACIm protected
The auto-correlation image of the reference.
Definition at line 166 of file imageXCorrFFT.hpp.
m_refIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_refIm protected
The normalized reference image.
Definition at line 141 of file imageXCorrFFT.hpp.
m_refMaskIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_refMaskIm protected
Mask image to use for the reference, may be needed for proper normalization even if refIm has 0 mask applied.
Definition at line 120 of file imageXCorrFFT.hpp.
m_refPeak
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_refPeak { 0 } protected
the x-corr peak of the reference shift to itself
Definition at line 174 of file imageXCorrFFT.hpp.
m_refValid
template<class _realImageT > bool mx::improc::imageXCorrFFT< _realImageT >::m_refValid { false } protected
Flag indicating whether the reference is valid. It can be invalidated if a mask, window, or normalize is set after the reference is set.
Definition at line 143 of file imageXCorrFFT.hpp.
m_refWinIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_refWinIm protected
Window image to use for the reference.
Definition at line 130 of file imageXCorrFFT.hpp.
m_refX0
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_refX0 { 0 } protected
The x-shift of the reference image to itself using the selected algorithm, used as coordinate origin
Definition at line 168 of file imageXCorrFFT.hpp.
m_refY0
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_refY0 { 0 } protected
The x-shift of the reference image to itself using the selected algorithm, used as coordinate origin
Definition at line 171 of file imageXCorrFFT.hpp.
m_rows
template<class _realImageT > int mx::improc::imageXCorrFFT< _realImageT >::m_rows { 0 } protected
The number of rows in the images.
Definition at line 104 of file imageXCorrFFT.hpp.
m_rowsPadded
template<class _realImageT > int mx::improc::imageXCorrFFT< _realImageT >::m_rowsPadded { 0 } protected
The number of rows in the padded CC.
Definition at line 116 of file imageXCorrFFT.hpp.
m_tol
template<class _realImageT > realT mx::improc::imageXCorrFFT< _realImageT >::m_tol { 0.1 } protected
For xcorrPeakMethod::interpPeak, the tolerance of the interpolated-magnified image, in pixels.
Definition at line 148 of file imageXCorrFFT.hpp.
m_winIm
template<class _realImageT > realImageT mx::improc::imageXCorrFFT< _realImageT >::m_winIm protected
Window image for the target image.
Definition at line 134 of file imageXCorrFFT.hpp.
The documentation for this class was generated from the following file:
improc/imageXCorrFFT.hpp