mxlib: /home/jrmales/Source/mxlib/source/ioutils/fits/fitsUtils.cpp File Reference
fitsUtils.cpp File Reference
General Utilities » Input/Output Utilities | Image Processing » FITS Files | Image Processing » Image Processing Files » FITS Files Files
Implementation of utilities to work with FITS files.
Implementation of utilities to work with FITS files.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file fitsUtils.cpp.
#include "ioutils/fits/fitsUtils.hpp"
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<>
mx::error_t mx::fits::fits_write_key< bool > (fitsfile *fptr, char *keyword, void *value, char *comment)
Specialization to handle the case bool.
Function Documentation
fits_write_key< bool >()
template<> mx::error_t mx::fits::fits_write_key< bool > (fitsfile * fptr, char * keyword, void * value, char * comment)
Specialization to handle the case bool.
This gets converted to unsigned char.
Definition at line 128 of file fitsUtils.cpp.
References mx::fits_status2error_t(), and mx::fits::fits_write_key().
Referenced by mx::fits::fitsHeaderCard< verboseT >::write().