mxlib: /home/jrmales/Source/mxlib/tests/include/math/geo_test.cpp File Reference
geo_test.cpp File Reference
#include "../../catch2/catch.hpp"
#include <Eigen/Dense>
#include "../../../include/math/geo.hpp"
Functions
SCENARIO ("Verify compilation and calculations of math::angleMod", "[math::angleMod]")
SCENARIO ("Verify compilation and calculations of math::angleDiff", "[math::angleDiff]")
Function Documentation
SCENARIO() [1/2]
SCENARIO ("Verify compilation and calculations of math::angleDiff" , "" [math::angleDiff])
Verify compilation and calculations of math::angleDiff. Tests that various angle differences are calculated correctly for both radians and degrees.
Definition at line 86 of file geo_test.cpp.
References mx::math::six_fifths().
SCENARIO() [2/2]
SCENARIO ("Verify compilation and calculations of math::angleMod" , "" [math::angleMod])
Verify compilation and calculations of math::angleMod. Tests that various angle modulos are calculated correctly for both radians and degrees.
Definition at line 16 of file geo_test.cpp.
References mx::math::dtor(), and mx::math::six_fifths().