mxlib: System Programming
System Programming
General Utilities
Tools for system programming
Modules
Interprocess Communication
Functions
template<size_t maxsz = 4096>
std::string mx::sys::getEnv (const std::string &estr)
Return the value of an environment variable.
Function Documentation
getEnv()
template<size_t maxsz = 4096> std::string mx::sys::getEnv (const std::string & estr)
Return the value of an environment variable.
Call the standard getenv function, but handles the null pointer as an empty string.
Returns
the value of the environment varialbe, or empty string if it doesn't exist
Template Parameters
maxsz is the maximum allowable size of the environment variable. Prevents buffer overflow.
Parameters
[in] estr is the name of the environment variable to query
Definition at line 48 of file environment.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT, _coronT >::simulatedAOSystem(), mx::math::ft::fftw_wisdom_filename(), mx::AO::path::basis::root(), mx::AO::path::dm::root(), mx::AO::path::pupil::root(), mx::AO::path::sys::root(), mx::app::application::setDefaults(), and mx::astro::astroSpectrum< _spectrumT, freq >::setParameters().