mxlib: The Moffat Function
The Moffat Function
General Mathematics » Special Functions
Utilities for working with the Moffat function
The Moffat Function[14], a.k.a. the Moffat Profile, a.k.a. the Moffat Distribution, has the form
\[ I(x) = I_{pk}\left[ 1 + \frac{x^2}{\alpha^2}\right]^{-\beta} \]
With \(\beta=1\) it is the Lorentzian or Cauchy distribution. See also https://en.wikipedia.org/wiki/Moffat_distribution and https://en.wikipedia.org/wiki/Cauchy_distribution.
1-D and 2-D symmetric forms are provided. Utilities are provided for normalizing and calculating the full-width at half-maximum.
Functions
template<typename realT >
realT mx::math::func::moffat (const realT x, const realT I0, const realT Ipk, const realT x0, const realT alpha, const realT beta)
Find value at position (x) of the 1D arbitrarily-centered symmetric unnormalized Moffat function.
template<typename realT >
realT mx::math::func::moffat2D (const realT x, const realT y, const realT I0, const realT Ipk, const realT x0, const realT y0, const realT alpha, const realT beta)
Find value at position (x,y) of the 2D arbitrarily-centered unnormalized symmetric Moffat function.
template<typename realT >
realT mx::math::func::moffatFWHM (realT alpha, realT beta)
Compute the full-width at half-maximum of a Moffat profile.
Function Documentation
moffat()
template<typename realT > realT mx::math::func::moffat (const realT x, const realT I0, const realT Ipk, const realT x0, const realT alpha, const realT beta)
Find value at position (x) of the 1D arbitrarily-centered symmetric unnormalized Moffat function.
The Moffat distribution is due to [14]. With \(\beta=1\) it is the Lorentzian or Cauchy distribution. See also https://en.wikipedia.org/wiki/Moffat_distribution and https://en.wikipedia.org/wiki/Cauchy_distribution.
Here we use the unnormalized general form, most useful for peak fitting.
This function computes:
\[ I(x) = I_0 + I_{pk}\left[ 1 + \frac{(x-x_0)^2}{\alpha^2}\right]^{-\beta} \]
Returns
the value of the 1D arbitrarily-centered unnormalized Moffat at (x)
Template Parameters
realT is type to use for arithmetic
Test:
Scenario: compiling 1D Moffat function [test doc]
Parameters
[in] x is the x-position at which to evaluate the Moffat function
[in] I0 is the constant to add to the Moffat function
[in] Ipk is the scaling factor (peak = A)
[in] x0 is the x-coordinate of the center
[in] alpha is the width parameter of the Moffat function.
[in] beta is the shape parameter of the Moffat function
Definition at line 73 of file moffat.hpp.
References mx::math::six_fifths().
moffat2D()
template<typename realT > realT mx::math::func::moffat2D (const realT x, const realT y, const realT I0, const realT Ipk, const realT x0, const realT y0, const realT alpha, const realT beta)
Find value at position (x,y) of the 2D arbitrarily-centered unnormalized symmetric Moffat function.
The Moffat distribution is due to [14]. With \(\beta=1\) it is the Lorentzian or Cauchy distribution. See also https://en.wikipedia.org/wiki/Moffat_distribution and https://en.wikipedia.org/wiki/Cauchy_distribution.
Here we use the unnormalized general form, most useful for peak fitting.
This function omputes:
\[ I(x) = I_0 + I_{pk}\left[ 1 + \frac{(x-x_0)^2 + (y-y_0)^2}{\alpha^2}\right]^{-\beta} \]
Returns
the value of the 2D arbitrarily-centered symmetric Moffat function at (x,y)
Template Parameters
realT is type to use for arithmetic
Test:
Scenario: compiling 2D Moffat function [test doc]
Parameters
[in] x the x-position at which to evaluate the Moffat function
[in] y the y-positoin at which to evaluate the Moffat function
[in] I0 the constant to add to the Moffat function
[in] Ipk the scaling factor (peak height is A-G0)
[in] x0 the x-coordinate of the center
[in] y0 the y-coordinate of the center
[in] alpha the width parameter of the Moffat function.
[in] beta the shape parameter of the Moffat function.
Definition at line 127 of file moffat.hpp.
References mx::math::six_fifths().
moffatFWHM()
template<typename realT > realT mx::math::func::moffatFWHM (realT alpha, realT beta)
Compute the full-width at half-maximum of a Moffat profile.
This returns the value of
\[ FWHM = 2 \alpha \sqrt{2^{1/\beta} - 1} \]
Returns
the FWHM of the Moffat profile
Template Parameters
realT is the type to use for arithmetic
Test:
Scenario: compiling Moffat FWHM [test doc]
Parameters
[in] alpha the width parameter of the Moffat function.
[in] beta the shape parameter of the Moffat function.
Definition at line 193 of file moffat.hpp.
References mx::math::six_fifths().
Referenced by mx::math::fit::fitMoffat1D< _realT >::fwhm(), and mx::math::fit::fitMoffat2D< fitterT >::fwhm().