mxlib: Special Functions
Special Functions
General Mathematics
Various special functions.
Various special functions.
Modules
The Gaussian Function
Utilities for working with the Gaussian function.
The Moffat Function
Utilities for working with the Moffat function.
The Airy Pattern
Utilities for working with the Airy Pattern.
Functions
template<typename T1 , typename T2 >
T2 mx::math::func::bessel_j (T1 v, T2 x)
Bessel Functions of the First Kind.
template<typename T >
T mx::math::func::factorial (T x)
The factorial function.
template<typename T >
T mx::math::func::tgamma (T x)
The Gamma Function.
template<typename T >
T mx::math::func::jinc (const T &x)
Returns the the Jinc function.
template<typename T >
T mx::math::func::jinc2 (const T &x)
Returns the Jinc2 function.
template<typename T >
T mx::math::func::legendre_p (int n, T x)
Legendre Polynomials.
template<typename floatT >
floatT mx::math::func::logistic_param (floatT x, floatT thalf)
Return the logistic function parameter for a specified rise time.
template<typename floatT >
floatT mx::math::func::logistic (floatT t, floatT t0=0, floatT a=1)
Return the value of the logistic function.
template<typename T >
T mx::math::func::sign (T x)
The sign function.
template<typename realT >
realT weibull_lambda (std::vector< realT > &x, realT k, realT x0=0)
The MLE of the Weibull distribution lambda parameter.
template<typename realT >
realT weibull (realT x, realT x0, realT k, realT lambda)
The general shifted Weibull distribution at a point.
template<typename realT >
realT weibull (realT x, realT k, realT lambda)
The Weibull distribution at a point.
Function Documentation
bessel_j()
template<typename T1 , typename T2 > T2 mx::math::func::bessel_j (T1 v, T2 x)
Bessel Functions of the First Kind.
Parameters
[in] v [in]
[in] x [in]
Definition at line 48 of file bessel.hpp.
Referenced by mx::sigproc::zernikeQNorm().
factorial()
template<typename T > T mx::math::func::factorial (T x)
The factorial function.
Parameters
[in] x [in] the argument
Definition at line 48 of file factorial.hpp.
jinc()
template<typename T > T mx::math::func::jinc (const T & x)
Returns the the Jinc function.
The Jinc function is defined here as
\[ Ji(x) = \frac{J_1(x)}{x} \]
where \(J_1 \) is the cylindrical bessel function of the first kind of order 1.
Follows the technique in boost sinc_pi, using the Taylor series for small arguments. If x is smaller than \(\epsilon \), then it returns 1/2. If x is larger than \(\epsilon \) but smaller than \(\sqrt{\epsilon} \), then this function returns
\[ Ji(x) \approx \frac{1}{2} - \frac{x^2}{16}. \]
Returns
the value of Ji(x)
Template Parameters
T is an floating point type
Parameters
[in] x [in] the argument
Definition at line 64 of file jinc.hpp.
Referenced by mx::math::func::airyPattern(), mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), mx::AO::analysis::Fm_projMod(), mx::AO::analysis::jincFuncs(), mx::AO::analysis::vonKarmanSpectrum< realT >::operator()(), mx::AO::analysis::phiInt_basic(), and mx::AO::analysis::phiInt_mod().
jinc2()
template<typename T > T mx::math::func::jinc2 (const T & x)
Returns the Jinc2 function.
The Jinc2 function is defined here as
\[ Ji_2(x) = \frac{J_2(x)}{x} \]
where \(J_2 \) is the cylindrical bessel function of the first kind of order 2.
If x is smaller than \(\sqrt{\epsilon} \), returns 0.
Returns
the value of Ji2(x)
Parameters
[in] x [in] the argument
Definition at line 118 of file jinc.hpp.
Referenced by mx::AO::analysis::vonKarmanSpectrum< realT >::operator()().
legendre_p()
template<typename T > T mx::math::func::legendre_p (int n, T x)
Legendre Polynomials.
See https://en.wikipedia.org/wiki/Legendre_polynomials and https://www.boost.org/doc/libs/1_75_0/libs/math/doc/html/math_toolkit/sf_poly/legendre.html
Returns
the value of the n-th Legendre polynomial at x.
Parameters
[in] n [in] the order of the Legendre polynomial, n>=0.
[in] x [in] the argument, -1 <= x <= 1.
Definition at line 52 of file legendre.hpp.
logistic()
template<typename floatT > floatT mx::math::func::logistic (floatT t, floatT t0 = 0, floatT a = 1)
Return the value of the logistic function.
The logistic function is
\[ f(t) = \frac{1}{1 + e^{-a(t-t_0)}} \]
Parameters
t [input] the argument.
t0 [input] [optional] the center of the curve, defaults to 0.
a [input] [optional] the exponent parameter, defaults to 1.
Returns
the value of the logistic function at t
Template Parameters
floatT is the floating point type of the arguments and the returned value.
Definition at line 83 of file logistic.hpp.
logistic_param()
template<typename floatT > floatT mx::math::func::logistic_param (floatT x, floatT thalf)
Return the logistic function parameter for a specified rise time.
The logistic function is
\[ f(t) = \frac{1}{1 + e^{-a(t-t_0)}} \]
The parameter \(a \) controls how fast the function rises. Here it is specified by the value \(f(t_{1/2}) = x\), where \(0 < x < 1 \).
Parameters
x [input] the value at which the rist time is specified.
thalf [input] half the rise time, or the time after 0 when f(t) = x.
Returns
the value of a
Template Parameters
floatT is the floating point type of the arguments and the returned value.
Definition at line 61 of file logistic.hpp.
sign()
template<typename T > T mx::math::func::sign (T x)
The sign function.
Parameters
[in] x [in] the argument
Definition at line 30 of file sign.hpp.
Referenced by mx::astro::solve_kepler_danby().
tgamma()
template<typename T > T mx::math::func::tgamma (T x)
The Gamma Function.
Parameters
[in] x [in] the argument of the gamma function
Definition at line 48 of file gamma.hpp.
weibull() [1/2]
template<typename realT > realT weibull (realT x, realT k, realT lambda)
The Weibull distribution at a point.
Calculates the value of the Weibull distribution at a location specified by x.
\[ f(x; \lambda, k) = \begin{cases} \frac{k}{\lambda}\left(\frac{x}{\lambda}\right)^{k-1} \exp \left(-\left(\frac{x}{\lambda}\right)^k \right), & x \ge 0 \\ 0, & x < 0 \end{cases} \]
Template Parameters
realT a real floating point type
Returns
the value of the Weibull distribution at x.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] x [in] the location at which to calculate the distribution
[in] k [in] the shape parameter
[in] lambda [in] the scale parameter
Definition at line 109 of file weibull.hpp.
References mx::astro::constants::k(), and weibull().
weibull() [2/2]
template<typename realT > realT weibull (realT x, realT x0, realT k, realT lambda)
The general shifted Weibull distribution at a point.
Calculates the value of the Weibull distribution at a location specified by x.
\[ f(x; x_o, \lambda, k) = \begin{cases} \frac{k}{\lambda}\left(\frac{x-x_o}{\lambda}\right)^{k-1} \exp \left(-\left(\frac{x-x_o}{\lambda}\right)^k \right), & x \ge 0 \\ 0, & x < 0 \end{cases} \]
Template Parameters
realT a real floating point type
Returns
the value of the Weibull distribution at x.
Parameters
[in] x [in] the location at which to calculate the distribution
[in] x0 [in] the location parameter
[in] k [in] the shape parameter
[in] lambda [in] the scale parameter
Definition at line 74 of file weibull.hpp.
References mx::astro::constants::k().
Referenced by weibull().
weibull_lambda()
template<typename realT > realT weibull_lambda (std::vector< realT > & x, realT k, realT x0 = 0)
The MLE of the Weibull distribution lambda parameter.
Template Parameters
realT a real floating point type
Returns
the MLE of lambda given the data.
Parameters
[in] x [in] the data points
[in] k [in] the shape parameter
[in] x0 [in] [optional] the location parameter
Definition at line 39 of file weibull.hpp.
References mx::astro::constants::k().