mxlib: Interpolation
Interpolation
General Mathematics
Various tools for interpolating data and discrete functions.
Classes
struct mx::math::gsl_interp_linear< _realT >
GSL Linear Interpolation.
struct mx::math::gsl_interp_steffen< _realT >
GSL Steffen Interpolation.
class mx::math::gslInterpolator< interpT >
Class to manage interpolation using the GSL interpolation library.
class mx::math::logInterpolator< interpT >
Interpolate a function in log space.
Modules
Image Transforms
Functions
template<typename realT >
int mx::math::gsl_interpolate (const gsl_interp_type *interpT, realT *xin, realT *yin, size_t Nin, realT *xout, realT *yout, size_t Nout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis.
template<typename realT >
int mx::math::gsl_interpolate (const gsl_interp_type *interpT, std::vector< realT > &xin, std::vector< realT > &yin, std::vector< realT > &xout, std::vector< realT > &yout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis (vector version)
Function Documentation
gsl_interpolate() [1/2]
template<typename realT > int mx::math::gsl_interpolate (const gsl_interp_type * interpT, realT * xin, realT * yin, size_t Nin, realT * xout, realT * yout, size_t Nout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis.
Parameters
interpT one of the gsl interpolation types.
[in] xin the input x-axis
[in] yin the input y-values
[in] Nin the size of the input x-y data series
[in] xout the desired x-axis
[out] yout the output interpolated y-values, pre-allocated
[in] Nout the size of the output x-y axis
Returns
0 on success
-1 on a gsl error.
Todo:
report errors iaw mxlib standard in gsl_interpolate
Definition at line 57 of file gslInterpolation.hpp.
References mx::math::six_fifths().
Referenced by mx::math::gsl_interpolate(), and mx::astro::astroSpectrum< _spectrumT, freq >::setSpectrum().
gsl_interpolate() [2/2]
template<typename realT > int mx::math::gsl_interpolate (const gsl_interp_type * interpT, std::vector< realT > & xin, std::vector< realT > & yin, std::vector< realT > & xout, std::vector< realT > & yout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis (vector version)
Parameters
interpT of the gsl interpolation types.
[in] xin the input x-axis
[in] yin the input y-values
[in] xout the desired x-axis
[out] yout the output interpolated y-values, does not need to be allocated
Return values
Definition at line 118 of file gslInterpolation.hpp.
References mx::math::gsl_interpolate(), and mx::math::six_fifths().