mxlib: 1-D Window Functions
1-D Window Functions
Signal Processing » Window Functions
1-D window functions for spectral analysis
Functions
template<typename realT >
void mx::sigproc::window::tukey (realT *filt, int N, realT alpha)
The Tukey Window.
template<typename realT >
void mx::sigproc::window::tukey (std::vector< realT > &filt, realT alpha)
The Tukey Window.
template<typename realT >
void mx::sigproc::window::genCosine (realT *filt, size_t N, realT a0, realT a1)
The generalized 2 parameter cosine Window.
template<typename realT >
void mx::sigproc::window::genCosine (realT *filt, size_t N, realT a0, realT a1, realT a2)
The generalized 3 parameter cosine Window.
template<typename realT >
void mx::sigproc::window::genCosine (realT *filt, size_t N, realT a0, realT a1, realT a2, realT a3)
The generalized 4 parameter cosine Window.
template<typename realT >
void mx::sigproc::window::hann (realT *filt, int N)
The Hann Window.
template<typename realT >
void mx::sigproc::window::hann (std::vector< realT > &filt)
The Hann Window.
template<typename realT >
void mx::sigproc::window::hamming (realT *filt, int N)
The Hamming Window.
template<typename realT >
void mx::sigproc::window::hamming (std::vector< realT > &filt)
The Hamming Window.
template<typename realT >
void mx::sigproc::window::blackman (realT *filt, size_t N)
The Blackman Window.
template<typename realT >
void mx::sigproc::window::blackman (std::vector< realT > &filt)
The Blackman Window.
template<typename realT >
void mx::sigproc::window::exactBlackman (realT *filt, size_t N)
The Exact Blackman Window.
template<typename realT >
void mx::sigproc::window::nuttal (realT *filt, size_t N)
The Nuttal Window.
template<typename realT >
void mx::sigproc::window::nuttal (std::vector< realT > &filt)
The Nuttal Window.
template<typename realT >
void mx::sigproc::window::blackmanNuttal (realT *filt, size_t N)
The Blackman-Nuttal Windwo.
template<typename realT >
void mx::sigproc::window::blackmanNuttal (std::vector< realT > &filt)
The Blackman-Nuttal Windwo.
Function Documentation
blackman() [1/2]
template<typename realT > void mx::sigproc::window::blackman (realT * filt, size_t N)
The Blackman Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
[in] N the size of the filter vector
Definition at line 242 of file signalWindows.hpp.
Referenced by mx::sigproc::window::blackman().
blackman() [2/2]
template<typename realT > void mx::sigproc::window::blackman (std::vector< realT > & filt)
The Blackman Window.
See https://en.wikipedia.org/wiki/Window_function
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
Definition at line 259 of file signalWindows.hpp.
References mx::sigproc::window::blackman().
blackmanNuttal() [1/2]
template<typename realT > void mx::sigproc::window::blackmanNuttal (realT * filt, size_t N)
The Blackman-Nuttal Windwo.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
[in] N the size of the filter vector
Definition at line 330 of file signalWindows.hpp.
Referenced by mx::sigproc::window::blackmanNuttal().
blackmanNuttal() [2/2]
template<typename realT > void mx::sigproc::window::blackmanNuttal (std::vector< realT > & filt)
The Blackman-Nuttal Windwo.
See https://en.wikipedia.org/wiki/Window_function
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
Definition at line 347 of file signalWindows.hpp.
References mx::sigproc::window::blackmanNuttal().
exactBlackman()
template<typename realT > void mx::sigproc::window::exactBlackman (realT * filt, size_t N)
The Exact Blackman Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
[in] N the size of the filter vector
Definition at line 272 of file signalWindows.hpp.
Referenced by mx::sigproc::window::exactBlackman().
genCosine() [1/3]
template<typename realT > void mx::sigproc::window::genCosine (realT * filt, size_t N, realT a0, realT a1)
The generalized 2 parameter cosine Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
[in] N the size of the filter vector
[in] a0 parameter of the generalized cosine window
[in] a1 parameter of the generalized cosine window
Definition at line 109 of file signalWindows.hpp.
References mx::math::six_fifths().
genCosine() [2/3]
template<typename realT > void mx::sigproc::window::genCosine (realT * filt, size_t N, realT a0, realT a1, realT a2)
The generalized 3 parameter cosine Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
[in] N the size of the filter vector
[in] a0 parameter of the generalized cosine window
[in] a1 parameter of the generalized cosine window
[in] a2 parameter of the generalized cosine window
Definition at line 131 of file signalWindows.hpp.
References mx::math::six_fifths().
genCosine() [3/3]
template<typename realT > void mx::sigproc::window::genCosine (realT * filt, size_t N, realT a0, realT a1, realT a2, realT a3)
The generalized 4 parameter cosine Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
[in] N the size of the filter vector
[in] a0 parameter of the generalized cosine window
[in] a1 parameter of the generalized cosine window
[in] a2 parameter of the generalized cosine window
[in] a3 parameter of the generalized cosine window
Definition at line 154 of file signalWindows.hpp.
References mx::math::six_fifths().
hamming() [1/2]
template<typename realT > void mx::sigproc::window::hamming (realT * filt, int N)
The Hamming Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a floating point type
Parameters
[out] filt the pre-allocated array to hold the filter
[in] N the size of the filter
Definition at line 211 of file signalWindows.hpp.
Referenced by mx::sigproc::window::hamming().
hamming() [2/2]
template<typename realT > void mx::sigproc::window::hamming (std::vector< realT > & filt)
The Hamming Window.
See https://en.wikipedia.org/wiki/Window_function
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
realT a floating point type
Parameters
[out] filt the pre-allocated vector to hold the filter
Definition at line 229 of file signalWindows.hpp.
References mx::sigproc::window::hamming().
hann() [1/2]
template<typename realT > void mx::sigproc::window::hann (realT * filt, int N)
The Hann Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a floating point type
Parameters
[out] filt the pre-allocated array to hold the filter
[in] N the size of the filter
Definition at line 179 of file signalWindows.hpp.
Referenced by mx::sigproc::window::hann(), mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::intensityPSD(), and mx::AO::analysis::speckleAmpPSD().
hann() [2/2]
template<typename realT > void mx::sigproc::window::hann (std::vector< realT > & filt)
The Hann Window.
See https://en.wikipedia.org/wiki/Window_function
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
realT a floating point type
Parameters
[out] filt the pre-allocated vector to hold the filter
Definition at line 197 of file signalWindows.hpp.
References mx::sigproc::window::hann().
nuttal() [1/2]
template<typename realT > void mx::sigproc::window::nuttal (realT * filt, size_t N)
The Nuttal Window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
[in] N the size of the filter vector
Definition at line 300 of file signalWindows.hpp.
Referenced by mx::sigproc::window::nuttal().
nuttal() [2/2]
template<typename realT > void mx::sigproc::window::nuttal (std::vector< realT > & filt)
The Nuttal Window.
See https://en.wikipedia.org/wiki/Window_function
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
realT a real floating point type
Parameters
[out] filt The pre-allocated vector which will store the filter
Definition at line 317 of file signalWindows.hpp.
References mx::sigproc::window::nuttal().
tukey() [1/2]
template<typename realT > void mx::sigproc::window::tukey (realT * filt, int N, realT alpha)
The Tukey Window.
The width of the window is controlled by alpha. alpha = 0 is a square wave, alpha=1.0 is the Hann window.
See https://en.wikipedia.org/wiki/Window_function
Template Parameters
realT a floating point type
Parameters
[out] filt the pre-allocated array to hold the filter
[in] N the size of the filter
[in] alpha the width parameter
Definition at line 53 of file signalWindows.hpp.
References mx::math::six_fifths().
Referenced by mx::sigproc::window::tukey().
tukey() [2/2]
template<typename realT > void mx::sigproc::window::tukey (std::vector< realT > & filt, realT alpha)
The Tukey Window.
The width of the window is controlled by alpha. alpha = 0 is a square wave, alpha=1.0 is the Hann window.
See https://en.wikipedia.org/wiki/Window_function
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
realT a floating point type
Parameters
[out] filt the pre-allocated vector to hold the filter
[in] alpha the width parameter
Definition at line 94 of file signalWindows.hpp.
References mx::sigproc::window::tukey().