mxlib: Noise Profiles
Noise Profiles
Image Processing | Signal Processing » Image Filters
Noise profiles of images
Function Documentation
stddevImage() [1/2]
template<typename eigenImT , typename eigenImT1 , typename eigenImT2 > void mx::improc::stddevImage (eigenImT & stdIm, const eigenImT1 & im, const eigenImT2 & mask, typename eigenImT::Scalar minRad, typename eigenImT::Scalar maxRad, bool divide = false)
Form a standard deviation image, and optionally divide the input by it to form a S/N map.
The standard deviation profile is calculated using linear interpolation on a 1 pixel grid
This version creates a radius map on each call, and calls the above version. This should not be used for repeated alls, rather create a radius map ahead of time.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
eigenImT the eigen array type of the output and non-reference images
Parameters
[out] stdIm the standard deviation image. This will be resized.
[in] im the image to form the standard deviation profile of, never altered.
[in] mask a 1/0 mask. 0 pixels are excluded from the std-dev calculations.
[in] minRad the minimum radius to analyze
[in] maxRad the maximum radius to analyze
[in] divide [optional] if true, the output is the input image is divided by the std-dev profile, i.e. a S/N map. default is false.
Definition at line 1401 of file imageFilters.hpp.
References mx::improc::radiusImage(), and mx::improc::stddevImage().
stddevImage() [2/2]
template<typename eigenImT , typename eigenImT1 , typename eigenImT2 , typename eigenImT3 > void mx::improc::stddevImage (eigenImT & stdIm, const eigenImT1 & im, const eigenImT2 & rad, const eigenImT3 & mask, typename eigenImT::Scalar minRad, typename eigenImT::Scalar maxRad, bool divide)
Form a standard deviation image, and optionally divide the input by it to form a S/N map.
The standard deviation profile is calculated using linear interpolation on a 1 pixel grid
Template Parameters
eigenImT the eigen array type of the output and non-reference images. Each image input can be a different type to allow references, etc.
Parameters
[out] stdIm the standard deviation image. This will be resized.
[in] im the image to form the standard deviation profile of, never altered.
[in] rad array of radius values
[in] mask a 1/0 mask. 0 pixels are excluded from the std-dev calculations.
[in] minRad the minimum radius to analyze
[in] maxRad the maximum radius to analyze
[in] divide if true, the output is the input image is divided by the std-dev profile, i.e. a S/N map. default is false.
Definition at line 1295 of file imageFilters.hpp.
References mx::math::vectorVariance().
Referenced by mx::improc::stddevImage(), and mx::improc::stddevImageCube().
stddevImageCube()
template<typename eigenCubeT , typename eigenCubeT1 , typename eigenCubeT2 , typename radT1 , typename radT2 > void mx::improc::stddevImageCube (eigenCubeT & stdImc, const eigenCubeT1 & imc, const eigenCubeT2 & maskCube, radT1 minRad, radT2 maxRad, bool divide = false)
Form a standard deviation image for each imamge in a cube, and optionally divide the input by it forming a S/N map cube.
The standard deviation profile is calculated using linear interpolation on a 1 pixel grid
Template Parameters
eigencubeT is the eigen cube type of the input and output cubes.
eigenImT the eigen array type of the output and non-reference images.
Parameters
[out] stdImc the standard deviation image cube. This will be resized.
[in] imc the image cube to form the standard deviation profile of.
[in] maskCube a 1/0 mask. 0 pixels are excluded from the std-dev calculations.
[in] minRad the minimum radius to analyze
[in] maxRad the maximum radius to analyze
[in] divide [optional] if true, the output is the input image is divided by the std-dev profile, i.e. a S/N map. default is false.
Definition at line 1430 of file imageFilters.hpp.
References mx::improc::radiusImage(), and mx::improc::stddevImage().