mxlib: Working with strings
Working with strings
General Utilities » Input/Output Utilities
Various tools for working with strings.
Various tools for working with strings.
Files
file stringUtils.hpp
utilities for working with strings
Functions
template<typename typeT , unsigned width = 0, char pad = ' '>
std::string mx::ioutils::convertToString (const typeT &value, int precision=0)
Convert a numerical value to a string.
template<>
std::string mx::ioutils::convertToString< std::string > (const std::string &value, int UNUSED(precision))
Specialization of convertToString to avoid converting a string to a string.
template<typename typeT >
typeT mx::ioutils::convertFromString (const std::string &str)
Convert a string to a numerical value.
template<>
char mx::ioutils::convertFromString< char > (const std::string &str)
Template specialization of convertFromString for char.
template<>
unsigned char mx::ioutils::convertFromString< unsigned char > (const std::string &str)
Template specialization of convertFromString for unsigned char.
template<>
short mx::ioutils::convertFromString< short > (const std::string &str)
Template specialization of convertFromString for short.
template<>
unsigned short mx::ioutils::convertFromString< unsigned short > (const std::string &str)
Template specialization of convertFromString for unsigned short.
template<>
int mx::ioutils::convertFromString< int > (const std::string &str)
Template specialization of convertFromString for int.
template<>
unsigned int mx::ioutils::convertFromString< unsigned int > (const std::string &str)
Template specialization of convertFromString for unsigned int.
template<>
long mx::ioutils::convertFromString< long > (const std::string &str)
Template specialization of convertFromString for long.
template<>
unsigned long mx::ioutils::convertFromString< unsigned long > (const std::string &str)
Template specialization of convertFromString for unsigned long.
template<>
long long mx::ioutils::convertFromString< long long > (const std::string &str)
Template specialization of convertFromString for long long.
template<>
unsigned long long mx::ioutils::convertFromString< unsigned long long > (const std::string &str)
Template specialization of convertFromString for unsigned long long.
template<>
float mx::ioutils::convertFromString< float > (const std::string &str)
Template specialization of convertFromString for float.
template<>
double mx::ioutils::convertFromString< double > (const std::string &str)
Template specialization of convertFromString for double.
template<>
long double mx::ioutils::convertFromString< long double > (const std::string &str)
Template specialization of convertFromString for long double.
template<>
bool mx::ioutils::convertFromString< bool > (const std::string &str)
Template specialization of convertFromString for bool.
void mx::ioutils::toLower (std::string &outstr, const std::string &instr)
Convert a string to all lower case.
std::string mx::ioutils::toLower (const std::string &instr)
Convert a string to all lower case.
void mx::ioutils::toUpper (std::string &outstr, const std::string &instr)
Convert a string to all upper case.
std::string mx::ioutils::toUpper (const std::string &instr)
Convert a string to all upper case.
void mx::ioutils::removeWhiteSpace (std::string &outstr, const std::string &instr)
Remove all white space from a string.
std::string mx::ioutils::removeWhiteSpace (const std::string &instr)
Remove all white space from a string.
int mx::ioutils::stringWrap (std::vector< std::string > &lines, const std::string &str, int width)
Wrap a string by breaking it into smaller sized portions of a desired width.
template<typename typeT >
void mx::ioutils::parseStringVector (std::vector< typeT > &v, const std::string &s, char delim=',')
Parses a string into a vector of tokens delimited by a character.
template<typename typeT >
void mx::ioutils::parseStringVector (std::vector< typeT > &v, const std::string &s, const std::string &delims)
Parses a string into a vector of tokens delimited by a set of characters.
Function Documentation
convertFromString()
template<typename typeT > typeT mx::ioutils::convertFromString (const std::string & str)
Convert a string to a numerical value.
The default version attempts to do the conversion with a simple c style cast. The various template specializations handle conversions to the basic types.
Example:
std::string str = "2.34567";
double d;
d = convertFromString<double>(str);
Template Parameters
typeT is the type of the numerical value desired
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 155 of file stringUtils.hpp.
convertFromString< bool >()
template<> bool mx::ioutils::convertFromString< bool > (const std::string & str) inline
Template specialization of convertFromString for bool.
First looks for 0/1,f/t, or F/T in the first non-space character of str. otherwise uses convertFromString<int>.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 330 of file stringUtils.hpp.
References mx::astro::constants::c(), and mx::ioutils::convertFromString< int >().
convertFromString< char >()
template<> char mx::ioutils::convertFromString< char > (const std::string & str) inline
Template specialization of convertFromString for char.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 170 of file stringUtils.hpp.
convertFromString< double >()
template<> double mx::ioutils::convertFromString< double > (const std::string & str) inline
Template specialization of convertFromString for double.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 305 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::Double().
convertFromString< float >()
template<> float mx::ioutils::convertFromString< float > (const std::string & str) inline
Template specialization of convertFromString for float.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 292 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::Float().
convertFromString< int >()
template<> int mx::ioutils::convertFromString< int > (const std::string & str) inline
Template specialization of convertFromString for int.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 220 of file stringUtils.hpp.
Referenced by mx::ioutils::convertFromString< bool >(), and mx::improc::fitsHeaderCard::Int().
convertFromString< long >()
template<> long mx::ioutils::convertFromString< long > (const std::string & str) inline
Template specialization of convertFromString for long.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 244 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::Long().
convertFromString< long double >()
template<> long double mx::ioutils::convertFromString< long double > (const std::string & str) inline
Template specialization of convertFromString for long double.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 317 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::longDouble().
convertFromString< long long >()
template<> long long mx::ioutils::convertFromString< long long > (const std::string & str) inline
Template specialization of convertFromString for long long.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 268 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::longLong().
convertFromString< short >()
template<> short mx::ioutils::convertFromString< short > (const std::string & str) inline
Template specialization of convertFromString for short.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 196 of file stringUtils.hpp.
convertFromString< unsigned char >()
template<> unsigned char mx::ioutils::convertFromString< unsigned char > (const std::string & str) inline
Template specialization of convertFromString for unsigned char.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 183 of file stringUtils.hpp.
convertFromString< unsigned int >()
template<> unsigned int mx::ioutils::convertFromString< unsigned int > (const std::string & str) inline
Template specialization of convertFromString for unsigned int.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 232 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::unsignedInt().
convertFromString< unsigned long >()
template<> unsigned long mx::ioutils::convertFromString< unsigned long > (const std::string & str) inline
Template specialization of convertFromString for unsigned long.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 256 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::unsignedLong().
convertFromString< unsigned long long >()
template<> unsigned long long mx::ioutils::convertFromString< unsigned long long > (const std::string & str) inline
Template specialization of convertFromString for unsigned long long.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 280 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::unsignedLongLong().
convertFromString< unsigned short >()
template<> unsigned short mx::ioutils::convertFromString< unsigned short > (const std::string & str) inline
Template specialization of convertFromString for unsigned short.
Returns
the converted numerical value.
Parameters
[in] str [in] is the string to convert
Definition at line 208 of file stringUtils.hpp.
convertToString()
template<typename typeT , unsigned width = 0, char pad = ' '> std::string mx::ioutils::convertToString (const typeT & value, int precision = 0)
Convert a numerical value to a string.
The default version uses the stream library to convert. A specialization is provided to prevent conversion of std::string.
The precision parameter is only used for floating point types. If the default precision==0 is passed, then the maximum useful precision is used, from the value of std::numeric_limits<typeT>::max_digits10.
The width and pad template parameters can be used to set a fixed maximum width and a pad character.
Examples:
To convert a double precision number to string:
double d = 2.898434;
std::string str;
str = convertToString(d);  //note that you will not normally need to specify <typeT>
To produce a fixed width 0 padded string from an integer:
int i = 23;
std::string str;
str = convertToString<int, 5, '0'>(i);  //result is "00023".
Template Parameters
typeT is the type of value to convert
width specifies the maximum width, not including the '\0'
pad specifies the pad character
Returns
a string representation of value
Parameters
[in] value [in] the value of type typeT to be converted
[in] precision [in] [optional] the precision (see http://www.cplusplus.com/reference/ios/ios_base/precision/) to use for floating point types.
Definition at line 83 of file stringUtils.hpp.
References mx::astro::constants::c().
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid(), mx::app::appConfigurator::get(), mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::getGridPSD(), mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::makePSDGrid(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT, _coronT >::~simulatedAOSystem().
convertToString< std::string >()
template<> std::string mx::ioutils::convertToString< std::string > (const std::string & value, int UNUSEDprecision) inline
Specialization of convertToString to avoid converting a string to a string.
Definition at line 128 of file stringUtils.hpp.
parseStringVector() [1/2]
template<typename typeT > void mx::ioutils::parseStringVector (std::vector< typeT > & v, const std::string & s, char delim = ',')
Parses a string into a vector of tokens delimited by a character.
E.g., the string
std::string s={"0,1,2,3,4"};
std::vector<int> v;
parseStringVector(v,s);
is parsed to a vector as if it was initialized with
std::vector<int> v = {0,1,2,3,4};
Template Parameters
typeT the type to convert the tokens too.
Parameters
[out] v [out] the vector holding the parsed and converted tokens. Is cleared.
[in] s [in] the string to parse
[in] delim [in] [optional] the delimiter. Default is comma ','.
Definition at line 511 of file stringUtils.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::readPSFSub().
parseStringVector() [2/2]
template<typename typeT > void mx::ioutils::parseStringVector (std::vector< typeT > & v, const std::string & s, const std::string & delims)
Parses a string into a vector of tokens delimited by a set of characters.
E.g., the string
std::string s={"0,1:2 3,4"};
std::vector<int> v;
parseStringVector(v, s, ",: ");
is parsed to a vector as if it was initialized with
std::vector<int> v = {0,1,2,3,4};
Template Parameters
typeT the type to convert the tokens too.
Parameters
[out] v [out] the vector holding the parsed and converted tokens. Is cleared.
[in] s [in] the string to parse
[in] delims [in] the delimiters.
Definition at line 549 of file stringUtils.hpp.
removeWhiteSpace() [1/2]
std::string mx::ioutils::removeWhiteSpace (const std::string & instr) inline
Remove all white space from a string.
Uses std::remove_if.
Returns
the modified string.
Parameters
[in] instr [in] is the string to remove whitespace from
Definition at line 434 of file stringUtils.hpp.
removeWhiteSpace() [2/2]
void mx::ioutils::removeWhiteSpace (std::string & outstr, const std::string & instr) inline
Remove all white space from a string.
Uses std::remove_if.
Parameters
[out] outstr [out] will contain the new string with no whitespace.
[in] instr [in] is the string to remove whitespace from
Definition at line 418 of file stringUtils.hpp.
Referenced by mx::astro::numSpType().
stringWrap()
int mx::ioutils::stringWrap (std::vector< std::string > & lines, const std::string & str, int width) inline
Wrap a string by breaking it into smaller sized portions of a desired width.
Whenever possible breaks at spaces. A single space is discarded at the break.
Parameters
[out] lines [out] each new entry contains a wrapped portion of the string. Not cleared, so can accumulate.
[in] str [in] the string to wrap
[in] width [in] the maximum width of the output strings
Definition at line 448 of file stringUtils.hpp.
Referenced by mx::ioutils::textTable::addCell().
toLower() [1/2]
std::string mx::ioutils::toLower (const std::string & instr) inline
Convert a string to all lower case.
Calls the c tolower function for each character in instr.
Returns
the all lower case string
Parameters
[in] instr [in] is the string to convert
Definition at line 370 of file stringUtils.hpp.
toLower() [2/2]
void mx::ioutils::toLower (std::string & outstr, const std::string & instr) inline
Convert a string to all lower case.
Calls the c tolower function for each character in instr.
Parameters
[out] outstr [out] will be resized and populated with the lower case characters
[in] instr [in] is the string to convert
Definition at line 350 of file stringUtils.hpp.
Referenced by mx::astro::picklesSpectrum< _units >::fileName().
toUpper() [1/2]
std::string mx::ioutils::toUpper (const std::string & instr) inline
Convert a string to all upper case.
Calls the c toupper function for each character in instr.
Returns
the all lower case string
Parameters
[in] instr [in] is the string to convert
Definition at line 404 of file stringUtils.hpp.
toUpper() [2/2]
void mx::ioutils::toUpper (std::string & outstr, const std::string & instr) inline
Convert a string to all upper case.
Calls the c toupper function for each character in instr.
Parameters
[out] outstr [out] will be resized and populated with the lower case characters
[in] instr [in] is the string to convert
Definition at line 384 of file stringUtils.hpp.
Referenced by mx::astro::numSpType().