mxlib: Bessel Functions
Bessel Functions
General Mathematics » Special Functions
Functions involving Bessel Functions.
Functions
template<typename T1 , typename T2 >
T2 mx::math::func::bessel_j (T1 v, T2 x)
Bessel Functions of the First Kind.
template<typename T >
T mx::math::func::jinc (const T &x)
The Jinc function.
template<typename T1 , typename T2 >
T2 mx::math::func::jincN (const T1 &v, const T2 &x)
The JincN function.
Function Documentation
bessel_j()
template<typename T1 , typename T2 > T2 mx::math::func::bessel_j (T1 v, T2 x)
Bessel Functions of the First Kind.
This is a wrapper for boost.
Parameters
[in] v
[in] x
Definition at line 49 of file bessel.hpp.
Referenced by mx::sigproc::zernikeQ(), and mx::sigproc::zernikeQNorm().
jinc()
template<typename T > T mx::math::func::jinc (const T & x)
The Jinc function.
The Jinc function is defined here as
\[ Ji(x) = \frac{J_1(x)}{x} \]
where \(J_1 \) is the cylindrical bessel function of the first kind of order 1.
Follows the technique in boost sinc_pi, using the Taylor series for small arguments. If x is smaller than \(\epsilon \), then it returns 1/2. If x is larger than \(\epsilon \) but smaller than \(\sqrt{\epsilon} \), then this function returns
\[ Ji(x) \approx \frac{1}{2} - \frac{x^2}{16}. \]
Returns
the value of Ji(x)
Template Parameters
T is an floating point type
Parameters
[in] x the argument
Definition at line 61 of file jinc.hpp.
References mx::math::six_fifths().
Referenced by mx::math::func::airyPattern(), mx::math::func::airyPattern(), mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), mx::AO::sim::turbSubHarmonic< _turbAtmosphereT, _verboseT >::initGrid(), mx::AO::analysis::jincFuncs(), mx::math::func::jincN(), mx::AO::analysis::vonKarmanSpectrum< realT >::operator()(), mx::AO::analysis::phiInt_basic(), mx::AO::analysis::phiInt_mod(), and mx::sigproc::zernikePPiston().
jincN()
template<typename T1 , typename T2 > T2 mx::math::func::jincN (const T1 & v, const T2 & x)
The JincN function.
The JincN function is defined here as
\[ Ji_N(x) = \frac{J_N(x)}{x} \]
where \(J_N \) is the cylindrical bessel function of the first kind of order N, \(N \ge 1 \).
If \(N == 1 \) this returns jinc(x).
Otherwise, if x is smaller than \(\sqrt{\epsilon} \), returns 0.
Returns
the value of JiN(x)
Parameters
[in] v the Bessel function order
[in] x the argument
Definition at line 112 of file jinc.hpp.
References mx::math::func::jinc(), and mx::math::six_fifths().
Referenced by mx::AO::sim::turbSubHarmonic< _turbAtmosphereT, _verboseT >::initGrid(), mx::AO::analysis::vonKarmanSpectrum< realT >::operator()(), mx::sigproc::zernikePAstig(), mx::sigproc::zernikePComa(), mx::sigproc::zernikePDefocus(), mx::sigproc::zernikePTipTilt(), and mx::sigproc::zernikePTrefoil().