mxlib: General Constants
General Constants
General Mathematics » Constants and units
Constants of general applicability
Modules
Boost Constants
Constants provided by the boost library.
Functions
template<typename T >
constexpr T mx::math::pi ()
Get the value of pi.
template<typename T >
constexpr T mx::math::two_pi ()
Get the value of 2pi.
template<typename T >
constexpr T mx::math::half_pi ()
Get the value of pi/2.
template<typename T >
constexpr T mx::math::rad2deg ()
Get the value of 180/pi.
template<typename T >
constexpr T mx::math::root_two ()
Get the value of sqrt(2)
template<typename T >
constexpr T mx::math::ln_two ()
Get the value of ln(2)
template<typename T >
constexpr T mx::math::third ()
Get the value of 1/3.
template<typename floatT >
constexpr floatT mx::math::five_thirds ()
Return 5/3 in the specified precision.
template<typename floatT >
constexpr floatT mx::math::five_sixths ()
Return 5/6 in the specified precision.
template<typename floatT >
constexpr floatT mx::math::eleven_thirds ()
Return 11/3 in the specified precision.
template<typename floatT >
constexpr floatT mx::math::eleven_sixths ()
Return 11/6 in the specified precision.
template<typename floatT >
constexpr floatT mx::math::six_fifths ()
Return 6/5 in the specified precision.
template<typename floatT >
constexpr floatT mx::math::three_fifths ()
Return 3/5 in the specified precision.
template<typename floatT >
constexpr floatT mx::math::seventeen_thirds ()
Return 17/3 in the specified precision.
Function Documentation
eleven_sixths()
template<typename floatT > constexpr floatT mx::math::eleven_sixths () constexpr
Return 11/6 in the specified precision.
This constant is used frequently in adaptive optics analysis.
Definition at line 393 of file constants.hpp.
eleven_thirds()
template<typename floatT > constexpr floatT mx::math::eleven_thirds () constexpr
Return 11/3 in the specified precision.
This constant is used frequently in adaptive optics analysis.
Definition at line 382 of file constants.hpp.
five_sixths()
template<typename floatT > constexpr floatT mx::math::five_sixths () constexpr
Return 5/6 in the specified precision.
This constant is used frequently in adaptive optics analysis.
Definition at line 371 of file constants.hpp.
five_thirds()
template<typename floatT > constexpr floatT mx::math::five_thirds () constexpr
Return 5/3 in the specified precision.
This constant is used frequently in adaptive optics analysis.
Definition at line 360 of file constants.hpp.
half_pi()
template<typename T > constexpr T mx::math::half_pi () constexpr
Get the value of pi/2.
Specializations provided for float, double, long double, and quad (if supported). Can default to boost for other types if MX_INCLUDE_BOOST is defined.
Definition at line 145 of file constants.hpp.
ln_two()
template<typename T > constexpr T mx::math::ln_two () constexpr
Get the value of ln(2)
Specializations provided for float, double, long double, and quad (if supported). Can default to boost for other types if MX_INCLUDE_BOOST is defined.
Definition at line 281 of file constants.hpp.
pi()
template<typename T > constexpr T mx::math::pi () constexpr
Get the value of pi.
Specializations provided for float, double, long double, and quad if supported. Can default to boost for other types if MX_INCLUDE_BOOST is defined.
Definition at line 55 of file constants.hpp.
rad2deg()
template<typename T > constexpr T mx::math::rad2deg () constexpr
Get the value of 180/pi.
Specializations provided for float, double, long double, and quad (if supported). Can default to boost for other types if MX_INCLUDE_BOOST is defined.
Definition at line 191 of file constants.hpp.
root_two()
template<typename T > constexpr T mx::math::root_two () constexpr
Get the value of sqrt(2)
Specializations provided for float, double, long double, and quad (if supported). Can default to boost for other types if MX_INCLUDE_BOOST is defined.
Definition at line 236 of file constants.hpp.
seventeen_thirds()
template<typename floatT > constexpr floatT mx::math::seventeen_thirds () constexpr
Return 17/3 in the specified precision.
This constant is used frequently in adaptive optics analysis.
Definition at line 426 of file constants.hpp.
six_fifths()
template<typename floatT > constexpr floatT mx::math::six_fifths () constexpr
Return 6/5 in the specified precision.
This constant is used frequently in adaptive optics analysis.
Definition at line 404 of file constants.hpp.
Referenced by mx::math::ft::fftwEnvironment< realT, threads >::fftwEnvironment(), mx::math::gslInterpolator< interpT >::gslInterpolator(), mx::math::gslInterpolator< interpT >::gslInterpolator(), mx::math::histogramUniform< realT >::histogramUniform(), mx::math::fit::levmarInterface< fitterT >::levmarInterface(), mx::math::point2D< _angleT >::point2D(), mx::math::point2D< _angleT >::point2D(), mx::math::randomT< typeT, _ranengT, _randistT >::randomT(), mx::math::ft::fftwEnvironment< realT, threads >::~fftwEnvironment(), mx::math::gslInterpolator< interpT >::~gslInterpolator(), mx::math::histogramUniform< realT >::accum(), mx::math::histogramUniform< realT >::accum(), mx::math::func::airyPattern(), mx::math::func::airyPattern(), mx::math::func::airyPattern(), mx::math::func::airyPattern2D(), mx::math::func::airyPatternEnclosed(), mx::math::func::airyPatternEnclosed(), mx::math::fit::levmarInterface< fitterT >::allocate_params(), mx::math::fit::levmarInterface< fitterT >::allocate_params(), mx::math::fit::levmarInterface< fitterT >::allocate_work(), mx::AO::analysis::aoAtmosphere< _realT >::alpha(), mx::math::angleDiff(), mx::improc::angleImage(), mx::math::angleMean(), mx::math::angleMod(), mx::improc::annulusBoundingRect(), mx::improc::annulusCoordsWorker(), mx::AO::applyPupil2Basis(), mx::sigproc::ar1FreqPhase(), mx::sigproc::ar1PSD(), mx::sigproc::ar1PSD(), mx::sigproc::ar1PSDNorm(), mx::math::ft::augmentR2CFFTOutput(), mx::AO::analysis::aoAtmosphere< _realT >::beta(), mx::AO::analysis::pywfsUnmod< realT, iosT >::beta_p(), mx::AO::analysis::pywfsModAsymptotic< realT, iosT >::beta_p(), mx::math::histogramUniform< realT >::binLeft(), mx::math::histogramUniform< realT >::binMid(), mx::math::histogramUniform< realT >::binRight(), mx::AO::sim::directPhaseReconstructor< realT >::calAmp(), mx::astro::calcAzEl(), mx::AO::constants::calcConstants(), mx::math::calcEigenVecs(), mx::math::calcKLModes(), mx::math::continueAngles(), mx::math::cubicDepressed(), mx::math::cubicDescriminant(), mx::math::cubicRealRoot(), mx::improc::drawLine(), mx::math::dtor(), mx::math::fit::levmarInterface< fitterT >::dumpParameters(), mx::math::fit::levmarInterface< fitterT >::dumpParameters(), mx::math::fit::levmarInterface< fitterT >::dumpReport(), mx::math::fit::levmarInterface< fitterT >::dumpReport(), mx::AO::analysis::aoAtmosphere< _realT >::dX(), mx::AO::analysis::aoAtmosphere< _realT >::dY(), mx::math::eigenGESDD(), mx::math::eigenPseudoInverse(), mx::math::eigenPseudoInverse(), mx::math::eigenPseudoInverse(), mx::math::eigenSYEVR(), mx::math::eigenSYRK(), mx::math::func::expModGaussian(), mx::math::func::expModGaussianMode(), mx::AO::analysis::F_basic(), mx::AO::analysis::aoAtmosphere< _realT >::f_g(), mx::AO::analysis::F_mod(), mx::math::ft::fftw_wisdom_filename(), mx::math::fit::fitGaussian1D< _realT >::fit(), mx::math::fit::fitGaussian2D< fitterT >::fit(), mx::math::fit::levmarInterface< fitterT >::fit(), mx::AO::analysis::fourierPSDMap(), mx::AO::analysis::fourierVarVec(), mx::math::histogramUniform< realT >::freq(), mx::math::fit::fitGaussian2D< fitterT >::fwhm(), mx::math::func::fwhm2sigma(), mx::math::func::gammaDistribution(), mx::math::func::gammaDistribution(), mx::math::func::gammaDistributionDenom(), mx::math::func::gaussian(), mx::math::func::gaussian2D(), mx::math::func::gaussian2D(), mx::math::func::gaussian2D_ang(), mx::math::func::gaussian2D_gen2rot(), mx::math::func::gaussian2D_jacobian(), mx::math::func::gaussian2D_rot2gen(), mx::sigproc::window::genCosine(), mx::sigproc::window::genCosine(), mx::sigproc::window::genCosine(), mx::astro::getGMST(), mx::math::gsl_interpolate(), mx::math::gsl_interpolate(), mx::math::fit::guessGauss2D_ang(), mx::math::hadd(), mx::math::hadd_impl(), mx::math::hadp_impl(), mx::AO::sim::turbSubHarmonic< _turbAtmosphereT, _verboseT >::initGrid(), mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::intensityPSD(), mx::math::func::jinc(), mx::AO::analysis::jincFuncs(), mx::math::func::jincN(), mx::AO::analysis::aoAtmosphere< _realT >::layer_Cn2(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::loadGMagAOX(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::loadGuyon2005(), mx::math::func::logistic(), mx::math::func::logistic_param(), mx::sigproc::makeFourierModeC(), mx::sigproc::makeFourierModeS(), mx::sigproc::makeModifiedFourierMode(), mx::wfp::fraunhoferPropagator< _wavefrontT, _cudaGPU >::makeShiftPhase(), mx::improc::maskWedge(), mx::math::func::moffat(), mx::math::func::moffat2D(), mx::math::func::moffatFWHM(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::ncpError(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::ncpError(), mx::math::histogramUniform< realT >::normalize(), mx::math::fit::levmarInterface< fitterT >::nParams(), mx::AO::analysis::clGainOpt< _realT >::olXfer(), mx::math::operator!=(), mx::math::gslInterpolator< interpT >::operator()(), mx::math::logInterpolator< interpT >::operator()(), mx::AO::analysis::vonKarmanSpectrum< realT >::operator()(), mx::math::operator==(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::optimumTauWFS(), mx::astro::orbitLambertPhase(), mx::astro::orbitMeanAnol(), mx::astro::orbitPeriod(), mx::astro::orbitSemiMaj(), mx::AO::orthogonalizeBasis(), mx::math::func::orthoNormalLegendre(), mx::math::ft::padC2CFFTOutput(), mx::math::ft::padR2CFFTOutput(), mx::math::laplace_distribution< _RealType >::param(), mx::AO::sim::pyramidSensor< _realT, _detectorT, _cudaGPU >::perStep(), mx::AO::analysis::phiInt_basic(), mx::AO::analysis::phiInt_mod(), mx::astro::planetMass2Radius(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::gnuPlot::plot(), mx::math::fit::levmarInterface< fitterT >::point_params(), mx::math::fit::levmarInterface< fitterT >::point_params(), mx::sigproc::psdVarMeanFunc(), mx::math::quarticRoots(), mx::AO::analysis::aoAtmosphere< _realT >::r_0(), mx::improc::radAngImage(), mx::math::radprofIntegral(), mx::math::randomSeed(), mx::math::point2D< _angleT >::rotate(), mx::math::point2D< _angleT >::rotate(), mx::math::point2D< _angleT >::rotateInPlace(), mx::math::point2D< _angleT >::rotateInPlace(), mx::math::rotatePoint(), mx::math::rtod(), SCENARIO(), SCENARIO(), mx::AO::sim::turbSubHarmonic< _turbAtmosphereT, _verboseT >::screen(), mx::math::randomT< typeT, _ranengT, _randistT >::seed(), mx::math::randomT< typeT, _ranengT, _randistT >::seed(), mx::math::func::seeingHalo(), mx::math::fit::levmarInterface< fitterT >::set_itmax(), mx::math::fit::levmarInterface< fitterT >::set_opts(), mx::math::fit::levmarInterface< fitterT >::set_params(), mx::math::fit::fitEmpirical2DGen< fitterT >::setArray(), mx::math::fit::fitEmpirical2DGen< fitterT >::setArray(), mx::math::fit::fitGaussian2D< fitterT >::setArray(), mx::math::fit::array2FitGaussian1D< realT >::setFixed(), mx::math::fit::array2FitGaussian2D< realT >::setFixed(), mx::math::fit::array2FitMoffat1D< realT >::setFixed(), mx::math::fit::array2FitMoffat< realT >::setFixed(), mx::math::fit::array2FitEmpirical< realT >::setFixed(), mx::math::fit::fitAiry2D< fitterT >::setGuess(), mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setKernel(), mx::astro::cahoyGrid< _units >::setSpectrum(), mx::math::logInterpolator< interpT >::setup(), mx::math::gslInterpolator< interpT >::setup(), mx::math::histogramUniform< realT >::setup(), mx::math::gslInterpolator< interpT >::setup(), mx::math::func::sigma2fwhm(), mx::AO::analysis::speckleAmpPSD(), mx::AO::analysis::aoAtmosphere< _realT >::tau_0(), mx::wfp::tiltWavefront(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::timeDelayError(), mx::sigproc::window::tukey(), mx::sigproc::window::tukey2d(), mx::sigproc::window::tukey2dAnnulus(), mx::sigproc::window::tukey2dSquare(), mx::AO::analysis::aoAtmosphere< _realT >::update_v_wind(), mx::AO::analysis::aoAtmosphere< _realT >::update_z_mean(), mx::math::vectorBinMeans(), mx::math::vectorCumHist(), mx::math::vectorCumHistReverse(), mx::math::vectorGaussConvolve(), mx::math::vectorMean(), mx::math::vectorMean(), mx::math::vectorMean(), mx::math::vectorMeanSub(), mx::math::vectorMeanSub(), mx::math::vectorMedian(), mx::math::vectorMedianInPlace(), mx::math::vectorMedianSub(), mx::math::vectorRebin(), mx::math::vectorScale(), mx::math::vectorSigmaMean(), mx::math::vectorSigmaMean(), mx::math::vectorSigmaMean(), mx::math::vectorSigmaMean(), mx::math::vectorSmoothMax(), mx::math::vectorSmoothMean(), mx::math::vectorSmoothMean(), mx::math::vectorSmoothMean(), mx::math::vectorSmoothMedian(), mx::math::vectorSortOrder(), mx::math::vectorSub(), mx::math::vectorSub(), mx::math::vectorSum(), mx::math::vectorSum(), mx::math::vectorVariance(), mx::math::vectorVariance(), mx::math::vectorVariance(), mx::math::vectorVariance(), mx::math::func::weibull(), mx::math::func::weibull_lambda(), mx::AO::analysis::aoAtmosphere< _realT >::X(), mx::AO::analysis::aoAtmosphere< _realT >::X_Z(), mx::AO::analysis::aoAtmosphere< _realT >::Y(), mx::sigproc::zernike(), mx::sigproc::zernikePAstig(), mx::sigproc::zernikePComa(), mx::sigproc::zernikePDefocus(), mx::sigproc::zernikePPiston(), mx::sigproc::zernikePTipTilt(), mx::sigproc::zernikePTrefoil(), mx::sigproc::zernikeQ(), and mx::sigproc::zernikeQNorm().
third()
template<typename T > constexpr T mx::math::third () constexpr
Get the value of 1/3.
Wrapper for boost constant. Specializations provided for float, double, and long double.
Definition at line 325 of file constants.hpp.
three_fifths()
template<typename floatT > constexpr floatT mx::math::three_fifths () constexpr
Return 3/5 in the specified precision.
This constant is used frequently in adaptive optics analysis.
Definition at line 415 of file constants.hpp.
two_pi()
template<typename T > constexpr T mx::math::two_pi () constexpr
Get the value of 2pi.
Specializations provided for float, double, long double, and quad (if supported). Can default to boost for other types if MX_INCLUDE_BOOST is defined.
Definition at line 100 of file constants.hpp.