mxlib: fitsHeaderCard Unit Tests
fitsHeaderCard Unit Tests
Testing » Unit Tests » I/O Utilities Unit Tests » FITS Unit Tests
Functions
mx::unitTest::fitsTest::fitsHeaderCardTest::TEST_CASE ("fitsHeaderCard setting types", "[ioutils::fits::fitsHeaderCard]")
Verify conversion of types.
mx::unitTest::fitsTest::fitsHeaderCardTest::TEST_CASE ("Removing white space around string values", "[ioutils::fits::fitsHeaderCard]")
Removing white space around string values.
mx::unitTest::fitsTest::fitsHeaderCardTest::TEST_CASE ("CONTINUE-ing a card", "[ioutils::fits::fitsHeaderCard]")
CONTINUE-ing a card.
Function Documentation
TEST_CASE() [1/3]
mx::unitTest::fitsTest::fitsHeaderCardTest::TEST_CASE ("CONTINUE-ing a card" , "" [ioutils::fits::fitsHeaderCard])
CONTINUE-ing a card.
Definition at line 220 of file fitsHeaderCard_test.cpp.
References mx::fits::fitsHeaderCard< verboseT >::comment(), mx::fits::fitsHeaderCard< verboseT >::keyword(), mx::noerror, and mx::fits::fitsHeaderCard< verboseT >::String().
TEST_CASE() [2/3]
mx::unitTest::fitsTest::fitsHeaderCardTest::TEST_CASE ("fitsHeaderCard setting types" , "" [ioutils::fits::fitsHeaderCard])
Verify conversion of types.
Definition at line 23 of file fitsHeaderCard_test.cpp.
References mx::fits::fitsHeaderCard< verboseT >::comment(), mx::error, mx::fits::fitsHeaderCard< verboseT >::Int(), mx::fits::fitsHeaderCard< verboseT >::keyword(), mx::noerror, mx::fits::fitsHeaderCard< verboseT >::type(), mx::fits::fitsHeaderCard< verboseT >::value(), mx::fits::fitsHeaderCard< verboseT >::valueGood(), mx::fits::fitsHeaderCard< verboseT >::valueStr(), and mx::fits::fitsHeaderCard< verboseT >::valueStrGood().
TEST_CASE() [3/3]
mx::unitTest::fitsTest::fitsHeaderCardTest::TEST_CASE ("Removing white space around string values" , "" [ioutils::fits::fitsHeaderCard])
Removing white space around string values.
Definition at line 109 of file fitsHeaderCard_test.cpp.
References mx::fits::fitsHeaderCard< verboseT >::String(), and mx::fits::fitsHeaderCard< verboseT >::value().