mxlib: Putting a thread to sleep
Putting a thread to sleep
General Utilities » Working with time
Wrappers for std::this_thread::sleep_for
Functions
void mx::sys::sleep (unsigned sec)
Sleep for a specified period in seconds.
void mx::sys::milliSleep (unsigned msec)
Sleep for a specified period in milliseconds.
void mx::sys::microSleep (unsigned usec)
Sleep for a specified period in microseconds.
void mx::sys::nanoSleep (unsigned nsec)
Sleep for a specified period in nanoseconds.
Function Documentation
microSleep()
void mx::sys::microSleep (unsigned usec)
Sleep for a specified period in microseconds.
Tests:
Verify operation of thread sleep functions. [test doc]
Parameters
[in] usec the number of microseconds to sleep.
Definition at line 61 of file timeUtils.cpp.
Referenced by SCENARIO().
milliSleep()
void mx::sys::milliSleep (unsigned msec)
Sleep for a specified period in milliseconds.
Tests:
Verify operation of thread sleep functions. [test doc]
Parameters
[in] msec the number of milliseconds to sleep.
Definition at line 56 of file timeUtils.cpp.
Referenced by SCENARIO().
nanoSleep()
void mx::sys::nanoSleep (unsigned nsec)
Sleep for a specified period in nanoseconds.
Tests
Verify operation of thread sleep functions. [test doc]
Parameters
[in] nsec the number of microseconds to sleep.
Definition at line 66 of file timeUtils.cpp.
Referenced by SCENARIO().
sleep()
void mx::sys::sleep (unsigned sec)
Sleep for a specified period in seconds.
Tests:
Verify operation of thread sleep functions. [test doc]
Parameters
[in] sec the number of seconds to sleep.
Definition at line 51 of file timeUtils.cpp.
Referenced by SCENARIO().