mxlib: error_t Utilities Unit Tests
error_t Utilities Unit Tests
Testing » Unit Tests » Error Handling Unit Tests
Functions
unitTest::errorTest::error_tTest::TEST_CASE ("Test error_t code names", "[error::error_t]")
Test error_t code names.
unitTest::errorTest::error_tTest::TEST_CASE ("Test error_t messages", "[error::error_t]")
Test error_t messages.
unitTest::errorTest::error_tTest::TEST_CASE ("Test errno conversions", "[error::error_t]")
Test errno conversions.
unitTest::errorTest::error_tTest::TEST_CASE ("Test FITS error conversions", "[error::error_t]")
Test FITS error conversions.
Function Documentation
TEST_CASE() [1/4]
unitTest::errorTest::error_tTest::TEST_CASE ("Test errno conversions" , "" [error::error_t])
Test errno conversions.
Definition at line 83 of file error_t_test.cpp.
References mx::errno2error_t(), and mx::error.
TEST_CASE() [2/4]
unitTest::errorTest::error_tTest::TEST_CASE ("Test error_t code names" , "" [error::error_t])
Test error_t code names.
Definition at line 21 of file error_t_test.cpp.
References mx::errorName().
TEST_CASE() [3/4]
unitTest::errorTest::error_tTest::TEST_CASE ("Test error_t messages" , "" [error::error_t])
Test error_t messages.
Definition at line 53 of file error_t_test.cpp.
References mx::errorMessage().
TEST_CASE() [4/4]
unitTest::errorTest::error_tTest::TEST_CASE ("Test FITS error conversions" , "" [error::error_t])
Test FITS error conversions.
Definition at line 113 of file error_t_test.cpp.
References mx::error, and mx::fits_status2error_t().