mxlib: The Zernike Basis
The Zernike Basis
Signal Processing
int mx::sigproc::noll_nm (int &n, int &m, int j)
Get the Zernike coefficients n,m corrresponding the Noll index j.
template<typename realT >
int mx::sigproc::zernikeRCoeffs (std::vector< realT > &c, int n, int m)
Calculate the coefficients of a Zernike radial polynomial.
template<typename realT , typename calcRealT >
realT mx::sigproc::zernikeR (realT rho, int n, int m, std::vector< calcRealT > &c)
Calculate the value of a Zernike radial polynomial at a given separation.
template<typename realT , typename calcRealT >
realT mx::sigproc::zernikeR (realT rho, int n, int m)
Calculate the value of a Zernike radial polynomial at a given separation.
template<typename realT , typename calcRealT >
realT mx::sigproc::zernike (realT rho, realT phi, int n, int m, std::vector< calcRealT > &c)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
template<typename realT , typename calcRealT >
realT mx::sigproc::zernike (realT rho, realT phi, int n, int m)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
template<typename realT , typename calcRealT >
realT mx::sigproc::zernike (realT rho, realT phi, int j)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
template<typename arrayT , typename calcRealT , int overscan = 2>
int mx::sigproc::zernike (arrayT &arr, int n, int m, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
template<typename arrayT , typename calcRealT >
int mx::sigproc::zernike (arrayT &arr, int j, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
template<typename arrayT , typename calcRealT >
int mx::sigproc::zernike (arrayT &arr, int n, int m, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
template<typename arrayT , typename calcRealT >
int mx::sigproc::zernike (arrayT &arr, int j, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
template<typename cubeT , typename calcRealT >
int mx::sigproc::zernikeBasis (cubeT &cube, typename cubeT::Scalar rad=-1, int minj=2)
Fill in an Eigencube-like array with Zernike polynomials in Noll order.
template<typename realT >
realT mx::sigproc::zernikeQNorm (realT k, realT phi, int n, int m)
Calculate the square-normed Fourier transform of a Zernike polynomial at position (k,phi)
template<typename realT >
realT mx::sigproc::zernikeQNorm (realT k, realT phi, int j)
Calculate the square-normed Fourier transform of a Zernike polynomial at position (k,phi)
template<typename arrayT >
int mx::sigproc::zernikeQNorm (arrayT &arr, arrayT &k, arrayT &phi, int j)
Fill in an Eigen-like array with the square-normed Fourier transform of a Zernike polynomial.
template<typename realT >
realT mx::sigproc::zernikePPiston (const realT &kD)
Calculate the spatial power spectrum of Piston.
template<typename realT >
realT mx::sigproc::zernikePTipTilt (const realT &kD)
Calculate the spatial power spectrum of Tip & Tilt.
template<typename realT >
realT mx::sigproc::zernikePDefocus (const realT &kD)
Calculate the spatial power spectrum of Defocus.
template<typename realT >
realT mx::sigproc::zernikePAstig (const realT &kD)
Calculate the spatial power spectrum of Astigmatism.
template<typename realT >
realT mx::sigproc::zernikePComa (const realT &kD)
Calculate the spatial power spectrum of Coma.
template<typename realT >
realT mx::sigproc::zernikePTrefoil (const realT &kD)
Calculate the spatial power spectrum of Trefoil.
Function Documentation
noll_nm()
int mx::sigproc::noll_nm (int & n, int & m, int j)
Get the Zernike coefficients n,m corrresponding the Noll index j.
Calculates the values of (n,m) for an index j following Noll (1976) [16] See also: http://en.wikipedia.org/wiki/Zernike_polynomials
If j is odd, this returns m <= 0.
Return values
0 on success
-1 on error (j < 1)
Test:
Scenario: testing noll_nm [test doc]
Parameters
[out] n n the radial index of the Zernike polynomial
[out] m m the azimuthal index of the Zernnike polynomial. m < 0 if j odd.
[in] j j the Noll index, j > 0.
Definition at line 38 of file zernike.cpp.
References MXE_INVALIDARG, mxError, and mx::math::func::sign().
Referenced by SCENARIO(), mx::sigproc::zernike(), and mx::sigproc::zernikeQNorm().
zernike() [1/7]
template<typename arrayT , typename calcRealT > int mx::sigproc::zernike (arrayT & arr, int j, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
The geometric center of the array, 0.5*(arr.rows()-1), 0.5*(arr.cols()-1), is used as the center. Sets any pixel which is at rad <= r < rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] j is the Noll index of the polynomial
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Template Parameters
arrayT is an Eigen-like array of real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Definition at line 489 of file zernike.hpp.
zernike() [2/7]
template<typename arrayT , typename calcRealT > int mx::sigproc::zernike (arrayT & arr, int j, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
Sets any pixel which is at rad <= r <= rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] j is the Noll index of the polynomial
[in] xcen is the x coordinate of the desired center of the polynomial, in pixels
[in] ycen is the y coordinate of the desired center of the polynomial, in pixels
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Definition at line 439 of file zernike.hpp.
zernike() [3/7]
template<typename arrayT , typename calcRealT > int mx::sigproc::zernike (arrayT & arr, int n, int m, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
The geometric center of the array, 0.5*(arr.rows()-1), 0.5*(arr.cols()-1), is used as the center. Sets any pixel which is at rad <= r < rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] j is the Noll index of the polynomial
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Definition at line 466 of file zernike.hpp.
zernike() [4/7]
template<typename arrayT , typename calcRealT , int overscan = 2> int mx::sigproc::zernike (arrayT & arr, int n, int m, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
Sets any pixel which is at rad <= r < rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] n is the radial index of the polynomial
[in] m is the azimuthal index of the polynomial
[in] xcen is the x coordinate of the desired center of the polynomial, in pixels
[in] ycen is the y coordinate of the desired center of the polynomial, in pixels
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Definition at line 375 of file zernike.hpp.
zernike() [5/7]
template<typename realT , typename calcRealT > realT mx::sigproc::zernike (realT rho, realT phi, int j)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Parameters
[in] rho the radial coordinate, \(0 \le \rho \le 1 \).
[in] phi the azimuthal angle (in radians)
[in] j the Noll index of the Zernike polynomial.
Definition at line 334 of file zernike.hpp.
References mx::sigproc::noll_nm().
zernike() [6/7]
template<typename realT , typename calcRealT > realT mx::sigproc::zernike (realT rho, realT phi, int n, int m)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Parameters
[in] rho the radial coordinate, \(0 \le \rho \le 1 \).
[in] phi the azimuthal angle (in radians)
[in] n the radial index of the Zernike polynomial.
[in] m the azimuthal index of the Zernike polynomial.
Definition at line 297 of file zernike.hpp.
References mx::astro::constants::c().
zernike() [7/7]
template<typename realT , typename calcRealT > realT mx::sigproc::zernike (realT rho, realT phi, int n, int m, std::vector< calcRealT > & c)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
Parameters
[in] rho is the radial coordinate, \(0 \le \rho \le 1 \).
[in] phi is the azimuthal angle (in radians)
[in] n is the radial index of the Zernike polynomial.
[in] m is the azimuthal index of the Zernike polynomial.
[in] c is contains the radial polynomial coeeficients, and must be of length \(0.5(n-m)+1\).
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Definition at line 242 of file zernike.hpp.
References mx::astro::constants::c().
zernikeBasis()
template<typename cubeT , typename calcRealT > int mx::sigproc::zernikeBasis (cubeT & cube, typename cubeT::Scalar rad = -1, int minj = 2)
Fill in an Eigencube-like array with Zernike polynomials in Noll order.
The cube is pre-allocated to set the image size and the number of modes.
Returns
0 on success
-1 on error
Template Parameters
cubeT is an Eigencube-like array with real floating point type
calcRealT is a real floating type used for internal calculations, should be at least double
Parameters
cube [in/out] the pre-allocated cube which will be filled with the Zernike basis
[in] rad [optional] the radius of the aperture. If -1 then the full image size is used.
[in] minj [optional] the minimum j value to include. The default is j=2, which skips piston (j=1).
Definition at line 509 of file zernike.hpp.
Referenced by mx::AO::makeZernikeBasis().
zernikePAstig()
template<typename realT > realT mx::sigproc::zernikePAstig (const realT & kD)
Calculate the spatial power spectrum of Astigmatism.
Parameters
[in] kD Spatial frequency in diameter units, i.e. cycles per aperture.
Definition at line 682 of file zernike.hpp.
References mx::math::func::jincN().
zernikePComa()
template<typename realT > realT mx::sigproc::zernikePComa (const realT & kD)
Calculate the spatial power spectrum of Coma.
Parameters
[in] kD Spatial frequency in diameter units, i.e. cycles per aperture.
Definition at line 689 of file zernike.hpp.
References mx::math::func::jincN().
zernikePDefocus()
template<typename realT > realT mx::sigproc::zernikePDefocus (const realT & kD)
Calculate the spatial power spectrum of Defocus.
Parameters
[in] kD Spatial frequency in diameter units, i.e. cycles per aperture.
Definition at line 675 of file zernike.hpp.
References mx::math::func::jincN().
zernikePPiston()
template<typename realT > realT mx::sigproc::zernikePPiston (const realT & kD)
Calculate the spatial power spectrum of Piston.
Parameters
[in] kD Spatial frequency in diameter units, i.e. cycles per aperture.
Definition at line 661 of file zernike.hpp.
References mx::math::func::jinc().
zernikePTipTilt()
template<typename realT > realT mx::sigproc::zernikePTipTilt (const realT & kD)
Calculate the spatial power spectrum of Tip & Tilt.
Parameters
[in] kD Spatial frequency in diameter units, i.e. cycles per aperture.
Definition at line 668 of file zernike.hpp.
References mx::math::func::jincN().
zernikePTrefoil()
template<typename realT > realT mx::sigproc::zernikePTrefoil (const realT & kD)
Calculate the spatial power spectrum of Trefoil.
Parameters
[in] kD Spatial frequency in diameter units, i.e. cycles per aperture.
Definition at line 696 of file zernike.hpp.
References mx::math::func::jincN().
zernikeQNorm() [1/3]
template<typename arrayT > int mx::sigproc::zernikeQNorm (arrayT & arr, arrayT & k, arrayT & phi, int j)
Fill in an Eigen-like array with the square-normed Fourier transform of a Zernike polynomial.
The array is filled in with the values of |Q(k,phi)|^2 according to Equation (8) of Noll (1976) [16].
Test:
Scenario: testing zernikeQNorm [test doc]
Returns
0 on success
-1 on error
Template Parameters
arrayT is the Eigen-like array type. Arithmetic will be done in arrayT::Scalar.
Parameters
[out] arr the allocated array. The rows() and cols() members are used to size the transform.
[in] k the normalized spatial frequency magnitude at each pixel
[in] phi the spatial frequency angle at each pixel
[in] j the polynomial index in the Noll convention [16]
Definition at line 628 of file zernike.hpp.
References mx::astro::constants::k(), MXE_INVALIDARG, mxError, and mx::sigproc::noll_nm().
Referenced by mx::sigproc::zernikeQNorm().
zernikeQNorm() [2/3]
template<typename realT > realT mx::sigproc::zernikeQNorm (realT k, realT phi, int j)
Calculate the square-normed Fourier transform of a Zernike polynomial at position (k,phi)
Implements Equation (8) of Noll (1976) [16].
Returns
the value of |Q(k,phi)|^2
Template Parameters
realT is the floating point type used for arithmetic
Parameters
[in] k the radial coordinate of normalized spatial frequency
[in] phi the azimuthal coordinate of normalized spatial frequency
[in] j the Zernike polynomial index j (Noll convention)
Definition at line 605 of file zernike.hpp.
References mx::astro::constants::k(), mx::sigproc::noll_nm(), and mx::sigproc::zernikeQNorm().
zernikeQNorm() [3/3]
template<typename realT > realT mx::sigproc::zernikeQNorm (realT k, realT phi, int n, int m)
Calculate the square-normed Fourier transform of a Zernike polynomial at position (k,phi)
Implements Equation (8) of Noll (1976) [16].
Todo:
need a more robust jinc_n function for n > 1
Test:
Scenario: testing zernikeQNorm [test doc]
Returns
the value of |Q(k,phi)|^2
Template Parameters
realT is the floating point type used for arithmetic
Parameters
[in] k the radial coordinate of normalized spatial frequency
[in] phi the azimuthal coordinate of normalized spatial frequency
[in] n the Zernike polynomial n
[in] m the Zernike polynomial m
Definition at line 547 of file zernike.hpp.
References mx::math::func::bessel_j(), and mx::astro::constants::k().
Referenced by SCENARIO().
zernikeR() [1/2]
template<typename realT , typename calcRealT > realT mx::sigproc::zernikeR (realT rho, int n, int m)
Calculate the value of a Zernike radial polynomial at a given separation.
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calculations, should be at least double
Parameters
[in] rho the radial coordinate, \(0 \le \rho \le 1 \).
[in] n the radial index of the Zernike polynomial.
[in] m the azimuthal index of the Zernike polynomial.
Definition at line 192 of file zernike.hpp.
References mx::astro::constants::c(), and mx::sigproc::zernikeRCoeffs().
zernikeR() [2/2]
template<typename realT , typename calcRealT > realT mx::sigproc::zernikeR (realT rho, int n, int m, std::vector< calcRealT > & c)
Calculate the value of a Zernike radial polynomial at a given separation.
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
calcRealT is a real floating type used for internal calcs, should be at least double.
Parameters
[in] rho the radial coordinate, \(0 \le \rho \le 1 \).
[in] n the radial index of the Zernike polynomial.
[in] m the azimuthal index of the Zernike polynomial.
[in] c contains the radial polynomial coeeficients, and must be of length \(0.5(n-m)+1\).
Definition at line 138 of file zernike.hpp.
References mx::astro::constants::c(), mx::astro::constants::k(), MXE_INVALIDARG, and mxError.
zernikeRCoeffs()
template<typename realT > int mx::sigproc::zernikeRCoeffs (std::vector< realT > & c, int n, int m)
Calculate the coefficients of a Zernike radial polynomial.
Return values
0 on success
-1 on error
Template Parameters
realT is a real floating type
Parameters
[out] c allocated to length \(0.5(n-m)+1\) and filled with the coefficients.
[in] n the radial index of the Zernike polynomial.
[in] m the azimuthal index of the Zernike polynomial.
Definition at line 81 of file zernike.hpp.
References mx::astro::constants::c(), mx::astro::constants::k(), MXE_INVALIDARG, and mxError.
Referenced by mx::sigproc::zernikeR().