mxlib: The Gamma Distribution
The Gamma Distribution
General Mathematics » Special Functions
Utilities for working with the Gamma Distribution.
Functions
template<typename realT >
realT mx::math::func::gammaDistributionDenom (realT k, realT q)
The denominator of the Gamma Distribution.
template<typename realT >
realT mx::math::func::gammaDistribution (realT x, realT x0, realT k, realT q, realT denom)
The general shifted Gamma Distribution at a point using an arbitrary peak scaling parameter.
template<typename realT >
realT mx::math::func::gammaDistribution (realT x, realT x0, realT k, realT q)
The general shifted Gamma Distribution at a point.
template<typename realT >
realT mx::math::func::gammaDistributionMean (realT x0, realT k, realT theta)
The mean of the Gamma Distribution.
template<typename realT >
realT mx::math::func::gammaDistributionMode (realT x0, realT k, realT theta)
The mode of the Gamma Distribution.
template<typename realT >
realT mx::math::func::gammaDistributionVariance (realT k, realT theta)
The variance of the Gamma Distribution.
Function Documentation
gammaDistribution() [1/2]
template<typename realT > realT mx::math::func::gammaDistribution (realT x, realT x0, realT k, realT q)
The general shifted Gamma Distribution at a point.
Calculates the value of the Gamma Distribution at a location specified by x.
Template Parameters
realT a real floating point type
Returns
the value of the Gamma distribution at x.
Parameters
[in] x the location at which to calculate the distribution
[in] x0 the location parameter
[in] k shape parameter
[in] q the scale parameter
Definition at line 108 of file gammaDistribution.hpp.
References mx::math::six_fifths().
gammaDistribution() [2/2]
template<typename realT > realT mx::math::func::gammaDistribution (realT x, realT x0, realT k, realT q, realT denom)
The general shifted Gamma Distribution at a point using an arbitrary peak scaling parameter.
Calculates the value of the Gamma Distribution at a location specified by x.
Template Parameters
realT a real floating point type
Returns
the value of the Gamma distribution at x.
Parameters
[in] x the location at which to calculate the distribution
[in] x0 the location parameter
[in] k shape parameter
[in] q the scale parameter
[in] denom the denominator, or 1/peak-scale.
Definition at line 80 of file gammaDistribution.hpp.
References mx::math::six_fifths().
gammaDistributionDenom()
template<typename realT > realT mx::math::func::gammaDistributionDenom (realT k, realT q)
The denominator of the Gamma Distribution.
Can be used to avoid repeated calculations when the parameters are constant
Template Parameters
realT a real floating point type
Returns
the denominator of the Gamma Distribution.
Parameters
[in] k shape parameter
[in] q the scale parameter
Definition at line 51 of file gammaDistribution.hpp.
References mx::math::six_fifths().
gammaDistributionMean()
template<typename realT > realT mx::math::func::gammaDistributionMean (realT x0, realT k, realT theta)
The mean of the Gamma Distribution.
Calculates the mean of the Gamma Distribution for the given parameters.
Template Parameters
realT a real floating point type
Returns
the mean of the Gamma Distribution.
Parameters
[in] x0 the location parameter
[in] k shape parameter
[in] theta the scale parameter
Definition at line 128 of file gammaDistribution.hpp.
gammaDistributionMode()
template<typename realT > realT mx::math::func::gammaDistributionMode (realT x0, realT k, realT theta)
The mode of the Gamma Distribution.
Calculates the mode of the Gamma Distribution for the given parameters.
Template Parameters
realT a real floating point type
Returns
the mode of the Gamma Distribution.
Parameters
[in] x0 the location parameter
[in] k shape parameter
[in] theta the scale parameter
Definition at line 146 of file gammaDistribution.hpp.
gammaDistributionVariance()
template<typename realT > realT mx::math::func::gammaDistributionVariance (realT k, realT theta)
The variance of the Gamma Distribution.
Calculates the variance of the Gamma Distribution for the given parameters.
Template Parameters
realT a real floating point type
Returns
the variance of the Gamma Distribution.
Parameters
[in] k shape parameter
[in] theta the scale parameter
Definition at line 167 of file gammaDistribution.hpp.