var group__gen__math__files =
[
    [ "Fitting Files", "group__fitting__files.html", "group__fitting__files" ],
    [ "Fourier Transform Files", "group__ft__files.html", "group__ft__files" ],
    [ "Cuda Files", "group__cuda__files.html", "group__cuda__files" ],
    [ "math.hpp", "math_8hpp.html", null ],
    [ "eigenLapack.hpp", "eigenLapack_8hpp.html", null ],
    [ "geo.hpp", "geo_8hpp.html", null ],
    [ "gslInterpolation.hpp", "gslInterpolation_8hpp.html", null ],
    [ "gslInterpolator.hpp", "gslInterpolator_8hpp.html", null ],
    [ "histogramUniform.hpp", "histogramUniform_8hpp.html", null ],
    [ "logInterpolator.hpp", "logInterpolator_8hpp.html", null ],
    [ "point2D.hpp", "point2D_8hpp.html", null ],
    [ "radprofIntegral.hpp", "radprofIntegral_8hpp.html", null ],
    [ "randomSeed.hpp", "randomSeed_8hpp.html", null ],
    [ "randomT.hpp", "randomT_8hpp.html", null ],
    [ "roots.hpp", "roots_8hpp.html", null ],
    [ "templateBLAS.hpp", "templateBLAS_8hpp.html", null ],
    [ "templateLapack.hpp", "templateLapack_8hpp.html", null ],
    [ "vectorUtils.hpp", "vectorUtils_8hpp.html", null ],
    [ "airyPattern.hpp", "airyPattern_8hpp.html", null ],
    [ "bessel.hpp", "bessel_8hpp.html", null ],
    [ "expModGaussian.hpp", "expModGaussian_8hpp.html", null ],
    [ "factorial.hpp", "factorial_8hpp.html", null ],
    [ "gamma.hpp", "gamma_8hpp.html", null ],
    [ "gammaDistribution.hpp", "gammaDistribution_8hpp.html", null ],
    [ "gaussian.hpp", "gaussian_8hpp.html", null ],
    [ "jinc.hpp", "jinc_8hpp.html", null ],
    [ "legendre.hpp", "legendre_8hpp.html", null ],
    [ "logistic.hpp", "logistic_8hpp.html", null ],
    [ "moffat.hpp", "moffat_8hpp.html", null ],
    [ "sign.hpp", "sign_8hpp.html", null ],
    [ "weibull.hpp", "weibull_8hpp.html", null ],
    [ "gslInterpolator.cpp", "gslInterpolator_8cpp.html", null ],
    [ "templateBLAS.cpp", "templateBLAS_8cpp.html", null ],
    [ "templateLapack.cpp", "templateLapack_8cpp.html", null ]
];