mxlib: File Utilities Unit Tests
File Utilities Unit Tests
Testing » Unit Tests » I/O Utilities Unit Tests
Functions
unitTest::ioutilsTest::fileUtilsTest::TEST_CASE ("Checking existence and whether or not a path is a directory", "[ioutils::fileUtils]")
Checking existence and whether or not a path is a directory.
unitTest::ioutilsTest::fileUtilsTest::TEST_CASE ("creating sequential filenames", "[ioutils::fileUtils]")
Verify creation of sequential file names.
unitTest::ioutilsTest::fileUtilsTest::TEST_CASE ("Getting a list of files", "[ioutils::fileUtils]")
Getting a list of files.
Function Documentation
TEST_CASE() [1/3]
unitTest::ioutilsTest::fileUtilsTest::TEST_CASE ("Checking existence and whether or not a path is a directory" , "" [ioutils::fileUtils])
Checking existence and whether or not a path is a directory.
Definition at line 35 of file fileUtils_test.cpp.
References mx::ioutils::dir_exists_is(), mx::eacces, mx::eexist, and mx::noerror.
TEST_CASE() [2/3]
unitTest::ioutilsTest::fileUtilsTest::TEST_CASE ("creating sequential filenames" , "" [ioutils::fileUtils])
Verify creation of sequential file names.
Definition at line 98 of file fileUtils_test.cpp.
References mx::ioutils::getSequentialFilename().
TEST_CASE() [3/3]
unitTest::ioutilsTest::fileUtilsTest::TEST_CASE ("Getting a list of files" , "" [ioutils::fileUtils])
Getting a list of files.
Tests that files are read according to the specification and sorted. Also tests basic errors.
Definition at line 174 of file fileUtils_test.cpp.
References mx::dirnotfound, mx::ioutils::getFileNames(), mx::invalidarg, and mx::noerror.