mxlib: fitsFile Unit Tests
fitsFile Unit Tests
Testing » Unit Tests » I/O Utilities Unit Tests » FITS Unit Tests
Functions
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Calculating subimage sizes", "[ioutils::fits::fitsFile]")
Calculating subimage sizes.
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Basic writing and reading", "[ioutils::fits::fitsFile]")
Basic writing and reading.
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Cube writing and reading", "[ioutils::fits::fitsFile]")
Cube writing and reading.
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Reading headers", "[ioutils::fits::fitsFile]")
Reading headers.
Function Documentation
TEST_CASE() [1/4]
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Basic writing and reading" , "" [ioutils::fits::fitsFile])
Basic writing and reading.
Definition at line 247 of file fitsFile_test.cpp.
References mx::fits::fitsHeader< verboseT >::append(), mx::noerror, mx::fits::fitsFile< dataT, verboseT >::read(), and mx::fits::fitsFile< dataT, verboseT >::write().
TEST_CASE() [2/4]
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Calculating subimage sizes" , "" [ioutils::fits::fitsFile])
Calculating subimage sizes.
Verify calculation of subimage sizes
Definition at line 81 of file fitsFile_test.cpp.
References mx::fits::fitsFile< dataT, verboseT >::calcPixarrs(), mx::fits::fitsFile< dataT, verboseT >::naxes(), mx::fits::fitsFile< dataT, verboseT >::naxis(), mx::fits::fitsFile< dataT, verboseT >::setCubeReadSize(), and mx::fits::fitsFile< dataT, verboseT >::setReadSize().
TEST_CASE() [3/4]
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Cube writing and reading" , "" [ioutils::fits::fitsFile])
Cube writing and reading.
Definition at line 283 of file fitsFile_test.cpp.
References mx::fits::fitsHeader< verboseT >::append(), mx::noerror, and mx::fits::fitsFile< dataT, verboseT >::write().
TEST_CASE() [4/4]
mx::unitTest::fitsTest::fitsFileTest::TEST_CASE ("Reading headers" , "" [ioutils::fits::fitsFile])
Reading headers.
Definition at line 325 of file fitsFile_test.cpp.
References mx::fits::fitsHeader< verboseT >::append(), mx::error, mx::invalidarg, mx::noerror, mx::fits::fitsFile< dataT, verboseT >::readHeader(), and mx::fits::fitsFile< dataT, verboseT >::write().