mxlib: Radial Profiles
Radial Profiles
Image Processing | Signal Processing » Image Filters
Radial profiles of images.
Radial profiles of images.
Functions
template<typename vecT , typename eigenImT1 , typename eigenImT2 , typename eigenImT3 >
void mx::improc::radprof (vecT &rad, vecT &prof, const eigenImT1 &im, const eigenImT2 &radim, const eigenImT3 *mask, bool mean=false, typename eigenImT1::Scalar minr=0)
Calculate the the radial profile.
template<typename vecT , typename eigenImT1 , typename eigenImT2 >
void mx::improc::radprof (vecT &rad, vecT &prof, const eigenImT1 &im, const eigenImT2 &mask, bool mean=false)
Calculate the the radial profile.
template<typename vecT , typename eigenImT1 >
void mx::improc::radprof (vecT &rad, vecT &prof, const eigenImT1 &im, bool mean=false, double dr=1)
Calculate the the radial profile.
template<typename radprofT , typename eigenImT1 , typename eigenImT2 , typename eigenImT3 >
void mx::improc::radprofim (radprofT &radprofIm, eigenImT1 &im, const eigenImT2 &rad, const eigenImT3 *mask, bool subtract, bool mean=false)
Form a radial profile image, and optionally subtract it from the input.
template<typename radprofT , typename eigenImT >
void mx::improc::radprofim (radprofT &radprof, eigenImT &im, bool subtract=false, bool mean=false)
Form a radial profile image, and optionally subtract it from the input.
Function Documentation
radprof() [1/3]
template<typename vecT , typename eigenImT1 > void mx::improc::radprof (vecT & rad, vecT & prof, const eigenImT1 & im, bool mean = false, double dr = 1)
Calculate the the radial profile.
The median radial profile is calculated by rebinning to a 1 pixel grid. This version calculates a centered radius image.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
vecT the std::vector-like type to contain the profile
eigenImT1 the eigen-array-like type of the input image
Parameters
[out] rad [out] the radius points for the profile. Should be empty.
[out] prof [out] the median image value at the corresponding radius. Should be empty.
[in] im [in] the image of which to calculate the profile
[in] mean [in] [optional] set to true to use the mean. If false (default) the median is used.
Definition at line 731 of file imageFilters.hpp.
References mx::improc::radiusImage().
Referenced by mx::improc::radprof(), and mx::improc::radprofim().
radprof() [2/3]
template<typename vecT , typename eigenImT1 , typename eigenImT2 > void mx::improc::radprof (vecT & rad, vecT & prof, const eigenImT1 & im, const eigenImT2 & mask, bool mean = false)
Calculate the the radial profile.
The median radial profile is calculated by rebinning to a 1 pixel grid. This version calculates a centered radius image.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Template Parameters
vecT the std::vector-like type to contain the profile
eigenImT1 the eigen-array-like type of the input image
eigenImT2 the eigen-array-like type of the radius and mask image
eigenImT3 the eigen-array-like type of the mask image
Parameters
[out] rad [out] the radius points for the profile. Should be empty.
[out] prof [out] the median image value at the corresponding radius. Should be empty.
[in] im [in] the image of which to calculate the profile
[in] mask [in] 1/0 mask, only pixels with a value of 1 are included in the profile
[in] mean [in] [optional] set to true to use the mean. If false (default) the median is used.
Definition at line 704 of file imageFilters.hpp.
References mx::improc::radiusImage(), and mx::improc::radprof().
radprof() [3/3]
template<typename vecT , typename eigenImT1 , typename eigenImT2 , typename eigenImT3 > void mx::improc::radprof (vecT & rad, vecT & prof, const eigenImT1 & im, const eigenImT2 & radim, const eigenImT3 * mask, bool mean = false, typename eigenImT1::Scalar minr = 0)
Calculate the the radial profile.
The median radial profile is calculated by rebinning to a 1 pixel grid.
Template Parameters
vecT the std::vector-like type to contain the profile
eigenImT1 the eigen-array-like type of the input image
eigenImT2 the eigen-array-like type of the radius and mask image
eigenImT3 the eigen-array-like type of the mask image
Parameters
[out] rad [out] the radius points for the profile. Should be empty.
[out] prof [out] the median image value at the corresponding radius. Should be empty.
[in] im [in] the image of which to calculate the profile
[in] radim [in] image of radius values per pixel
[in] mask [in] [optional] 1/0 mask, only pixels with a value of 1 are included in the profile. Set to 0 to not use.
[in] mean [in] [optional] set to true to use the mean. If false (default) the median is used.
Definition at line 584 of file imageFilters.hpp.
References mx::astro::constants::c().
radprofim() [1/2]
template<typename radprofT , typename eigenImT > void mx::improc::radprofim (radprofT & radprof, eigenImT & im, bool subtract = false, bool mean = false)
Form a radial profile image, and optionally subtract it from the input.
The radial profile is calculated using linear interpolation on a 1 pixel grid. This version calculates a centered radius image.
Template Parameters
radprofT the eigen array type of the output
eigenImT the eigen array type of the input
Parameters
[out] radprof [out] the radial profile image. This will be resized.
[in] im [in] the image to form the profile of.
[in] subtract [in] [optional] if true, then on ouput im will have had its radial profile subtracted.
[in] mean [in] [optional] set to true to use the mean. If false (default) the median is used.
Definition at line 810 of file imageFilters.hpp.
References mx::improc::radiusImage(), and mx::improc::radprof().
radprofim() [2/2]
template<typename radprofT , typename eigenImT1 , typename eigenImT2 , typename eigenImT3 > void mx::improc::radprofim (radprofT & radprofIm, eigenImT1 & im, const eigenImT2 & rad, const eigenImT3 * mask, bool subtract, bool mean = false)
Form a radial profile image, and optionally subtract it from the input.
The radial profile is calculated using linear interpolation on a 1 pixel grid
Template Parameters
radprofT the eigen array type of the output
eigenImT1 the eigen array type of the input image
eigenImT2 the eigen array type of the radius image
eigenImT3 the eigen array type of the mask image
Parameters
[out] radprofIm [out] the radial profile image. This will be resized.
im [in the image to form the profile of.
[in] rad [in] an array of radius values for each pixel
[in] mask [in] [optional 1/0 mask, only pixels with a value of 1 are included in the profile. Can be nullptr.
[in] subtract [in] if true, then on ouput im will have had its radial profile subtracted.
[in] mean [in] [optional] set to true to use the mean. If false (default) the median is used.
Definition at line 758 of file imageFilters.hpp.
References mx::astro::constants::c(), and mx::improc::radprof().
Referenced by mx::improc::HCIobservation< _realT >::preProcess().