mxlib: binVector Binary File Format
binVector Binary File Format
General Utilities » Input/Output Utilities
A simple binary file format for storing vectors of data on disk.
A simple binary file format for storing vectors of data on disk.
The binVector file format is very simple: the first 8 bytes contain a unit64_t integer which specifies the type of the data. The second 8 bytes contain a uint64_t integer which specifies the length L of the data vector. The remaining L*sizeof(dataT) bytes contain the data.
The suggested extension for BinVector files is ".binv".
Namespaces
namespace mx::ioutils::binVTypes
Namespace fo the bin-vector type-codes.
Typedefs
typedef uint64_t mx::ioutils::binVTypeT
The type of binVector type codes.
Enumerations
enum : binVTypeT
The pre-defined type codes for binVector.
Functions
template<typename dataT >
binVTypeT mx::ioutils::binVectorTypeCode ()
Get the integer type code corresponding to the type.
template<typename dataT >
int mx::ioutils::readBinVector (std::vector< dataT > &vec, const std::string &fname)
Read a BinVector file from disk.
template<typename dataT >
int mx::ioutils::writeBinVector (const std::string &fname, std::vector< dataT > &vec)
Write a BinVector file to disk.
Typedef Documentation
binVTypeT
typedef uint64_t mx::ioutils::binVTypeT
The type of binVector type codes.
Definition at line 61 of file binVector.hpp.
Enumeration Type Documentation
anonymous enum
anonymous enum : binVTypeT
The pre-defined type codes for binVector.
Definition at line 72 of file binVector.hpp.
Function Documentation
binVectorTypeCode()
template<typename dataT > binVTypeT mx::ioutils::binVectorTypeCode ()
Get the integer type code corresponding to the type.
Returns
an integer which uniquely identifies the type.
Template Parameters
dataT is the type
readBinVector()
template<typename dataT > int mx::ioutils::readBinVector (std::vector< dataT > & vec, const std::string & fname)
Read a BinVector file from disk.
Note
dataT must match what was stored in the file.
Returns
0 on success.
-1 if an error occurs.
Parameters
[out] vec vec is a vector which will be resized and populated.
[in] fname fname is the name (full-path) of the file.
Definition at line 240 of file binVector.hpp.
References mx::errno2error_t(), mx::filererr, mx::internal::mxlib_error_report(), and mx::sizeerr.
Referenced by mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::getGridFreq(), mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::getGridPSD(), and mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::intensityPSD().
writeBinVector()
template<typename dataT > int mx::ioutils::writeBinVector (const std::string & fname, std::vector< dataT > & vec)
Write a BinVector file to disk.
Returns
0 on success.
-1 if an error occurs.
Parameters
[in] fname fname is the name (full-path) of the file.
[in] vec vec is the vector which will be written to disk.
Definition at line 336 of file binVector.hpp.
References mx::errno2error_t(), and mx::internal::mxlib_error_report().
Referenced by mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::analyzePSDGrid(), and mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >::makePSDGrid().