mxlib: Error Reporting Unit Tests
Error Reporting Unit Tests
Testing » Unit Tests » Error Handling Unit Tests
Functions
unitTest::errorTest::errorTest::TEST_CASE ("Test error_t boolean operators and functions", "[error::error]")
Test error_t boolean operators and functions.
unitTest::errorTest::errorTest::TEST_CASE ("Internal error messages", "[error::error]")
Internal error messages.
unitTest::errorTest::errorTest::TEST_CASE ("Internal error reports", "[error::error]")
Internal error reports.
unitTest::errorTest::errorTest::TEST_CASE ("Error messages", "[error::error]")
Error messages.
unitTest::errorTest::errorTest::TEST_CASE ("Error reports", "[error::error]")
Error reports.
unitTest::errorTest::errorTest::TEST_CASE ("Error macros", "[error::error]")
Error macros.
Function Documentation
TEST_CASE() [1/6]
unitTest::errorTest::errorTest::TEST_CASE ("Error macros" , "" [error::error])
Error macros.
Definition at line 420 of file error_test.cpp.
References mx::eacces, mx::error, mx::exception, mx_error_check, mx_error_check_code, mx_error_check_code_rv, mx_error_check_rv, mx_error_return, mx_error_return_code, and mx::noerror.
TEST_CASE() [2/6]
unitTest::errorTest::errorTest::TEST_CASE ("Error messages" , "" [error::error])
Error messages.
Definition at line 218 of file error_test.cpp.
References mx::error, mx::error_message(), mx::error_message< mx::verbose::o >(), mx::error_message< mx::verbose::v >(), mx::error_message< mx::verbose::vv >(), mx::error_message< mx::verbose::vvv >(), and mx::noerror.
TEST_CASE() [3/6]
unitTest::errorTest::errorTest::TEST_CASE ("Error reports" , "" [error::error])
Error reports.
Definition at line 289 of file error_test.cpp.
References mx::error, mx::error_report(), mx::error_report< mx::verbose::o >(), and mx::noerror.
TEST_CASE() [4/6]
unitTest::errorTest::errorTest::TEST_CASE ("Internal error messages" , "" [error::error])
Internal error messages.
Definition at line 76 of file error_test.cpp.
References mx::error, mx::internal::mxlib_error_message(), mx::internal::mxlib_error_message< mx::verbose::o >(), mx::internal::mxlib_error_message< mx::verbose::v >(), mx::internal::mxlib_error_message< mx::verbose::vv >(), mx::internal::mxlib_error_message< mx::verbose::vvv >(), and mx::noerror.
TEST_CASE() [5/6]
unitTest::errorTest::errorTest::TEST_CASE ("Internal error reports" , "" [error::error])
Internal error reports.
Definition at line 147 of file error_test.cpp.
References mx::error, mx::internal::mxlib_error_report(), mx::internal::mxlib_error_report< mx::verbose::o >(), and mx::noerror.
TEST_CASE() [6/6]
unitTest::errorTest::errorTest::TEST_CASE ("Test error_t boolean operators and functions" , "" [error::error])
Test error_t boolean operators and functions.
Definition at line 17 of file error_test.cpp.
References mx::error, mx::isError(), mx::noerror, mx::operator!(), mx::operator!=(), and mx::operator==().