mxlib: Signal Processing
Signal Processing
Tools for processing signals
Classes
struct mx::sigproc::autocorrelationFromPSD< T >
Functor for calculating the autocorrelation given a PSD.
struct mx::sigproc::linearPredictor< _realT >
A class to support linear prediction.
Modules
Power Spectra
The Fourier Basis
The Zernike Basis
Window Functions
Image Filters
Signal Processing Files
Circular Buffer
A circular buffer class.
Functions
template<typename T >
void mx::sigproc::autocorrelation (T *ac, size_t Nac, T *sig, size_t Nsig)
Calculate the autocorrelation of a time-series.
template<typename T >
void mx::sigproc::autocorrelation (std::vector< T > &ac, std::vector< T > &sig)
Calculate the autocorrelation of a time-series.
template<typename realT >
int mx::sigproc::basisMask (improc::eigenCube< realT > &modes, improc::eigenImage< realT > &mask)
Mask a basis set.
template<typename realT >
int mx::sigproc::basisMeanSub (improc::eigenCube< realT > &modes, improc::eigenImage< realT > &mask, bool postMult=true)
Mean-subtract a basis set.
template<typename realT >
int mx::sigproc::basisNormalize (improc::eigenCube< realT > &modes, improc::eigenImage< realT > &mask)
Normalize a basis set.
template<typename realT >
int mx::sigproc::basisAmplitudes (std::vector< realT > &amps, improc::eigenImage< realT > &im, improc::eigenCube< realT > &modes, improc::eigenImage< realT > &mask, bool subtract=false, int meanIgnore=0, int N=-1)
Measure the amplitudes of a set of basis modes fit to an image. Optionally subtract them.
template<int progress = 0, typename eigenTout , typename eigenTin >
void mx::sigproc::gramSchmidt (eigenTout &out, const eigenTin &in, bool normalize=true)
Perform Gram-Schmidt ortogonalization of a basis set, and normalize the result.
template<int progress = 0, typename eigenTout , typename eigenTin , typename eigenTWin >
void mx::sigproc::gramSchmidt (eigenTout &out, const eigenTin &in, const eigenTWin &window)
Perform Gram-Schmidt ortogonalization of a basis set on a window, and normalize the result.
template<int progress = 0, typename eigenTout , typename eigenTout2 , typename eigenTin >
void mx::sigproc::gramSchmidtSpectrum (eigenTout &out, eigenTout2 &spect, const eigenTin &in, typename eigenTin::Scalar normPix=0.0)
Perform Gram-Schmidt ortogonalization of a basis set, and normalize the result, while recording the spectrum.
Function Documentation
autocorrelation() [1/2]
template<typename T > void mx::sigproc::autocorrelation (std::vector< T > & ac, std::vector< T > & sig)
Calculate the autocorrelation of a time-series.
Template Parameters
T is the real type of the data and autocorrelation.
Todo:
this should probably re-allocate if ac.size() != sig.size(), or at least <
Parameters
[out] ac will contain the autocorrelation on return. If ac.size()==0 then it is resized to sig.size().
[in] sig is the input time-series (signal)
Definition at line 81 of file autocorrelation.hpp.
References mx::sigproc::autocorrelation().
autocorrelation() [2/2]
template<typename T > void mx::sigproc::autocorrelation (T * ac, size_t Nac, T * sig, size_t Nsig)
Calculate the autocorrelation of a time-series.
Template Parameters
T is the real type of the data and autocorrelation.
Parameters
[out] ac is the pre-allocated array of length Nac which will contain the autocorrelation on return
[in] Nac is the length of ac
[in] sig is the input time-series (signal)
[in] Nsig is the length of the input time-series
Definition at line 47 of file autocorrelation.hpp.
Referenced by mx::sigproc::autocorrelation().
basisAmplitudes()
template<typename realT > int mx::sigproc::basisAmplitudes (std::vector< realT > & amps, improc::eigenImage< realT > & im, improc::eigenCube< realT > & modes, improc::eigenImage< realT > & mask, bool subtract = false, int meanIgnore = 0, int N = -1)
Measure the amplitudes of a set of basis modes fit to an image. Optionally subtract them.
Mode subtraction occurs one by one, so subtraction will work with non-orthogonal basis sets.
Returns
0 on success
-1 on error
Template Parameters
realT the floating point type.
Parameters
[out] amps the amplitudes of each mode fit to the image (will be resized).
im [in.out] the image to fit. Is subtracted in place if desired.
[in] modes the modes to fit.
[in] mask the 1/0 mask which defines the domain of the fit.
[in] subtract [opt] if true then the modes are subtracted as they are fit to the image
[in] meanIgnore [opt] if 1 then the mean, or if 2 the median, value is subtracted before fitting. If subtract is false, this value is added back after the subtraction.
[in] N [opt] the number of modes to actually fit. If N < 0 then all modes are fit.
Definition at line 150 of file basisUtils2D.hpp.
References mx::improc::imageMedian().
basisMask()
template<typename realT > int mx::sigproc::basisMask (improc::eigenCube< realT > & modes, improc::eigenImage< realT > & mask)
Mask a basis set.
Multiplies each mode in a basis set by a mask.
Returns
0 on success
-1 on error
Template Parameters
realT a real floating point type.
Parameters
modes [in.out] the basis to normalize.
[in] mask 1/0 mask defining the domain of the basis
Definition at line 51 of file basisUtils2D.hpp.
basisMeanSub()
template<typename realT > int mx::sigproc::basisMeanSub (improc::eigenCube< realT > & modes, improc::eigenImage< realT > & mask, bool postMult = true)
Mean-subtract a basis set.
Subtracts the mean of each mode calculated over a domain defined by a mask.
Returns
0 on success
-1 on error
Template Parameters
realT a real floating point type.
Parameters
modes [in.out] the basis to normalize.
[in] mask 1/0 mask defining the domain of the basis
[in] postMult [optional] if true, then each image is multiplied by the mask after subtraction.
Definition at line 74 of file basisUtils2D.hpp.
basisNormalize()
template<typename realT > int mx::sigproc::basisNormalize (improc::eigenCube< realT > & modes, improc::eigenImage< realT > & mask)
Normalize a basis set.
RMS normalize each mode over a domain defined by a mask.
Returns
0 on success
-1 on error
Template Parameters
realT a real floating point type.
Parameters
modes [in.out] the basis to normalize.
[in] mask 1/0 mask defining the domain of the normalization
Definition at line 105 of file basisUtils2D.hpp.
gramSchmidt() [1/2]
template<int progress = 0, typename eigenTout , typename eigenTin > void mx::sigproc::gramSchmidt (eigenTout & out, const eigenTin & in, bool normalize = true)
Perform Gram-Schmidt ortogonalization of a basis set, and normalize the result.
Performs the stabilized Gram-Schmidt procedure on the input basis set, which is the columns of the array. Optionally the output is normalized.
Template Parameters
progress if true, then the loop index is printed for progress reporting
eigenTout is the Eigen array type of the desired output
eigenTin is the Eigen array type of the input
Parameters
[out] out the orthonormal basis set constructed from the input
[in] in a basis set, where each column represents one vector.
[in] normalize [optional] whether or not to normalize the output
Definition at line 48 of file gramSchmidt.hpp.
gramSchmidt() [2/2]
template<int progress = 0, typename eigenTout , typename eigenTin , typename eigenTWin > void mx::sigproc::gramSchmidt (eigenTout & out, const eigenTin & in, const eigenTWin & window)
Perform Gram-Schmidt ortogonalization of a basis set on a window, and normalize the result.
Performs the stabilized Gram-Schmidt procedure on the input basis set over a window (or weight function), followed by normalization of the result.
Parameters
out [out] is the orthonormal basis set constructed from the input
in [in] is a basis set, where each column represents one vector.
window [in] is the window, or weighting function
Template Parameters
progress if true, then the loop index is printed for progress reporting
eigenTout is the Eigen array type of the desired output
eigenTin is the Eigen array type of the input
eigenTWin is the Eigen array type of the window
Definition at line 103 of file gramSchmidt.hpp.
gramSchmidtSpectrum()
template<int progress = 0, typename eigenTout , typename eigenTout2 , typename eigenTin > void mx::sigproc::gramSchmidtSpectrum (eigenTout & out, eigenTout2 & spect, const eigenTin & in, typename eigenTin::Scalar normPix = 0.0)
Perform Gram-Schmidt ortogonalization of a basis set, and normalize the result, while recording the spectrum.
Performs the stabilized Gram-Schmidt procedure on the input basis set, followed by normalization of the result. Also records the spectrum, that is the coefficients of the linear expansion in the orginal basis set for the resultant basis set.
Template Parameters
progress if true, then the loop index is printed for progress reporting
eigenTout is the Eigen array type of the output orthogonalized array
eigenTout2 is the Eigen array type of the spectrum
eigenTin is the Eigen array type of the input
Parameters
[out] out the orthonormal basis set constructed from the input
[out] spect the spectrum
[in] in a basis set, where each column represents one vector
[in] normPix [optional] area of (usually number of pixels in) the orthogonal region for normalization. If 0 the basis is not renormalized
Definition at line 170 of file gramSchmidt.hpp.