mxlib: The Exponentially Modified Gaussian Distribution
The Exponentially Modified Gaussian Distribution
General Mathematics » Special Functions
Utilities for working with the Exponentially Modified Gaussian Distribution
Functions
template<typename realT >
realT mx::math::func::expModGaussian (realT x, realT mu, realT sigma, realT lambda)
The Exponentially Modified Gaussian at a point.
template<typename realT >
realT mx::math::func::expModGaussianMean (realT mu, realT lambda)
The Mean of the Exponentially Modified Gaussian.
template<typename realT >
realT mx::math::func::expModGaussianVariance (realT sigma, realT lambda)
The Variance of the Exponentially Modified Gaussian.
template<typename realT >
realT mx::math::func::expModGaussianMode (realT mu, realT sigma, realT lambda)
The Mode of the Exponentially Modified Gaussian.
Function Documentation
expModGaussian()
template<typename realT > realT mx::math::func::expModGaussian (realT x, realT mu, realT sigma, realT lambda)
The Exponentially Modified Gaussian at a point.
Calculates the value of the Exponentially Modified Gaussian distribution at a location specified by x.
Template Parameters
realT a real floating point type
Returns
the value of the Exponentially Modified Gaussian distribution at x.
Parameters
[in] x the location at which to calculate the distribution
[in] mu the mean parameter
[in] sigma the standard deviation
[in] lambda the rate of decay
Definition at line 54 of file expModGaussian.hpp.
References mx::astro::constants::sigma().
expModGaussianMean()
template<typename realT > realT mx::math::func::expModGaussianMean (realT mu, realT lambda)
The Mean of the Exponentially Modified Gaussian.
Calculates the mean of the Exponentially Modified Gaussian distribution.
Template Parameters
realT a real floating point type
Returns
the mean of the Exponentially Modified Gaussian.
Parameters
[in] mu the mean parameter
[in] lambda the rate of decay
Definition at line 74 of file expModGaussian.hpp.
Referenced by mx::math::func::expModGaussianMode().
expModGaussianMode()
template<typename realT > realT mx::math::func::expModGaussianMode (realT mu, realT sigma, realT lambda)
The Mode of the Exponentially Modified Gaussian.
Calculates the mode of the Exponentially Modified Gaussian distribution. This is done iteratively with Brent's method.
Template Parameters
realT a real floating point type
Returns
the mode of the Exponentially Modified Gaussian.
Parameters
[in] mu the mean parameter
[in] sigma the standard deviation
[in] lambda the rate of decay
Definition at line 123 of file expModGaussian.hpp.
References mx::math::func::expModGaussianMean(), mx::math::func::expModGaussianVariance(), and mx::astro::constants::sigma().
expModGaussianVariance()
template<typename realT > realT mx::math::func::expModGaussianVariance (realT sigma, realT lambda)
The Variance of the Exponentially Modified Gaussian.
Calculates the variance of the Exponentially Modified Gaussian distribution.
Template Parameters
realT a real floating point type
Returns
the variance of the Exponentially Modified Gaussian.
Parameters
[in] sigma the standard deviation
[in] lambda the rate of decay
Definition at line 92 of file expModGaussian.hpp.
References mx::astro::constants::sigma().
Referenced by mx::math::func::expModGaussianMode().