mxlib: Error Codes
Error Codes
Error Handling
The mxlib error codes and utility functions.
Enumerations
enum class mx::error_t {
mx::error_t::noerror , mx::error_t::error , mx::error_t::invalidarg , mx::error_t::invalidconfig ,
mx::error_t::notimpl , mx::error_t::paramnotset , mx::error_t::envnotset , mx::error_t::notfound ,
mx::error_t::sizeerr , mx::error_t::allocerr , mx::error_t::freeerr , mx::error_t::parseerr ,
mx::error_t::filesystem , mx::error_t::fileoerr , mx::error_t::filewerr , mx::error_t::filererr ,
mx::error_t::filecerr , mx::error_t::filenotfound , mx::error_t::fileempty , mx::error_t::dirnotfound ,
mx::error_t::dirempty , mx::error_t::procerr , mx::error_t::timeout , mx::error_t::liberr ,
mx::error_t::exception , mx::error_t::std_exception , mx::error_t::std_bad_alloc , mx::error_t::std_logic_error ,
mx::error_t::std_invalid_argument , mx::error_t::std_domain_error , mx::error_t::std_length_error , mx::error_t::std_out_of_range ,
mx::error_t::std_future_error , mx::error_t::std_bad_optional_access , mx::error_t::std_filesystem_error , mx::error_t::std_runtime_error ,
mx::error_t::std_range_error , mx::error_t::std_overflow_error , mx::error_t::std_underflow_error , mx::error_t::std_ios_base_failure ,
mx::error_t::std_format_error , mx::error_t::gnuploterr , mx::error_t::lapackerr , mx::error_t::e2big ,
mx::error_t::eacces , mx::error_t::eaddrinuse , mx::error_t::eaddrnotavail , mx::error_t::eafnosupport ,
mx::error_t::eagain , mx::error_t::ealready , mx::error_t::ebadf , mx::error_t::ebadmsg ,
mx::error_t::ebusy , mx::error_t::ecanceled , mx::error_t::echild , mx::error_t::econnaborted ,
mx::error_t::econnrefused , mx::error_t::econnreset , mx::error_t::edestaddrreq , mx::error_t::edom ,
mx::error_t::eexist , mx::error_t::efault , mx::error_t::efbig , mx::error_t::ehostunreach ,
mx::error_t::eidrm , mx::error_t::eilseq , mx::error_t::einprogress , mx::error_t::eintr ,
mx::error_t::einval , mx::error_t::eio , mx::error_t::eisconn , mx::error_t::eisdir ,
mx::error_t::eloop , mx::error_t::emfile , mx::error_t::emlink , mx::error_t::emsgsize ,
mx::error_t::enametoolong , mx::error_t::enetdown , mx::error_t::enetreset , mx::error_t::enetunreach ,
mx::error_t::enfile , mx::error_t::enobufs , mx::error_t::enodata , mx::error_t::enodev ,
mx::error_t::enoent , mx::error_t::enoexec , mx::error_t::enolck , mx::error_t::enolink ,
mx::error_t::enomem , mx::error_t::enomsg , mx::error_t::enoprotoopt , mx::error_t::enospc ,
mx::error_t::enosr , mx::error_t::enostr , mx::error_t::enosys , mx::error_t::enotconn ,
mx::error_t::enotdir , mx::error_t::enotempty , mx::error_t::enotrecoverable , mx::error_t::enotsock ,
mx::error_t::enotsup , mx::error_t::enotty , mx::error_t::enxio , mx::error_t::eopnotsupp ,
mx::error_t::eoverflow , mx::error_t::eownerdead , mx::error_t::eperm , mx::error_t::epipe ,
mx::error_t::eproto , mx::error_t::eprotonosupport , mx::error_t::eprototype , mx::error_t::erange ,
mx::error_t::erofs , mx::error_t::espipe , mx::error_t::esrch , mx::error_t::etime ,
mx::error_t::etimedout , mx::error_t::etxtbsy , mx::error_t::ewouldblock , mx::error_t::exdev ,
mx::error_t::fits_same_file , mx::error_t::fits_too_many_files , mx::error_t::fits_file_not_opened , mx::error_t::fits_file_not_created ,
mx::error_t::fits_write_error , mx::error_t::fits_end_of_file , mx::error_t::fits_read_error , mx::error_t::fits_file_not_closed ,
mx::error_t::fits_array_too_big , mx::error_t::fits_readonly_file , mx::error_t::fits_memory_allocation , mx::error_t::fits_bad_fileptr ,
mx::error_t::fits_null_input_ptr , mx::error_t::fits_seek_error , mx::error_t::fits_bad_nettimeout , mx::error_t::fits_bad_url_prefix ,
mx::error_t::fits_too_many_drivers , mx::error_t::fits_driver_init_failed , mx::error_t::fits_no_matching_driver , mx::error_t::fits_url_parse_error ,
mx::error_t::fits_range_parse_error , mx::error_t::fits_shared_badarg , mx::error_t::fits_shared_nulptr , mx::error_t::fits_shared_tabfull ,
mx::error_t::fits_shared_notinit , mx::error_t::fits_shared_ipcerr , mx::error_t::fits_shared_nomem , mx::error_t::fits_shared_again ,
mx::error_t::fits_shared_nofile , mx::error_t::fits_shared_noresize , mx::error_t::fits_header_not_empty , mx::error_t::fits_key_no_exist ,
mx::error_t::fits_key_out_bounds , mx::error_t::fits_value_undefined , mx::error_t::fits_no_quote , mx::error_t::fits_bad_index_key ,
mx::error_t::fits_bad_keychar , mx::error_t::fits_bad_order , mx::error_t::fits_not_pos_int , mx::error_t::fits_no_end ,
mx::error_t::fits_bad_bitpix , mx::error_t::fits_bad_naxis , mx::error_t::fits_bad_naxes , mx::error_t::fits_bad_pcount ,
mx::error_t::fits_bad_gcount , mx::error_t::fits_bad_tfields , mx::error_t::fits_neg_width , mx::error_t::fits_neg_rows ,
mx::error_t::fits_col_not_found , mx::error_t::fits_bad_simple , mx::error_t::fits_no_simple , mx::error_t::fits_no_bitpix ,
mx::error_t::fits_no_naxis , mx::error_t::fits_no_naxes , mx::error_t::fits_no_xtension , mx::error_t::fits_not_atable ,
mx::error_t::fits_not_btable , mx::error_t::fits_no_pcount , mx::error_t::fits_no_gcount , mx::error_t::fits_no_tfields ,
mx::error_t::fits_no_tbcol , mx::error_t::fits_no_tform , mx::error_t::fits_not_image , mx::error_t::fits_bad_tbcol ,
mx::error_t::fits_not_table , mx::error_t::fits_col_too_wide , mx::error_t::fits_col_not_unique , mx::error_t::fits_bad_row_width ,
mx::error_t::fits_unknown_ext , mx::error_t::fits_unknown_rec , mx::error_t::fits_end_junk , mx::error_t::fits_bad_header_fill ,
mx::error_t::fits_bad_data_fill , mx::error_t::fits_bad_tform , mx::error_t::fits_bad_tform_dtype , mx::error_t::fits_bad_tdim ,
mx::error_t::fits_bad_heap_ptr , mx::error_t::fits_bad_hdu_num , mx::error_t::fits_bad_col_num , mx::error_t::fits_neg_file_pos ,
mx::error_t::fits_neg_bytes , mx::error_t::fits_bad_row_num , mx::error_t::fits_bad_elem_num , mx::error_t::fits_not_ascii_col ,
mx::error_t::fits_not_logical_col , mx::error_t::fits_bad_atable_format , mx::error_t::fits_bad_btable_format , mx::error_t::fits_no_null ,
mx::error_t::fits_not_vari_len , mx::error_t::fits_bad_dimen , mx::error_t::fits_bad_pix_num , mx::error_t::fits_zero_scale ,
mx::error_t::fits_neg_axis , mx::error_t::fits_not_group_table , mx::error_t::fits_hdu_already_member , mx::error_t::fits_member_not_found ,
mx::error_t::fits_group_not_found , mx::error_t::fits_bad_group_id , mx::error_t::fits_too_many_hdus_tracked , mx::error_t::fits_hdu_already_tracked ,
mx::error_t::fits_bad_option , mx::error_t::fits_identical_pointers , mx::error_t::fits_bad_group_attach , mx::error_t::fits_bad_group_detach ,
mx::error_t::fits_ngp_no_memory , mx::error_t::fits_ngp_read_err , mx::error_t::fits_ngp_nul_ptr , mx::error_t::fits_ngp_empty_curline ,
mx::error_t::fits_ngp_unread_queue_full , mx::error_t::fits_ngp_inc_nesting , mx::error_t::fits_ngp_err_fopen , mx::error_t::fits_ngp_eof ,
mx::error_t::fits_ngp_bad_arg , mx::error_t::fits_ngp_token_not_expect , mx::error_t::fits_bad_i2c , mx::error_t::fits_bad_f2c ,
mx::error_t::fits_bad_intkey , mx::error_t::fits_bad_logicalkey , mx::error_t::fits_bad_floatkey , mx::error_t::fits_bad_doublekey ,
mx::error_t::fits_bad_c2i , mx::error_t::fits_bad_c2f , mx::error_t::fits_bad_c2d , mx::error_t::fits_bad_datatype ,
mx::error_t::fits_bad_decim , mx::error_t::fits_num_overflow , mx::error_t::fits_data_compression_err , mx::error_t::fits_data_decompression_err ,
mx::error_t::fits_bad_date , mx::error_t::fits_parse_syntax_err , mx::error_t::fits_parse_bad_type , mx::error_t::fits_parse_lrg_vector ,
mx::error_t::fits_parse_no_output , mx::error_t::fits_parse_bad_col , mx::error_t::fits_parse_bad_output , mx::error_t::fits_angle_too_big ,
mx::error_t::fits_bad_wcs_val , mx::error_t::fits_wcs_error , mx::error_t::fits_bad_wcs_proj , mx::error_t::fits_no_wcs_key ,
mx::error_t::fits_approx_wcs_key , mx::error_t::cuda_success , mx::error_t::cuda_invalid_value , mx::error_t::cuda_memory_allocation ,
mx::error_t::cuda_initialization_error , mx::error_t::cuda_cudart_unloading , mx::error_t::cuda_profiler_disabled , mx::error_t::cuda_profiler_not_initialized ,
mx::error_t::cuda_profiler_already_started , mx::error_t::cuda_profiler_already_stopped , mx::error_t::cuda_invalid_configuration , mx::error_t::cuda_invalid_pitch_value ,
mx::error_t::cuda_invalid_symbol , mx::error_t::cuda_invalid_host_pointer , mx::error_t::cuda_invalid_device_pointer , mx::error_t::cuda_invalid_texture ,
mx::error_t::cuda_invalid_texture_binding , mx::error_t::cuda_invalid_channel_descriptor , mx::error_t::cuda_invalid_memcpy_direction , mx::error_t::cuda_address_of_constant ,
mx::error_t::cuda_texture_fetch_failed , mx::error_t::cuda_texture_not_bound , mx::error_t::cuda_synchronization_error , mx::error_t::cuda_invalid_filter_setting ,
mx::error_t::cuda_invalid_norm_setting , mx::error_t::cuda_mixed_device_execution , mx::error_t::cuda_not_yet_implemented , mx::error_t::cuda_memory_value_too_large ,
mx::error_t::cuda_stub_library , mx::error_t::cuda_insufficient_driver , mx::error_t::cuda_call_requires_newer_driver , mx::error_t::cuda_invalid_surface ,
mx::error_t::cuda_duplicate_variable_name , mx::error_t::cuda_duplicate_texture_name , mx::error_t::cuda_duplicate_surface_name , mx::error_t::cuda_devices_unavailable ,
mx::error_t::cuda_incompatible_driver_context , mx::error_t::cuda_missing_configuration , mx::error_t::cuda_prior_launch_failure , mx::error_t::cuda_launch_max_depth_exceeded ,
mx::error_t::cuda_launch_file_scoped_tex , mx::error_t::cuda_launch_file_scoped_surf , mx::error_t::cuda_sync_depth_exceeded , mx::error_t::cuda_launch_pending_count_exceeded ,
mx::error_t::cuda_invalid_device_function , mx::error_t::cuda_no_device , mx::error_t::cuda_invalid_device , mx::error_t::cuda_device_not_licensed ,
mx::error_t::cuda_software_validity_not_established , mx::error_t::cuda_startup_failure , mx::error_t::cuda_invalid_kernel_image , mx::error_t::cuda_device_uninitialized ,
mx::error_t::cuda_map_buffer_object_failed , mx::error_t::cuda_unmap_buffer_object_failed , mx::error_t::cuda_array_is_mapped , mx::error_t::cuda_already_mapped ,
mx::error_t::cuda_no_kernel_image_for_device , mx::error_t::cuda_already_acquired , mx::error_t::cuda_not_mapped , mx::error_t::cuda_not_mapped_as_array ,
mx::error_t::cuda_not_mapped_as_pointer , mx::error_t::cuda_e_c_c_uncorrectable , mx::error_t::cuda_unsupported_limit , mx::error_t::cuda_device_already_in_use ,
mx::error_t::cuda_peer_access_unsupported , mx::error_t::cuda_invalid_ptx , mx::error_t::cuda_invalid_graphics_context , mx::error_t::cuda_nvlink_uncorrectable ,
mx::error_t::cuda_jit_compiler_not_found , mx::error_t::cuda_unsupported_ptx_version , mx::error_t::cuda_jit_compilation_disabled , mx::error_t::cuda_unsupported_exec_affinity ,
mx::error_t::cuda_invalid_source , mx::error_t::cuda_file_not_found , mx::error_t::cuda_shared_object_symbol_not_found , mx::error_t::cuda_shared_object_init_failed ,
mx::error_t::cuda_operating_system , mx::error_t::cuda_invalid_resource_handle , mx::error_t::cuda_illegal_state , mx::error_t::cuda_symbol_not_found ,
mx::error_t::cuda_not_ready , mx::error_t::cuda_illegal_address , mx::error_t::cuda_launch_out_of_resources , mx::error_t::cuda_launch_timeout ,
mx::error_t::cuda_launch_incompatible_texturing , mx::error_t::cuda_peer_access_already_enabled , mx::error_t::cuda_peer_access_not_enabled , mx::error_t::cuda_set_on_active_process ,
mx::error_t::cuda_context_is_destroyed , mx::error_t::cuda_assert , mx::error_t::cuda_too_many_peers , mx::error_t::cuda_host_memory_already_registered ,
mx::error_t::cuda_host_memory_not_registered , mx::error_t::cuda_hardware_stack_error , mx::error_t::cuda_illegal_instruction , mx::error_t::cuda_misaligned_address ,
mx::error_t::cuda_invalid_address_space , mx::error_t::cuda_invalid_pc , mx::error_t::cuda_launch_failure , mx::error_t::cuda_cooperative_launch_too_large ,
mx::error_t::cuda_not_permitted , mx::error_t::cuda_not_supported , mx::error_t::cuda_system_not_ready , mx::error_t::cuda_system_driver_mismatch ,
mx::error_t::cuda_compat_not_supported_on_device , mx::error_t::cuda_mps_connection_failed , mx::error_t::cuda_mps_rpc_failure , mx::error_t::cuda_mps_server_not_ready ,
mx::error_t::cuda_mps_max_clients_reached , mx::error_t::cuda_mps_max_connections_reached , mx::error_t::cuda_mps_client_terminated , mx::error_t::cuda_cdp_not_supported ,
mx::error_t::cuda_cdp_version_mismatch , mx::error_t::cuda_stream_capture_unsupported , mx::error_t::cuda_stream_capture_invalidated , mx::error_t::cuda_stream_capture_merge ,
mx::error_t::cuda_stream_capture_unmatched , mx::error_t::cuda_stream_capture_unjoined , mx::error_t::cuda_stream_capture_isolation , mx::error_t::cuda_stream_capture_implicit ,
mx::error_t::cuda_captured_event , mx::error_t::cuda_stream_capture_wrong_thread , mx::error_t::cuda_timeout , mx::error_t::cuda_graph_exec_update_failure ,
mx::error_t::cuda_external_device , mx::error_t::cuda_invalid_cluster_size , mx::error_t::cuda_unknown , mx::error_t::cuda_api_failure_base ,
mx::error_t::__sentinel
}
The mxlib error codes.
Functions
static constexpr const char * mx::errorName (const error_t &errc)
Convert a error_t code to its name.
static constexpr const char * mx::errorMessage (const error_t &errc)
Get the descriptive message for a error_t code.
static constexpr error_t mx::errno2error_t (const int &err)
Convert an errno code to error_t.
Enumeration Type Documentation
error_t
enum class mx::error_t strong
The mxlib error codes.
Enumerator
noerror
No error has occurred.
error
A general error has occurred.
invalidarg
An argument was invalid.
invalidconfig
A config setting was invalid.
notimpl
A component or technique is not implemented.
paramnotset
A parameter was not set.
envnotset
A environment variable was not set.
notfound
An item was not found.
sizeerr
A size was invalid or calculated incorrectly.
allocerr
An error occurred during memory allocation.
freeerr
An error occurred during memory de-allocation.
parseerr
A parsing error occurred.
filesystem
A general filesystem error occurred.
fileoerr
An error occurred while opening a file.
filewerr
An error occurred while writing to a file.
filererr
An error occurred while reading from a file.
filecerr
An error occurred while closing a file.
filenotfound
The file was not found.
fileempty
The file is empty.
dirnotfound
The directory was not found.
dirempty
The directory was empty.
procerr
An error occurred while starting a process.
timeout
A timeout occurred.
liberr
An error was returned by a library.
exception
An exception was thrown.
std_exception
An exception was thrown.
std_bad_alloc
A bad allocation exception was thrown.
std_logic_error
A logic error exception was thrown.
std_invalid_argument
An invalid argument exception was thrown.
std_domain_error
A domain error exception was thrown.
std_length_error
A length error exception was thrown.
std_out_of_range
An out of range exception was thrown.
std_future_error
A future error exception was thrown.
std_bad_optional_access
A bad optional access exception was thrown.
std_filesystem_error
A filesystem error exception was thrown.
std_runtime_error
A runtime error exception was thrown.
std_range_error
A range error exception was thrown.
std_overflow_error
An overflow exception was thrown.
std_underflow_error
An underflow exception was thrown.
std_ios_base_failure
An ios::base::failure exception was thrown.
std_format_error
A format library exception was thrown.
gnuploterr
An error was returned by gnuplot.
lapackerr
An error was returned by Lapack.
e2big
Argument list too long (E2BIG)
eacces
Permission denied (EACCES)
eaddrinuse
Address already in use (EADDRINUSE)
eaddrnotavail
Cannot assign requested address (EADDRNOTAVAIL)
eafnosupport
Address family not supported by protocol (EAFNOSUPPORT)
eagain
Resource temporarily unavailable (EAGAIN)
ealready
Operation already in progress (EALREADY)
ebadf
Bad file descriptor (EBADF)
ebadmsg
Bad message (EBADMSG)
ebusy
Device or resource busy (EBUSY)
ecanceled
Operation canceled (ECANCELED)
echild
No child processes (ECHILD)
econnaborted
Software caused connection abort (ECONNABORTED)
econnrefused
Connection refused (ECONNREFUSED)
econnreset
Connection reset by peer (ECONNRESET)
edestaddrreq
Destination address required (EDESTADDRREQ)
edom
Numerical argument out of domain (EDOM)
eexist
File exists (EEXIST)
efault
Bad address (EFAULT)
efbig
File too large (EFBIG)
ehostunreach
No route to host (EHOSTUNREACH)
eidrm
Identifier removed (EIDRM)
eilseq
Invalid or incomplete multibyte or wide character (EILSEQ)
einprogress
Operation now in progress (EINPROGRESS)
eintr
Interrupted system call (EINTR)
einval
Invalid argument (EINVAL)
eio
Input/output error (EIO)
eisconn
Transport endpoint is already connected (EISCONN)
eisdir
Is a directory (EISDIR)
eloop
Too many levels of symbolic links (ELOOP)
emfile
Too many open files (EMFILE)
emlink
Too many links (EMLINK)
emsgsize
Message too long (EMSGSIZE)
enametoolong
File name too long (ENAMETOOLONG)
enetdown
Network is down (ENETDOWN)
enetreset
Network dropped connection on reset (ENETRESET)
enetunreach
Network is unreachable (ENETUNREACH)
enfile
Too many open files in system (ENFILE)
enobufs
No buffer space available (ENOBUFS)
enodata
No data available (ENODATA)
enodev
No such device (ENODEV)
enoent
No such file or directory (ENOENT)
enoexec
Exec format error (ENOEXEC)
enolck
No locks available (ENOLCK)
enolink
Link has been severed (ENOLINK)
enomem
Cannot allocate memory (ENOMEM)
enomsg
No message of desired type (ENOMSG)
enoprotoopt
Protocol not available (ENOPROTOOPT)
enospc
No space left on device (ENOSPC)
enosr
Out of streams resources (ENOSR)
enostr
Device not a stream (ENOSTR)
enosys
Function not implemented (ENOSYS)
enotconn
Transport endpoint is not connected (ENOTCONN)
enotdir
Not a directory (ENOTDIR)
enotempty
Directory not empty (ENOTEMPTY)
enotrecoverable
State not recoverable (ENOTRECOVERABLE)
enotsock
Socket operation on non-socket (ENOTSOCK)
enotsup
Operation not supported (ENOTSUP)
enotty
Inappropriate ioctl for device (ENOTTY)
enxio
No such device or address (ENXIO)
eopnotsupp
Operation not supported (EOPNOTSUPP)
eoverflow
Value too large for defined data type (EOVERFLOW)
eownerdead
Owner died (EOWNERDEAD)
eperm
Operation not permitted (EPERM)
epipe
Broken pipe (EPIPE)
eproto
Protocol error (EPROTO)
eprotonosupport
Protocol not supported (EPROTONOSUPPORT)
eprototype
Protocol wrong type for socket (EPROTOTYPE)
erange
Numerical result out of range (ERANGE)
erofs
Read-only file system (EROFS)
espipe
Illegal seek (ESPIPE)
esrch
No such process (ESRCH)
etime
Timer expired (ETIME)
etimedout
Connection timed out (ETIMEDOUT)
etxtbsy
Text file busy (ETXTBSY)
ewouldblock
Resource temporarily unavailable (EWOULDBLOCK)
exdev
Invalid cross-device link (EXDEV)
fits_same_file
FITS: input and output files are the same.
fits_too_many_files
FITS: tried to open too many FITS files at once.
fits_file_not_opened
FITS: could not open the named file.
fits_file_not_created
FITS: could not create the named file.
fits_write_error
FITS: error writing to FITS file.
fits_end_of_file
FITS: tried to move past end of file.
fits_read_error
FITS: error reading from FITS file.
fits_file_not_closed
FITS: could not close the file.
fits_array_too_big
FITS: array dimensions exceed internal limit.
fits_readonly_file
FITS: Cannot write to readonly file.
fits_memory_allocation
FITS: Could not allocate memory.
fits_bad_fileptr
FITS: invalid fitsfile pointer.
fits_null_input_ptr
FITS: NULL input pointer to routine.
fits_seek_error
FITS: error seeking position in file.
fits_bad_nettimeout
FITS: bad value for file download timeout setting.
fits_bad_url_prefix
FITS: invalid URL prefix on file name.
fits_too_many_drivers
FITS: tried to register too many IO drivers.
fits_driver_init_failed
FITS: driver initialization failed.
fits_no_matching_driver
FITS: matching driver is not registered.
fits_url_parse_error
FITS: failed to parse input file URL.
fits_range_parse_error
FITS: parse error in range list.
fits_shared_badarg
FITS: bad argument in shared memory driver.
fits_shared_nulptr
FITS: null pointer passed as an argument.
fits_shared_tabfull
FITS: no more free shared memory handles.
fits_shared_notinit
FITS: shared memory driver is not initialized.
fits_shared_ipcerr
FITS: IPC error returned by a system call.
fits_shared_nomem
FITS: no memory in shared memory driver.
fits_shared_again
FITS: resource deadlock would occur.
fits_shared_nofile
FITS: attempt to open/create lock file failed.
fits_shared_noresize
FITS: shared memory block cannot be resized at the moment.
fits_header_not_empty
FITS: header already contains keywords.
fits_key_no_exist
FITS: keyword not found in header.
fits_key_out_bounds
FITS: keyword record number is out of bounds.
fits_value_undefined
FITS: keyword value field is blank.
fits_no_quote
FITS: string is missing the closing quote.
fits_bad_index_key
FITS: illegal indexed keyword name (e.g. 'TFORM1000')
fits_bad_keychar
FITS: illegal character in keyword name or card.
fits_bad_order
FITS: required keywords out of order.
fits_not_pos_int
FITS: keyword value is not a positive integer.
fits_no_end
FITS: couldn't find END keyword.
fits_bad_bitpix
FITS: illegal BITPIX keyword value.
fits_bad_naxis
FITS: illegal NAXIS keyword value.
fits_bad_naxes
FITS: illegal NAXISn keyword value.
fits_bad_pcount
FITS: illegal PCOUNT keyword value.
fits_bad_gcount
FITS: illegal GCOUNT keyword value.
fits_bad_tfields
FITS: illegal TFIELDS keyword value.
fits_neg_width
FITS: negative table row size.
fits_neg_rows
FITS: negative number of rows in table.
fits_col_not_found
FITS: column with this name not found in table.
fits_bad_simple
FITS: illegal value of SIMPLE keyword.
fits_no_simple
FITS: Primary array doesn't start with SIMPLE.
fits_no_bitpix
FITS: Second keyword not BITPIX.
fits_no_naxis
FITS: Third keyword not NAXIS.
fits_no_naxes
FITS: Couldn't find all the NAXISn keywords.
fits_no_xtension
FITS: HDU doesn't start with XTENSION keyword.
fits_not_atable
FITS: the CHDU is not an ASCII table extension.
fits_not_btable
FITS: the CHDU is not a binary table extension.
fits_no_pcount
FITS: couldn't find PCOUNT keyword.
fits_no_gcount
FITS: couldn't find GCOUNT keyword.
fits_no_tfields
FITS: couldn't find TFIELDS keyword.
fits_no_tbcol
FITS: couldn't find TBCOLn keyword.
fits_no_tform
FITS: couldn't find TFORMn keyword.
fits_not_image
FITS: the CHDU is not an IMAGE extension.
fits_bad_tbcol
FITS: TBCOLn keyword value < 0 or > rowlength.
fits_not_table
FITS: the CHDU is not a table.
fits_col_too_wide
FITS: column is too wide to fit in table.
fits_col_not_unique
FITS: more than 1 column name matches template.
fits_bad_row_width
FITS: sum of column widths not = NAXIS1.
fits_unknown_ext
FITS: unrecognizable FITS extension type.
fits_unknown_rec
FITS: unknown record; 1st keyword not SIMPLE or XTENSION.
fits_end_junk
FITS: END keyword is not blank.
fits_bad_header_fill
FITS: Header fill area contains non-blank chars.
fits_bad_data_fill
FITS: Illegal data fill bytes (not zero or blank)
fits_bad_tform
FITS: illegal TFORM format code.
fits_bad_tform_dtype
FITS: unrecognizable TFORM data type code.
fits_bad_tdim
FITS: illegal TDIMn keyword value.
fits_bad_heap_ptr
FITS: invalid BINTABLE heap pointer is out of range.
fits_bad_hdu_num
FITS: HDU number < 1.
fits_bad_col_num
FITS: column number < 1 or > tfields.
fits_neg_file_pos
FITS: tried to move to negative byte location in file.
fits_neg_bytes
FITS: tried to read or write negative number of bytes.
fits_bad_row_num
FITS: illegal starting row number in table.
fits_bad_elem_num
FITS: illegal starting element number in vector.
fits_not_ascii_col
FITS: this is not an ASCII string column.
fits_not_logical_col
FITS: this is not a logical data type column.
fits_bad_atable_format
FITS: ASCII table column has wrong format.
fits_bad_btable_format
FITS: Binary table column has wrong format.
fits_no_null
FITS: null value has not been defined.
fits_not_vari_len
FITS: this is not a variable length column.
fits_bad_dimen
FITS: illegal number of dimensions in array.
fits_bad_pix_num
FITS: first pixel number greater than last pixel.
fits_zero_scale
FITS: illegal BSCALE or TSCALn keyword = 0.
fits_neg_axis
FITS: illegal axis length < 1.
fits_not_group_table
FITS: Grouping function error.
fits_hdu_already_member
FITS: hdu already member.
fits_member_not_found
FITS: member not found.
fits_group_not_found
FITS: group not found.
fits_bad_group_id
FITS: bad group id.
fits_too_many_hdus_tracked
FITS: too many hdus tracked.
fits_hdu_already_tracked
FITS: hdu already tracked.
fits_bad_option
FITS: bad option.
fits_identical_pointers
FITS: identical pointers.
fits_bad_group_attach
FITS: bad group attach.
fits_bad_group_detach
FITS: bad group detach.
fits_ngp_no_memory
FITS: malloc failed.
fits_ngp_read_err
FITS: read error from file.
fits_ngp_nul_ptr
FITS: null pointer passed as an argument.
fits_ngp_empty_curline
FITS: line read seems to be empty (used.
fits_ngp_unread_queue_full
FITS: cannot unread more then 1 line.
fits_ngp_inc_nesting
FITS: too deep include file nesting.
fits_ngp_err_fopen
FITS: fopen() failed, cannot open template file.
fits_ngp_eof
FITS: end of file encountered and not expected.
fits_ngp_bad_arg
FITS: bad arguments passed.
fits_ngp_token_not_expect
FITS: token not expected here.
fits_bad_i2c
FITS: bad int to formatted string conversion.
fits_bad_f2c
FITS: bad float to formatted string conversion.
fits_bad_intkey
FITS: can't interpret keyword value as integer.
fits_bad_logicalkey
FITS: can't interpret keyword value as logical.
fits_bad_floatkey
FITS: can't interpret keyword value as float.
fits_bad_doublekey
FITS: can't interpret keyword value as double.
fits_bad_c2i
FITS: bad formatted string to int conversion.
fits_bad_c2f
FITS: bad formatted string to float conversion.
fits_bad_c2d
FITS: bad formatted string to double conversion.
fits_bad_datatype
FITS: illegal datatype code value.
fits_bad_decim
FITS: bad number of decimal places specified.
fits_num_overflow
FITS: overflow during data type conversion.
fits_data_compression_err
FITS: error compressing image.
fits_data_decompression_err
FITS: error uncompressing image.
fits_bad_date
FITS: error in date or time conversion.
fits_parse_syntax_err
FITS: syntax error in parser expression.
fits_parse_bad_type
FITS: expression did not evaluate to desired type.
fits_parse_lrg_vector
FITS: vector result too large to return in array.
fits_parse_no_output
FITS: data parser failed not sent an out column.
fits_parse_bad_col
FITS: bad data encounter while parsing column.
fits_parse_bad_output
FITS: Output file not of proper type.
fits_angle_too_big
FITS: celestial angle too large for projection.
fits_bad_wcs_val
FITS: bad celestial coordinate or pixel value.
fits_wcs_error
FITS: error in celestial coordinate calculation.
fits_bad_wcs_proj
FITS: unsupported type of celestial projection.
fits_no_wcs_key
FITS: celestial coordinate keywords not found.
fits_approx_wcs_key
FITS: approximate wcs keyword values were returned.
cuda_success
CUDA: no error.
cuda_invalid_value
CUDA: invalid argument.
cuda_memory_allocation
CUDA: out of memory.
cuda_initialization_error
CUDA: initialization error.
cuda_cudart_unloading
CUDA: driver shutting down.
cuda_profiler_disabled
CUDA: profiler disabled while using external profiling tool.
cuda_profiler_not_initialized
CUDA: profiler not initialized: call cudaProfilerInitialize()
cuda_profiler_already_started
CUDA: profiler already started.
cuda_profiler_already_stopped
CUDA: profiler already stopped.
cuda_invalid_configuration
CUDA: invalid configuration argument.
cuda_invalid_pitch_value
CUDA: invalid pitch argument.
cuda_invalid_symbol
CUDA: invalid device symbol.
cuda_invalid_host_pointer
CUDA: invalid host pointer.
cuda_invalid_device_pointer
CUDA: invalid device pointer.
cuda_invalid_texture
CUDA: invalid texture reference.
cuda_invalid_texture_binding
CUDA: texture is not bound to a pointer.
cuda_invalid_channel_descriptor
CUDA: invalid channel descriptor.
cuda_invalid_memcpy_direction
CUDA: invalid copy direction for memcpy.
cuda_address_of_constant
CUDA: invalid address of constant.
cuda_texture_fetch_failed
CUDA: fetch from texture failed.
cuda_texture_not_bound
CUDA: cannot fetch from a texture that is not bound.
cuda_synchronization_error
CUDA: incorrect use of __syncthreads()
cuda_invalid_filter_setting
CUDA: linear filtering not supported for non-float type.
cuda_invalid_norm_setting
CUDA: read as normalized float not supported for 32-bit non float type.
cuda_mixed_device_execution
CUDA: device emulation mode and device execution mode cannot be mixed.
cuda_not_yet_implemented
CUDA: feature not yet implemented.
cuda_memory_value_too_large
CUDA: memory size or pointer value too large to fit in 32 bit.
cuda_stub_library
CUDA: CUDA driver is a stub library.
cuda_insufficient_driver
CUDA: CUDA driver version is insufficient for CUDA runtime version.
cuda_call_requires_newer_driver
CUDA: API call is not supported in the installed CUDA driver.
cuda_invalid_surface
CUDA: invalid surface reference.
cuda_duplicate_variable_name
CUDA: duplicate global variable looked up by string name.
cuda_duplicate_texture_name
CUDA: duplicate texture looked up by string name.
cuda_duplicate_surface_name
CUDA: duplicate surface looked up by string name.
cuda_devices_unavailable
CUDA: CUDA-capable device(s) is/are busy or unavailable.
cuda_incompatible_driver_context
CUDA: incompatible driver context.
cuda_missing_configuration
CUDA: global function call is not configured.
cuda_prior_launch_failure
CUDA: unspecified launch failure in prior launch.
cuda_launch_max_depth_exceeded
CUDA: launch would exceed maximum depth of nested launches.
cuda_launch_file_scoped_tex
CUDA: launch failed because kernel uses unsupported, file-scoped textures (texture objects are supported)
cuda_launch_file_scoped_surf
CUDA: launch failed because kernel uses unsupported, file-scoped surfaces (surface objects are supported)
cuda_sync_depth_exceeded
CUDA: cudaDeviceSynchronize failed because caller's grid depth exceeds cudaLimitDevRuntimeSyncDepth.
cuda_launch_pending_count_exceeded
CUDA: launch failed because launch would exceed cudaLimitDevRuntimePendingLaunchCount.
cuda_invalid_device_function
CUDA: invalid device function.
cuda_no_device
CUDA: no CUDA-capable device is detected.
cuda_invalid_device
CUDA: invalid device ordinal.
cuda_device_not_licensed
CUDA: device doesn't have valid Grid license.
cuda_software_validity_not_established
CUDA: integrity checks failed.
cuda_startup_failure
CUDA: startup failure in cuda runtime.
cuda_invalid_kernel_image
CUDA: device kernel image is invalid.
cuda_device_uninitialized
CUDA: invalid device context.
cuda_map_buffer_object_failed
CUDA: mapping of buffer object failed.
cuda_unmap_buffer_object_failed
CUDA: unmapping of buffer object failed.
cuda_array_is_mapped
CUDA: array is mapped.
cuda_already_mapped
CUDA: resource already mapped.
cuda_no_kernel_image_for_device
CUDA: no kernel image is available for execution on the device.
cuda_already_acquired
CUDA: resource already acquired.
cuda_not_mapped
CUDA: resource not mapped.
cuda_not_mapped_as_array
CUDA: resource not mapped as array.
cuda_not_mapped_as_pointer
CUDA: resource not mapped as pointer.
cuda_e_c_c_uncorrectable
CUDA: uncorrectable ECC error encountered.
cuda_unsupported_limit
CUDA: limit is not supported on this architecture.
cuda_device_already_in_use
CUDA: exclusive-thread device already in use by a different thread.
cuda_peer_access_unsupported
CUDA: peer access is not supported between these two devices.
cuda_invalid_ptx
CUDA: a PTX JIT compilation failed.
cuda_invalid_graphics_context
CUDA: invalid OpenGL or DirectX context.
cuda_nvlink_uncorrectable
CUDA: uncorrectable NVLink error detected during the execution.
cuda_jit_compiler_not_found
CUDA: PTX JIT compiler library not found.
cuda_unsupported_ptx_version
CUDA: the provided PTX was compiled with an unsupported toolchain.
cuda_jit_compilation_disabled
CUDA: PTX JIT compilation was disabled.
cuda_unsupported_exec_affinity
CUDA: the provided execution affinity is not supported.
cuda_invalid_source
CUDA: device kernel image is invalid.
cuda_file_not_found
CUDA: file not found.
cuda_shared_object_symbol_not_found
CUDA: shared object symbol not found.
cuda_shared_object_init_failed
CUDA: shared object initialization failed.
cuda_operating_system
CUDA: OS call failed or operation not supported on this OS.
cuda_invalid_resource_handle
CUDA: invalid resource handle.
cuda_illegal_state
CUDA: the operation cannot be performed in the present state.
cuda_symbol_not_found
CUDA: named symbol not found.
cuda_not_ready
CUDA: device not ready.
cuda_illegal_address
CUDA: an illegal memory access was encountered.
cuda_launch_out_of_resources
CUDA: too many resources requested for launch.
cuda_launch_timeout
CUDA: the launch timed out and was terminated.
cuda_launch_incompatible_texturing
CUDA: launch uses incompatible texturing mode.
cuda_peer_access_already_enabled
CUDA: peer access is already enabled.
cuda_peer_access_not_enabled
CUDA: peer access has not been enabled.
cuda_set_on_active_process
CUDA: cannot set while device is active in this process.
cuda_context_is_destroyed
CUDA: context is destroyed.
cuda_assert
CUDA: device-side assert triggered.
cuda_too_many_peers
CUDA: peer mapping resources exhausted.
cuda_host_memory_already_registered
CUDA: part or all of the requested memory range is already mapped.
cuda_host_memory_not_registered
CUDA: pointer does not correspond to a registered memory region.
cuda_hardware_stack_error
CUDA: hardware stack error.
cuda_illegal_instruction
CUDA: an illegal instruction was encountered.
cuda_misaligned_address
CUDA: misaligned address.
cuda_invalid_address_space
CUDA: operation not supported on global/shared address space.
cuda_invalid_pc
CUDA: invalid program counter.
cuda_launch_failure
CUDA: unspecified launch failure.
cuda_cooperative_launch_too_large
CUDA: too many blocks in cooperative launch.
cuda_not_permitted
CUDA: operation not permitted.
cuda_not_supported
CUDA: operation not supported.
cuda_system_not_ready
CUDA: system not yet initialized.
cuda_system_driver_mismatch
CUDA: system has unsupported display driver / cuda driver combination.
cuda_compat_not_supported_on_device
CUDA: forward compatibility was attempted on non supported HW.
cuda_mps_connection_failed
CUDA: MPS client failed to connect to the MPS control daemon or the MPS server.
cuda_mps_rpc_failure
CUDA: the remote procedural call between the MPS server and the MPS client failed.
cuda_mps_server_not_ready
CUDA: MPS server is not ready to accept new MPS client requests.
cuda_mps_max_clients_reached
CUDA: the hardware resources required to create MPS client have been exhausted.
cuda_mps_max_connections_reached
CUDA: the hardware resources required to support device connections have been exhausted.
cuda_mps_client_terminated
CUDA: the MPS client has been terminated by the server.
cuda_cdp_not_supported
CUDA: is using CUDA Dynamic Parallelism, but the current configuration, like MPS, does not support it.
cuda_cdp_version_mismatch
CUDA: unsupported interaction between different versions of CUDA Dynamic Parallelism.
cuda_stream_capture_unsupported
CUDA: operation not permitted when stream is capturing.
cuda_stream_capture_invalidated
CUDA: operation failed due to a previous error during capture.
cuda_stream_capture_merge
CUDA: operation would result in a merge of separate capture sequences.
cuda_stream_capture_unmatched
CUDA: capture was not ended in the same stream as it began.
cuda_stream_capture_unjoined
CUDA: capturing stream has unjoined work.
cuda_stream_capture_isolation
CUDA: dependency created on uncaptured work in another stream.
cuda_stream_capture_implicit
CUDA: operation would make the legacy stream depend on a capturing blocking stream.
cuda_captured_event
CUDA: operation not permitted on an event last recorded in a capturing stream.
cuda_stream_capture_wrong_thread
CUDA: attempt to terminate a thread-local capture sequence from another thread.
cuda_timeout
CUDA: wait operation timed out.
cuda_graph_exec_update_failure
CUDA: the graph update was not performed because it included changes which violated constraints specific to instantiated graph update.
cuda_external_device
CUDA: an async error has occured in external entity outside of CUDA.
cuda_invalid_cluster_size
CUDA: a kernel launch error has occurred due to cluster misconfiguration.
cuda_unknown
CUDA: unknown error.
cuda_api_failure_base
CUDA: api failure base.
__sentinel
do not use
Definition at line 25 of file error_t.hpp.
Function Documentation
errno2error_t()
static constexpr error_t mx::errno2error_t (const int & err) static constexpr
Convert an errno code to error_t.
Returns
the error_t code corresponding to the errno code
Parameters
[in] err the errno code to convert
Definition at line 2006 of file error_t.hpp.
References mx::eacces, mx::eaddrinuse, mx::eaddrnotavail, mx::eafnosupport, mx::eagain, mx::ealready, mx::ebadf, mx::ebadmsg, mx::ebusy, mx::ecanceled, mx::echild, mx::econnaborted, mx::econnrefused, mx::econnreset, mx::edestaddrreq, mx::edom, mx::eexist, mx::efault, mx::efbig, mx::ehostunreach, mx::eidrm, mx::eilseq, mx::einprogress, mx::eintr, mx::einval, mx::eio, mx::eisconn, mx::eisdir, mx::eloop, mx::emfile, mx::emlink, mx::emsgsize, mx::enametoolong, mx::enetdown, mx::enetreset, mx::enetunreach, mx::enfile, mx::enobufs, mx::enodata, mx::enodev, mx::enoent, mx::enoexec, mx::enolck, mx::enolink, mx::enomem, mx::enomsg, mx::enoprotoopt, mx::enospc, mx::enosr, mx::enostr, mx::enosys, mx::enotconn, mx::enotdir, mx::enotempty, mx::enotrecoverable, mx::enotsock, mx::enotsup, mx::enotty, mx::enxio, mx::eoverflow, mx::eownerdead, mx::eperm, mx::epipe, mx::eproto, mx::eprotonosupport, mx::eprototype, mx::erange, mx::erofs, mx::error, mx::espipe, mx::esrch, mx::etime, mx::etimedout, mx::etxtbsy, and mx::exdev.
Referenced by mx::ioutils::createDirectories(), mx::ioutils::dir_exists_is(), mx::ioutils::exists(), mx::math::randomSeed(), mx::ioutils::readBinVector(), mx::ioutils::readColumns(), mx::ioutils::readRawBinary(), mx::ipc::runCommand(), unitTest::errorTest::error_tTest::TEST_CASE(), mx::ioutils::writeBinVector(), and mx::ioutils::writeRawBinary().
errorMessage()
static constexpr const char * mx::errorMessage (const error_t & errc) static constexpr
Get the descriptive message for a error_t code.
Returns
the descriptive message corresponding to the error_t code
Parameters
[in] errc the error code for which to get the message
Definition at line 1215 of file error_t.hpp.
References mx::allocerr, mx::cuda_address_of_constant, mx::cuda_already_acquired, mx::cuda_already_mapped, mx::cuda_api_failure_base, mx::cuda_array_is_mapped, mx::cuda_assert, mx::cuda_call_requires_newer_driver, mx::cuda_captured_event, mx::cuda_cdp_not_supported, mx::cuda_cdp_version_mismatch, mx::cuda_compat_not_supported_on_device, mx::cuda_context_is_destroyed, mx::cuda_cooperative_launch_too_large, mx::cuda_cudart_unloading, mx::cuda_device_already_in_use, mx::cuda_device_not_licensed, mx::cuda_device_uninitialized, mx::cuda_devices_unavailable, mx::cuda_duplicate_surface_name, mx::cuda_duplicate_texture_name, mx::cuda_duplicate_variable_name, mx::cuda_e_c_c_uncorrectable, mx::cuda_external_device, mx::cuda_file_not_found, mx::cuda_graph_exec_update_failure, mx::cuda_hardware_stack_error, mx::cuda_host_memory_already_registered, mx::cuda_host_memory_not_registered, mx::cuda_illegal_address, mx::cuda_illegal_instruction, mx::cuda_illegal_state, mx::cuda_incompatible_driver_context, mx::cuda_initialization_error, mx::cuda_insufficient_driver, mx::cuda_invalid_address_space, mx::cuda_invalid_channel_descriptor, mx::cuda_invalid_cluster_size, mx::cuda_invalid_configuration, mx::cuda_invalid_device, mx::cuda_invalid_device_function, mx::cuda_invalid_device_pointer, mx::cuda_invalid_filter_setting, mx::cuda_invalid_graphics_context, mx::cuda_invalid_host_pointer, mx::cuda_invalid_kernel_image, mx::cuda_invalid_memcpy_direction, mx::cuda_invalid_norm_setting, mx::cuda_invalid_pc, mx::cuda_invalid_pitch_value, mx::cuda_invalid_ptx, mx::cuda_invalid_resource_handle, mx::cuda_invalid_source, mx::cuda_invalid_surface, mx::cuda_invalid_symbol, mx::cuda_invalid_texture, mx::cuda_invalid_texture_binding, mx::cuda_invalid_value, mx::cuda_jit_compilation_disabled, mx::cuda_jit_compiler_not_found, mx::cuda_launch_failure, mx::cuda_launch_file_scoped_surf, mx::cuda_launch_file_scoped_tex, mx::cuda_launch_incompatible_texturing, mx::cuda_launch_max_depth_exceeded, mx::cuda_launch_out_of_resources, mx::cuda_launch_pending_count_exceeded, mx::cuda_launch_timeout, mx::cuda_map_buffer_object_failed, mx::cuda_memory_allocation, mx::cuda_memory_value_too_large, mx::cuda_misaligned_address, mx::cuda_missing_configuration, mx::cuda_mixed_device_execution, mx::cuda_mps_client_terminated, mx::cuda_mps_connection_failed, mx::cuda_mps_max_clients_reached, mx::cuda_mps_max_connections_reached, mx::cuda_mps_rpc_failure, mx::cuda_mps_server_not_ready, mx::cuda_no_device, mx::cuda_no_kernel_image_for_device, mx::cuda_not_mapped, mx::cuda_not_mapped_as_array, mx::cuda_not_mapped_as_pointer, mx::cuda_not_permitted, mx::cuda_not_ready, mx::cuda_not_supported, mx::cuda_not_yet_implemented, mx::cuda_nvlink_uncorrectable, mx::cuda_operating_system, mx::cuda_peer_access_already_enabled, mx::cuda_peer_access_not_enabled, mx::cuda_peer_access_unsupported, mx::cuda_prior_launch_failure, mx::cuda_profiler_already_started, mx::cuda_profiler_already_stopped, mx::cuda_profiler_disabled, mx::cuda_profiler_not_initialized, mx::cuda_set_on_active_process, mx::cuda_shared_object_init_failed, mx::cuda_shared_object_symbol_not_found, mx::cuda_software_validity_not_established, mx::cuda_startup_failure, mx::cuda_stream_capture_implicit, mx::cuda_stream_capture_invalidated, mx::cuda_stream_capture_isolation, mx::cuda_stream_capture_merge, mx::cuda_stream_capture_unjoined, mx::cuda_stream_capture_unmatched, mx::cuda_stream_capture_unsupported, mx::cuda_stream_capture_wrong_thread, mx::cuda_stub_library, mx::cuda_success, mx::cuda_symbol_not_found, mx::cuda_sync_depth_exceeded, mx::cuda_synchronization_error, mx::cuda_system_driver_mismatch, mx::cuda_system_not_ready, mx::cuda_texture_fetch_failed, mx::cuda_texture_not_bound, mx::cuda_timeout, mx::cuda_too_many_peers, mx::cuda_unknown, mx::cuda_unmap_buffer_object_failed, mx::cuda_unsupported_exec_affinity, mx::cuda_unsupported_limit, mx::cuda_unsupported_ptx_version, mx::dirempty, mx::dirnotfound, mx::e2big, mx::eacces, mx::eaddrinuse, mx::eaddrnotavail, mx::eafnosupport, mx::eagain, mx::ealready, mx::ebadf, mx::ebadmsg, mx::ebusy, mx::ecanceled, mx::echild, mx::econnaborted, mx::econnrefused, mx::econnreset, mx::edestaddrreq, mx::edom, mx::eexist, mx::efault, mx::efbig, mx::ehostunreach, mx::eidrm, mx::eilseq, mx::einprogress, mx::eintr, mx::einval, mx::eio, mx::eisconn, mx::eisdir, mx::eloop, mx::emfile, mx::emlink, mx::emsgsize, mx::enametoolong, mx::enetdown, mx::enetreset, mx::enetunreach, mx::enfile, mx::enobufs, mx::enodata, mx::enodev, mx::enoent, mx::enoexec, mx::enolck, mx::enolink, mx::enomem, mx::enomsg, mx::enoprotoopt, mx::enospc, mx::enosr, mx::enostr, mx::enosys, mx::enotconn, mx::enotdir, mx::enotempty, mx::enotrecoverable, mx::enotsock, mx::enotsup, mx::enotty, mx::envnotset, mx::enxio, mx::eopnotsupp, mx::eoverflow, mx::eownerdead, mx::eperm, mx::epipe, mx::eproto, mx::eprotonosupport, mx::eprototype, mx::erange, mx::erofs, mx::error, mx::espipe, mx::esrch, mx::etime, mx::etimedout, mx::etxtbsy, mx::ewouldblock, mx::exception, mx::exdev, mx::filecerr, mx::fileempty, mx::filenotfound, mx::fileoerr, mx::filererr, mx::filesystem, mx::filewerr, mx::fits_angle_too_big, mx::fits_approx_wcs_key, mx::fits_array_too_big, mx::fits_bad_atable_format, mx::fits_bad_bitpix, mx::fits_bad_btable_format, mx::fits_bad_c2d, mx::fits_bad_c2f, mx::fits_bad_c2i, mx::fits_bad_col_num, mx::fits_bad_data_fill, mx::fits_bad_datatype, mx::fits_bad_date, mx::fits_bad_decim, mx::fits_bad_dimen, mx::fits_bad_doublekey, mx::fits_bad_elem_num, mx::fits_bad_f2c, mx::fits_bad_fileptr, mx::fits_bad_floatkey, mx::fits_bad_gcount, mx::fits_bad_group_attach, mx::fits_bad_group_detach, mx::fits_bad_group_id, mx::fits_bad_hdu_num, mx::fits_bad_header_fill, mx::fits_bad_heap_ptr, mx::fits_bad_i2c, mx::fits_bad_index_key, mx::fits_bad_intkey, mx::fits_bad_keychar, mx::fits_bad_logicalkey, mx::fits_bad_naxes, mx::fits_bad_naxis, mx::fits_bad_nettimeout, mx::fits_bad_option, mx::fits_bad_order, mx::fits_bad_pcount, mx::fits_bad_pix_num, mx::fits_bad_row_num, mx::fits_bad_row_width, mx::fits_bad_simple, mx::fits_bad_tbcol, mx::fits_bad_tdim, mx::fits_bad_tfields, mx::fits_bad_tform, mx::fits_bad_tform_dtype, mx::fits_bad_url_prefix, mx::fits_bad_wcs_proj, mx::fits_bad_wcs_val, mx::fits_col_not_found, mx::fits_col_not_unique, mx::fits_col_too_wide, mx::fits_data_compression_err, mx::fits_data_decompression_err, mx::fits_driver_init_failed, mx::fits_end_junk, mx::fits_end_of_file, mx::fits_file_not_closed, mx::fits_file_not_created, mx::fits_file_not_opened, mx::fits_group_not_found, mx::fits_hdu_already_member, mx::fits_hdu_already_tracked, mx::fits_header_not_empty, mx::fits_identical_pointers, mx::fits_key_no_exist, mx::fits_key_out_bounds, mx::fits_member_not_found, mx::fits_memory_allocation, mx::fits_neg_axis, mx::fits_neg_bytes, mx::fits_neg_file_pos, mx::fits_neg_rows, mx::fits_neg_width, mx::fits_ngp_bad_arg, mx::fits_ngp_empty_curline, mx::fits_ngp_eof, mx::fits_ngp_err_fopen, mx::fits_ngp_inc_nesting, mx::fits_ngp_no_memory, mx::fits_ngp_nul_ptr, mx::fits_ngp_read_err, mx::fits_ngp_token_not_expect, mx::fits_ngp_unread_queue_full, mx::fits_no_bitpix, mx::fits_no_end, mx::fits_no_gcount, mx::fits_no_matching_driver, mx::fits_no_naxes, mx::fits_no_naxis, mx::fits_no_null, mx::fits_no_pcount, mx::fits_no_quote, mx::fits_no_simple, mx::fits_no_tbcol, mx::fits_no_tfields, mx::fits_no_tform, mx::fits_no_wcs_key, mx::fits_no_xtension, mx::fits_not_ascii_col, mx::fits_not_atable, mx::fits_not_btable, mx::fits_not_group_table, mx::fits_not_image, mx::fits_not_logical_col, mx::fits_not_pos_int, mx::fits_not_table, mx::fits_not_vari_len, mx::fits_null_input_ptr, mx::fits_num_overflow, mx::fits_parse_bad_col, mx::fits_parse_bad_output, mx::fits_parse_bad_type, mx::fits_parse_lrg_vector, mx::fits_parse_no_output, mx::fits_parse_syntax_err, mx::fits_range_parse_error, mx::fits_read_error, mx::fits_readonly_file, mx::fits_same_file, mx::fits_seek_error, mx::fits_shared_again, mx::fits_shared_badarg, mx::fits_shared_ipcerr, mx::fits_shared_nofile, mx::fits_shared_nomem, mx::fits_shared_noresize, mx::fits_shared_notinit, mx::fits_shared_nulptr, mx::fits_shared_tabfull, mx::fits_too_many_drivers, mx::fits_too_many_files, mx::fits_too_many_hdus_tracked, mx::fits_unknown_ext, mx::fits_unknown_rec, mx::fits_url_parse_error, mx::fits_value_undefined, mx::fits_wcs_error, mx::fits_write_error, mx::fits_zero_scale, mx::freeerr, mx::gnuploterr, mx::invalidarg, mx::invalidconfig, mx::lapackerr, mx::liberr, mx::noerror, mx::notfound, mx::notimpl, mx::paramnotset, mx::parseerr, mx::procerr, mx::sizeerr, mx::std_bad_alloc, mx::std_bad_optional_access, mx::std_domain_error, mx::std_exception, mx::std_filesystem_error, mx::std_format_error, mx::std_future_error, mx::std_invalid_argument, mx::std_ios_base_failure, mx::std_length_error, mx::std_logic_error, mx::std_out_of_range, mx::std_overflow_error, mx::std_range_error, mx::std_runtime_error, mx::std_underflow_error, and mx::timeout.
Referenced by unitTest::errorTest::error_tTest::TEST_CASE().
errorName()
static constexpr const char * mx::errorName (const error_t & errc) static constexpr
Convert a error_t code to its name.
Returns
the name of the error_t code
Parameters
[in] errc the error code to convert
Definition at line 424 of file error_t.hpp.
References mx::allocerr, mx::cuda_address_of_constant, mx::cuda_already_acquired, mx::cuda_already_mapped, mx::cuda_api_failure_base, mx::cuda_array_is_mapped, mx::cuda_assert, mx::cuda_call_requires_newer_driver, mx::cuda_captured_event, mx::cuda_cdp_not_supported, mx::cuda_cdp_version_mismatch, mx::cuda_compat_not_supported_on_device, mx::cuda_context_is_destroyed, mx::cuda_cooperative_launch_too_large, mx::cuda_cudart_unloading, mx::cuda_device_already_in_use, mx::cuda_device_not_licensed, mx::cuda_device_uninitialized, mx::cuda_devices_unavailable, mx::cuda_duplicate_surface_name, mx::cuda_duplicate_texture_name, mx::cuda_duplicate_variable_name, mx::cuda_e_c_c_uncorrectable, mx::cuda_external_device, mx::cuda_file_not_found, mx::cuda_graph_exec_update_failure, mx::cuda_hardware_stack_error, mx::cuda_host_memory_already_registered, mx::cuda_host_memory_not_registered, mx::cuda_illegal_address, mx::cuda_illegal_instruction, mx::cuda_illegal_state, mx::cuda_incompatible_driver_context, mx::cuda_initialization_error, mx::cuda_insufficient_driver, mx::cuda_invalid_address_space, mx::cuda_invalid_channel_descriptor, mx::cuda_invalid_cluster_size, mx::cuda_invalid_configuration, mx::cuda_invalid_device, mx::cuda_invalid_device_function, mx::cuda_invalid_device_pointer, mx::cuda_invalid_filter_setting, mx::cuda_invalid_graphics_context, mx::cuda_invalid_host_pointer, mx::cuda_invalid_kernel_image, mx::cuda_invalid_memcpy_direction, mx::cuda_invalid_norm_setting, mx::cuda_invalid_pc, mx::cuda_invalid_pitch_value, mx::cuda_invalid_ptx, mx::cuda_invalid_resource_handle, mx::cuda_invalid_source, mx::cuda_invalid_surface, mx::cuda_invalid_symbol, mx::cuda_invalid_texture, mx::cuda_invalid_texture_binding, mx::cuda_invalid_value, mx::cuda_jit_compilation_disabled, mx::cuda_jit_compiler_not_found, mx::cuda_launch_failure, mx::cuda_launch_file_scoped_surf, mx::cuda_launch_file_scoped_tex, mx::cuda_launch_incompatible_texturing, mx::cuda_launch_max_depth_exceeded, mx::cuda_launch_out_of_resources, mx::cuda_launch_pending_count_exceeded, mx::cuda_launch_timeout, mx::cuda_map_buffer_object_failed, mx::cuda_memory_allocation, mx::cuda_memory_value_too_large, mx::cuda_misaligned_address, mx::cuda_missing_configuration, mx::cuda_mixed_device_execution, mx::cuda_mps_client_terminated, mx::cuda_mps_connection_failed, mx::cuda_mps_max_clients_reached, mx::cuda_mps_max_connections_reached, mx::cuda_mps_rpc_failure, mx::cuda_mps_server_not_ready, mx::cuda_no_device, mx::cuda_no_kernel_image_for_device, mx::cuda_not_mapped, mx::cuda_not_mapped_as_array, mx::cuda_not_mapped_as_pointer, mx::cuda_not_permitted, mx::cuda_not_ready, mx::cuda_not_supported, mx::cuda_not_yet_implemented, mx::cuda_nvlink_uncorrectable, mx::cuda_operating_system, mx::cuda_peer_access_already_enabled, mx::cuda_peer_access_not_enabled, mx::cuda_peer_access_unsupported, mx::cuda_prior_launch_failure, mx::cuda_profiler_already_started, mx::cuda_profiler_already_stopped, mx::cuda_profiler_disabled, mx::cuda_profiler_not_initialized, mx::cuda_set_on_active_process, mx::cuda_shared_object_init_failed, mx::cuda_shared_object_symbol_not_found, mx::cuda_software_validity_not_established, mx::cuda_startup_failure, mx::cuda_stream_capture_implicit, mx::cuda_stream_capture_invalidated, mx::cuda_stream_capture_isolation, mx::cuda_stream_capture_merge, mx::cuda_stream_capture_unjoined, mx::cuda_stream_capture_unmatched, mx::cuda_stream_capture_unsupported, mx::cuda_stream_capture_wrong_thread, mx::cuda_stub_library, mx::cuda_success, mx::cuda_symbol_not_found, mx::cuda_sync_depth_exceeded, mx::cuda_synchronization_error, mx::cuda_system_driver_mismatch, mx::cuda_system_not_ready, mx::cuda_texture_fetch_failed, mx::cuda_texture_not_bound, mx::cuda_timeout, mx::cuda_too_many_peers, mx::cuda_unknown, mx::cuda_unmap_buffer_object_failed, mx::cuda_unsupported_exec_affinity, mx::cuda_unsupported_limit, mx::cuda_unsupported_ptx_version, mx::dirempty, mx::dirnotfound, mx::e2big, mx::eacces, mx::eaddrinuse, mx::eaddrnotavail, mx::eafnosupport, mx::eagain, mx::ealready, mx::ebadf, mx::ebadmsg, mx::ebusy, mx::ecanceled, mx::echild, mx::econnaborted, mx::econnrefused, mx::econnreset, mx::edestaddrreq, mx::edom, mx::eexist, mx::efault, mx::efbig, mx::ehostunreach, mx::eidrm, mx::eilseq, mx::einprogress, mx::eintr, mx::einval, mx::eio, mx::eisconn, mx::eisdir, mx::eloop, mx::emfile, mx::emlink, mx::emsgsize, mx::enametoolong, mx::enetdown, mx::enetreset, mx::enetunreach, mx::enfile, mx::enobufs, mx::enodata, mx::enodev, mx::enoent, mx::enoexec, mx::enolck, mx::enolink, mx::enomem, mx::enomsg, mx::enoprotoopt, mx::enospc, mx::enosr, mx::enostr, mx::enosys, mx::enotconn, mx::enotdir, mx::enotempty, mx::enotrecoverable, mx::enotsock, mx::enotsup, mx::enotty, mx::envnotset, mx::enxio, mx::eopnotsupp, mx::eoverflow, mx::eownerdead, mx::eperm, mx::epipe, mx::eproto, mx::eprotonosupport, mx::eprototype, mx::erange, mx::erofs, mx::error, mx::espipe, mx::esrch, mx::etime, mx::etimedout, mx::etxtbsy, mx::ewouldblock, mx::exception, mx::exdev, mx::filecerr, mx::fileempty, mx::filenotfound, mx::fileoerr, mx::filererr, mx::filesystem, mx::filewerr, mx::fits_angle_too_big, mx::fits_approx_wcs_key, mx::fits_array_too_big, mx::fits_bad_atable_format, mx::fits_bad_bitpix, mx::fits_bad_btable_format, mx::fits_bad_c2d, mx::fits_bad_c2f, mx::fits_bad_c2i, mx::fits_bad_col_num, mx::fits_bad_data_fill, mx::fits_bad_datatype, mx::fits_bad_date, mx::fits_bad_decim, mx::fits_bad_dimen, mx::fits_bad_doublekey, mx::fits_bad_elem_num, mx::fits_bad_f2c, mx::fits_bad_fileptr, mx::fits_bad_floatkey, mx::fits_bad_gcount, mx::fits_bad_group_attach, mx::fits_bad_group_detach, mx::fits_bad_group_id, mx::fits_bad_hdu_num, mx::fits_bad_header_fill, mx::fits_bad_heap_ptr, mx::fits_bad_i2c, mx::fits_bad_index_key, mx::fits_bad_intkey, mx::fits_bad_keychar, mx::fits_bad_logicalkey, mx::fits_bad_naxes, mx::fits_bad_naxis, mx::fits_bad_nettimeout, mx::fits_bad_option, mx::fits_bad_order, mx::fits_bad_pcount, mx::fits_bad_pix_num, mx::fits_bad_row_num, mx::fits_bad_row_width, mx::fits_bad_simple, mx::fits_bad_tbcol, mx::fits_bad_tdim, mx::fits_bad_tfields, mx::fits_bad_tform, mx::fits_bad_tform_dtype, mx::fits_bad_url_prefix, mx::fits_bad_wcs_proj, mx::fits_bad_wcs_val, mx::fits_col_not_found, mx::fits_col_not_unique, mx::fits_col_too_wide, mx::fits_data_compression_err, mx::fits_data_decompression_err, mx::fits_driver_init_failed, mx::fits_end_junk, mx::fits_end_of_file, mx::fits_file_not_closed, mx::fits_file_not_created, mx::fits_file_not_opened, mx::fits_group_not_found, mx::fits_hdu_already_member, mx::fits_hdu_already_tracked, mx::fits_header_not_empty, mx::fits_identical_pointers, mx::fits_key_no_exist, mx::fits_key_out_bounds, mx::fits_member_not_found, mx::fits_memory_allocation, mx::fits_neg_axis, mx::fits_neg_bytes, mx::fits_neg_file_pos, mx::fits_neg_rows, mx::fits_neg_width, mx::fits_ngp_bad_arg, mx::fits_ngp_empty_curline, mx::fits_ngp_eof, mx::fits_ngp_err_fopen, mx::fits_ngp_inc_nesting, mx::fits_ngp_no_memory, mx::fits_ngp_nul_ptr, mx::fits_ngp_read_err, mx::fits_ngp_token_not_expect, mx::fits_ngp_unread_queue_full, mx::fits_no_bitpix, mx::fits_no_end, mx::fits_no_gcount, mx::fits_no_matching_driver, mx::fits_no_naxes, mx::fits_no_naxis, mx::fits_no_null, mx::fits_no_pcount, mx::fits_no_quote, mx::fits_no_simple, mx::fits_no_tbcol, mx::fits_no_tfields, mx::fits_no_tform, mx::fits_no_wcs_key, mx::fits_no_xtension, mx::fits_not_ascii_col, mx::fits_not_atable, mx::fits_not_btable, mx::fits_not_group_table, mx::fits_not_image, mx::fits_not_logical_col, mx::fits_not_pos_int, mx::fits_not_table, mx::fits_not_vari_len, mx::fits_null_input_ptr, mx::fits_num_overflow, mx::fits_parse_bad_col, mx::fits_parse_bad_output, mx::fits_parse_bad_type, mx::fits_parse_lrg_vector, mx::fits_parse_no_output, mx::fits_parse_syntax_err, mx::fits_range_parse_error, mx::fits_read_error, mx::fits_readonly_file, mx::fits_same_file, mx::fits_seek_error, mx::fits_shared_again, mx::fits_shared_badarg, mx::fits_shared_ipcerr, mx::fits_shared_nofile, mx::fits_shared_nomem, mx::fits_shared_noresize, mx::fits_shared_notinit, mx::fits_shared_nulptr, mx::fits_shared_tabfull, mx::fits_too_many_drivers, mx::fits_too_many_files, mx::fits_too_many_hdus_tracked, mx::fits_unknown_ext, mx::fits_unknown_rec, mx::fits_url_parse_error, mx::fits_value_undefined, mx::fits_wcs_error, mx::fits_write_error, mx::fits_zero_scale, mx::freeerr, mx::gnuploterr, mx::invalidarg, mx::invalidconfig, mx::lapackerr, mx::liberr, mx::noerror, mx::notfound, mx::notimpl, mx::paramnotset, mx::parseerr, mx::procerr, mx::sizeerr, mx::std_bad_alloc, mx::std_bad_optional_access, mx::std_domain_error, mx::std_exception, mx::std_filesystem_error, mx::std_format_error, mx::std_future_error, mx::std_invalid_argument, mx::std_ios_base_failure, mx::std_length_error, mx::std_logic_error, mx::std_out_of_range, mx::std_overflow_error, mx::std_range_error, mx::std_runtime_error, mx::std_underflow_error, and mx::timeout.
Referenced by unitTest::errorTest::error_tTest::TEST_CASE().