var hierarchy =
[
    [ "mx::improc::ADIDerotator< _realT >", "structmx_1_1improc_1_1ADIDerotator.html", null ],
    [ "mx::math::fit::airy2D_obs_fitter< _realT >", "structmx_1_1math_1_1fit_1_1airy2D__obs__fitter.html", null ],
    [ "mx::math::fit::airy2D_obs_fitter_ps< _realT >", "structmx_1_1math_1_1fit_1_1airy2D__obs__fitter__ps.html", null ],
    [ "mx::math::fit::airy2D_obs_fitter_ps_eps< _realT >", "structmx_1_1math_1_1fit_1_1airy2D__obs__fitter__ps__eps.html", null ],
    [ "mx::AO::analysis::aoAtmosphere< _realT >", "classmx_1_1AO_1_1analysis_1_1aoAtmosphere.html", null ],
    [ "mx::AO::analysis::aoAtmosphere< realT >", "classmx_1_1AO_1_1analysis_1_1aoAtmosphere.html", null ],
    [ "mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >", "classmx_1_1AO_1_1analysis_1_1aoSystem.html", null ],
    [ "mx::improc::aperturePhotometer< realT >", "classmx_1_1improc_1_1aperturePhotometer.html", null ],
    [ "mx::app::appConfigurator", "structmx_1_1app_1_1appConfigurator.html", null ],
    [ "mx::app::application", "classmx_1_1app_1_1application.html", null ],
    [ "mx::math::fit::array2Fit< realT >", "structmx_1_1math_1_1fit_1_1array2Fit.html", null ],
    [ "mx::math::fit::array2FitAiry< realT >", "structmx_1_1math_1_1fit_1_1array2FitAiry.html", null ],
    [ "mx::math::fit::array2FitGaussian1D< realT >", "structmx_1_1math_1_1fit_1_1array2FitGaussian1D.html", null ],
    [ "mx::math::fit::array2FitGaussian2D< realT >", "structmx_1_1math_1_1fit_1_1array2FitGaussian2D.html", null ],
    [ "mx::math::fit::array2FitMoffat< realT >", "structmx_1_1math_1_1fit_1_1array2FitMoffat.html", null ],
    [ "mx::math::fit::array2FitMoffat1D< realT >", "structmx_1_1math_1_1fit_1_1array2FitMoffat1D.html", null ],
    [ "mx::sigproc::psdFilterTypes::arrayT< realT, rank >", "structmx_1_1sigproc_1_1psdFilterTypes_1_1arrayT.html", null ],
    [ "mx::astro::astroFilter< _units, _rsr >", "structmx_1_1astro_1_1astroFilter.html", null ],
    [ "mx::sigproc::autocorrelationFromPSD< T >", "structmx_1_1sigproc_1_1autocorrelationFromPSD.html", null ],
    [ "mx::sigproc::autocorrelationFromPSD< realT >", "structmx_1_1sigproc_1_1autocorrelationFromPSD.html", null ],
    [ "mx::sigproc::averagePeriodogram< realT >", "classmx_1_1sigproc_1_1averagePeriodogram.html", null ],
    [ "mx::improc::azBoxKernel< _arrayT, _kernW >", "structmx_1_1improc_1_1azBoxKernel.html", null ],
    [ "mx::astro::baseSpectrum< realT >", "structmx_1_1astro_1_1baseSpectrum.html", null ],
    [ "mx::astro::baseSpectrum< _spectrumT::units::realT >", "structmx_1_1astro_1_1baseSpectrum.html", [
      [ "mx::astro::astroSpectrum< _spectrumT, freq >", "structmx_1_1astro_1_1astroSpectrum.html", null ]
    ] ],
    [ "mx::astro::baseSpectrum< _units::realT >", "structmx_1_1astro_1_1baseSpectrum.html", [
      [ "mx::astro::cahoyGrid< _units >", "structmx_1_1astro_1_1cahoyGrid.html", null ]
    ] ],
    [ "mx::astro::basicSpectrum< _units >", "structmx_1_1astro_1_1basicSpectrum.html", null ],
    [ "mx::improc::bilinearTransform< _arithT >", "structmx_1_1improc_1_1bilinearTransform.html", null ],
    [ "mx::astro::blackbody< units, freq >", "structmx_1_1astro_1_1blackbody.html", null ],
    [ "mx::astro::cahoySpectrumRaw< _units >", "structmx_1_1astro_1_1cahoySpectrumRaw.html", null ],
    [ "mx::astro::calspecSpectrum< _units >", "structmx_1_1astro_1_1calspecSpectrum.html", null ],
    [ "mx::AO::sim::ccdDetector< _realT >", "classmx_1_1AO_1_1sim_1_1ccdDetector.html", null ],
    [ "mx::astro::units::cgs< _realT >", "structmx_1_1astro_1_1units_1_1cgs.html", null ],
    [ "mx::sigproc::circularBufferBase< _derivedT, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", null ],
    [ "mx::sigproc::circularBufferBase< circularBufferBranch< _storedT, _indexT >, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", [
      [ "mx::sigproc::circularBufferBranch< _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBranch.html", null ]
    ] ],
    [ "mx::sigproc::circularBufferBase< circularBufferIndex< _storedT, _indexT >, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", [
      [ "mx::sigproc::circularBufferIndex< _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferIndex.html", null ]
    ] ],
    [ "mx::sigproc::circularBufferBase< circularBufferMod< _storedT, _indexT >, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", [
      [ "mx::sigproc::circularBufferMod< _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferMod.html", null ]
    ] ],
    [ "mx::AO::analysis::clAOLinearPredictor< _realT >", "structmx_1_1AO_1_1analysis_1_1clAOLinearPredictor.html", null ],
    [ "mx::AO::analysis::clGainOpt< _realT >", "structmx_1_1AO_1_1analysis_1_1clGainOpt.html", null ],
    [ "mx::AO::analysis::clGainOpt< realT >", "structmx_1_1AO_1_1analysis_1_1clGainOpt.html", null ],
    [ "mx::AO::analysis::clGainOptOptGain_OL< realT >", "structmx_1_1AO_1_1analysis_1_1clGainOptOptGain__OL.html", null ],
    [ "mx::app::clOptions", "structmx_1_1app_1_1clOptions.html", null ],
    [ "mx::app::configTarget", "structmx_1_1app_1_1configTarget.html", null ],
    [ "mx::improc::cubicConvolTransform< _arithT >", "structmx_1_1improc_1_1cubicConvolTransform.html", null ],
    [ "mx::cuda::cudaPtr< T >", "structmx_1_1cuda_1_1cudaPtr.html", null ],
    [ "mx::cuda::cudaPtr< complexT >", "structmx_1_1cuda_1_1cudaPtr.html", null ],
    [ "mx::AO::sim::directPhaseReconstructor< realT >", "classmx_1_1AO_1_1sim_1_1directPhaseReconstructor.html", null ],
    [ "mx::astro::units::earth< _realT >", "structmx_1_1astro_1_1units_1_1earth.html", null ],
    [ "mx::astro::earthAlbedo< _units >", "structmx_1_1astro_1_1earthAlbedo.html", null ],
    [ "mx::improc::eigenArrPlanes< arrT, isCube >", "structmx_1_1improc_1_1eigenArrPlanes.html", null ],
    [ "mx::improc::eigenCube< dataT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::improc::eigenCube< floatT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::improc::eigenCube< realT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::math::fft::fftT< _inputT, _outputT, _rank, 0 >", "classmx_1_1math_1_1fft_1_1fftT_3_01__inputT_00_01__outputT_00_01__rank_00_010_01_4.html", null ],
    [ "mx::math::fft::fftwEnvironment< realT, threads >", "structmx_1_1math_1_1fft_1_1fftwEnvironment.html", null ],
    [ "mx::math::fft::fftwPlanSpec< realT >", "structmx_1_1math_1_1fft_1_1fftwPlanSpec.html", null ],
    [ "mx::math::fft::fftwPlanSpec< double >", "structmx_1_1math_1_1fft_1_1fftwPlanSpec_3_01double_01_4.html", null ],
    [ "mx::math::fft::fftwPlanSpec< float >", "structmx_1_1math_1_1fft_1_1fftwPlanSpec_3_01float_01_4.html", null ],
    [ "mx::math::fft::fftwPlanSpec< long double >", "structmx_1_1math_1_1fft_1_1fftwPlanSpec_3_01long_01double_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< _inputDataT, _outputDataT >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec.html", null ],
    [ "mx::math::fft::fftwTypeSpec< complexDT, complexDT >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01complexDT_00_01complexDT_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< complexDT, double >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01complexDT_00_01double_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< complexFT, complexFT >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01complexFT_00_01complexFT_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< complexFT, float >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01complexFT_00_01float_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< complexLT, complexLT >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01complexLT_00_01complexLT_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< complexLT, long double >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01complexLT_00_01long_01double_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< double, complexDT >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01double_00_01complexDT_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< float, complexFT >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01float_00_01complexFT_01_4.html", null ],
    [ "mx::math::fft::fftwTypeSpec< long double, complexLT >", "structmx_1_1math_1_1fft_1_1fftwTypeSpec_3_01long_01double_00_01complexLT_01_4.html", null ],
    [ "mx::fits::fitsFile< dataT >", "classmx_1_1fits_1_1fitsFile.html", null ],
    [ "mx::fits::fitsHeader", "classmx_1_1fits_1_1fitsHeader.html", null ],
    [ "mx::fits::fitsHeaderCard", "classmx_1_1fits_1_1fitsHeaderCard.html", null ],
    [ "mx::AO::analysis::fourierCovariance< realT, aosysT >", "structmx_1_1AO_1_1analysis_1_1fourierCovariance.html", null ],
    [ "mx::sigproc::fourierModeDef", "structmx_1_1sigproc_1_1fourierModeDef.html", null ],
    [ "mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >", "structmx_1_1AO_1_1analysis_1_1fourierTemporalPSD.html", null ],
    [ "mx::wfp::fraunhoferPropagator< _wavefrontT >", "classmx_1_1wfp_1_1fraunhoferPropagator.html", null ],
    [ "mx::wfp::fraunhoferPropagator< _wavefrontT, 1 >", "classmx_1_1wfp_1_1fraunhoferPropagator_3_01__wavefrontT_00_011_01_4.html", null ],
    [ "mx::wfp::fraunhoferPropagator< complexFieldT >", "classmx_1_1wfp_1_1fraunhoferPropagator.html", null ],
    [ "mx::math::fit::gaussian1D_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gaussian1D__fitter.html", null ],
    [ "mx::math::fit::gaussian2D_gen_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gaussian2D__gen__fitter.html", null ],
    [ "mx::math::fit::gaussian2D_sym_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gaussian2D__sym__fitter.html", null ],
    [ "mx::improc::gaussKernel< _arrayT, _kernW >", "structmx_1_1improc_1_1gaussKernel.html", null ],
    [ "mx::AO::sim::generalIntegrator< _realT >", "classmx_1_1AO_1_1sim_1_1generalIntegrator.html", null ],
    [ "mx::sys::gitRepo", "classmx_1_1sys_1_1gitRepo.html", null ],
    [ "mx::math::gnuPlot", "classmx_1_1math_1_1gnuPlot.html", null ],
    [ "mx::math::gsl_interp_linear< _realT >", "structmx_1_1math_1_1gsl__interp__linear.html", null ],
    [ "mx::math::gsl_interp_steffen< _realT >", "structmx_1_1math_1_1gsl__interp__steffen.html", null ],
    [ "mx::math::gslInterpolator< interpT >", "classmx_1_1math_1_1gslInterpolator.html", null ],
    [ "mx::math::gslInterpolator< mx::math::gsl_interp_linear< double > >", "classmx_1_1math_1_1gslInterpolator.html", null ],
    [ "mx::math::gslInterpolator< mx::math::gsl_interp_linear< realT > >", "classmx_1_1math_1_1gslInterpolator.html", null ],
    [ "mx::math::gslInterpolator< mx::math::gsl_interp_steffen< realT > >", "classmx_1_1math_1_1gslInterpolator.html", null ],
    [ "mx::math::fit::hasJacobian< T >", "structmx_1_1math_1_1fit_1_1hasJacobian.html", null ],
    [ "mx::improc::HCIobservation< _realT >", "structmx_1_1improc_1_1HCIobservation.html", [
      [ "mx::improc::ADIobservation< _realT, _derotFunctObj >", "structmx_1_1improc_1_1ADIobservation.html", [
        [ "mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >", "structmx_1_1improc_1_1KLIPreduction.html", null ]
      ] ]
    ] ],
    [ "mx::math::histogramUniform< realT >", "classmx_1_1math_1_1histogramUniform.html", null ],
    [ "mx::wfp::idealCoronagraph< _realT >", "structmx_1_1wfp_1_1idealCoronagraph.html", null ],
    [ "mx::improc::imageXCorrDiscrete< _ccImT >", "classmx_1_1improc_1_1imageXCorrDiscrete.html", null ],
    [ "mx::improc::imageXCorrFFT< _ccImT >", "classmx_1_1improc_1_1imageXCorrFFT.html", null ],
    [ "mx::improc::imCenterCircleSym< realT >", "structmx_1_1improc_1_1imCenterCircleSym.html", null ],
    [ "mx::app::iniFile", "structmx_1_1app_1_1iniFile.html", null ],
    [ "mx::improc::is_eigenCube< T >", "structmx_1_1improc_1_1is__eigenCube.html", null ],
    [ "mx::wfp::is_imagingArray< T >", "structmx_1_1wfp_1_1is__imagingArray.html", null ],
    [ "mx::meta::is_std_vector< T, if_value_type >", "structmx_1_1meta_1_1is__std__vector.html", null ],
    [ "mx::meta::is_std_vector< T, false >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01false_01_4.html", null ],
    [ "mx::meta::is_std_vector< T, true >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01true_01_4.html", null ],
    [ "mx::astro::units::jupiter< _realT >", "structmx_1_1astro_1_1units_1_1jupiter.html", null ],
    [ "mx::math::laplace_distribution< _RealType >", "classmx_1_1math_1_1laplace__distribution.html", null ],
    [ "mx::AO::sim::leakyIntegrator< _realT >", "classmx_1_1AO_1_1sim_1_1leakyIntegrator.html", null ],
    [ "mx::math::fit::levmarInterface< fitterT >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", [
      [ "mx::math::fit::fitGaussian2D< realT >", "classmx_1_1math_1_1fit_1_1fitGaussian2D.html", null ],
      [ "mx::math::fit::fitGaussian2D< mx::math::fit::gaussian2D_gen_fitter< Scalar > >", "classmx_1_1math_1_1fit_1_1fitGaussian2D.html", null ],
      [ "mx::math::fit::fitAiry2D< fitterT >", "classmx_1_1math_1_1fit_1_1fitAiry2D.html", null ],
      [ "mx::math::fit::fitGaussian2D< fitterT >", "classmx_1_1math_1_1fit_1_1fitGaussian2D.html", null ],
      [ "mx::math::fit::fitMoffat2D< fitterT >", "classmx_1_1math_1_1fit_1_1fitMoffat2D.html", null ]
    ] ],
    [ "mx::math::fit::levmarInterface< gaussian1D_fitter< _realT > >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", [
      [ "mx::math::fit::fitGaussian1D< _realT >", "classmx_1_1math_1_1fit_1_1fitGaussian1D.html", null ]
    ] ],
    [ "mx::math::fit::levmarInterface< moffat1D_fitter< _realT > >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", [
      [ "mx::math::fit::fitMoffat1D< _realT >", "classmx_1_1math_1_1fit_1_1fitMoffat1D.html", null ]
    ] ],
    [ "mx::sigproc::linearPredictor< _realT >", "structmx_1_1sigproc_1_1linearPredictor.html", null ],
    [ "mx::sigproc::linearPredictor< realT >", "structmx_1_1sigproc_1_1linearPredictor.html", null ],
    [ "mx::math::logInterpolator< realT >", "classmx_1_1math_1_1logInterpolator.html", null ],
    [ "mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >", "structmx_1_1wfp_1_1lyotCoronagraph.html", null ],
    [ "mx::astro::mainSequence< realT >", "structmx_1_1astro_1_1mainSequence.html", null ],
    [ "mx::math::fit::moffat1D_fitter< _realT >", "structmx_1_1math_1_1fit_1_1moffat1D__fitter.html", null ],
    [ "mx::math::fit::moffat2D_sym_fitter< _realT >", "structmx_1_1math_1_1fit_1_1moffat2D__sym__fitter.html", null ],
    [ "mx::err::mxException", "classmx_1_1err_1_1mxException.html", [
      [ "mx::err::allocerr", "classmx_1_1err_1_1allocerr.html", null ],
      [ "mx::err::filecerr", "classmx_1_1err_1_1filecerr.html", null ],
      [ "mx::err::fileoerr", "classmx_1_1err_1_1fileoerr.html", null ],
      [ "mx::err::filererr", "classmx_1_1err_1_1filererr.html", null ],
      [ "mx::err::filewerr", "classmx_1_1err_1_1filewerr.html", null ],
      [ "mx::err::invalidarg", "classmx_1_1err_1_1invalidarg.html", null ],
      [ "mx::err::invalidconfig", "classmx_1_1err_1_1invalidconfig.html", null ],
      [ "mx::err::liberr", "classmx_1_1err_1_1liberr.html", null ],
      [ "mx::err::notimpl", "classmx_1_1err_1_1notimpl.html", null ],
      [ "mx::err::paramnotset", "classmx_1_1err_1_1paramnotset.html", null ],
      [ "mx::err::sizeerr", "classmx_1_1err_1_1sizeerr.html", null ]
    ] ],
    [ "mx::ipc::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine, _time >", "classmx_1_1ipc_1_1ompLoopWatcher.html", null ],
    [ "mx::math::laplace_distribution< _RealType >::param_type", "structmx_1_1math_1_1laplace__distribution_1_1param__type.html", null ],
    [ "mx::astro::sqWaveFilter< _units, _rsr >::paramsT", "structmx_1_1astro_1_1sqWaveFilter_1_1paramsT.html", null ],
    [ "mx::astro::phoenixSpectrum< _units >", "structmx_1_1astro_1_1phoenixSpectrum.html", null ],
    [ "mx::astro::picklesSpectrum< _units >", "structmx_1_1astro_1_1picklesSpectrum.html", null ],
    [ "mx::sigproc::psdFilter< _realT, 1 >", "classmx_1_1sigproc_1_1psdFilter_3_01__realT_00_011_01_4.html", null ],
    [ "mx::sigproc::psdFilter< _realT, _rank, 0 >", "classmx_1_1sigproc_1_1psdFilter_3_01__realT_00_01__rank_00_010_01_4.html", null ],
    [ "mx::sigproc::psdVarMean< paramsT >", "structmx_1_1sigproc_1_1psdVarMean.html", null ],
    [ "mx::sigproc::psdVarMeanParams< _realT >", "structmx_1_1sigproc_1_1psdVarMeanParams.html", null ],
    [ "mx::AO::sim::pywfsSlopeReconstructor< _floatT >", "classmx_1_1AO_1_1sim_1_1pywfsSlopeReconstructor.html", null ],
    [ "mx::math::randomT< typeT, _ranengT, _randistT >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< int, std::mt19937_64, std::poisson_distribution< int > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< long, std::mt19937_64, std::poisson_distribution< long > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< realT >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< realT, std::mt19937_64, std::gamma_distribution< realT > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< realT, std::mt19937_64, std::normal_distribution< realT > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::ipc::sharedMemSegment", "classmx_1_1ipc_1_1sharedMemSegment.html", null ],
    [ "mx::astro::units::si< _realT >", "structmx_1_1astro_1_1units_1_1si.html", null ],
    [ "mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT, _coronT >", "classmx_1_1AO_1_1sim_1_1simulatedAOSystem.html", null ],
    [ "mx::ioutils::skipCol", "structmx_1_1ioutils_1_1skipCol.html", null ],
    [ "mx::astro::units::solar< _realT >", "structmx_1_1astro_1_1units_1_1solar.html", null ],
    [ "mx::improc::sourceFinder< _realT >", "classmx_1_1improc_1_1sourceFinder.html", null ],
    [ "mx::astro::sqWaveFilter< _units, _rsr >", "structmx_1_1astro_1_1sqWaveFilter.html", null ],
    [ "mx::math::syevrMem< floatT >", "structmx_1_1math_1_1syevrMem.html", null ],
    [ "mx::ioutils::textTable", "structmx_1_1ioutils_1_1textTable.html", null ],
    [ "mx::meta::trueFalseT< trueFalse >", "structmx_1_1meta_1_1trueFalseT.html", null ],
    [ "mx::meta::trueFalseT< false >", "structmx_1_1meta_1_1trueFalseT_3_01false_01_4.html", null ],
    [ "mx::meta::trueFalseT< true >", "structmx_1_1meta_1_1trueFalseT_3_01true_01_4.html", [
      [ "mx::meta::has_value_type< T, void_t< typename T::value_type > >", "structmx_1_1meta_1_1has__value__type_3_01T_00_01void__t_3_01typename_01T_1_1value__type_01_4_01_4.html", null ]
    ] ],
    [ "mx::AO::sim::turbAtmosphere< _realT >", "structmx_1_1AO_1_1sim_1_1turbAtmosphere.html", null ],
    [ "mx::AO::sim::turbLayer< _realT >", "structmx_1_1AO_1_1sim_1_1turbLayer.html", null ],
    [ "mx::meta::typeDescription< T >", "structmx_1_1meta_1_1typeDescription.html", null ],
    [ "mx::fits::fitsHeaderCard::values", "unionmx_1_1fits_1_1fitsHeaderCard_1_1values.html", null ],
    [ "mx::astro::venusAlbedo< _units >", "structmx_1_1astro_1_1venusAlbedo.html", null ],
    [ "mx::AO::analysis::vonKarmanSpectrum< realT >", "structmx_1_1AO_1_1analysis_1_1vonKarmanSpectrum.html", null ],
    [ "mx::AO::sim::wavefront< _realT >", "structmx_1_1AO_1_1sim_1_1wavefront.html", null ],
    [ "mx::AO::analysis::wfs< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1wfs.html", null ],
    [ "mx::AO::analysis::wfs< realT, std::ostream >", "structmx_1_1AO_1_1analysis_1_1wfs.html", [
      [ "mx::AO::analysis::pywfsModAsymptotic< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1pywfsModAsymptotic.html", null ],
      [ "mx::AO::analysis::pywfsUnmod< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1pywfsUnmod.html", null ],
      [ "mx::AO::analysis::shwfs< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1shwfs.html", null ]
    ] ]
];