var hierarchy =
[
    [ "mx::math::fit::airy2D_obs_fitter< _realT >", "structmx_1_1math_1_1fit_1_1airy2D__obs__fitter.html", null ],
    [ "mx::math::fit::airy2D_obs_fitter_ps< _realT >", "structmx_1_1math_1_1fit_1_1airy2D__obs__fitter__ps.html", null ],
    [ "mx::math::fit::airy2D_obs_fitter_ps_eps< _realT >", "structmx_1_1math_1_1fit_1_1airy2D__obs__fitter__ps__eps.html", null ],
    [ "mx::AO::analysis::aoAtmosphere< _realT >", "classmx_1_1AO_1_1analysis_1_1aoAtmosphere.html", null ],
    [ "mx::AO::analysis::aoAtmosphere< realT >", "classmx_1_1AO_1_1analysis_1_1aoAtmosphere.html", null ],
    [ "mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >", "classmx_1_1AO_1_1analysis_1_1aoSystem.html", null ],
    [ "mx::improc::aperturePhotometer< realT >", "classmx_1_1improc_1_1aperturePhotometer.html", null ],
    [ "mx::app::appConfigurator", "structmx_1_1app_1_1appConfigurator.html", null ],
    [ "mx::app::application", "classmx_1_1app_1_1application.html", null ],
    [ "mx::math::fit::array2Fit< realT >", "structmx_1_1math_1_1fit_1_1array2Fit.html", null ],
    [ "mx::math::fit::array2FitAiry< realT >", "structmx_1_1math_1_1fit_1_1array2FitAiry.html", null ],
    [ "mx::math::fit::array2FitEmpirical< realT >", "structmx_1_1math_1_1fit_1_1array2FitEmpirical.html", null ],
    [ "mx::math::fit::array2FitExpModGaussian< realT >", "structmx_1_1math_1_1fit_1_1array2FitExpModGaussian.html", null ],
    [ "mx::math::fit::array2FitGammaDistribution< realT >", "structmx_1_1math_1_1fit_1_1array2FitGammaDistribution.html", null ],
    [ "mx::math::fit::array2FitGaussian1D< realT >", "structmx_1_1math_1_1fit_1_1array2FitGaussian1D.html", null ],
    [ "mx::math::fit::array2FitGaussian2D< realT >", "structmx_1_1math_1_1fit_1_1array2FitGaussian2D.html", null ],
    [ "mx::math::fit::array2FitMoffat< realT >", "structmx_1_1math_1_1fit_1_1array2FitMoffat.html", null ],
    [ "mx::math::fit::array2FitMoffat1D< realT >", "structmx_1_1math_1_1fit_1_1array2FitMoffat1D.html", null ],
    [ "mx::math::fit::array2FitWeibull< realT >", "structmx_1_1math_1_1fit_1_1array2FitWeibull.html", null ],
    [ "mx::sigproc::psdFilterTypes::arrayT< realT, rank >", "structmx_1_1sigproc_1_1psdFilterTypes_1_1arrayT.html", null ],
    [ "mx::astro::astroFilter< _units, _rsr >", "structmx_1_1astro_1_1astroFilter.html", null ],
    [ "mx::sigproc::autocorrelationFromPSD< T >", "structmx_1_1sigproc_1_1autocorrelationFromPSD.html", null ],
    [ "mx::sigproc::autocorrelationFromPSD< realT >", "structmx_1_1sigproc_1_1autocorrelationFromPSD.html", null ],
    [ "mx::sigproc::averagePeriodogram< realT >", "classmx_1_1sigproc_1_1averagePeriodogram.html", null ],
    [ "mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >", "structmx_1_1improc_1_1azBoxKernel.html", null ],
    [ "mx::astro::baseSpectrum< realT >", "structmx_1_1astro_1_1baseSpectrum.html", null ],
    [ "mx::astro::baseSpectrum< _spectrumT::units::realT >", "structmx_1_1astro_1_1baseSpectrum.html", [
      [ "mx::astro::astroSpectrum< _spectrumT, freq >", "structmx_1_1astro_1_1astroSpectrum.html", null ]
    ] ],
    [ "mx::astro::baseSpectrum< _units::realT >", "structmx_1_1astro_1_1baseSpectrum.html", [
      [ "mx::astro::cahoyGrid< _units >", "structmx_1_1astro_1_1cahoyGrid.html", null ]
    ] ],
    [ "mx::astro::basicSpectrum< _units >", "structmx_1_1astro_1_1basicSpectrum.html", null ],
    [ "mx::improc::bilinearTransform< _arithT >", "structmx_1_1improc_1_1bilinearTransform.html", null ],
    [ "mx::astro::blackbody< units, freq >", "structmx_1_1astro_1_1blackbody.html", null ],
    [ "mx::astro::cahoySpectrumRaw< _units >", "structmx_1_1astro_1_1cahoySpectrumRaw.html", null ],
    [ "mx::astro::calspecSpectrum< _units >", "structmx_1_1astro_1_1calspecSpectrum.html", null ],
    [ "mx::AO::sim::ccdDetector< _realT >", "classmx_1_1AO_1_1sim_1_1ccdDetector.html", null ],
    [ "mx::astro::units::cgs< _realT >", "structmx_1_1astro_1_1units_1_1cgs.html", null ],
    [ "mx::base::changeable< _derivedT >", "classmx_1_1base_1_1changeable.html", [
      [ "mx::AO::sim::turbAtmosphere< aoSystemT, verboseT >", "structmx_1_1AO_1_1sim_1_1turbAtmosphere.html", null ],
      [ "mx::AO::sim::turbAtmosphere< _aoSystemT, _verboseT >", "structmx_1_1AO_1_1sim_1_1turbAtmosphere.html", null ]
    ] ],
    [ "mx::base::changeable< turbAtmosphere< _aoSystemT, mx::verbose::d > >", "classmx_1_1base_1_1changeable.html", null ],
    [ "mx::base::changeable< turbAtmosphere< aoSystemT, verboseT > >", "classmx_1_1base_1_1changeable.html", null ],
    [ "mx::base::changeable< turbSubHarmonic< _turbAtmosphereT > >", "classmx_1_1base_1_1changeable.html", [
      [ "mx::AO::sim::turbSubHarmonic< _turbAtmosphereT, _verboseT >", "classmx_1_1AO_1_1sim_1_1turbSubHarmonic.html", null ]
    ] ],
    [ "mx::sigproc::circularBufferBase< _derivedT, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", null ],
    [ "mx::sigproc::circularBufferBase< circularBufferBranch< _storedT, _indexT >, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", [
      [ "mx::sigproc::circularBufferBranch< _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBranch.html", null ]
    ] ],
    [ "mx::sigproc::circularBufferBase< circularBufferIndex< _storedT, _indexT >, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", [
      [ "mx::sigproc::circularBufferIndex< _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferIndex.html", null ]
    ] ],
    [ "mx::sigproc::circularBufferBase< circularBufferMod< _storedT, _indexT >, _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferBase.html", [
      [ "mx::sigproc::circularBufferMod< _storedT, _indexT >", "classmx_1_1sigproc_1_1circularBufferMod.html", null ]
    ] ],
    [ "mx::AO::analysis::clAOLinearPredictor< _realT >", "structmx_1_1AO_1_1analysis_1_1clAOLinearPredictor.html", null ],
    [ "mx::AO::analysis::clGainOpt< _realT >", "structmx_1_1AO_1_1analysis_1_1clGainOpt.html", null ],
    [ "mx::AO::analysis::clGainOpt< realT >", "structmx_1_1AO_1_1analysis_1_1clGainOpt.html", null ],
    [ "mx::AO::analysis::clGainOptOptGain_OL< realT >", "structmx_1_1AO_1_1analysis_1_1clGainOptOptGain__OL.html", null ],
    [ "mx::app::clOptions", "structmx_1_1app_1_1clOptions.html", null ],
    [ "mx::app::configTarget", "structmx_1_1app_1_1configTarget.html", null ],
    [ "mx::improc::cubicConvolTransform< _arithT >", "structmx_1_1improc_1_1cubicConvolTransform.html", null ],
    [ "mx::math::degradT< degrad, realT >", "structmx_1_1math_1_1degradT.html", null ],
    [ "mx::math::degradT< degrees, _realT >", "structmx_1_1math_1_1degradT_3_01degrees_00_01__realT_01_4.html", null ],
    [ "mx::math::degradT< radians, _realT >", "structmx_1_1math_1_1degradT_3_01radians_00_01__realT_01_4.html", null ],
    [ "mx::AO::sim::directPhaseReconstructor< realT >", "classmx_1_1AO_1_1sim_1_1directPhaseReconstructor.html", null ],
    [ "mx::astro::units::earth< _realT >", "structmx_1_1astro_1_1units_1_1earth.html", null ],
    [ "mx::astro::earthAlbedo< _units >", "structmx_1_1astro_1_1earthAlbedo.html", null ],
    [ "mx::improc::eigenArrPlanes< arrT, isCube >", "structmx_1_1improc_1_1eigenArrPlanes.html", null ],
    [ "mx::improc::eigenCube< dataT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::improc::eigenCube< floatT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::improc::eigenCube< realT >", "classmx_1_1improc_1_1eigenCube.html", null ],
    [ "mx::math::fit::empirical2D_fitter< _realT >", "structmx_1_1math_1_1fit_1_1empirical2D__fitter.html", null ],
    [ "mx::exception< verboseT >", "classmx_1_1exception.html", null ],
    [ "mx::math::ft::fftT< _inputT, _outputT, _rank, 0 >", "classmx_1_1math_1_1ft_1_1fftT_3_01__inputT_00_01__outputT_00_01__rank_00_010_01_4.html", null ],
    [ "mx::math::ft::fftT< _inputT, _outputT, _rank, 1 >", "classmx_1_1math_1_1ft_1_1fftT_3_01__inputT_00_01__outputT_00_01__rank_00_011_01_4.html", null ],
    [ "mx::math::ft::fftwEnvironment< realT, threads >", "structmx_1_1math_1_1ft_1_1fftwEnvironment.html", null ],
    [ "mx::math::ft::fftwPlanSpec< realT >", "structmx_1_1math_1_1ft_1_1fftwPlanSpec.html", null ],
    [ "mx::math::ft::fftwPlanSpec< double >", "structmx_1_1math_1_1ft_1_1fftwPlanSpec_3_01double_01_4.html", null ],
    [ "mx::math::ft::fftwPlanSpec< float >", "structmx_1_1math_1_1ft_1_1fftwPlanSpec_3_01float_01_4.html", null ],
    [ "mx::math::ft::fftwPlanSpec< long double >", "structmx_1_1math_1_1ft_1_1fftwPlanSpec_3_01long_01double_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< _inputDataT, _outputDataT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec.html", null ],
    [ "mx::math::ft::fftwTypeSpec< complexDT, complexDT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01complexDT_00_01complexDT_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< complexDT, double >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01complexDT_00_01double_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< complexFT, complexFT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01complexFT_00_01complexFT_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< complexFT, float >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01complexFT_00_01float_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< complexLT, complexLT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01complexLT_00_01complexLT_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< complexLT, long double >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01complexLT_00_01long_01double_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< double, complexDT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01double_00_01complexDT_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< float, complexFT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01float_00_01complexFT_01_4.html", null ],
    [ "mx::math::ft::fftwTypeSpec< inputT, outputT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec.html", null ],
    [ "mx::math::ft::fftwTypeSpec< long double, complexLT >", "structmx_1_1math_1_1ft_1_1fftwTypeSpec_3_01long_01double_00_01complexLT_01_4.html", null ],
    [ "mx::math::fit::fitExpModGaussian_3param_fitter< _realT >", "structmx_1_1math_1_1fit_1_1fitExpModGaussian__3param__fitter.html", null ],
    [ "mx::math::fit::fitExpModGaussian_4param_fitter< _realT >", "structmx_1_1math_1_1fit_1_1fitExpModGaussian__4param__fitter.html", null ],
    [ "mx::fits::fitsFile< dataT, verboseT >", "classmx_1_1fits_1_1fitsFile.html", null ],
    [ "mx::fits::fitsHeader< verboseT >", "classmx_1_1fits_1_1fitsHeader.html", null ],
    [ "mx::fits::fitsHeaderCard< verboseT >", "classmx_1_1fits_1_1fitsHeaderCard.html", null ],
    [ "mx::fits::fitsHeaderCard< verbose::d >", "classmx_1_1fits_1_1fitsHeaderCard.html", null ],
    [ "mx::AO::analysis::fourierCovariance< realT, aosysT >", "structmx_1_1AO_1_1analysis_1_1fourierCovariance.html", null ],
    [ "mx::sigproc::fourierModeDef", "structmx_1_1sigproc_1_1fourierModeDef.html", null ],
    [ "mx::AO::analysis::fourierTemporalPSD< _realT, aosysT >", "structmx_1_1AO_1_1analysis_1_1fourierTemporalPSD.html", null ],
    [ "mx::wfp::fraunhoferPropagator< _wavefrontT, _cudaGPU >", "classmx_1_1wfp_1_1fraunhoferPropagator.html", null ],
    [ "mx::wfp::fraunhoferPropagator< complexFieldT >", "classmx_1_1wfp_1_1fraunhoferPropagator.html", null ],
    [ "mx::wfp::fraunhoferPropagator< complexFieldT, cudaGPU >", "classmx_1_1wfp_1_1fraunhoferPropagator.html", null ],
    [ "mx::math::fit::gammaDistribution_2param_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gammaDistribution__2param__fitter.html", null ],
    [ "mx::math::fit::gammaDistribution_3param_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gammaDistribution__3param__fitter.html", null ],
    [ "mx::math::fit::gammaDistribution_4param_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gammaDistribution__4param__fitter.html", null ],
    [ "mx::math::fit::gaussian1D_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gaussian1D__fitter.html", null ],
    [ "mx::math::fit::gaussian2D_gen_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gaussian2D__gen__fitter.html", null ],
    [ "mx::math::fit::gaussian2D_sym_fitter< _realT >", "structmx_1_1math_1_1fit_1_1gaussian2D__sym__fitter.html", null ],
    [ "mx::AO::sim::generalIntegrator< _realT >", "classmx_1_1AO_1_1sim_1_1generalIntegrator.html", null ],
    [ "mx::sys::gitRepo", "classmx_1_1sys_1_1gitRepo.html", null ],
    [ "mx::math::gnuPlot", "classmx_1_1math_1_1gnuPlot.html", null ],
    [ "mx::math::gsl_interp_linear< _realT >", "structmx_1_1math_1_1gsl__interp__linear.html", null ],
    [ "mx::math::gsl_interp_steffen< _realT >", "structmx_1_1math_1_1gsl__interp__steffen.html", null ],
    [ "mx::math::gslInterpolator< interpT >", "classmx_1_1math_1_1gslInterpolator.html", null ],
    [ "mx::math::gslInterpolator< mx::math::gsl_interp_linear< double > >", "classmx_1_1math_1_1gslInterpolator.html", null ],
    [ "mx::math::gslInterpolator< mx::math::gsl_interp_steffen< realT > >", "classmx_1_1math_1_1gslInterpolator.html", null ],
    [ "mx::math::fit::hasJacobian< T >", "structmx_1_1math_1_1fit_1_1hasJacobian.html", null ],
    [ "mx::math::histogramUniform< realT >", "classmx_1_1math_1_1histogramUniform.html", null ],
    [ "mx::wfp::idealCoronagraph< _realT >", "structmx_1_1wfp_1_1idealCoronagraph.html", null ],
    [ "mx::improc::imagePeakInterp< transformT >", "structmx_1_1improc_1_1imagePeakInterp.html", null ],
    [ "mx::improc::imageXCorrDiscrete< _ccImT >", "classmx_1_1improc_1_1imageXCorrDiscrete.html", null ],
    [ "mx::improc::imageXCorrFFT< _realImageT >", "classmx_1_1improc_1_1imageXCorrFFT.html", null ],
    [ "mx::improc::imCenterCircleSym< realT >", "structmx_1_1improc_1_1imCenterCircleSym.html", null ],
    [ "mx::improc::imCenterRadon< transformT >", "structmx_1_1improc_1_1imCenterRadon.html", null ],
    [ "mx::app::iniFile", "structmx_1_1app_1_1iniFile.html", null ],
    [ "mx::improc::is_eigenCube< T >", "structmx_1_1improc_1_1is__eigenCube.html", null ],
    [ "mx::wfp::is_imagingArray< T >", "structmx_1_1wfp_1_1is__imagingArray.html", null ],
    [ "mx::meta::is_std_vector< T, if_value_type >", "structmx_1_1meta_1_1is__std__vector.html", null ],
    [ "mx::meta::is_std_vector< T, false >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01false_01_4.html", null ],
    [ "mx::meta::is_std_vector< T, true >", "structmx_1_1meta_1_1is__std__vector_3_01T_00_01true_01_4.html", null ],
    [ "mx::astro::units::jupiter< _realT >", "structmx_1_1astro_1_1units_1_1jupiter.html", null ],
    [ "mx::math::laplace_distribution< _RealType >", "classmx_1_1math_1_1laplace__distribution.html", null ],
    [ "mx::AO::sim::leakyIntegrator< _realT >", "classmx_1_1AO_1_1sim_1_1leakyIntegrator.html", null ],
    [ "mx::math::fit::levmarInterface< fitterT >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", [
      [ "mx::math::fit::fitGaussian2D< realT >", "classmx_1_1math_1_1fit_1_1fitGaussian2D.html", null ],
      [ "mx::math::fit::fitGaussian2D< mx::math::fit::gaussian2D_gen_fitter< Scalar > >", "classmx_1_1math_1_1fit_1_1fitGaussian2D.html", null ],
      [ "mx::math::fit::fitGaussian2D< mx::math::fit::gaussian2D_gen_fitter< realT > >", "classmx_1_1math_1_1fit_1_1fitGaussian2D.html", null ],
      [ "mx::math::fit::fitAiry2D< fitterT >", "classmx_1_1math_1_1fit_1_1fitAiry2D.html", null ],
      [ "mx::math::fit::fitEmpirical2DGen< fitterT >", "classmx_1_1math_1_1fit_1_1fitEmpirical2DGen.html", null ],
      [ "mx::math::fit::fitExpModGaussian< fitterT >", "classmx_1_1math_1_1fit_1_1fitExpModGaussian.html", null ],
      [ "mx::math::fit::fitGammaDistribution< fitterT >", "classmx_1_1math_1_1fit_1_1fitGammaDistribution.html", null ],
      [ "mx::math::fit::fitGaussian2D< fitterT >", "classmx_1_1math_1_1fit_1_1fitGaussian2D.html", null ],
      [ "mx::math::fit::fitMoffat2D< fitterT >", "classmx_1_1math_1_1fit_1_1fitMoffat2D.html", null ],
      [ "mx::math::fit::fitWeibull< fitterT >", "classmx_1_1math_1_1fit_1_1fitWeibull.html", null ]
    ] ],
    [ "mx::math::fit::levmarInterface< gaussian1D_fitter< _realT > >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", [
      [ "mx::math::fit::fitGaussian1D< _realT >", "classmx_1_1math_1_1fit_1_1fitGaussian1D.html", null ]
    ] ],
    [ "mx::math::fit::levmarInterface< moffat1D_fitter< _realT > >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", [
      [ "mx::math::fit::fitMoffat1D< _realT >", "classmx_1_1math_1_1fit_1_1fitMoffat1D.html", null ]
    ] ],
    [ "mx::math::fit::levmarInterface< mx::math::fit::gaussian2D_gen_fitter< realT > >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", null ],
    [ "mx::math::fit::levmarInterface< mx::math::fit::gaussian2D_gen_fitter< Scalar > >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", null ],
    [ "mx::math::fit::levmarInterface< realT >", "classmx_1_1math_1_1fit_1_1levmarInterface.html", null ],
    [ "mx::sigproc::linearPredictor< _realT >", "structmx_1_1sigproc_1_1linearPredictor.html", null ],
    [ "mx::sigproc::linearPredictor< realT >", "structmx_1_1sigproc_1_1linearPredictor.html", null ],
    [ "mx::math::logInterpolator< interpT >", "classmx_1_1math_1_1logInterpolator.html", null ],
    [ "mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >", "structmx_1_1wfp_1_1lyotCoronagraph.html", null ],
    [ "mx::astro::mainSequence< realT >", "structmx_1_1astro_1_1mainSequence.html", null ],
    [ "mx::math::ft::mftT< _inputT, _outputT, _rank, 0 >", "classmx_1_1math_1_1ft_1_1mftT_3_01__inputT_00_01__outputT_00_01__rank_00_010_01_4.html", null ],
    [ "mx::math::fit::moffat1D_fitter< _realT >", "structmx_1_1math_1_1fit_1_1moffat1D__fitter.html", null ],
    [ "mx::math::fit::moffat2D_sym_fitter< _realT >", "structmx_1_1math_1_1fit_1_1moffat2D__sym__fitter.html", null ],
    [ "mx::err::mxException", "classmx_1_1err_1_1mxException.html", [
      [ "mx::err::allocerr", "classmx_1_1err_1_1allocerr.html", null ],
      [ "mx::err::exceptthrown", "classmx_1_1err_1_1exceptthrown.html", null ],
      [ "mx::err::filecerr", "classmx_1_1err_1_1filecerr.html", null ],
      [ "mx::err::fileoerr", "classmx_1_1err_1_1fileoerr.html", null ],
      [ "mx::err::filererr", "classmx_1_1err_1_1filererr.html", null ],
      [ "mx::err::filewerr", "classmx_1_1err_1_1filewerr.html", null ],
      [ "mx::err::invalidarg", "classmx_1_1err_1_1invalidarg.html", null ],
      [ "mx::err::invalidconfig", "classmx_1_1err_1_1invalidconfig.html", null ],
      [ "mx::err::liberr", "classmx_1_1err_1_1liberr.html", null ],
      [ "mx::err::notfound", "classmx_1_1err_1_1notfound.html", null ],
      [ "mx::err::notimpl", "classmx_1_1err_1_1notimpl.html", null ],
      [ "mx::err::paramnotset", "classmx_1_1err_1_1paramnotset.html", null ],
      [ "mx::err::sizeerr", "classmx_1_1err_1_1sizeerr.html", null ]
    ] ],
    [ "mx::verbose::o", "structmx_1_1verbose_1_1o.html", null ],
    [ "mx::ipc::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine, _time >", "classmx_1_1ipc_1_1ompLoopWatcher.html", null ],
    [ "mx::math::laplace_distribution< _RealType >::param_type", "structmx_1_1math_1_1laplace__distribution_1_1param__type.html", null ],
    [ "mx::astro::sqWaveFilter< _units, _rsr >::paramsT", "structmx_1_1astro_1_1sqWaveFilter_1_1paramsT.html", null ],
    [ "mx::astro::phoenixSpectrum< _units >", "structmx_1_1astro_1_1phoenixSpectrum.html", null ],
    [ "mx::astro::picklesSpectrum< _units >", "structmx_1_1astro_1_1picklesSpectrum.html", null ],
    [ "mx::math::point2D< _angleT >", "classmx_1_1math_1_1point2D.html", null ],
    [ "mx::improc::precalcKernel< kernelT >", "structmx_1_1improc_1_1precalcKernel.html", null ],
    [ "mx::sigproc::psdFilter< _realT, 1 >", "classmx_1_1sigproc_1_1psdFilter_3_01__realT_00_011_01_4.html", null ],
    [ "mx::sigproc::psdFilter< _realT, _rank, 0 >", "classmx_1_1sigproc_1_1psdFilter_3_01__realT_00_01__rank_00_010_01_4.html", null ],
    [ "mx::sigproc::psdVarMean< paramsT >", "structmx_1_1sigproc_1_1psdVarMean.html", null ],
    [ "mx::sigproc::psdVarMeanParams< _realT >", "structmx_1_1sigproc_1_1psdVarMeanParams.html", null ],
    [ "mx::AO::sim::pyramidSensor< _realT, _detectorT, _cudaGPU >", "classmx_1_1AO_1_1sim_1_1pyramidSensor.html", null ],
    [ "mx::AO::sim::pywfsSlopeReconstructor< _floatT >", "classmx_1_1AO_1_1sim_1_1pywfsSlopeReconstructor.html", null ],
    [ "mx::math::randomT< typeT, _ranengT, _randistT >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< int, std::mt19937_64, std::poisson_distribution< int > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< long, std::mt19937_64, std::poisson_distribution< long > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< realT >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< realT, std::mt19937_64, std::gamma_distribution< realT > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::math::randomT< realT, std::mt19937_64, std::normal_distribution< realT > >", "classmx_1_1math_1_1randomT.html", null ],
    [ "mx::ipc::sharedMemSegment", "classmx_1_1ipc_1_1sharedMemSegment.html", null ],
    [ "mx::astro::units::si< _realT >", "structmx_1_1astro_1_1units_1_1si.html", null ],
    [ "mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT, _coronT >", "classmx_1_1AO_1_1sim_1_1simulatedAOSystem.html", null ],
    [ "mx::ioutils::skipCol", "structmx_1_1ioutils_1_1skipCol.html", null ],
    [ "mx::astro::units::solar< _realT >", "structmx_1_1astro_1_1units_1_1solar.html", null ],
    [ "mx::improc::sourceFinder< _realT >", "classmx_1_1improc_1_1sourceFinder.html", null ],
    [ "mx::astro::sqWaveFilter< _units, _rsr >", "structmx_1_1astro_1_1sqWaveFilter.html", null ],
    [ "mx::math::syevrMem< floatT >", "structmx_1_1math_1_1syevrMem.html", null ],
    [ "mx::meta::tagT< T >", "structmx_1_1meta_1_1tagT.html", null ],
    [ "mx::ioutils::textTable", "structmx_1_1ioutils_1_1textTable.html", null ],
    [ "mx::meta::trueFalseT< trueFalse >", "structmx_1_1meta_1_1trueFalseT.html", null ],
    [ "mx::meta::trueFalseT< false >", "structmx_1_1meta_1_1trueFalseT_3_01false_01_4.html", null ],
    [ "mx::meta::trueFalseT< true >", "structmx_1_1meta_1_1trueFalseT_3_01true_01_4.html", [
      [ "mx::meta::has_value_type< T, void_t< typename T::value_type > >", "structmx_1_1meta_1_1has__value__type_3_01T_00_01void__t_3_01typename_01T_1_1value__type_01_4_01_4.html", null ]
    ] ],
    [ "mx::AO::sim::turbLayer< _aoSystemT, _verboseT >", "structmx_1_1AO_1_1sim_1_1turbLayer.html", null ],
    [ "mx::meta::typeDescription< T >", "structmx_1_1meta_1_1typeDescription.html", null ],
    [ "mx::verbose::v", "structmx_1_1verbose_1_1v.html", null ],
    [ "mx::fits::fitsHeaderCard< verboseT >::values", "unionmx_1_1fits_1_1fitsHeaderCard_1_1values.html", null ],
    [ "mx::astro::venusAlbedo< _units >", "structmx_1_1astro_1_1venusAlbedo.html", null ],
    [ "mx::AO::analysis::vonKarmanSpectrum< realT >", "structmx_1_1AO_1_1analysis_1_1vonKarmanSpectrum.html", null ],
    [ "mx::verbose::vv", "structmx_1_1verbose_1_1vv.html", null ],
    [ "mx::verbose::vvv", "structmx_1_1verbose_1_1vvv.html", null ],
    [ "mx::AO::sim::wavefront< _realT >", "structmx_1_1AO_1_1sim_1_1wavefront.html", null ],
    [ "mx::math::fit::weibull_2param_fitter< _realT >", "structmx_1_1math_1_1fit_1_1weibull__2param__fitter.html", null ],
    [ "mx::math::fit::weibull_3param_fitter< _realT >", "structmx_1_1math_1_1fit_1_1weibull__3param__fitter.html", null ],
    [ "mx::AO::analysis::wfs< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1wfs.html", [
      [ "mx::AO::analysis::calculatedWFS< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1calculatedWFS.html", null ],
      [ "mx::AO::analysis::pywfsModAsymptotic< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1pywfsModAsymptotic.html", null ],
      [ "mx::AO::analysis::pywfsUnmod< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1pywfsUnmod.html", null ],
      [ "mx::AO::analysis::shwfs< realT, iosT >", "structmx_1_1AO_1_1analysis_1_1shwfs.html", null ]
    ] ],
    [ "mx::AO::analysis::wfs< realT, std::ostream >", "structmx_1_1AO_1_1analysis_1_1wfs.html", null ],
    [ "mx::AO::analysis::zernikeCovariance< realT, aosysT >", "structmx_1_1AO_1_1analysis_1_1zernikeCovariance.html", null ],
    [ "mx::AO::analysis::zernikeTemporalPSD< _realT, aosysT >", "structmx_1_1AO_1_1analysis_1_1zernikeTemporalPSD.html", null ]
];