mxlib: /home/jrmales/Source/mxlib/tests/include/improc/imageTransforms_test.cpp File Reference
imageTransforms_test.cpp File Reference
#include "../../catch2/catch.hpp"
#include <vector>
#include <Eigen/Dense>
#include "../../../include/math/func/gaussian.hpp"
#include "../../../include/improc/imageUtils.hpp"
#include "../../../include/improc/eigenCube.hpp"
#include "../../../include/improc/imageTransforms.hpp"
#include "../../../include/math/fit/fitGaussian.hpp"
Functions
SCENARIO ("Verify direction and accuracy of various image shifts", "[improc::imageTransforms]")
Function Documentation
SCENARIO()
SCENARIO ("Verify direction and accuracy of various image shifts" , "" [improc::imageTransforms])
Scenario: Verify direction and accuracy of various image shifts
Tests image shifts by fractional pixels.
Definition at line 25 of file imageTransforms_test.cpp.
References mx::math::fit::fitGaussian2D< fitterT >::fit(), mx::improc::imageShift(), mx::math::fit::fitGaussian2D< fitterT >::setArray(), mx::math::fit::fitGaussian2D< fitterT >::setGuess(), mx::math::fit::fitGaussian2D< fitterT >::x0(), and mx::math::fit::fitGaussian2D< fitterT >::y0().