mxlib: ao/analysis/jincFuncs.hpp File Reference
jincFuncs.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
The +/- Jinc functions for analyzing contrast.
The +/- Jinc functions for analyzing contrast.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file jincFuncs.hpp.
#include "../../math/constants.hpp"
#include "../../math/func/jinc.hpp"
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename realT >
int mx::AO::analysis::jincFuncs (realT &Jp, realT &Jm, int mpos, int npos, int mmode, int nmode)
The +/- Jinc functions for analyzing contrast.
Function Documentation
jincFuncs()
template<typename realT > int mx::AO::analysis::jincFuncs (realT & Jp, realT & Jm, int mpos, int npos, int mmode, int nmode)
The +/- Jinc functions for analyzing contrast.
See Males and Guyon
Parameters
[out] Jp
[out] Jm
[in] mpos
[in] npos
[in] mmode
[in] nmode
Definition at line 26 of file jincFuncs.hpp.
References mx::math::func::jinc(), mx::AO::analysis::jincFuncs(), and mx::math::six_fifths().
Referenced by mx::AO::analysis::jincFuncs().