mxlib: mx::improc::HCI Namespace Reference
mx::improc::HCI Namespace Reference
Astronomy | Image Processing » High Contrast Imaging » HCI Enums
Namespace for high contrast imaging enums.
Namespace for high contrast imaging enums.
Enumerations
enum fakeMethods { single, list }
Fake injection PSF file specification methods.
enum combineMethods { noCombine, medianCombine, meanCombine, sigmaMeanCombine }
Possible combination methods.
enum meansubMethods {
imageMean, imageMedian, imageMode, meanImage,
medianImage
}
Mean subtraction methods.
enum excludeMethods { excludeNone, excludePixel, excludeAngle, excludeImno }
Image exclusion methods.
enum includeMethods {
includeAll, includeCorr, includeTime, includeAngle,
includeImno
}
Image inclusion methods.
Functions
std::string fakeMethodsStr (int method)
Get the string name of a fake injection method.
int fakeMethodFmStr (const std::string &method)
Get the fake injection method from its string name.
std::string combineMethodStr (int method)
Get the string name of the combineMethod integer.
int combineMethodFmStr (const std::string &method)
Get the combineMethod from the corresponding string name.
Function Documentation
combineMethodFmStr()
int mx::improc::HCI::combineMethodFmStr (const std::string & method)
Get the combineMethod from the corresponding string name.
Returns
the combineMethods enum member corresponding to the string name.
Parameters
[in] method [in] the string name of the combineMethod
Definition at line 28 of file HCIobservation.cpp.
References meanCombine, medianCombine, noCombine, and sigmaMeanCombine.
Referenced by mx::improc::HCIobservation< _realT >::readPSFSub().
combineMethodStr()
std::string mx::improc::HCI::combineMethodStr (int method)
Get the string name of the combineMethod integer.
Returns
a string with the name of the combineMethod
Parameters
[in] method [in] one of the combineMethods enum members
Definition at line 19 of file HCIobservation.cpp.
References meanCombine, medianCombine, noCombine, and sigmaMeanCombine.
Referenced by mx::improc::HCIobservation< _realT >::stdFitsHeader(), and mx::improc::HCIobservation< _realT >::writeFinim().
fakeMethodFmStr()
int mx::improc::HCI::fakeMethodFmStr (const std::string & method)
Get the fake injection method from its string name.
Returns
the corresponding member of the fakeMethods enum
Parameters
[in] method [in] the fake injection method name
Definition at line 27 of file ADIobservation.cpp.
References list, and single.
fakeMethodsStr()
std::string mx::improc::HCI::fakeMethodsStr (int method)
Get the string name of a fake injection method.
Returns
the string name corresponding to the fake injection method
Parameters
[in] method [in] the fake injection method
Definition at line 20 of file ADIobservation.cpp.
References list, and single.