mxlib: sigproc/psdVarMean.hpp File Reference
psdVarMean.hpp File Reference
Signal Processing » Signal Processing Files
Tools for calculating the variance of the mean of a PSD.
Tools for calculating the variance of the mean of a PSD.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file psdVarMean.hpp.
#include <vector>
#include <gsl/gsl_integration.h>
#include <gsl/gsl_errno.h>
#include "../math/func/bessel.hpp"
#include "../math/constants.hpp"
#include "../math/gslInterpolator.hpp"
#include "psdFilter.hpp"
Classes
struct mx::sigproc::psdVarMeanParams< _realT >
Parameters for calculating the variance of the mean from a numerical PSD.
struct mx::sigproc::psdVarMean< paramsT >
Calculate the variance of the mean for a process given its PSD.
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename paramsT >
paramsT::realT mx::sigproc::psdVarMeanFunc (typename paramsT::realT k, void *params)
Integration worker function for psdVarMean::operator()
Function Documentation
psdVarMeanFunc()
template<typename paramsT > paramsT::realT mx::sigproc::psdVarMeanFunc (typename paramsT::realT k, void * params)
Integration worker function for psdVarMean::operator()
Template Parameters
paramsT the type of the parameter structure. See psdVarMean.
Returns
the value of the integrand at k
Parameters
[in] k the scaled frequency coordinate
[in] params pointer to the parameter structure
Definition at line 137 of file psdVarMean.hpp.
References mx::sigproc::psdVarMeanFunc(), and mx::math::six_fifths().
Referenced by mx::sigproc::psdVarMeanFunc().