mxlib: math/roots.hpp File Reference
roots.hpp File Reference
General Mathematics » Gen. Math Files
Declares and defines functions for finding roots.
Declares and defines functions for finding roots.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file roots.hpp.
#include <vector>
#include <complex>
#include <cmath>
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename realT >
realT mx::math::cubicDescriminant (const realT &a, const realT &b, const realT &c, const realT &d)
Calculate the descriminant for the general cubic.
template<typename realT >
realT mx::math::cubicDescriminant (const realT &p, const realT &q)
Calculate the descriminant for the depressed cubic.
template<typename realT >
void mx::math::cubicDepressed (realT &p, realT &q, const realT &a, const realT &b, const realT &c, const realT &d)
Convert a general cubic equation to depressed form.
template<typename realT >
realT mx::math::cubicRealRoot (const realT &p, const realT &q)
Calculate the real root for a depressed cubic with negative descriminant.
template<typename realT >
void mx::math::quarticRoots (std::vector< std::complex< realT > > &x, realT a, realT b, realT c, realT d, realT e)
Find the roots of the general quartic equation.
Function Documentation
cubicDepressed()
template<typename realT > void mx::math::cubicDepressed (realT & p, realT & q, const realT & a, const realT & b, const realT & c, const realT & d)
Convert a general cubic equation to depressed form.
The general cubic is
\[ ax^3 + bx^2 + cx + d = 0 \]
which can be converted to compressed form
\[ t^3 + pt + q = 0 \]
Parameters
[out] p the 1st order coefficient of the depressed cubic
[out] q the 0th order coefficient of the depressed cubic
[in] a the 3rd order coefficient of the general cubic
[in] b the 2nd order coefficient of the general cubic
[in] c the 1st order coefficient of the general cubic
[in] d the 0th order coefficient of the general cubic
Definition at line 77 of file roots.hpp.
References mx::math::cubicDepressed(), and mx::math::six_fifths().
Referenced by mx::math::cubicDepressed().
cubicDescriminant() [1/2]
template<typename realT > realT mx::math::cubicDescriminant (const realT & a, const realT & b, const realT & c, const realT & d)
Calculate the descriminant for the general cubic.
Returns
the descriminant
Parameters
[in] a the 3rd order coefficient of the general cubic
[in] b the 2nd order coefficient of the general cubic
[in] c the 1st order coefficient of the general cubic
[in] d the 0th order coefficient of the general cubic
Definition at line 44 of file roots.hpp.
References mx::math::cubicDescriminant().
Referenced by mx::math::cubicDescriminant(), and mx::math::cubicDescriminant().
cubicDescriminant() [2/2]
template<typename realT > realT mx::math::cubicDescriminant (const realT & p, const realT & q)
Calculate the descriminant for the depressed cubic.
Returns
the descriminant
Parameters
[in] p the 0th order coefficient of the depressed cubic
[in] q the 0th order coefficient of the depressed cubic
Definition at line 58 of file roots.hpp.
References mx::math::cubicDescriminant(), and mx::math::six_fifths().
cubicRealRoot()
template<typename realT > realT mx::math::cubicRealRoot (const realT & p, const realT & q)
Calculate the real root for a depressed cubic with negative descriminant.
Returns
the real root for a depressed cubic defined by p and q
Exceptions
std::runtime_error if there are 3 real roots
Parameters
[in] p the 1st order coefficient of the depressed cubic
[in] q the 0th order coefficient of the depressed cubic
Definition at line 97 of file roots.hpp.
References mx::math::cubicRealRoot(), and mx::math::six_fifths().
Referenced by mx::math::cubicRealRoot().