mxlib: astro/stars.hpp File Reference
stars.hpp File Reference
Astronomy » Astronomy Files
Various utilities related to stars.
Various utilities related to stars.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file stars.hpp.
#include "../math/gslInterpolator.hpp"
#include "units.hpp"
#include "../ioutils/stringUtils.hpp"
#include "../ioutils/readColumns.hpp"
#include "mamajek.inc"
Classes
struct mx::astro::mainSequence< realT >
Provide various characteristics of main sequence stars according to their spectral type.
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename realT = float>
realT mx::astro::numSpType (std::string spType)
Parse a main sequence spectral type string into a numeric code.
void mx::astro::maintenance::makeMSTable (const std::string &fn)
Read in the main sequence table of Mamajek, and construct the vectors for input into the mainSequence class.
Function Documentation
makeMSTable()
void mx::astro::maintenance::makeMSTable (const std::string & fn)
Read in the main sequence table of Mamajek, and construct the vectors for input into the mainSequence class.
This is used to create mamajek.inc. The table should be copied to a text file, and all ... replaced with -99, then any remaining . replaced with space.
Definition at line 489 of file stars.hpp.
References mx::astro::maintenance::makeMSTable(), mx::astro::numSpType(), and mx::ioutils::readColumns().
Referenced by mx::astro::maintenance::makeMSTable().