mxlib: mx::math::fit::array2FitGaussian1D< realT > Struct Template Reference
mx::math::fit::array2FitGaussian1D< realT > Struct Template Reference
General Mathematics » Data Fitting » Peak Fitting » Gaussians
template<typename realT>
struct mx::math::fit::array2FitGaussian1D< realT >
Wrapper for a native array to pass to levmarInterface, with !D Gaussian details.
Supports fixing G0, G, x0, and sigma independently.
Definition at line 45 of file array2FitGaussian1D.hpp.
#include <math/fit/array2FitGaussian1D.hpp>
Public Member Functions
void setFixed (bool G0, bool G, bool x0, bool sigma)
Set whether each parameter is fixed.
Public Attributes
realT * m_data {nullptr}
///< Pointer to the array of y values
realT * m_coords {nullptr}
Pointer to the array of x values (optional)
size_t m_nx {0}
X dimension of the array.
realT * m_mask {nullptr}
Pointer to the (optional) mask array. Any 0 pixels are excluded from the fit.
Member Function Documentation
setFixed()
template<typename realT > void mx::math::fit::array2FitGaussian1D< realT >::setFixed (bool G0, bool G, bool x0, bool sigma)
Set whether each parameter is fixed.
Sets the parameter indices appropriately.
Definition at line 104 of file array2FitGaussian1D.hpp.
References mx::astro::constants::G(), and mx::astro::constants::sigma().
Referenced by mx::math::fit::fitGaussian1D< _realT >::setFixed().
Member Data Documentation
m_coords
template<typename realT > realT* mx::math::fit::array2FitGaussian1D< realT >::m_coords {nullptr}
Pointer to the array of x values (optional)
Definition at line 48 of file array2FitGaussian1D.hpp.
Referenced by mx::math::fit::fitGaussian1D< _realT >::setArray().
m_data
template<typename realT > realT* mx::math::fit::array2FitGaussian1D< realT >::m_data {nullptr}
///< Pointer to the array of y values
Definition at line 47 of file array2FitGaussian1D.hpp.
Referenced by mx::math::fit::fitGaussian1D< _realT >::setArray().
m_mask
template<typename realT > realT* mx::math::fit::array2FitGaussian1D< realT >::m_mask {nullptr}
Pointer to the (optional) mask array. Any 0 pixels are excluded from the fit.
Definition at line 51 of file array2FitGaussian1D.hpp.
m_nx
template<typename realT > size_t mx::math::fit::array2FitGaussian1D< realT >::m_nx {0}
X dimension of the array.
Definition at line 49 of file array2FitGaussian1D.hpp.
Referenced by mx::math::fit::fitGaussian1D< _realT >::setArray().
The documentation for this struct was generated from the following file:
math/fit/array2FitGaussian1D.hpp