mxlib: mx::AO::analysis::pywfsModAsymptotic< realT, iosT > Struct Template Reference
mx::AO::analysis::pywfsModAsymptotic< realT, iosT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename realT, typename iosT = std::ostream>
struct mx::AO::analysis::pywfsModAsymptotic< realT, iosT >
The asymptotic modulated pyramid wavefront sensor sensitivity function.
Provides the \(\beta_p \) parameter of Guyon, 2005 [8] for the modulated PyWFS in the asymptotic limit.
Template Parameters
realT is the floating point type used for calculations
iosT is an output stream type with operator << defined (default is std::ostream)
Definition at line 169 of file aoWFS.hpp.
#include <ao/analysis/aoWFS.hpp>
Public Member Functions
virtual realT beta_p (int m, int n, realT D, realT d, realT r0)
Get the photon sensitivity at a spatial frequency.
virtual realT beta_r (int m, int n, realT D, realT d, realT r0)
Get the read noise sensitivity at a spatial frequency.
Public Member Functions inherited from mx::AO::analysis::wfs< realT, iosT >
wfs ()
Constructor.
virtual ~wfs ()
Destructor.
virtual iosT & dumpWFS (iosT &ios)
Dump the details of the WFS to an io stream.
Member Function Documentation
beta_p()
template<typename realT , typename iosT = std::ostream> virtual realT mx::AO::analysis::pywfsModAsymptotic< realT, iosT >::beta_p (int m, int n, realT D, realT d, realT r0) inline virtual
Get the photon sensitivity at a spatial frequency.
The photon noise sensitivity of the asymptotic modulated PyWFS is \(2 \sqrt{2} \) at all k.
Returns
the sensitivity to photon noise parameter
Parameters
[in] m the spatial frequency index for u (not used by this WFS)
[in] n the spatial frequency index for v (not used by this WFS)
[in] D the telescope diameter (not used by this WFS)
[in] d the sub-ap spacing (not used by this WFS)
[in] r0 Fried's parameter (not used by this WFS)
Reimplemented from mx::AO::analysis::wfs< realT, iosT >.
Definition at line 181 of file aoWFS.hpp.
References mx::math::six_fifths().
Referenced by mx::AO::analysis::pywfsModAsymptotic< realT, iosT >::beta_r().
beta_r()
template<typename realT , typename iosT = std::ostream> virtual realT mx::AO::analysis::pywfsModAsymptotic< realT, iosT >::beta_r (int m, int n, realT D, realT d, realT r0) inline virtual
Get the read noise sensitivity at a spatial frequency.
Here we assume beta_r is the same as beta_p
Returns
the sensitivity to read noise parameter
Parameters
[in] m the spatial frequency index for u (not used by this WFS)
[in] n the spatial frequency index for v (not used by this WFS)
[in] D the telescope diameter (not used by this WFS)
[in] d the sub-ap spacing (not used by this WFS)
[in] r0 Fried's parameter (not used by this WFS)
Reimplemented from mx::AO::analysis::wfs< realT, iosT >.
Definition at line 203 of file aoWFS.hpp.
References mx::AO::analysis::pywfsModAsymptotic< realT, iosT >::beta_p().
The documentation for this struct was generated from the following file:
ao/analysis/aoWFS.hpp