mxlib: mx::astro::mainSequence< realT > Struct Template Reference
mx::astro::mainSequence< realT > Struct Template Reference
Astronomy » Stars
template<typename realT>
struct mx::astro::mainSequence< realT >
Provide various characteristics of main sequence stars according to their spectral type.
Interpolates on "A Modern Mean Dwarf Stellar Color and Effective Temperature Sequence" by Eric Mamajek, available at http://www.pas.rochester.edu/~emamajek/EEM_dwarf_UBVIJHK_colors_Teff.txt.
Loads values of the sequence at construction (hard coded), and then provides interpolation in between the points.
Version of the sequence used: 2017.03.14
Definition at line 110 of file stars.hpp.
#include <astro/stars.hpp>
Public Member Functions
realT Teff (realT numType)
Get the interpolated effective temperature.
realT Teff (const std::string &spType)
Get the interpolated effective temperature.
realT radius (realT numType)
Get the interpolated radius.
realT radius (const std::string &spType)
Get the interpolated radius.
realT logL (realT numType)
Get the interpolated log of luminosity.
realT logL (const std::string &spType)
Get the interpolated log of luminosity.
realT Mv (realT numType)
Get the interpolated absolute V magnitude.
realT Mv (const std::string &spType)
Get the interpolated absolute V magnitude.
realT V_Rc (realT numType)
Get the interpolated absolute V-Rc color.
realT V_Rc (const std::string &spType)
Get the interpolated absolute V-Rc color.
realT V_Ic (realT numType)
Get the interpolated absolute V-Ic color.
realT V_Ic (const std::string &spType)
Get the interpolated absolute V-Ic color.
realT V_Ks (realT numType)
Get the interpolated absolute V-Ks color.
realT V_Ks (const std::string &spType)
Get the interpolated absolute V-Ks color.
realT J_H (realT numType)
Get the interpolated absolute J-H color.
realT J_H (const std::string &spType)
Get the interpolated absolute J-H color.
realT H_Ks (realT numType)
Get the interpolated absolute H-Ks color.
realT H_Ks (const std::string &spType)
Get the interpolated absolute H-Ks color.
Public Attributes
std::vector< double > m_numTypes
The numeric spectral type codes from the sequence.
std::vector< double > m_numTypesR
The numeric spectral type codes from the sequence, in reversed order.
std::vector< double > m_Teffs
The effective temperatures from the sequence.
std::vector< double > m_TeffsR
The effective temperatures from the sequence, reveresed order.
std::vector< double > m_logLs
The log10 luminosities from the sequence.
std::vector< double > m_rads
The radii from the sequence.
std::vector< double > m_masses
The masses from the sequence.
std::vector< double > m_Mvs
The absolute V magnitudes from the sequence.
std::vector< double > m_V_Rcs
The V-Rc colors from the sequence.
std::vector< double > m_V_Ics
The V-Ic colors from the sequence.
std::vector< double > m_V_Kss
The V-Ks colors from the sequence.
std::vector< double > m_J_Hs
The J-H colors from the sequence.
std::vector< double > m_H_Kss
The H-Ks colors from the sequence.
math::gslInterpolator< math::gsl_interp_linear< double > > interpT
The interpolator for effective Temperature.
double m_minT
The minimum numeric spectral type for effective Temperature.
double m_maxT
The maximum numeric spectral type for effective Temperature.
math::gslInterpolator< math::gsl_interp_linear< double > > interpRad
The interpolator for effective Temperature.
double m_minRad
The minimum numeric spectral type for effective Temperature.
double m_maxRad
The maximum numeric spectral type for effective Temperature.
math::gslInterpolator< math::gsl_interp_linear< double > > interpL
The interpolator for log luminosity.
double m_minL
The minimum numeric spectral type for log luminosity.
double m_maxL
The maximum numeric spectral type for log luminosity.
math::gslInterpolator< math::gsl_interp_linear< double > > interpMv
The interpolator for absolute V magnitude.
double m_minMv
The minimum numeric spectral type for absolute V magnitude.
double m_maxMv
The maximum numeric spectral type for absolute V magnitude.
math::gslInterpolator< math::gsl_interp_linear< double > > interpVRc
The interpolator for V-Rc color.
double m_minVRc
The minimum numeric spectral type for V-Rc color.
double m_maxVRc
The maximum numeric spectral type for V-Rc color.
math::gslInterpolator< math::gsl_interp_linear< double > > interpVIc
The interpolator for V-Ic color.
double m_minVIc
The minimum numeric spectral type for V-Ic color.
double m_maxVIc
The maximum numeric spectral type for V-Ic color.
math::gslInterpolator< math::gsl_interp_linear< double > > interpVKs
The interpolator for V-Ks color.
double m_minVKs
The minimum numeric spectral type for V-Ks color.
double m_maxVKs
The maximum numeric spectral type for V-Ks color.
math::gslInterpolator< math::gsl_interp_linear< double > > interpJH
The interpolator for J-H color.
double m_minJH
The minimum numeric spectral type for J-H color.
double m_maxJH
The maximum numeric spectral type for J-H color.
math::gslInterpolator< math::gsl_interp_linear< double > > interpHKs
The interpolator for H-Ks color.
double m_minHKs
The minimum numeric spectral type for H-Ks color.
double m_maxHKs
The maximum numeric spectral type for H-Ks color.
math::gslInterpolator< math::gsl_interp_linear< double > > interpSpTfmT
The interpolator for effective Temperature.
double m_minSpTfmT
The minimum numeric spectral type for effective Temperature.
double m_maxSpTfmT
The maximum numeric spectral type for effective Temperature.
Member Function Documentation
H_Ks() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::H_Ks (const std::string & spType) inline
Get the interpolated absolute H-Ks color.
Returns
the aboslute H-Ks color
-999 if the input type is out of range.
Get the interpolated absolute H-Ks color
Returns
the aboslute H-Ks color
-999 if the input type code is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 462 of file stars.hpp.
References mx::astro::mainSequence< realT >::H_Ks(), and mx::astro::numSpType().
H_Ks() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::H_Ks (realT numType) inline
Get the interpolated absolute H-Ks color.
Returns
the aboslute H-Ks color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 447 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpHKs, and mx::astro::mainSequence< realT >::m_maxHKs.
Referenced by mx::astro::mainSequence< realT >::H_Ks().
J_H() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::J_H (const std::string & spType) inline
Get the interpolated absolute J-H color.
Returns
the aboslute J-H color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 437 of file stars.hpp.
References mx::astro::mainSequence< realT >::J_H(), and mx::astro::numSpType().
J_H() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::J_H (realT numType) inline
Get the interpolated absolute J-H color.
Returns
the aboslute J-H color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 422 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpJH, and mx::astro::mainSequence< realT >::m_maxJH.
Referenced by mx::astro::mainSequence< realT >::J_H().
logL() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::logL (const std::string & spType) inline
Get the interpolated log of luminosity.
Returns
the log of luminosity.
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 312 of file stars.hpp.
References mx::astro::mainSequence< realT >::logL(), and mx::astro::numSpType().
logL() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::logL (realT numType) inline
Get the interpolated log of luminosity.
Returns
the log of luminosity.
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 297 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpL, and mx::astro::mainSequence< realT >::m_maxL.
Referenced by mx::astro::mainSequence< realT >::logL().
Mv() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::Mv (const std::string & spType) inline
Get the interpolated absolute V magnitude.
Returns
the aboslute V magnitude
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 337 of file stars.hpp.
References mx::astro::mainSequence< realT >::Mv(), and mx::astro::numSpType().
Mv() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::Mv (realT numType) inline
Get the interpolated absolute V magnitude.
Returns
the aboslute V magnitude
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 322 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpMv, and mx::astro::mainSequence< realT >::m_maxMv.
Referenced by mx::astro::mainSequence< realT >::Mv().
radius() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::radius (const std::string & spType) inline
Get the interpolated radius.
Returns
the radius in Solar units.
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 287 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::radius().
radius() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::radius (realT numType) inline
Get the interpolated radius.
Returns
the radius in Solar units.
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 272 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpRad, and mx::astro::mainSequence< realT >::m_maxRad.
Referenced by mx::astro::mainSequence< realT >::radius().
Teff() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::Teff (const std::string & spType) inline
Get the interpolated effective temperature.
Returns
the effective temperature.
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 262 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::Teff().
Teff() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::Teff (realT numType) inline
Get the interpolated effective temperature.
Returns
the effective temperature.
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 247 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpT, and mx::astro::mainSequence< realT >::m_maxT.
Referenced by mx::astro::mainSequence< realT >::Teff().
V_Ic() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ic (const std::string & spType) inline
Get the interpolated absolute V-Ic color.
Returns
the aboslute V-Ic color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 387 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::V_Ic().
V_Ic() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ic (realT numType) inline
Get the interpolated absolute V-Ic color.
Returns
the aboslute V-Ic color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 372 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpVIc, and mx::astro::mainSequence< realT >::m_maxVIc.
Referenced by mx::astro::mainSequence< realT >::V_Ic().
V_Ks() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ks (const std::string & spType) inline
Get the interpolated absolute V-Ks color.
Returns
the aboslute V-Ks color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 412 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::V_Ks().
V_Ks() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ks (realT numType) inline
Get the interpolated absolute V-Ks color.
Returns
the aboslute V-Ks color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 397 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpVKs, and mx::astro::mainSequence< realT >::m_maxVKs.
Referenced by mx::astro::mainSequence< realT >::V_Ks().
V_Rc() [1/2]
template<typename realT > realT mx::astro::mainSequence< realT >::V_Rc (const std::string & spType) inline
Get the interpolated absolute V-Rc color.
Returns
the aboslute V-Rc color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 362 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::V_Rc().
V_Rc() [2/2]
template<typename realT > realT mx::astro::mainSequence< realT >::V_Rc (realT numType) inline
Get the interpolated absolute V-Rc color.
Returns
the aboslute V-Rc color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 347 of file stars.hpp.
References mx::astro::mainSequence< realT >::interpVRc, and mx::astro::mainSequence< realT >::m_maxVRc.
Referenced by mx::astro::mainSequence< realT >::V_Rc().
Member Data Documentation
interpHKs
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpHKs
The interpolator for H-Ks color.
Definition at line 160 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::H_Ks().
interpJH
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpJH
The interpolator for J-H color.
Definition at line 156 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::J_H().
interpL
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpL
The interpolator for log luminosity.
Definition at line 136 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::logL().
interpMv
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpMv
The interpolator for absolute V magnitude.
Definition at line 140 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::Mv().
interpRad
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpRad
The interpolator for effective Temperature.
Definition at line 132 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::radius().
interpSpTfmT
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpSpTfmT
The interpolator for effective Temperature.
Definition at line 164 of file stars.hpp.
interpT
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpT
The interpolator for effective Temperature.
Definition at line 128 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::Teff().
interpVIc
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpVIc
The interpolator for V-Ic color.
Definition at line 148 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Ic().
interpVKs
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpVKs
The interpolator for V-Ks color.
Definition at line 152 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Ks().
interpVRc
template<typename realT > math::gslInterpolator<math::gsl_interp_linear<double> > mx::astro::mainSequence< realT >::interpVRc
The interpolator for V-Rc color.
Definition at line 144 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Rc().
m_H_Kss
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_H_Kss
The H-Ks colors from the sequence.
Definition at line 126 of file stars.hpp.
m_J_Hs
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_J_Hs
The J-H colors from the sequence.
Definition at line 125 of file stars.hpp.
m_logLs
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_logLs
The log10 luminosities from the sequence.
Definition at line 118 of file stars.hpp.
m_masses
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_masses
The masses from the sequence.
Definition at line 120 of file stars.hpp.
m_maxHKs
template<typename realT > double mx::astro::mainSequence< realT >::m_maxHKs
The maximum numeric spectral type for H-Ks color.
Definition at line 162 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::H_Ks().
m_maxJH
template<typename realT > double mx::astro::mainSequence< realT >::m_maxJH
The maximum numeric spectral type for J-H color.
Definition at line 158 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::J_H().
m_maxL
template<typename realT > double mx::astro::mainSequence< realT >::m_maxL
The maximum numeric spectral type for log luminosity.
Definition at line 138 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::logL().
m_maxMv
template<typename realT > double mx::astro::mainSequence< realT >::m_maxMv
The maximum numeric spectral type for absolute V magnitude.
Definition at line 142 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::Mv().
m_maxRad
template<typename realT > double mx::astro::mainSequence< realT >::m_maxRad
The maximum numeric spectral type for effective Temperature.
Definition at line 134 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::radius().
m_maxSpTfmT
template<typename realT > double mx::astro::mainSequence< realT >::m_maxSpTfmT
The maximum numeric spectral type for effective Temperature.
Definition at line 166 of file stars.hpp.
m_maxT
template<typename realT > double mx::astro::mainSequence< realT >::m_maxT
The maximum numeric spectral type for effective Temperature.
Definition at line 130 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::Teff().
m_maxVIc
template<typename realT > double mx::astro::mainSequence< realT >::m_maxVIc
The maximum numeric spectral type for V-Ic color.
Definition at line 150 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Ic().
m_maxVKs
template<typename realT > double mx::astro::mainSequence< realT >::m_maxVKs
The maximum numeric spectral type for V-Ks color.
Definition at line 154 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Ks().
m_maxVRc
template<typename realT > double mx::astro::mainSequence< realT >::m_maxVRc
The maximum numeric spectral type for V-Rc color.
Definition at line 146 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Rc().
m_minHKs
template<typename realT > double mx::astro::mainSequence< realT >::m_minHKs
The minimum numeric spectral type for H-Ks color.
Definition at line 161 of file stars.hpp.
m_minJH
template<typename realT > double mx::astro::mainSequence< realT >::m_minJH
The minimum numeric spectral type for J-H color.
Definition at line 157 of file stars.hpp.
m_minL
template<typename realT > double mx::astro::mainSequence< realT >::m_minL
The minimum numeric spectral type for log luminosity.
Definition at line 137 of file stars.hpp.
m_minMv
template<typename realT > double mx::astro::mainSequence< realT >::m_minMv
The minimum numeric spectral type for absolute V magnitude.
Definition at line 141 of file stars.hpp.
m_minRad
template<typename realT > double mx::astro::mainSequence< realT >::m_minRad
The minimum numeric spectral type for effective Temperature.
Definition at line 133 of file stars.hpp.
m_minSpTfmT
template<typename realT > double mx::astro::mainSequence< realT >::m_minSpTfmT
The minimum numeric spectral type for effective Temperature.
Definition at line 165 of file stars.hpp.
m_minT
template<typename realT > double mx::astro::mainSequence< realT >::m_minT
The minimum numeric spectral type for effective Temperature.
Definition at line 129 of file stars.hpp.
m_minVIc
template<typename realT > double mx::astro::mainSequence< realT >::m_minVIc
The minimum numeric spectral type for V-Ic color.
Definition at line 149 of file stars.hpp.
m_minVKs
template<typename realT > double mx::astro::mainSequence< realT >::m_minVKs
The minimum numeric spectral type for V-Ks color.
Definition at line 153 of file stars.hpp.
m_minVRc
template<typename realT > double mx::astro::mainSequence< realT >::m_minVRc
The minimum numeric spectral type for V-Rc color.
Definition at line 145 of file stars.hpp.
m_Mvs
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_Mvs
The absolute V magnitudes from the sequence.
Definition at line 121 of file stars.hpp.
m_numTypes
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_numTypes
The numeric spectral type codes from the sequence.
Definition at line 112 of file stars.hpp.
m_numTypesR
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_numTypesR
The numeric spectral type codes from the sequence, in reversed order.
Definition at line 113 of file stars.hpp.
m_rads
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_rads
The radii from the sequence.
Definition at line 119 of file stars.hpp.
m_Teffs
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_Teffs
The effective temperatures from the sequence.
Definition at line 115 of file stars.hpp.
m_TeffsR
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_TeffsR
The effective temperatures from the sequence, reveresed order.
Definition at line 116 of file stars.hpp.
m_V_Ics
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_V_Ics
The V-Ic colors from the sequence.
Definition at line 123 of file stars.hpp.
m_V_Kss
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_V_Kss
The V-Ks colors from the sequence.
Definition at line 124 of file stars.hpp.
m_V_Rcs
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::m_V_Rcs
The V-Rc colors from the sequence.
Definition at line 122 of file stars.hpp.
The documentation for this struct was generated from the following file:
astro/stars.hpp