mxlib: mx::AO::analysis::wfs< realT, iosT > Struct Template Reference
mx::AO::analysis::wfs< realT, iosT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename realT, typename iosT = std::ostream>
struct mx::AO::analysis::wfs< realT, iosT >
The ideal wavefront sensor sensitivity function.
Provides the \(\beta_p \) parameter of Guyon, 2005 [8] for the ideal WFS.
This is the base class for all WFS.
Template Parameters
realT is the floating point type used for calculations
iosT is an output stream type with operator << defined (default is std::ostream)
Definition at line 35 of file aoWFS.hpp.
#include <ao/analysis/aoWFS.hpp>
Public Member Functions
wfs ()
Constructor.
virtual ~wfs ()
Destructor.
virtual realT beta_p (int m, int n, realT D, realT d, realT r0)
Get the photon noise sensitivity at a spatial frequency.
virtual realT beta_r (int m, int n, realT D, realT d, realT r0)
Get the read noise sensitivity at a spatial frequency.
virtual iosT & dumpWFS (iosT &ios)
Dump the details of the WFS to an io stream.
Constructor & Destructor Documentation
wfs()
template<typename realT , typename iosT = std::ostream> mx::AO::analysis::wfs< realT, iosT >::wfs () inline
Constructor.
Only sets the value of _id.
Definition at line 42 of file aoWFS.hpp.
~wfs()
template<typename realT , typename iosT = std::ostream> virtual mx::AO::analysis::wfs< realT, iosT >::~wfs () inline virtual
Destructor.
Declared virtual so more complicated derived types can be created.
Definition at line 50 of file aoWFS.hpp.
Member Function Documentation
beta_p()
template<typename realT , typename iosT = std::ostream> virtual realT mx::AO::analysis::wfs< realT, iosT >::beta_p (int m, int n, realT D, realT d, realT r0) inline virtual
Get the photon noise sensitivity at a spatial frequency.
The sensitivity of the ideal WFS is 1 at all k [8].
Returns
the sensitivity to photon noise parameter
Parameters
[in] m the spatial frequency index for u (not used by this WFS)
[in] n the spatial frequency index for v (not used by this WFS)
[in] D the telescope diameter (not used by this WFS)
[in] d the sub-ap spacing (not used by this WFS)
[in] r0 Fried's parameter (not used by this WFS)
Reimplemented in mx::AO::analysis::pywfsUnmod< realT, iosT >, mx::AO::analysis::pywfsModAsymptotic< realT, iosT >, mx::AO::analysis::shwfs< realT, iosT >, and mx::AO::analysis::calculatedWFS< realT, iosT >.
Definition at line 60 of file aoWFS.hpp.
Referenced by mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::beta_p(), and mx::AO::analysis::wfs< realT, iosT >::beta_r().
beta_r()
template<typename realT , typename iosT = std::ostream> virtual realT mx::AO::analysis::wfs< realT, iosT >::beta_r (int m, int n, realT D, realT d, realT r0) inline virtual
Get the read noise sensitivity at a spatial frequency.
Here we assume beta_r is the same as beta_p.
Returns
the sensitivity to read noise parameter
Parameters
[in] m the spatial frequency index for u (not used by this WFS)
[in] n the spatial frequency index for v (not used by this WFS)
[in] D the telescope diameter (not used by this WFS)
[in] d the sub-ap spacing (not used by this WFS)
[in] r0 Fried's parameter (not used by this WFS)
Reimplemented in mx::AO::analysis::pywfsUnmod< realT, iosT >, mx::AO::analysis::pywfsModAsymptotic< realT, iosT >, mx::AO::analysis::shwfs< realT, iosT >, and mx::AO::analysis::calculatedWFS< realT, iosT >.
Definition at line 82 of file aoWFS.hpp.
References mx::AO::analysis::wfs< realT, iosT >::beta_p().
dumpWFS()
template<typename realT , typename iosT = std::ostream> virtual iosT & mx::AO::analysis::wfs< realT, iosT >::dumpWFS (iosT & ios) inline virtual
Dump the details of the WFS to an io stream.
Is virtual so that derived types can add parameters.
Reimplemented in mx::AO::analysis::calculatedWFS< realT, iosT >.
Definition at line 95 of file aoWFS.hpp.
Referenced by mx::AO::analysis::calculatedWFS< realT, iosT >::dumpWFS().
The documentation for this struct was generated from the following file:
ao/analysis/aoWFS.hpp