mxlib: mx::cuda::cusolverDnParams Struct Reference
mx::cuda::cusolverDnParams Struct Reference
Management of a cusolverDnParams structure.
RAII management of a cusolverDnParams structure.
The handle is not created automatically on default construction, e.g. in case it is desired to do so in a critical block scope.
The handle is destroyed on the call to this class's destructor.
Todo:
throw exceptions in cuda::cusolverDnParams
Definition at line 48 of file cusolverDnParams.hpp.
#include <math/cuda/cusolverDnParams.hpp>
Public Member Functions
cusolverDnParams ()
Default c'tor.
cusolverDnParams (bool create)
Constructor with option to create /not-create the structure.
~cusolverDnParams ()
Destructor.
void create ()
Create (allocate) the structure.
cusolverDnParams_t operator() ()
Get the structure for use in calls to cusolverDN routines.
operator cusolverDnParams_t ()
Conversion operator, allows objects of this class to be used as if they are the structure.
Constructor & Destructor Documentation
cusolverDnParams() [1/2]
mx::cuda::cusolverDnParams::cusolverDnParams () inline
Default c'tor.
Creates the structure
Definition at line 58 of file cusolverDnParams.hpp.
References create().
cusolverDnParams() [2/2]
mx::cuda::cusolverDnParams::cusolverDnParams (bool create) inline explicit
Constructor with option to create /not-create the structure.
Parameters
[in] create if true the structure is created. if false it is not created.
Definition at line 64 of file cusolverDnParams.hpp.
References create().
~cusolverDnParams()
mx::cuda::cusolverDnParams::~cusolverDnParams () inline
Destructor.
Definition at line 73 of file cusolverDnParams.hpp.
Member Function Documentation
create()
void mx::cuda::cusolverDnParams::create () inline
Create (allocate) the structure.
Definition at line 82 of file cusolverDnParams.hpp.
Referenced by cusolverDnParams(), and cusolverDnParams().
operator cusolverDnParams_t()
mx::cuda::cusolverDnParams::operator cusolverDnParams_t () inline
Conversion operator, allows objects of this class to be used as if they are the structure.
Returns
the cusolverDnParams structure
Definition at line 105 of file cusolverDnParams.hpp.
operator()()
cusolverDnParams_t mx::cuda::cusolverDnParams::operator() () inline
Get the structure for use in calls to cusolverDN routines.
Returns
the cusolverDnParams structure
Definition at line 96 of file cusolverDnParams.hpp.
The documentation for this struct was generated from the following file:
math/cuda/cusolverDnParams.hpp