mxlib: mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT > Struct Template Reference
mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT > Struct Template Reference
Image Processing | Signal Processing » Image Filters » Filter With Kernels
template<typename _arrayT, size_t _kernW = 2, class _verboseT = verbose::d>
struct mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >
Azimuthally variable boxcar kernel.
Averages the image in a boxcar defined by a radial and azimuthal extent.
Definition at line 134 of file imageFilters.hpp.
#include <improc/imageFilters.hpp>
Public Member Functions
azBoxKernel (arithT radWidth, arithT azWidth)
azBoxKernel (arithT radWidth, arithT azWidth, arithT maxAz)
void setMaxWidth ()
Sets the max width based on the configured az and rad widths.
error_t setKernel (arithT x, arithT y, arrayT &kernel) const
Public Attributes
arithT m_radWidth { 0 }
the half-width of the averaging box, in the radial direction, in pixels.
arithT m_azWidth { 0 }
the half-width of the averaging box, in the azimuthal direction, in pixels.
arithT m_maxAz { 0 }
the maximum half-width of the averging box in the azimuthal direction, in degrees. >= 0. If 0 or >= 180, then no maximum is enforced.
Constructor & Destructor Documentation
azBoxKernel() [1/2]
template<typename _arrayT , size_t _kernW = 2, class _verboseT = verbose::d> mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::azBoxKernel (arithT radWidth, arithT azWidth) inline
Parameters
[in] radWidth the half-width of the averaging box, in the radial direction, in pixels.
[in] azWidth the half-width of the averaging box, in the azimuthal direction, in pixels.
Definition at line 150 of file imageFilters.hpp.
References mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setMaxWidth().
azBoxKernel() [2/2]
template<typename _arrayT , size_t _kernW = 2, class _verboseT = verbose::d> mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::azBoxKernel (arithT radWidth, arithT azWidth, arithT maxAz) inline
Parameters
[in] radWidth the half-width of the averaging box, in the radial direction, in pixels.
[in] azWidth the half-width of the averaging box, in the azimuthal direction, in pixels.
[in] maxAz the maximum half-width of the averaging box in the azimuthal direction, in degrees. >= 0. If 0 or >= 180, then no maximum is enforced.
Definition at line 158 of file imageFilters.hpp.
References mx::math::dtor(), mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_maxAz, and mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setMaxWidth().
Member Function Documentation
setKernel()
template<typename _arrayT , size_t _kernW = 2, class _verboseT = verbose::d> error_t mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setKernel (arithT x, arithT y, arrayT & kernel) const inline
Parameters
[in] x x-coordinate relative to image center
[in] y x-coordinate relative to image center
[in] kernel the array to populate with the kernel, resized
Definition at line 193 of file imageFilters.hpp.
References mx::invalidconfig, mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_azWidth, mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_maxAz, mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_radWidth, mx::noerror, mx::math::six_fifths(), and mx::sizeerr.
setMaxWidth()
template<typename _arrayT , size_t _kernW = 2, class _verboseT = verbose::d> void mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setMaxWidth () inline
Sets the max width based on the configured az and rad widths.
Definition at line 175 of file imageFilters.hpp.
References mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_azWidth, and mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_radWidth.
Referenced by mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::azBoxKernel(), and mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::azBoxKernel().
Member Data Documentation
m_azWidth
template<typename _arrayT , size_t _kernW = 2, class _verboseT = verbose::d> arithT mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_azWidth { 0 }
the half-width of the averaging box, in the azimuthal direction, in pixels.
Definition at line 144 of file imageFilters.hpp.
Referenced by mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setKernel(), and mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setMaxWidth().
m_maxAz
template<typename _arrayT , size_t _kernW = 2, class _verboseT = verbose::d> arithT mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_maxAz { 0 }
the maximum half-width of the averging box in the azimuthal direction, in degrees. >= 0. If 0 or >= 180, then no maximum is enforced.
Definition at line 145 of file imageFilters.hpp.
Referenced by mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::azBoxKernel(), and mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setKernel().
m_radWidth
template<typename _arrayT , size_t _kernW = 2, class _verboseT = verbose::d> arithT mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::m_radWidth { 0 }
the half-width of the averaging box, in the radial direction, in pixels.
Definition at line 143 of file imageFilters.hpp.
Referenced by mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setKernel(), and mx::improc::azBoxKernel< _arrayT, _kernW, _verboseT >::setMaxWidth().
The documentation for this struct was generated from the following file:
improc/imageFilters.hpp