mxlib: mx::AO::analysis::calculatedWFS< realT, iosT > Struct Template Reference
mx::AO::analysis::calculatedWFS< realT, iosT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename realT, typename iosT = std::ostream>
struct mx::AO::analysis::calculatedWFS< realT, iosT >
The calculated WFS uses sensitivities provided by FITS files.
Provides the \(\beta_p \) and \(\beta_r \) parameters from FITS files.
Template Parameters
realT is the floating point type used for calculations
iosT is an output stream type with operator << defined (default is std::ostream)
Definition at line 274 of file aoWFS.hpp.
#include <ao/analysis/aoWFS.hpp>
Public Member Functions
virtual realT beta_p (int m, int n, realT D, realT d, realT r0)
Get the photon noise sensitivity at a spatial frequency.
virtual realT beta_r (int m, int n, realT D, realT d, realT r0)
Get the read noise sensitivity at a spatial frequency.
virtual iosT & dumpWFS (iosT &ios)
Dump the details of the WFS to an io stream.
Public Member Functions inherited from mx::AO::analysis::wfs< realT, iosT >
wfs ()
Constructor.
virtual ~wfs ()
Destructor.
Member Function Documentation
beta_p()
template<typename realT , typename iosT = std::ostream> virtual realT mx::AO::analysis::calculatedWFS< realT, iosT >::beta_p (int m, int n, realT D, realT d, realT r0) inline virtual
Get the photon noise sensitivity at a spatial frequency.
The photon noise sensitivity from the FITS file is returned.
Returns
the sensitivity to photon noise parameter
Parameters
[in] m the spatial frequency index for u
[in] n the spatial frequency index for v
[in] D the telescope diameter
[in] d the sub-ap spacing
[in] r0 Fried's parameter
Reimplemented from mx::AO::analysis::wfs< realT, iosT >.
Definition at line 295 of file aoWFS.hpp.
References mx::fits::fitsFile< dataT, verboseT >::read().
beta_r()
template<typename realT , typename iosT = std::ostream> virtual realT mx::AO::analysis::calculatedWFS< realT, iosT >::beta_r (int m, int n, realT D, realT d, realT r0) inline virtual
Get the read noise sensitivity at a spatial frequency.
The read noise sensitivity from the FITS file is returned.
Returns
the sensitivity to read noise parameter
Parameters
[in] m the spatial frequency index for u
[in] n the spatial frequency index for v
[in] D the telescope diameter
[in] d the sub-ap spacing
[in] r0 Fried's parameter
Reimplemented from mx::AO::analysis::wfs< realT, iosT >.
Definition at line 353 of file aoWFS.hpp.
References mx::fits::fitsFile< dataT, verboseT >::read(), and mx::sizeerr.
dumpWFS()
template<typename realT , typename iosT = std::ostream> virtual iosT & mx::AO::analysis::calculatedWFS< realT, iosT >::dumpWFS (iosT & ios) inline virtual
Dump the details of the WFS to an io stream.
Is virtual so that derived types can add parameters.
Reimplemented from mx::AO::analysis::wfs< realT, iosT >.
Definition at line 388 of file aoWFS.hpp.
References mx::AO::analysis::wfs< realT, iosT >::dumpWFS().
The documentation for this struct was generated from the following file:
ao/analysis/aoWFS.hpp