mxlib: mx::astro::astroSpectrum< _spectrumT, freq > Struct Template Reference
mx::astro::astroSpectrum< _spectrumT, freq > Struct Template Reference
Astronomy » Astronomical Photometry
template<typename _spectrumT, bool freq = false>
struct mx::astro::astroSpectrum< _spectrumT, freq >
Class to manage an astronomical spectrum.
Details of the spectra, including units, file-location, and how they are read from disk, are specified by template parameter _spectrumT: see the available spectrum definitions. Spectra are loaded and immediately interpolated onto a wavelength grid. This is to facilitate manipulation of spectra, i.e. for multiplying by filters, etc.
Inherits functions and operators to manipulate and characterize spectra from baseSpectrum.
Template Parameters
_spectrumT is the underlying spectrum type, which provides (through static interfaces) the specifications of how to read or calculate the spectrum.
freq specify whether this spectrum uses frequency instead of wavelength. Default is false.
Definition at line 289 of file astroSpectrum.hpp.
#include <astro/astroSpectrum.hpp>
Public Member Functions
astroSpectrum ()
Default c'tor.
astroSpectrum (const paramsT &params)
Constructor specifying name, the enivronment will be queried for data directory.
astroSpectrum (const paramsT &params, const std::string &dataDir)
Constructor specifying name and data directory.
int setParameters (const paramsT &params)
Set the parameters of the spectrum, using the underlying spectrums parameter type.
int setParameters (const paramsT &params, const std::string &dataDir)
Set the parameters of the spectrum, using the underlying spectrum's parameter type.
template<typename gridT >
int setSpectrum (gridT &lambda)
Load the spectrum and interpolate it onto a wavelength scale.
Public Member Functions inherited from mx::astro::baseSpectrum< _spectrumT::units::realT >
size_t size ()
Get the current size of the spectrum.
_spectrumT::units::realT & operator[] (size_t i)
Access a single point in the spectrum, specified by its vector index.
const _spectrumT::units::realT operator[] (size_t i) const
Access a single point in the spectrum, specified by its vector index.
baseSpectrum< _spectrumT::units::realT > operator* (const compSpectrumT &spec)
Multiply two spectra together.
_spectrumT::units::realT mean ()
Calculate the mean value of the spectrum.
_spectrumT::units::realT mean (const compSpectrumT &T)
Calculate the mean value of the spectrum when mutiplied by another.
void charTrans (_spectrumT::units::realT &lambda0, _spectrumT::units::realT &weff, _spectrumT::units::realT &max, _spectrumT::units::realT &fwhm, std::vector< _spectrumT::units::realT > &lambda)
Characterize the spectrum as a filter transmission curve.
void charFlux (_spectrumT::units::realT &flambda0, _spectrumT::units::realT &fnu0, _spectrumT::units::realT &fphot0, const _spectrumT::units::realT &lambda_0, const std::vector< _spectrumT::units::realT > &lambda, const filterT &trans)
Characterize the flux densities of the spectrum w.r.t. a filter transmission curve.
void charFlux (_spectrumT::units::realT &flambda0, _spectrumT::units::realT &fnu0, _spectrumT::units::realT &fphot0, const _spectrumT::units::realT &lambda_0, const std::vector< _spectrumT::units::realT > &lambda, const std::vector< _spectrumT::units::realT > &trans)
Characterize the flux densities of the spectrum w.r.t. a filter transmission curve.
Public Attributes
std::string _dataDir
The directory containing the spectrum.
paramsT _params
Public Attributes inherited from mx::astro::baseSpectrum< _spectrumT::units::realT >
std::vector< _spectrumT::units::realT > _spectrum
Contains the spectrum after it is set.
Constructor & Destructor Documentation
astroSpectrum() [1/3]
template<typename _spectrumT , bool freq = false> mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum () inline
Default c'tor.
Definition at line 302 of file astroSpectrum.hpp.
astroSpectrum() [2/3]
template<typename _spectrumT , bool freq = false> mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum (const paramsT & params) inline explicit
Constructor specifying name, the enivronment will be queried for data directory.
Parameters
[in] params The name of the spectrum
Definition at line 307 of file astroSpectrum.hpp.
References mx::astro::astroSpectrum< _spectrumT, freq >::setParameters().
astroSpectrum() [3/3]
template<typename _spectrumT , bool freq = false> mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum (const paramsT & params, const std::string & dataDir) inline
Constructor specifying name and data directory.
Parameters
[in] params The name of the spectrum
[in] dataDir The directory containing the spectrum
Definition at line 313 of file astroSpectrum.hpp.
References mx::astro::astroSpectrum< _spectrumT, freq >::setParameters().
Member Function Documentation
setParameters() [1/2]
template<typename _spectrumT , bool freq = false> int mx::astro::astroSpectrum< _spectrumT, freq >::setParameters (const paramsT & params) inline
Set the parameters of the spectrum, using the underlying spectrums parameter type.
Parameters
[in] params The name of the spectrum
Definition at line 321 of file astroSpectrum.hpp.
References mx::astro::astroSpectrum< _spectrumT, freq >::_dataDir, mx::astro::astroSpectrum< _spectrumT, freq >::_params, and mx::sys::getEnv().
Referenced by mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum(), mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum(), and mx::astro::cahoyGrid< _units >::loadGrid().
setParameters() [2/2]
template<typename _spectrumT , bool freq = false> int mx::astro::astroSpectrum< _spectrumT, freq >::setParameters (const paramsT & params, const std::string & dataDir) inline
Set the parameters of the spectrum, using the underlying spectrum's parameter type.
This version also sets the data directory, instead of using the enivronment variable.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] params The name of the spectrum
[in] dataDir The directory containing the spectrum
Definition at line 338 of file astroSpectrum.hpp.
References mx::astro::astroSpectrum< _spectrumT, freq >::_dataDir, and mx::astro::astroSpectrum< _spectrumT, freq >::_params.
setSpectrum()
template<typename _spectrumT , bool freq = false> template<typename gridT > int mx::astro::astroSpectrum< _spectrumT, freq >::setSpectrum (gridT & lambda) inline
Load the spectrum and interpolate it onto a wavelength scale.
Returns
-1 on an error reading the spectrum.
0 on success.
Definition at line 350 of file astroSpectrum.hpp.
References mx::astro::astroSpectrum< _spectrumT, freq >::_dataDir, mx::astro::astroSpectrum< _spectrumT, freq >::_params, mx::astro::baseSpectrum< _spectrumT::units::realT >::_spectrum, mx::math::gsl_interpolate(), MXE_PARAMNOTSET, mxError, and mx::noerror.
Referenced by mx::astro::cahoyGrid< _units >::loadGrid().
Member Data Documentation
_dataDir
template<typename _spectrumT , bool freq = false> std::string mx::astro::astroSpectrum< _spectrumT, freq >::_dataDir
The directory containing the spectrum.
Definition at line 296 of file astroSpectrum.hpp.
Referenced by mx::astro::astroSpectrum< _spectrumT, freq >::setParameters(), mx::astro::astroSpectrum< _spectrumT, freq >::setParameters(), and mx::astro::astroSpectrum< _spectrumT, freq >::setSpectrum().
_params
template<typename _spectrumT , bool freq = false> paramsT mx::astro::astroSpectrum< _spectrumT, freq >::_params
The parameters of the spectrum, e.g. its name or the numerical parameters needed to generate the name.
Definition at line 298 of file astroSpectrum.hpp.
Referenced by mx::astro::astroSpectrum< _spectrumT, freq >::setParameters(), mx::astro::astroSpectrum< _spectrumT, freq >::setParameters(), and mx::astro::astroSpectrum< _spectrumT, freq >::setSpectrum().
The documentation for this struct was generated from the following file:
astro/astroSpectrum.hpp