mxlib: mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT > Struct Template Reference
mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT > Struct Template Reference
Astronomy | Image Processing » High Contrast Imaging
template<typename _realT, class _derotFunctObj, typename _evCalcT = double>
struct mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >
An implementation of the Karhunen-Loeve Image Processing (KLIP) algorithm.
KLIP[25] is a principle components analysis (PCA) based technique for PSF estimation.
Template Parameters
_realT is the floating point type in which to do calculations
_derotFunctObj the ADIobservation derotator class.
_evCalcT the real type in which to do eigen-decomposition. Should generally be double for stable results.
Definition at line 83 of file KLIPreduction.hpp.
#include <improc/KLIPreduction.hpp>
Public Member Functions
KLIPreduction ()
Default c'tor.
KLIPreduction (const std::string &dir, const std::string &prefix, const std::string &ext)
Construct and load the target file list.
KLIPreduction (const std::string &fileListFile)
Construct using a file containing the target file list.
KLIPreduction (const std::string &dir, const std::string &prefix, const std::string &ext, const std::string &RDIdir, const std::string &RDIprefix, const std::string &RDIext="")
KLIPreduction (const std::string &fileListFile, const std::string &RDIfileListFile)
void meanSubtract (eigenCube< realT > &rims, eigenCube< realT > &tims, eigenImageT &cmask, std::vector< realT > &sds)
Subtract the basis mean from each of the images.
int regions (const std::vector< realT > &minr, const std::vector< realT > &maxr, const std::vector< realT > &minq, const std::vector< realT > &maxq)
Run KLIP in a set of geometric search regions.
int regions (realT minr, realT maxr, realT minq, realT maxq)
Run KLIP in a geometric search region.
void worker (eigenCube< realT > &rims, eigenCube< realT > &tims, eigenImageT &cmask, std::vector< size_t > &idx, realT dang, realT dangMax)
Public Member Functions inherited from mx::improc::ADIobservation< _realT, _derotFunctObj >
ADIobservation (const std::string &dir, const std::string &prefix, const std::string &ext)
ADIobservation (const std::string &fileListFile)
ADIobservation (const std::string &dir, const std::string &prefix, const std::string &ext, const std::string &RDIdir, const std::string &RDIprefix, const std::string &RDIext="")
ADIobservation (const std::string &fileListFile, const std::string &RDIfileListFile)
int readFiles ()
Read in the target files.
virtual int postReadFiles ()
Actions to take after the files are first read in by HCIobservation.
virtual int postCoadd ()
Post target coadd actions.
int readRDIFiles ()
Read in the RDI files.
virtual int postRDIReadFiles ()
Post reference read actions, including fake injection.
virtual int postRDICoadd ()
Post reference coadd actions.
int readPSFSub (const std::string &dir, const std::string &prefix, const std::string &ext, size_t nReductions)
Read in already PSF-subtracted files.
virtual void makeMaskCube ()
Populate the mask cube which is used for post-processing.
void derotate ()
De-rotate the PSF subtracted images.
int injectFake (eigenCube< realT > &ims, std::vector< std::string > &fileList, derotFunctObj &derotF, realT RDIfluxScale, realT RDISepScale)
Inkect the fake plants.
int injectFake (eigenImageT &fakePSF, eigenCube< realT > &ims, int image_i, realT derotAngle, realT PA, realT sep, realT contrast, realT scale, realT RDIfluxScale, realT RDISepScale)
Inject the fake planet into a single image.
Public Member Functions inherited from mx::improc::HCIobservation< _realT >
int readPSFSub (const std::string &dir, const std::string &prefix, const std::string &ext, size_t nReductions)
Read in already PSF-subtracted files.
HCIobservation ()
Default c'tor.
HCIobservation (const std::string &dir, const std::string &prefix, const std::string &ext)
Construct and load the target file list.
HCIobservation (const std::string &fileListFile)
Construct using a file containing the target file list.
HCIobservation (const std::string &dir, const std::string &prefix, const std::string &ext, const std::string &RDIdir, const std::string &RDIprefix, const std::string &RDIext="")
Construct and load the target file list and the RDI file list.
HCIobservation (const std::string &fileListFile, const std::string &RDIfileListFile)
Construct using a file containing the target file list and a file containing the RDI target file list.
void load_fileList (const std::string &dir, const std::string &prefix, const std::string &ext)
Load the file list.
void load_fileList (const std::string &fileListFile)
Load the file list from a file.
void load_RDIfileList (const std::string &dir, const std::string &prefix, const std::string &ext)
Load the RDI basis file list.
void load_RDIfileList (const std::string &fileListFile)
Load the RDI basis file list from a file.
int threshold (std::vector< std::string > &fileList, const std::string &qualityFile, realT qualityThreshold)
Read the image qualities from a qualityFile and apply the threshold to a fileList.
int readFiles ()
Read the list of files, cut to size, and preprocess.
int readRDIFiles ()
Read the list of reference files, cut to size, and preprocess.
void coaddImages (int coaddCombineMethod, int coaddMaxImno, int coaddMaxTime, std::vector< std::string > &coaddKeywords, std::vector< double > &imageMJD, std::vector< fits::fitsHeader > &heads, eigenCube< realT > &ims)
Coadd the images.
void readMask ()
Read the mask file, resizing to imSize if needed.
void preProcess (eigenCube< realT > &ims)
Do the pre-processing.
void preProcess_meanSub (eigenCube< realT > &ims)
Do mean subtraction as part of pre-processing.
void preProcess_pixelTSNorm (eigenCube< realT > &ims)
Do pixel time-series normalization as part of pre-processing.
int readWeights ()
Read the image weights from m_weightFile.
void combineFinim ()
Combine the images into a single final image.
void outputPreProcessed ()
Output the pre-processed target images.
void outputRDIPreProcessed ()
Output the pre-processed reference images.
void stdFitsHeader (fits::fitsHeader &head)
Fill in the HCIobservation standard FITS header.
void writeFinim (fits::fitsHeader *addHead=0)
Write the final combined image to disk.
void outputPSFSub (fits::fitsHeader *addHead=0)
Write the PSF subtracted images to disk.
Public Attributes
HCI::meanSubMethod m_meanSubMethod { HCI::meanSubMethod::imageMean }
Specify how the data are centered for PCA within each search region.
HCI::pixelTSNormMethod m_pixelTSNormMethod {HCI::pixelTSNormMethod::none}
Specify if each pixel time-series is normalized.
realT m_pixelTSSigma {3}
Sigma-clipping parameter for pixel time-series normalization.
std::vector< int > m_Nmodes
Specifies the number of modes to include in the PSF.
realT m_minDPx { 0 }
realT m_maxDPx { 0 }
int m_excludeMethod { HCI::excludeNone }
int m_excludeMethodMax { HCI::excludeNone }
int m_includeRefNum { 0 }
Number of reference images to include in the covariance matrix.
int m_includeMethod { HCI::includeAll }
Controls how number of included images is calculated.
Public Attributes inherited from mx::improc::ADIobservation< _realT, _derotFunctObj >
int m_fakeMethod { HCI::single }
Method for reading fake files, either HCI::single or HCI::list.
std::string m_fakeFileName
FITS file containing the fake planet PSF to inject or a list of fake images.
std::string m_fakeScaleFileName
One-column text file containing a scale factor for each point in time.
std::vector< realT > m_fakeSep
Separation(s) of the fake planet(s)
std::vector< realT > m_fakePA
Position angles(s) of the fake planet(s)
std::vector< realT > m_fakeContrast
Contrast(s) of the fake planet(s)
realT m_RDIFluxScale { 1 }
realT m_RDISepScale { 1 }
Public Attributes inherited from mx::improc::HCIobservation< _realT >
eigenCube< realT > m_tgtIms
The target image cube.
int m_Nims { 0 }
Number of images in m_tgtIms.
int m_Nrows { 0 }
Number of rows of the images in m_tgtIms.
int m_Ncols { 0 }
Number of columns of the images in m_tgtIms.
int m_Npix { 0 }
Pixels per image, that is Nrows*Ncols.
std::vector< double > m_imageMJD
Vector of target image times, in MJD.
std::vector< fits::fitsHeader > m_heads
Vector of FITS headers, one per file, populated with the values for the keywords.
bool m_filesRead { false }
Whether or not the m_fileList has been read.
bool m_filesDeleted { false }
Whether or not the specified files have been deleted from m_fileList.
std::vector< realT > m_comboWeights
Vector to hold the image weights read from the m_weightFile.
eigenCube< realT > m_refIms
The optional reference image cube.
std::vector< double > m_RDIimageMJD
Vector of reference image times, in MJD.
std::vector< fits::fitsHeader > m_RDIheads
Vector of FITS headers, one per reference file, populated with the values for the keywords.
bool m_RDIfilesRead { false }
Whether or not the reference files have been read.
bool m_RDIfilesDeleted { false }
Whether or not the specified files have been deleted from m_RDIfileList.
std::vector< eigenCube< realT > > m_psfsub
The PSF subtracted images.
eigenCube< realT > m_finim
The final combined images, one for each cube in psfsub.
std::vector< std::string > m_fileList
The list of files to read in.
int m_deleteFront { 0 }
Specify how many files from m_fileList to delete from the front of the list.
int m_deleteBack { 0 }
Specify how many files from m_fileList to delete from the back of the list.
std::string m_qualityFile
File containing 2 space-delimited columns of fileVame qualityValue pairs.
realT m_qualityThreshold { 0 }
Threshold to apply to qualityValues read from qualityFile.
bool m_thresholdOnly { false }
Just prints the names and qualities of the files which pass threshold, and stop.
std::string m_MJDKeyword { "DATE-OBS" }
Name of the keyword to use for the image date.
bool m_MJDisISO8601 { true }
Whether or not the date is in ISO 8601 format.
realT m_MJDUnits { 1.0 }
If the date is not ISO 8601, this specifies the conversion to Julian Days (i.e. seconds to days)
std::vector< std::string > m_keywords
Vector of FITS header keywords to read from the files in m_fileList.
int m_imSize { 0 }
Set the image size. Images are cut down to this size after reading.
std::vector< std::string > m_RDIfileList
The list of files to read in for the RDI basis.
int m_RDIdeleteFront { 0 }
Specify how many files from m_RDIfileList to delete from the front of the list.
int m_RDIdeleteBack { 0 }
Specify how many files from m_RDIfileList to delete from the back of the list.
std::string m_RDIqualityFile
File containing 2 space-delimited columns of fileMame qualityValue pairs for the reference images.
realT m_RDIqualityThreshold { 0 }
Threshold to apply to qualityValues read from qualityFile.
std::vector< std::string > m_RDIkeywords
Vector of FITS header keywords to read from the files in m_fileList.
int m_coaddCombineMethod { HCI::noCombine }
Determine how to coadd the raw images.
int m_coaddMaxImno { 0 }
Maximum number of images to coadd.
realT m_coaddMaxTime { 0 }
Maximum elapsed time over which to coadd the images.
std::vector< std::string > m_coaddKeywords
The values of these keywords will be averaged and replaced.
std::string m_maskFile
Specify a mask file to apply.
eigenImageT m_mask
The mask.
eigenCube< realT > m_maskCube
bool m_skipPreProcess { false }
Don't do any of the pre-processing steps (including coadding).
bool m_preProcess_beforeCoadd { false }
controls whether pre-processing takes place before or after coadding
bool m_preProcess_mask { true }
If true, the mask is applied during each pre-processing step.
bool m_preProcess_subradprof { false }
If true, a radial profile is subtracted from each image.
realT m_preProcess_azUSM_azW { 0 }
Azimuthal boxcar width for azimuthal unsharp mask [pixels].
realT m_preProcess_azUSM_maxAz { 45 }
Mazimum azimuthal boxcar width for azimuthal unsharp mask [degrees].
realT m_preProcess_azUSM_radW { 0 }
Radial boxcar width for azimuthal unsharp mask [pixels].
int m_preProcess_medianUSM_fwhm { 0 }
Kernel FWHM for symmetric box median unsharp mask (USM)
realT m_preProcess_gaussUSM_fwhm { 0 }
Kernel FWHM for symmetric Gaussian unsharp mask (USM)
HCI::meanSubMethod m_preProcess_meanSubMethod { HCI::meanSubMethod::none }
The mean subtraction method during pre-processing.
HCI::pixelTSNormMethod m_preProcess_pixelTSNormMethod { HCI::pixelTSNormMethod::none }
Specify if each pixel time-series is normalized.
realT m_pixelTSSigma { 3 }
Sigma-clipping parameter for pixel time-series normalization.
std::string m_preProcess_outputPrefix
Set path and file prefix to output the pre-processed images.
bool m_preProcess_only { false }
If true, then we stop after pre-processing.
int m_combineMethod { HCI::meanCombine }
Determine how to combine the PSF subtracted images.
std::string m_weightFile
Specifies a file containing the image weights, for combining with weighted mean.
realT m_sigmaThreshold { 0 }
The standard deviation threshold used if combineMethod == HCI::sigmaMeanCombine.
realT m_minGoodFract { 0.0 }
std::string m_auxDataDir { "/tmp/klipReduceAux/" }
Location for temporary auxilliary output files (e.g. masks)
bool m_moveAuxDataDir { true }
Whether or not to move the temp. aux files.
int m_doWriteFinim { 1 }
Set whether the final combined image is written to disk.
std::string m_outputDir
The directory where to write output files.
std::string m_finimName { "finim_" }
The base file name of the output final image.
bool m_exactFinimName { false }
Use m_finimName exactly as specified, without appending a number or an extension.
bool m_doOutputPSFSub { false }
Controls whether or not the individual PSF subtracted images are written to disk.
std::string m_PSFSubPrefix
Additional Inherited Members
Public Types inherited from mx::improc::HCIobservation< _realT >
typedef _realT realT
The arithmetic type used for calculations. Does not have to match the type in images on disk.
typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic > eigenImageT
The Eigen image array type basted on realT.
Constructor & Destructor Documentation
KLIPreduction() [1/5]
template<typename _realT , class _derotFunctObj , typename _evCalcT > mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::KLIPreduction ()
Default c'tor.
Definition at line 342 of file KLIPreduction.hpp.
KLIPreduction() [2/5]
template<typename _realT , class _derotFunctObj , typename _evCalcT > mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::KLIPreduction (const std::string & dir, const std::string & prefix, const std::string & ext)
Construct and load the target file list.
Populates the m_fileList vector by searching on disk for files which match "dir/prefix*.ext". See load_fileList
Parameters
[in] dir the directory to search for files.
[in] prefix the prefix of the files
[in] ext the extension of the files
Definition at line 347 of file KLIPreduction.hpp.
KLIPreduction() [3/5]
template<typename _realT , class _derotFunctObj , typename _evCalcT > mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::KLIPreduction (const std::string & fileListFile) explicit
Construct using a file containing the target file list.
Populates the m_fileList vector by reading the file, which should be a single column of new-line delimited file names.
Parameters
[in] fileListFile the full path to a file containing a list of files
Definition at line 355 of file KLIPreduction.hpp.
KLIPreduction() [4/5]
template<typename _realT , class _derotFunctObj , typename _evCalcT > mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::KLIPreduction (const std::string & dir, const std::string & prefix, const std::string & ext, const std::string & RDIdir, const std::string & RDIprefix, const std::string & RDIext = "")
Populates the m_fileList vector by searching on disk for files which match "dir/prefix*.ext". See load_fileList
Populates the m_RDIfileList vector by searching on disk for files which match "RDIdir/RDIprefix*.RDIext". See load_RDIfileList
Parameters
[in] dir the directory to search for files.
[in] prefix the prefix of the files
[in] ext the extension of the files, default is .fits
[in] RDIdir the directory to search for the reference files.
[in] RDIprefix the initial part of the file name for the reference files. Can be empty "".
[in] RDIext [optional] the extension to append to the RDI file name, must include the '.'. If empty "" then same extension as target files is used.
Definition at line 361 of file KLIPreduction.hpp.
KLIPreduction() [5/5]
template<typename _realT , class _derotFunctObj , typename _evCalcT > mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::KLIPreduction (const std::string & fileListFile, const std::string & RDIfileListFile) explicit
Construct using a file containing the target file list and a file containing the RDI target file list Populates the m_fileList vector by reading the file, which should be a single column of new-line delimited file names.
Populates the m_RDIfileList vector by reading the file, which should be a single column of new-line delimited file names.
Parameters
[in] fileListFile a file name path to read for the target file names.
[in] RDIfileListFile a file name path to read for the reference file names.
Definition at line 372 of file KLIPreduction.hpp.
Member Function Documentation
meanSubtract()
template<typename realT , class derotFunctObj , typename evCalcT > void mx::improc::KLIPreduction< realT, derotFunctObj, evCalcT >::meanSubtract (eigenCube< realT > & rims, eigenCube< realT > & tims, eigenImageT & cmask, std::vector< realT > & sds)
Subtract the basis mean from each of the images.
The mean is subtracted according to m_meanSubMethod.
Parameters
rims [in.out] The reference images. These are mean subtracted on output.
tims [in.out] The target images, which can be the same cube as rims (tested by pointer comparison), in which case they will be ignored. Mean subtractedon output.
[in] cmask the cutout mask. Ignored if empty.
[out] sds The standard deviation of the mean subtracted reference images.
Definition at line 384 of file KLIPreduction.hpp.
References mx::improc::eigenCube< dataT >::image(), mx::improc::HCI::imageMean, mx::improc::imageMedian(), mx::improc::HCI::imageMedian, mx::improc::eigenCube< dataT >::mean(), mx::improc::HCI::meanImage, mx::improc::eigenCube< dataT >::median(), mx::improc::HCI::medianImage, mx::improc::HCI::none, mx::improc::HCI::rmsSigmaClipped, mx::improc::HCI::unknown, and mx::math::vectorVariance().
regions() [1/2]
template<typename _realT , class _derotFunctObj , typename _evCalcT > int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::regions (const std::vector< realT > & minr, const std::vector< realT > & maxr, const std::vector< realT > & minq, const std::vector< realT > & maxq)
Run KLIP in a set of geometric search regions.
The arguments are 4 vectors, where each entry defines one component of the search region.
Returns
0 on success
-1 on error
Parameters
[in] minr
[in] maxr
[in] minq
[in] maxq
Definition at line 540 of file KLIPreduction.hpp.
References mx::improc::cutImageRegion(), mx::math::dtor(), mx::improc::HCI::excludeAngle, mx::improc::HCI::excludeImno, mx::improc::HCI::excludeNone, mx::improc::HCI::excludePixel, mx::sys::get_curr_time(), mx::improc::eigenCube< dataT >::image(), and mx::fits::fitsFile< dataT >::write().
Referenced by mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::regions().
regions() [2/2]
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::regions (realT minr, realT maxr, realT minq, realT maxq) inline
Run KLIP in a geometric search region.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
0 on success
-1 on error
Parameters
[in] minr
[in] maxr
[in] minq
[in] maxq
Definition at line 289 of file KLIPreduction.hpp.
References mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::regions().
worker()
template<typename _realT , class _derotFunctObj , typename _evCalcT > void mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker (eigenCube< realT > & rims, eigenCube< realT > & tims, eigenImageT & cmask, std::vector< size_t > & idx, realT dang, realT dangMax)
omp_get_num_threads();
Definition at line 947 of file KLIPreduction.hpp.
References mx::improc::eigenCube< dataT >::asVectors(), mx::math::calcKLModes(), mx::improc::eigenCube< dataT >::cube(), mx::math::eigenSYRK(), mx::improc::HCI::excludeNone, mx::sys::get_curr_time(), mx::ipc::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine, _time >::incrementAndOutputStatus(), mx::improc::insertImageRegion(), mx::improc::maskCircle(), mx::math::six_fifths(), and mx::fits::fitsFile< dataT >::write().
Member Data Documentation
m_excludeMethod
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_excludeMethod { HCI::excludeNone }
Controls how reference images are excluded, if at all, from the covariance matrix for each target image based on a minimum criterion. Can have the following values:
HCI::excludeNone = no exclusion, all images included [default]
HCI::excludePixel = exclude based on pixels of rotation at the inner edge of the region
HCI::excludeAngle = exclude based on degrees of rotation at the inner edge of the region
HCI::excludeImno = exclude based on number of images
Definition at line 206 of file KLIPreduction.hpp.
m_excludeMethodMax
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_excludeMethodMax { HCI::excludeNone }
Controls how reference images are excluded, if at all, from the covariance matrix for each target image based on a maximum criterion. Can have the following values:
HCI::excludeNone = no exclusion, all images included [default]
HCI::excludePixel = exclude based on pixels of rotation at the inner edge of the region
HCI::excludeAngle = exclude based on degrees of rotation at the inner edge of the region
HCI::excludeImno = exclude based on number of images
Definition at line 218 of file KLIPreduction.hpp.
m_includeMethod
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_includeMethod { HCI::includeAll }
Controls how number of included images is calculated.
The number of included images is calculated after exclusion is complete. Can have the following values:
HCI::includeAll = all remaining images are included [default]
HCI::includeCorr = the m_includeRefNum of the remaining images which are most correlated with the target are included
HCI::includeTime = the m_includeRefNum of the remaining images which are closest in time to the target are included
HCI::includeAngle = the m_includeRefNum of the remaining images which are closest in angle to the target are included
HCI::includeImno = the m_includeRefNum of the remaining images which are closest in image number to the target are included
Definition at line 241 of file KLIPreduction.hpp.
m_includeRefNum
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_includeRefNum { 0 }
Number of reference images to include in the covariance matrix.
If > 0, then at most this many images, determined by highest cross-correlation, are included. This is determined after rotational/image-number exclusion. If == 0, then all reference images are included.
Definition at line 226 of file KLIPreduction.hpp.
m_maxDPx
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> realT mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_maxDPx { 0 }
Specify the maximum pixel difference at the inner edge of the search region
Definition at line 194 of file KLIPreduction.hpp.
m_meanSubMethod
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> HCI::meanSubMethod mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_meanSubMethod { HCI::meanSubMethod::imageMean }
Specify how the data are centered for PCA within each search region.
Can have the following values:
HCI::meanSubMethod::imageMean = the mean of each image (within the search region) is subtracted from itself
HCI::meanSubMethod::imageMedian = the median of each image (within the search region) is subtracted from itself
HCI::meanSubMethod::imageMode = the mode of each image (within the search region) is subtracted from itself
HCI::meanSubMethod::meanImage = the mean image of the data is subtracted from each image
HCI::meanSubMethod::medianImage = the median image of the data is subtracted from each image
Definition at line 158 of file KLIPreduction.hpp.
m_minDPx
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> realT mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_minDPx { 0 }
Specify the minimum pixel difference at the inner edge of the search region
Definition at line 190 of file KLIPreduction.hpp.
m_Nmodes
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> std::vector<int> mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_Nmodes
Specifies the number of modes to include in the PSF.
The output image is a cube with a plane for each entry in m_Nmodes. Only the number of eigenvalues required for the maximum value of m_Nmodes are calculated, so this can have an important impact on speed.
Can be initialized as:
red.m_Nmodes={5,10,15,20};
Definition at line 184 of file KLIPreduction.hpp.
m_pixelTSNormMethod
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> HCI::pixelTSNormMethod mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_pixelTSNormMethod {HCI::pixelTSNormMethod::none}
Specify if each pixel time-series is normalized.
This normalizaton is applied after centering. Can have the following values:
HCI::pixelTSNormMethod::none: no normalization (the default)
HCI::pixelTSNormMethod::rms: divide by the time-series rms
HCI::pixelTSNormMethod::rmsSigmaClipped: divide by the sigma-slipped time-series rms. The sigma is provided by m_pixelTSSigma.
Definition at line 167 of file KLIPreduction.hpp.
m_pixelTSSigma
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> realT mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::m_pixelTSSigma {3}
Sigma-clipping parameter for pixel time-series normalization.
Definition at line 169 of file KLIPreduction.hpp.
The documentation for this struct was generated from the following file:
improc/KLIPreduction.hpp