mxlib: mx::improc::ADIobservation< _realT, _derotFunctObj > Struct Template Reference
mx::improc::ADIobservation< _realT, _derotFunctObj > Struct Template Reference
Astronomy | Image Processing » High Contrast Imaging
template<typename _realT, class _derotFunctObj>
struct mx::improc::ADIobservation< _realT, _derotFunctObj >
Process an angular differential imaging (ADI) observation.
Angular differential imaging (ADI) uses sky rotation to differentiate real objects from speckles.
Template Parameters
realT is the floating point type in which to do calculations
_derotFunctObj is the derotation object with the following minimum interface:
template<typename _realT>
struct derotF
{
   typedef  _realT realT;
   //Vector of keywords to extract from the fits headers
   std::vector<std::string> keywords;
   //Vector(s) to hold the keyword values
   std::vector<realT> keyValue1;
   ///To allow ADIobservation to check for errors.
   bool isSetup()
   {
     if( <any condition indicating not set up>) return false;
     return true;
   }
   //Method called by HCIobservation to get keyword-values
   void extractKeywords(vector<fitsHeader> & heads)
   {
      keyValue1 = headersToValues<float>(heads, "KEYWORD1");
   }
   //Calculate the derotation angle for a given image number
   realT derotAngle(size_t imno) const
   {
      return some_function_of(keyValue1[imno]); //This function uses keyValue1[imno] to produce the derotation angle
in radians.
   }
};
Definition at line 94 of file ADIobservation.hpp.
#include <improc/ADIobservation.hpp>
Public Member Functions
ADIobservation (const std::string &dir, const std::string &prefix, const std::string &ext)
ADIobservation (const std::string &fileListFile)
ADIobservation (const std::string &dir, const std::string &prefix, const std::string &ext, const std::string &RDIdir, const std::string &RDIprefix, const std::string &RDIext="")
ADIobservation (const std::string &fileListFile, const std::string &RDIfileListFile)
int readFiles ()
Read in the target files.
virtual int postReadFiles ()
Actions to take after the files are first read in by HCIobservation.
virtual int postCoadd ()
Post target coadd actions.
int readRDIFiles ()
Read in the RDI files.
virtual int postRDIReadFiles ()
Post reference read actions, including fake injection.
virtual int postRDICoadd ()
Post reference coadd actions.
int readPSFSub (const std::string &dir, const std::string &prefix, const std::string &ext, size_t nReductions)
Read in already PSF-subtracted files.
virtual void makeMaskCube ()
Populate the mask cube which is used for post-processing.
void derotate ()
De-rotate the PSF subtracted images.
Public Member Functions inherited from mx::improc::HCIobservation< _realT >
int readPSFSub (const std::string &dir, const std::string &prefix, const std::string &ext, size_t nReductions)
Read in already PSF-subtracted files.
HCIobservation ()
Default c'tor.
HCIobservation (const std::string &dir, const std::string &prefix, const std::string &ext)
Construct and load the target file list.
HCIobservation (const std::string &fileListFile)
Construct using a file containing the target file list.
HCIobservation (const std::string &dir, const std::string &prefix, const std::string &ext, const std::string &RDIdir, const std::string &RDIprefix, const std::string &RDIext="")
Construct and load the target file list and the RDI file list.
HCIobservation (const std::string &fileListFile, const std::string &RDIfileListFile)
Construct using a file containing the target file list and a file containing the RDI target file list.
void load_fileList (const std::string &dir, const std::string &prefix, const std::string &ext)
Load the file list.
void load_fileList (const std::string &fileListFile)
Load the file list from a file.
void load_RDIfileList (const std::string &dir, const std::string &prefix, const std::string &ext)
Load the RDI basis file list.
void load_RDIfileList (const std::string &fileListFile)
Load the RDI basis file list from a file.
int threshold (std::vector< std::string > &fileList, const std::string &qualityFile, realT qualityThreshold)
Read the image qualities from a qualityFile and apply the threshold to a fileList.
int readFiles ()
Read the list of files, cut to size, and preprocess.
int readRDIFiles ()
Read the list of reference files, cut to size, and preprocess.
void coaddImages (int coaddCombineMethod, int coaddMaxImno, int coaddMaxTime, std::vector< std::string > &coaddKeywords, std::vector< double > &imageMJD, std::vector< fits::fitsHeader > &heads, eigenCube< realT > &ims)
Coadd the images.
void readMask ()
Read the mask file, resizing to imSize if needed.
void preProcess (eigenCube< realT > &ims)
Do the pre-processing.
void preProcess_meanSub (eigenCube< realT > &ims)
Do mean subtraction as part of pre-processing.
void preProcess_pixelTSNorm (eigenCube< realT > &ims)
Do pixel time-series normalization as part of pre-processing.
int readWeights ()
Read the image weights from m_weightFile.
void combineFinim ()
Combine the images into a single final image.
void outputPreProcessed ()
Output the pre-processed target images.
void outputRDIPreProcessed ()
Output the pre-processed reference images.
void stdFitsHeader (fits::fitsHeader &head)
Fill in the HCIobservation standard FITS header.
void writeFinim (fits::fitsHeader *addHead=0)
Write the final combined image to disk.
void outputPSFSub (fits::fitsHeader *addHead=0)
Write the PSF subtracted images to disk.
Fake Planets
int m_fakeMethod { HCI::single }
Method for reading fake files, either HCI::single or HCI::list.
std::string m_fakeFileName
FITS file containing the fake planet PSF to inject or a list of fake images.
std::string m_fakeScaleFileName
One-column text file containing a scale factor for each point in time.
std::vector< realT > m_fakeSep
Separation(s) of the fake planet(s)
std::vector< realT > m_fakePA
Position angles(s) of the fake planet(s)
std::vector< realT > m_fakeContrast
Contrast(s) of the fake planet(s)
realT m_RDIFluxScale { 1 }
realT m_RDISepScale { 1 }
int injectFake (eigenCube< realT > &ims, std::vector< std::string > &fileList, derotFunctObj &derotF, realT RDIfluxScale, realT RDISepScale)
Inkect the fake plants.
int injectFake (eigenImageT &fakePSF, eigenCube< realT > &ims, int image_i, realT derotAngle, realT PA, realT sep, realT contrast, realT scale, realT RDIfluxScale, realT RDISepScale)
Inject the fake planet into a single image.
Additional Inherited Members
Public Types inherited from mx::improc::HCIobservation< _realT >
typedef _realT realT
The arithmetic type used for calculations. Does not have to match the type in images on disk.
typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic > eigenImageT
The Eigen image array type basted on realT.
Public Attributes inherited from mx::improc::HCIobservation< _realT >
eigenCube< realT > m_tgtIms
The target image cube.
int m_Nims { 0 }
Number of images in m_tgtIms.
int m_Nrows { 0 }
Number of rows of the images in m_tgtIms.
int m_Ncols { 0 }
Number of columns of the images in m_tgtIms.
int m_Npix { 0 }
Pixels per image, that is Nrows*Ncols.
std::vector< double > m_imageMJD
Vector of target image times, in MJD.
std::vector< fits::fitsHeader > m_heads
Vector of FITS headers, one per file, populated with the values for the keywords.
bool m_filesRead { false }
Whether or not the m_fileList has been read.
bool m_filesDeleted { false }
Whether or not the specified files have been deleted from m_fileList.
std::vector< realT > m_comboWeights
Vector to hold the image weights read from the m_weightFile.
eigenCube< realT > m_refIms
The optional reference image cube.
std::vector< double > m_RDIimageMJD
Vector of reference image times, in MJD.
std::vector< fits::fitsHeader > m_RDIheads
Vector of FITS headers, one per reference file, populated with the values for the keywords.
bool m_RDIfilesRead { false }
Whether or not the reference files have been read.
bool m_RDIfilesDeleted { false }
Whether or not the specified files have been deleted from m_RDIfileList.
std::vector< eigenCube< realT > > m_psfsub
The PSF subtracted images.
eigenCube< realT > m_finim
The final combined images, one for each cube in psfsub.
std::vector< std::string > m_fileList
The list of files to read in.
int m_deleteFront { 0 }
Specify how many files from m_fileList to delete from the front of the list.
int m_deleteBack { 0 }
Specify how many files from m_fileList to delete from the back of the list.
std::string m_qualityFile
File containing 2 space-delimited columns of fileVame qualityValue pairs.
realT m_qualityThreshold { 0 }
Threshold to apply to qualityValues read from qualityFile.
bool m_thresholdOnly { false }
Just prints the names and qualities of the files which pass threshold, and stop.
std::string m_MJDKeyword { "DATE-OBS" }
Name of the keyword to use for the image date.
bool m_MJDisISO8601 { true }
Whether or not the date is in ISO 8601 format.
realT m_MJDUnits { 1.0 }
If the date is not ISO 8601, this specifies the conversion to Julian Days (i.e. seconds to days)
std::vector< std::string > m_keywords
Vector of FITS header keywords to read from the files in m_fileList.
int m_imSize { 0 }
Set the image size. Images are cut down to this size after reading.
std::vector< std::string > m_RDIfileList
The list of files to read in for the RDI basis.
int m_RDIdeleteFront { 0 }
Specify how many files from m_RDIfileList to delete from the front of the list.
int m_RDIdeleteBack { 0 }
Specify how many files from m_RDIfileList to delete from the back of the list.
std::string m_RDIqualityFile
File containing 2 space-delimited columns of fileMame qualityValue pairs for the reference images.
realT m_RDIqualityThreshold { 0 }
Threshold to apply to qualityValues read from qualityFile.
std::vector< std::string > m_RDIkeywords
Vector of FITS header keywords to read from the files in m_fileList.
int m_coaddCombineMethod { HCI::noCombine }
Determine how to coadd the raw images.
int m_coaddMaxImno { 0 }
Maximum number of images to coadd.
realT m_coaddMaxTime { 0 }
Maximum elapsed time over which to coadd the images.
std::vector< std::string > m_coaddKeywords
The values of these keywords will be averaged and replaced.
std::string m_maskFile
Specify a mask file to apply.
eigenImageT m_mask
The mask.
eigenCube< realT > m_maskCube
bool m_skipPreProcess { false }
Don't do any of the pre-processing steps (including coadding).
bool m_preProcess_beforeCoadd { false }
controls whether pre-processing takes place before or after coadding
bool m_preProcess_mask { true }
If true, the mask is applied during each pre-processing step.
bool m_preProcess_subradprof { false }
If true, a radial profile is subtracted from each image.
realT m_preProcess_azUSM_azW { 0 }
Azimuthal boxcar width for azimuthal unsharp mask [pixels].
realT m_preProcess_azUSM_maxAz { 45 }
Mazimum azimuthal boxcar width for azimuthal unsharp mask [degrees].
realT m_preProcess_azUSM_radW { 0 }
Radial boxcar width for azimuthal unsharp mask [pixels].
int m_preProcess_medianUSM_fwhm { 0 }
Kernel FWHM for symmetric box median unsharp mask (USM)
realT m_preProcess_gaussUSM_fwhm { 0 }
Kernel FWHM for symmetric Gaussian unsharp mask (USM)
HCI::meanSubMethod m_preProcess_meanSubMethod { HCI::meanSubMethod::none }
The mean subtraction method during pre-processing.
HCI::pixelTSNormMethod m_preProcess_pixelTSNormMethod { HCI::pixelTSNormMethod::none }
Specify if each pixel time-series is normalized.
realT m_pixelTSSigma { 3 }
Sigma-clipping parameter for pixel time-series normalization.
std::string m_preProcess_outputPrefix
Set path and file prefix to output the pre-processed images.
bool m_preProcess_only { false }
If true, then we stop after pre-processing.
int m_combineMethod { HCI::meanCombine }
Determine how to combine the PSF subtracted images.
std::string m_weightFile
Specifies a file containing the image weights, for combining with weighted mean.
realT m_sigmaThreshold { 0 }
The standard deviation threshold used if combineMethod == HCI::sigmaMeanCombine.
realT m_minGoodFract { 0.0 }
std::string m_auxDataDir { "/tmp/klipReduceAux/" }
Location for temporary auxilliary output files (e.g. masks)
bool m_moveAuxDataDir { true }
Whether or not to move the temp. aux files.
int m_doWriteFinim { 1 }
Set whether the final combined image is written to disk.
std::string m_outputDir
The directory where to write output files.
std::string m_finimName { "finim_" }
The base file name of the output final image.
bool m_exactFinimName { false }
Use m_finimName exactly as specified, without appending a number or an extension.
bool m_doOutputPSFSub { false }
Controls whether or not the individual PSF subtracted images are written to disk.
std::string m_PSFSubPrefix
Constructor & Destructor Documentation
ADIobservation() [1/4]
template<typename _realT , class _derotFunctObj > mx::improc::ADIobservation< _realT, _derotFunctObj >::ADIobservation (const std::string & dir, const std::string & prefix, const std::string & ext)
Parameters
[in] dir the directory to search.
[in] prefix the initial part of the file name. Can be empty "".
[in] ext the extension to append to the file name, must include the '.'.
Definition at line 240 of file ADIobservation.hpp.
ADIobservation() [2/4]
template<typename _realT , class _derotFunctObj > mx::improc::ADIobservation< _realT, _derotFunctObj >::ADIobservation (const std::string & fileListFile) explicit
Parameters
[in] fileListFile a file name path to read.
Definition at line 248 of file ADIobservation.hpp.
ADIobservation() [3/4]
template<typename _realT , class _derotFunctObj > mx::improc::ADIobservation< _realT, _derotFunctObj >::ADIobservation (const std::string & dir, const std::string & prefix, const std::string & ext, const std::string & RDIdir, const std::string & RDIprefix, const std::string & RDIext = "")
Parameters
[in] dir the directory to search.
[in] prefix the initial part of the file name. Can be empty "".
[in] ext the extension to append to the file name, must include the '.'.
[in] RDIdir the directory to search for the reference files.
[in] RDIprefix the initial part of the file name for the reference files. Can be empty "".
[in] RDIext [optional] the extension to append to the RDI file name, must include the '.'. If empty "" then same extension as target files is used.
Definition at line 254 of file ADIobservation.hpp.
ADIobservation() [4/4]
template<typename _realT , class _derotFunctObj > mx::improc::ADIobservation< _realT, _derotFunctObj >::ADIobservation (const std::string & fileListFile, const std::string & RDIfileListFile)
Parameters
[in] fileListFile a file name path to read for the target file names.
[in] RDIfileListFile a file name path to read for the reference file names.
Definition at line 265 of file ADIobservation.hpp.
Member Function Documentation
derotate()
template<typename _realT , class _derotFunctObj > void mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate ()
De-rotate the PSF subtracted images.
Definition at line 664 of file ADIobservation.hpp.
References mx::sys::get_curr_time(), and mx::improc::imageRotate().
injectFake() [1/2]
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake (eigenCube< realT > & ims, std::vector< std::string > & fileList, derotFunctObj & derotF, realT RDIfluxScale, realT RDISepScale)
Inkect the fake plants.
Todo:
should pad the fake before calling the single image version
throw exceptions for all errors, and switch to void
Parameters
ims [in.out] the image cube in which to inject the fakes.
[in] fileList a list of file paths used for per-image fake PSFs. If empty, then m_fakeFileName is used.
[in] RDIfluxScale the flux scaling for RDI. In SDI, this is from the planet spectrum.
[in] RDISepScale the separation scale for RDI. In SDI, this is the ratio of wavlengths after lambda/D scaling.
Definition at line 468 of file ADIobservation.hpp.
References mx::sys::get_curr_time(), mx::improc::HCI::list, mx::ioutils::pathFilename(), mx::fits::fitsFile< dataT >::read(), mx::ioutils::readColumns(), and mx::improc::HCI::single.
injectFake() [2/2]
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake (eigenImageT & fakePSF, eigenCube< realT > & ims, int image_i, realT derotAngle, realT PA, realT sep, realT contrast, realT scale, realT RDIfluxScale, realT RDISepScale)
Inject the fake planet into a single image.
Todo:
should pad the fake before this point
throw exceptions for all errors, and switch to void
Definition at line 559 of file ADIobservation.hpp.
References mx::improc::cutPaddedImage(), mx::math::dtor(), mx::improc::eigenCube< dataT >::image(), mx::improc::imageShift(), and mx::improc::padImage().
makeMaskCube()
template<typename realT , class derotFunctObj > void mx::improc::ADIobservation< realT, derotFunctObj >::makeMaskCube () virtual
Populate the mask cube which is used for post-processing.
Derived classes can do this as appropriate, e.g. by rotating the mask.
Exceptions
mx::err::invalidconfig if mask is not the same size as the images
Reimplemented from mx::improc::HCIobservation< _realT >.
Definition at line 622 of file ADIobservation.hpp.
References mx::ioutils::createDirectories(), mx::improc::rotateMask(), and mx::fits::fitsFile< dataT >::write().
postCoadd()
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::postCoadd () virtual
Post target coadd actions.
Here updates derotation for new average values.
Reimplemented from mx::improc::HCIobservation< _realT >.
Definition at line 327 of file ADIobservation.hpp.
postRDICoadd()
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::postRDICoadd () virtual
Post reference coadd actions.
Here updates derotation for new average values.
Reimplemented from mx::improc::HCIobservation< _realT >.
Definition at line 371 of file ADIobservation.hpp.
postRDIReadFiles()
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::postRDIReadFiles () virtual
Post reference read actions, including fake injection.
Reimplemented from mx::improc::HCIobservation< _realT >.
Definition at line 358 of file ADIobservation.hpp.
postReadFiles()
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::postReadFiles () virtual
Actions to take after the files are first read in by HCIobservation.
Exracts the angle keywords from the FITS headers, and checks that a valid value is found for each file. Performs fake planet injectio if configured.
Exceptions
returns -1 if an error occurs.
Reimplemented from mx::improc::HCIobservation< _realT >.
Definition at line 298 of file ADIobservation.hpp.
readFiles()
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::readFiles ()
Read in the target files.
First sets up the keywords, then calls HCIobservation readFiles
Definition at line 272 of file ADIobservation.hpp.
readPSFSub()
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::readPSFSub (const std::string & dir, const std::string & prefix, const std::string & ext, size_t nReductions)
Read in already PSF-subtracted files.
Used to take up final processing after applying some non-klipReduce processing steps to PSF-subtracted images.
Definition at line 378 of file ADIobservation.hpp.
References mx::fits::fitsHeader::count(), mx::ioutils::getFileNames(), mx::ioutils::parseStringVector(), and mx::fits::fitsFile< dataT >::read().
readRDIFiles()
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::readRDIFiles ()
Read in the RDI files.
First sets up the keywords, then calls HCIobservation readRDIFiles
Definition at line 334 of file ADIobservation.hpp.
Member Data Documentation
m_fakeContrast
template<typename _realT , class _derotFunctObj > std::vector<realT> mx::improc::ADIobservation< _realT, _derotFunctObj >::m_fakeContrast
Contrast(s) of the fake planet(s)
Definition at line 181 of file ADIobservation.hpp.
m_fakeFileName
template<typename _realT , class _derotFunctObj > std::string mx::improc::ADIobservation< _realT, _derotFunctObj >::m_fakeFileName
FITS file containing the fake planet PSF to inject or a list of fake images.
Definition at line 175 of file ADIobservation.hpp.
m_fakeMethod
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::m_fakeMethod { HCI::single }
Method for reading fake files, either HCI::single or HCI::list.
Definition at line 173 of file ADIobservation.hpp.
m_fakePA
template<typename _realT , class _derotFunctObj > std::vector<realT> mx::improc::ADIobservation< _realT, _derotFunctObj >::m_fakePA
Position angles(s) of the fake planet(s)
Definition at line 180 of file ADIobservation.hpp.
m_fakeScaleFileName
template<typename _realT , class _derotFunctObj > std::string mx::improc::ADIobservation< _realT, _derotFunctObj >::m_fakeScaleFileName
One-column text file containing a scale factor for each point in time.
Definition at line 177 of file ADIobservation.hpp.
m_fakeSep
template<typename _realT , class _derotFunctObj > std::vector<realT> mx::improc::ADIobservation< _realT, _derotFunctObj >::m_fakeSep
Separation(s) of the fake planet(s)
Definition at line 179 of file ADIobservation.hpp.
m_RDIFluxScale
template<typename _realT , class _derotFunctObj > realT mx::improc::ADIobservation< _realT, _derotFunctObj >::m_RDIFluxScale { 1 }
Flux scaling to apply to fake planets injected in RDI. Would depend on the assumed spectrum in SDI.
Definition at line 183 of file ADIobservation.hpp.
m_RDISepScale
template<typename _realT , class _derotFunctObj > realT mx::improc::ADIobservation< _realT, _derotFunctObj >::m_RDISepScale { 1 }
Scaling to apply to fake planet separation in RDI. Would be ratio of wavelengths for SDI.
Definition at line 185 of file ADIobservation.hpp.
The documentation for this struct was generated from the following file:
improc/ADIobservation.hpp