mxlib: mx::sigproc::linearPredictor< _realT > Struct Template Reference
mx::sigproc::linearPredictor< _realT > Struct Template Reference
Signal Processing
template<typename _realT>
struct mx::sigproc::linearPredictor< _realT >
A class to support linear prediction.
Todo:
document linearPredictor
Definition at line 57 of file linearPredictor.hpp.
#include <sigproc/linearPredictor.hpp>
Public Member Functions
int calcCoefficients (const std::vector< realT > &ac, size_t Nc, size_t Npred=1, realT condition=0)
Calculate the LP coefficients given an autocorrelation.
int calcCoefficientsLevinson (const std::vector< realT > &ac, size_t Nc, size_t Npred=1)
int calcCoefficientsLevinson (const realT *ac, size_t acSz, size_t Nc, unsigned Npred=1)
Member Function Documentation
calcCoefficients()
template<typename _realT > int mx::sigproc::linearPredictor< _realT >::calcCoefficients (const std::vector< realT > & ac, size_t Nc, size_t Npred = 1, realT condition = 0) inline
Calculate the LP coefficients given an autocorrelation.
If condition==0 then the levinson recursion is used. Otherwise, SVD pseudo-inversion is used with the given condition number.
Definition at line 71 of file linearPredictor.hpp.
References mx::sigproc::linearPredictor< _realT >::calcCoefficients().
Referenced by mx::sigproc::linearPredictor< _realT >::calcCoefficients(), and mx::AO::analysis::clAOLinearPredictor< _realT >::calcCoefficients().
calcCoefficientsLevinson() [1/2]
template<typename _realT > int mx::sigproc::linearPredictor< _realT >::calcCoefficientsLevinson (const realT * ac, size_t acSz, size_t Nc, unsigned Npred = 1) inline
Parameters
[in] ac The autocorrelation, at least Nc+Npred in length
[in] acSz The length of the autocorrelation
[in] Nc The number of LP coefficients desired
[in] Npred [optional] The prediction length, default is 1
Definition at line 135 of file linearPredictor.hpp.
References mx::invalidarg.
calcCoefficientsLevinson() [2/2]
template<typename _realT > int mx::sigproc::linearPredictor< _realT >::calcCoefficientsLevinson (const std::vector< realT > & ac, size_t Nc, size_t Npred = 1) inline
Parameters
[in] ac The autocorrelation, at least Nc+Npred in length
[in] Nc The number of LP coefficients desired
[in] Npred [optional] The prediction length, default is 1
Definition at line 123 of file linearPredictor.hpp.
References mx::sigproc::linearPredictor< _realT >::calcCoefficientsLevinson().
Referenced by mx::sigproc::linearPredictor< _realT >::calcCoefficientsLevinson().
The documentation for this struct was generated from the following file:
sigproc/linearPredictor.hpp