mxlib: /home/jrmales/Source/mxlib/tests/include/sys/timeUtils_test.cpp File Reference
timeUtils_test.cpp File Reference
#include "../../catch2/catch.hpp"
#include "../../../include/sys/timeUtils.hpp"
Functions
SCENARIO ("Verify operation of get_curr_time", "[timeutils]")
SCENARIO ("Verify operation of thread sleep functions", "[timeutils]")
SCENARIO ("Verify operation of timespecAddNsec", "[timeutils]")
SCENARIO ("Verify parsing of a formatted time string", "[timeutils]")
SCENARIO ("Verify calculation of MJD", "[timeutils]")
SCENARIO ("Verify parsing of an ISO 8601 time string", "[timeutils]")
SCENARIO ("Verify conversion of an ISO 8601 time string to MJD", "[timeutils]")
Function Documentation
SCENARIO() [1/7]
SCENARIO ("Verify calculation of MJD" , "" [timeutils])
Test:
Scenario: Verify calculation of MJD
Definition at line 256 of file timeUtils_test.cpp.
References mx::sys::Cal2mjd().
SCENARIO() [2/7]
SCENARIO ("Verify conversion of an ISO 8601 time string to MJD" , "" [timeutils])
Test:
Scenario: Verify conversion of an ISO 8601 time string to MJD
Definition at line 336 of file timeUtils_test.cpp.
References mx::sys::ISO8601date2mjd().
SCENARIO() [3/7]
SCENARIO ("Verify operation of get_curr_time" , "" [timeutils])
Test:
Scenario: Verify operation of get_curr_time.
This only checks for increasing time on subsequent calls.
Definition at line 13 of file timeUtils_test.cpp.
References mx::sys::get_curr_time().
SCENARIO() [4/7]
SCENARIO ("Verify operation of thread sleep functions" , "" [timeutils])
Test:
Scenario: Verify operation of thread sleep functions
Uses mx::sys::get_curr_time to verify duration of sleep.
Definition at line 46 of file timeUtils_test.cpp.
References mx::sys::get_curr_time(), mx::sys::microSleep(), mx::sys::milliSleep(), mx::sys::nanoSleep(), and mx::sys::sleep().
SCENARIO() [5/7]
SCENARIO ("Verify operation of timespecAddNsec" , "" [timeutils])
Test:
Scenario: Verify operation of timespecAddNsec
Definition at line 89 of file timeUtils_test.cpp.
References mx::sys::timespecAddNsec().
SCENARIO() [6/7]
SCENARIO ("Verify parsing of a formatted time string" , "" [timeutils])
Test:
Scenario: Verify parsing of a formatted time string
Tests parsing of a string of format hh:mm:ss.s
Definition at line 194 of file timeUtils_test.cpp.
References mx::sys::parse_hms().
SCENARIO() [7/7]
SCENARIO ("Verify parsing of an ISO 8601 time string" , "" [timeutils])
Test:
Scenario: Verify parsing of an ISO 8601 time string
Definition at line 281 of file timeUtils_test.cpp.
References mx::sys::ISO8601dateBreakdown().