mxlib: ao/analysis/zernikeCovariance.hpp File Reference
zernikeCovariance.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Calculation of the modal covariance in the zernike basis.
Calculation of the modal covariance in the zernike basis.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file zernikeCovariance.hpp.
Classes
struct mx::AO::analysis::zernikeCovariance< realT, aosysT >
Structure to manage the zernike mode covariance calculation, passed to integration functions.
Namespaces
namespace mx
The mxlib c++ namespace.
Functions
template<typename realT , typename aosysT >
int mx::AO::analysis::zernikeVarVec (const std::string &fname, int N, aosysT &aosys, realT absTol, realT relTol, bool modifed=true)
Calculate a vector of zernike mode variances.
template<typename realT , typename aosysT >
int mx::AO::analysis::zernikePSDMap (improc::eigenImage< realT > &var, improc::eigenImage< realT > &psd, int N, int overSample, aosysT &aosys)
Calculate a map of zernike variances by convolution with the PSD.
template<typename realT >
int mx::AO::analysis::zernikeCovarMap (const std::string &fname, int N, realT D, realT L_0, bool subPist, bool subTilt, realT absTol, realT relTol, bool modified=true)
Function Documentation
zernikeCovarMap()
template<typename realT > int mx::AO::analysis::zernikeCovarMap (const std::string & fname, int N, realT D, realT L_0, bool subPist, bool subTilt, realT absTol, realT relTol, bool modified = true)
Parameters
[out] fname the path where the output FITS file will be written
[in] N the linear number of zernike modes across the aperture. The Nyquist frequency is set by N/2.
Definition at line 370 of file zernikeCovariance.hpp.
References mx::fits::fitsHeader::append(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::D(), mx::ipc::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine, _time >::incrementAndOutputStatus(), mx::AO::analysis::aoAtmosphere< _realT >::L_0(), mx::AO::analysis::aoSystem< _realT, _inputSpectT, iosT >::loadMagAOX(), mx::AO::analysis::modified, mx::AO::analysis::aoAtmosphere< _realT >::r_0(), mx::fits::fitsFile< dataT >::write(), and mx::AO::analysis::zernikeCovarMap().
Referenced by mx::AO::analysis::zernikeCovarMap().
zernikePSDMap()
template<typename realT , typename aosysT > int mx::AO::analysis::zernikePSDMap (improc::eigenImage< realT > & var, improc::eigenImage< realT > & psd, int N, int overSample, aosysT & aosys)
Calculate a map of zernike variances by convolution with the PSD.
Uses the Airy pattern for the circularly unobstructed aperture.
Returns
0 on success
-1 on error
Parameters
[out] var The variance estimated by convolution with the PSD
[out] psd the PSD map
[in] N the number of components to analyze
aosys [in[ the AO system defining the PSD characteristics.
Definition at line 314 of file zernikeCovariance.hpp.
References mx::math::func::airyPattern(), mx::math::six_fifths(), mx::AO::analysis::varmapToImage(), and mx::AO::analysis::zernikePSDMap().
Referenced by mx::AO::analysis::zernikePSDMap().
zernikeVarVec()
template<typename realT , typename aosysT > int mx::AO::analysis::zernikeVarVec (const std::string & fname, int N, aosysT & aosys, realT absTol, realT relTol, bool modifed = true)
Calculate a vector of zernike mode variances.
Definition at line 225 of file zernikeCovariance.hpp.
References mx::ipc::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine, _time >::incrementAndOutputStatus(), mx::math::six_fifths(), and mx::AO::analysis::zernikeVarVec().
Referenced by mx::AO::analysis::zernikeVarVec().