var searchData=
[
  ['padding_0',['Image Padding',['../group__image__padding.html',1,'']]],
  ['path_20management_1',['Adaptive Optics Path Management',['../group__mxAO__paths.html',1,'']]],
  ['pattern_2',['The Airy Pattern',['../group__gen__math__airy__pattern.html',1,'']]],
  ['patterns_3',['Airy Patterns',['../group__airy__peak__fit.html',1,'']]],
  ['peak_20fitting_4',['Peak Fitting',['../group__peak__fit.html',1,'']]],
  ['photometry_5',['Astronomical Photometry',['../group__astrophot.html',1,'']]],
  ['physical_20and_20astronomical_20constants_6',['Physical and Astronomical Constants',['../group__astroconstants.html',1,'']]],
  ['plan_20specification_7',['Plan Specification',['../group__fftw__template__plan__specs.html',1,'']]],
  ['planets_8',['Planets',['../group__planets.html',1,'']]],
  ['planning_9',['Planning',['../group__fftw__template__plans.html',1,'']]],
  ['plotting_20data_10',['Plotting Data',['../group__plotting.html',1,'']]],
  ['point_20spread_20functions_11',['Point Spread Functions',['../group__psfs.html',1,'']]],
  ['positional_20astronomy_12',['Positional Astronomy',['../group__posastro.html',1,'']]],
  ['power_20spectra_13',['power spectra',['../group__arpsds.html',1,'Autoregressive Power Spectra'],['../group__psds.html',1,'Power Spectra']]],
  ['precision_14',['Machine Precision',['../group__gen__math__precision.html',1,'']]],
  ['problem_15',['The Kepler Problem',['../group__kepler.html',1,'']]],
  ['processing_16',['processing',['../group__image__processing.html',1,'Image Processing'],['../group__signal__processing.html',1,'Signal Processing']]],
  ['processing_20files_17',['processing files',['../group__image__processing__files.html',1,'Image Processing Files'],['../group__signal__processing__files.html',1,'Signal Processing Files']]],
  ['processing_20with_20eigen_18',['Image Processing with Eigen',['../group__eigen__image__processing.html',1,'']]],
  ['profiles_19',['profiles',['../group__std__prof.html',1,'Noise Profiles'],['../group__rad__prof.html',1,'Radial Profiles']]],
  ['programming_20',['System Programming',['../group__system.html',1,'']]],
  ['programming_20utilities_21',['Meta-programming Utilities.',['../group__meta.html',1,'']]],
  ['propagation_22',['Wavefront Propagation',['../group__imaging.html',1,'']]],
  ['propagation_20files_23',['Wavefront Propagation Files',['../group__imaging__files.html',1,'']]],
  ['psd_20filter_24',['PSD Filter',['../group__psd__filter.html',1,'']]],
  ['putting_20a_20thread_20to_20sleep_25',['Putting a thread to sleep',['../group__timeutils__sleep.html',1,'']]]
];
