var searchData=
[
  ['fast_20fourier_20transforms_0',['Fast Fourier Transforms',['../group__fft.html',1,'']]],
  ['fftw_1',['Template FFTW',['../group__fftw__templates.html',1,'']]],
  ['fftw_20environment_2',['FFTW Environment',['../group__fftw__env.html',1,'']]],
  ['fftw_20interface_3',['FFTW Interface',['../group__fftw.html',1,'']]],
  ['fftw_20library_4',['The FFTW Library',['../group__fftw__lib.html',1,'']]],
  ['file_20format_5',['binVector Binary File Format',['../group__binvector.html',1,'']]],
  ['file_20system_20utilities_6',['File System Utilities',['../group__fileutils.html',1,'']]],
  ['file_20utilities_20unit_20tests_7',['File Utilities Unit Tests',['../group__fileUtils__unit__tests.html',1,'']]],
  ['files_8',['files',['../group__mxAO__files.html',1,'Adaptive Optics Files'],['../group__mxApp__files.html',1,'Application Files'],['../group__astrofiles.html',1,'Astronomy Files'],['../group__cuda__files.html',1,'Cuda Files'],['../group__error__handling__files.html',1,'Error Handling Files'],['../group__plotting__files.html',1,'Files'],['../group__fits__processing.html',1,'FITS Files'],['../group__fitting__files.html',1,'Fitting Files'],['../group__ft__files.html',1,'Fourier Transform Files'],['../group__gen__math__files.html',1,'Gen. Math Files'],['../group__image__processing__files.html',1,'Image Processing Files'],['../group__signal__processing__files.html',1,'Signal Processing Files'],['../group__utils__files.html',1,'Utility Files'],['../group__imaging__files.html',1,'Wavefront Propagation Files']]],
  ['files_20files_9',['FITS Files Files',['../group__fits__processing__files.html',1,'']]],
  ['filter_10',['PSD Filter',['../group__psd__filter.html',1,'']]],
  ['filter_20with_20averaging_11',['Filter With Averaging',['../group__image__filters__average.html',1,'']]],
  ['filter_20with_20kernels_12',['Filter With Kernels',['../group__image__filters__kernels.html',1,'']]],
  ['filters_13',['Image Filters',['../group__image__filters.html',1,'']]],
  ['fits_20files_14',['FITS Files',['../group__fits__processing.html',1,'']]],
  ['fits_20files_20files_15',['FITS Files Files',['../group__fits__processing__files.html',1,'']]],
  ['fits_20unit_20tests_16',['FITS Unit Tests',['../group__fits__unit__tests.html',1,'']]],
  ['fits_20utilities_17',['FITS Utilities',['../group__fits__utils.html',1,'']]],
  ['fitsfile_20typedefs_18',['fitsFile typedefs',['../group__fits__processing__typedefs.html',1,'']]],
  ['fitsfile_20unit_20tests_19',['fitsFile Unit Tests',['../group__fitsFile__unit__tests.html',1,'']]],
  ['fitsheader_20unit_20tests_20',['fitsHeader Unit Tests',['../group__fitsHeader__unit__tests.html',1,'']]],
  ['fitsheadercard_20unit_20tests_21',['fitsHeaderCard Unit Tests',['../group__fitsHeaderCard__unit__tests.html',1,'']]],
  ['fitting_22',['fitting',['../group__fitting.html',1,'Data Fitting'],['../group__peak__fit.html',1,'Peak Fitting']]],
  ['fitting_20files_23',['Fitting Files',['../group__fitting__files.html',1,'']]],
  ['format_24',['binVector Binary File Format',['../group__binvector.html',1,'']]],
  ['fourier_20basis_25',['The Fourier Basis',['../group__fourier__basis.html',1,'']]],
  ['fourier_20transform_20files_26',['Fourier Transform Files',['../group__ft__files.html',1,'']]],
  ['fourier_20transforms_27',['fourier transforms',['../group__fft.html',1,'Fast Fourier Transforms'],['../group__ft.html',1,'Fourier Transforms'],['../group__mft.html',1,'Matrix Fourier Transforms']]],
  ['framework_28',['Application Framework',['../group__mxApp.html',1,'']]],
  ['function_29',['function',['../group__gen__math__gamma.html',1,'The Gamma Function'],['../group__gen__math__gaussians.html',1,'The Gaussian Function'],['../group__gen__math__logistic.html',1,'The Logistic Function'],['../group__gen__math__moffats.html',1,'The Moffat Function']]],
  ['functions_30',['functions',['../group__signal__windows1D.html',1,'1-D Window Functions'],['../group__signal__windows2D.html',1,'2-D Window Functions'],['../group__gen__math__bessel.html',1,'Bessel Functions'],['../group__moffat__peak__fit.html',1,'Moffat Functions'],['../group__psfs.html',1,'Point Spread Functions'],['../group__functions.html',1,'Special Functions'],['../group__signal__windows.html',1,'Window Functions']]]
];
