var searchData=
[
  ['a_20thread_20to_20sleep_0',['Putting a thread to sleep',['../group__timeutils__sleep.html',1,'']]],
  ['adaptive_20optics_1',['adaptive optics',['../group__mxAO.html',1,'Adaptive Optics'],['../group__mxAOAnalytic.html',1,'Analysis of Adaptive Optics'],['../group__mxAOSim.html',1,'Simulation of Adaptive Optics']]],
  ['adaptive_20optics_20files_2',['Adaptive Optics Files',['../group__mxAO__files.html',1,'']]],
  ['adaptive_20optics_20path_20management_3',['Adaptive Optics Path Management',['../group__mxAO__paths.html',1,'']]],
  ['airy_20pattern_4',['The Airy Pattern',['../group__gen__math__airy__pattern.html',1,'']]],
  ['airy_20patterns_5',['Airy Patterns',['../group__airy__peak__fit.html',1,'']]],
  ['allocation_6',['Allocation',['../group__fftw__template__alloc.html',1,'']]],
  ['analysis_20of_20adaptive_20optics_7',['Analysis of Adaptive Optics',['../group__mxAOAnalytic.html',1,'']]],
  ['and_20astronomical_20constants_8',['Physical and Astronomical Constants',['../group__astroconstants.html',1,'']]],
  ['and_20geodesy_9',['Geometry and Geodesy',['../group__geo.html',1,'']]],
  ['and_20lapack_10',['Templatized BLAS and Lapack',['../group__template__blaslap.html',1,'']]],
  ['and_20units_11',['Constants and units',['../group__constants.html',1,'']]],
  ['ao_20constants_12',['AO Constants',['../group__aoConstants.html',1,'']]],
  ['application_20files_13',['Application Files',['../group__mxApp__files.html',1,'']]],
  ['application_20framework_14',['Application Framework',['../group__mxApp.html',1,'']]],
  ['ascii_20i_20o_20utilities_15',['ASCII I/O Utilities',['../group__asciiutils.html',1,'']]],
  ['astrodynamics_16',['Astrodynamics',['../group__astrodynamics.html',1,'']]],
  ['astronomical_20constants_17',['Physical and Astronomical Constants',['../group__astroconstants.html',1,'']]],
  ['astronomical_20photometry_18',['Astronomical Photometry',['../group__astrophot.html',1,'']]],
  ['astronomical_20spectra_19',['Astronomical Spectra',['../group__astrophot__spectra.html',1,'']]],
  ['astronomy_20',['astronomy',['../group__genastro.html',1,'Astronomy'],['../group__posastro.html',1,'Positional Astronomy']]],
  ['astronomy_20files_21',['Astronomy Files',['../group__astrofiles.html',1,'']]],
  ['atlas_22',['Getting ATLAS',['../group__atlas.html',1,'']]],
  ['autoregressive_20power_20spectra_23',['Autoregressive Power Spectra',['../group__arpsds.html',1,'']]],
  ['averaging_24',['Filter With Averaging',['../group__image__filters__average.html',1,'']]]
];
