var searchData=
[
  ['template_20fftw_0',['Template FFTW',['../group__fftw__templates.html',1,'']]],
  ['templatized_20blas_20and_20lapack_1',['Templatized BLAS and Lapack',['../group__template__blaslap.html',1,'']]],
  ['templatized_20blas_20interface_2',['Templatized BLAS interface',['../group__template__blas.html',1,'']]],
  ['templatized_20lapack_20interface_3',['Templatized Lapack interface',['../group__template__lapack.html',1,'']]],
  ['the_20airy_20pattern_4',['The Airy Pattern',['../group__gen__math__airy__pattern.html',1,'']]],
  ['the_20exponentially_20modified_20gaussian_20distribution_5',['The Exponentially Modified Gaussian Distribution',['../group__gen__math__expModGaussian.html',1,'']]],
  ['the_20fftw_20library_6',['The FFTW Library',['../group__fftw__lib.html',1,'']]],
  ['the_20fourier_20basis_7',['The Fourier Basis',['../group__fourier__basis.html',1,'']]],
  ['the_20gamma_20distribution_8',['The Gamma Distribution',['../group__gen__math__gammaDist.html',1,'']]],
  ['the_20gamma_20function_9',['The Gamma Function',['../group__gen__math__gamma.html',1,'']]],
  ['the_20gaussian_20function_10',['The Gaussian Function',['../group__gen__math__gaussians.html',1,'']]],
  ['the_20kepler_20problem_11',['The Kepler Problem',['../group__kepler.html',1,'']]],
  ['the_20levmar_20library_12',['The levmar library',['../group__levmar.html',1,'']]],
  ['the_20logistic_20function_13',['The Logistic Function',['../group__gen__math__logistic.html',1,'']]],
  ['the_20moffat_20function_14',['The Moffat Function',['../group__gen__math__moffats.html',1,'']]],
  ['the_20sofa_20library_15',['The SOFA Library',['../group__astro__sofa.html',1,'']]],
  ['the_20weibull_20distribution_16',['The Weibull Distribution',['../group__gen__math__weibull.html',1,'']]],
  ['the_20zernike_20basis_17',['The Zernike Basis',['../group__zernike__basis.html',1,'']]],
  ['thread_20to_20sleep_18',['Putting a thread to sleep',['../group__timeutils__sleep.html',1,'']]],
  ['threading_20utilities_19',['Multi-threading Utilities',['../group__mtutils.html',1,'']]],
  ['time_20',['Working with time',['../group__timeutils.html',1,'']]],
  ['timespec_20comparisons_21',['Timespec comparisons',['../group__timeutils__tscomp.html',1,'']]],
  ['to_20sleep_22',['Putting a thread to sleep',['../group__timeutils__sleep.html',1,'']]],
  ['transform_20files_23',['Fourier Transform Files',['../group__ft__files.html',1,'']]],
  ['transforms_24',['transforms',['../group__fft.html',1,'Fast Fourier Transforms'],['../group__ft.html',1,'Fourier Transforms'],['../group__image__transforms.html',1,'Image Transforms'],['../group__mft.html',1,'Matrix Fourier Transforms']]],
  ['type_20specification_25',['Type Specification',['../group__fftw__template__type__specs.html',1,'']]],
  ['typedefs_26',['fitsFile typedefs',['../group__fits__processing__typedefs.html',1,'']]],
  ['types_27',['Types',['../group__fftw__template__types.html',1,'']]]
];
