var searchData=
[
  ['template_20fftw_0',['Template FFTW',['../group__fftw__templates.html',1,'']]],
  ['templatized_20blas_20and_20lapack_1',['Templatized BLAS and Lapack',['../group__template__blaslap.html',1,'']]],
  ['templatized_20blas_20interface_2',['Templatized BLAS interface',['../group__template__blas.html',1,'']]],
  ['templatized_20lapack_20interface_3',['Templatized Lapack interface',['../group__template__lapack.html',1,'']]],
  ['testing_4',['Testing',['../group__mxlib__testing.html',1,'']]],
  ['tests_5',['tests',['../group__testing__building.html',1,'Building Tests'],['../group__error__unit__tests.html',1,'Error Handling Unit Tests'],['../group__error__error__unit__tests.html',1,'Error Reporting Unit Tests'],['../group__error__error__t__unit__tests.html',1,'error_t Utilities Unit Tests'],['../group__fileUtils__unit__tests.html',1,'File Utilities Unit Tests'],['../group__fits__unit__tests.html',1,'FITS Unit Tests'],['../group__fitsFile__unit__tests.html',1,'fitsFile Unit Tests'],['../group__fitsHeader__unit__tests.html',1,'fitsHeader Unit Tests'],['../group__fitsHeaderCard__unit__tests.html',1,'fitsHeaderCard Unit Tests'],['../group__ioutils__unit__tests.html',1,'I/O Utilities Unit Tests'],['../group__readColumns__unit__tests.html',1,'readColumns Unit Tests'],['../group__stringUtils__unit__tests.html',1,'String Utilities Unit Tests'],['../group__unit__tests.html',1,'Unit Tests']]],
  ['the_20airy_20pattern_6',['The Airy Pattern',['../group__gen__math__airy__pattern.html',1,'']]],
  ['the_20exponentially_20modified_20gaussian_20distribution_7',['The Exponentially Modified Gaussian Distribution',['../group__gen__math__expModGaussian.html',1,'']]],
  ['the_20fftw_20library_8',['The FFTW Library',['../group__fftw__lib.html',1,'']]],
  ['the_20fourier_20basis_9',['The Fourier Basis',['../group__fourier__basis.html',1,'']]],
  ['the_20gamma_20distribution_10',['The Gamma Distribution',['../group__gen__math__gammaDist.html',1,'']]],
  ['the_20gamma_20function_11',['The Gamma Function',['../group__gen__math__gamma.html',1,'']]],
  ['the_20gaussian_20function_12',['The Gaussian Function',['../group__gen__math__gaussians.html',1,'']]],
  ['the_20kepler_20problem_13',['The Kepler Problem',['../group__kepler.html',1,'']]],
  ['the_20levmar_20library_14',['The levmar library',['../group__levmar.html',1,'']]],
  ['the_20logistic_20function_15',['The Logistic Function',['../group__gen__math__logistic.html',1,'']]],
  ['the_20moffat_20function_16',['The Moffat Function',['../group__gen__math__moffats.html',1,'']]],
  ['the_20sofa_20library_17',['The SOFA Library',['../group__astro__sofa.html',1,'']]],
  ['the_20weibull_20distribution_18',['The Weibull Distribution',['../group__gen__math__weibull.html',1,'']]],
  ['the_20zernike_20basis_19',['The Zernike Basis',['../group__zernike__basis.html',1,'']]],
  ['thread_20to_20sleep_20',['Putting a thread to sleep',['../group__timeutils__sleep.html',1,'']]],
  ['threading_20utilities_21',['Multi-threading Utilities',['../group__mtutils.html',1,'']]],
  ['time_22',['Working with time',['../group__timeutils.html',1,'']]],
  ['timespec_20comparisons_23',['Timespec comparisons',['../group__timeutils__tscomp.html',1,'']]],
  ['to_20sleep_24',['Putting a thread to sleep',['../group__timeutils__sleep.html',1,'']]],
  ['transform_20files_25',['Fourier Transform Files',['../group__ft__files.html',1,'']]],
  ['transforms_26',['transforms',['../group__fft.html',1,'Fast Fourier Transforms'],['../group__ft.html',1,'Fourier Transforms'],['../group__image__transforms.html',1,'Image Transforms'],['../group__mft.html',1,'Matrix Fourier Transforms']]],
  ['type_20specification_27',['Type Specification',['../group__fftw__template__type__specs.html',1,'']]],
  ['typedefs_28',['fitsFile typedefs',['../group__fits__processing__typedefs.html',1,'']]],
  ['types_29',['Types',['../group__fftw__template__types.html',1,'']]]
];
